### ISSUE TITLE
Atualizar screenshots do SourceForge e do Site

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#100]
Após completarmos a refatoração para a versão 2.5, não podemos nos esquecer de atualizar as descrições e as screenshots do SrouceForge e do site do Portugol.

![print](https://cloud.githubusercontent.com/assets/709553/13437625/073fca4a-dfc4-11e5-99f7-7f6c5f6b898f.png)

![print2](https://cloud.githubusercontent.com/assets/709553/13437632/0bd4ded8-dfc4-11e5-8bb4-650a09382081.png)

Também tem a atualização das videoaulas, mas isso abrimos em outra issue mais pra frente, pois vai ser mais difícil de fazer.

**Comment by AlissonSteffens** [comment]
@AdsonEsteves será nós dois conseguimos fazer ainda essa semana?
