### ISSUE TITLE
ERRO NA INHA 0 

### ISSUE THREAD

**Issue by betabasica** [UNIVALI-LITE/Portugol-Studio#1000]
programa
{
	
	funcao inicio()
	{
		inteiro  i
		real media=0.0 , N , idades
		escreva("Quantas idades irá introduzir?\t")
		leia(N)
		
		para(i=1;i<=N;i++){
			escreva("Introduza a idade do",i,"aluno(a)")
			leia(idades)
		}

		se(idades>0){
			media=idades/N
			escreva("A média de idades dos",N,"alunos é de",media)
		}
	}
}

**Comment by AdsonEsteves** [comment]
@betabasica 
Inicie todas as suas variáveis com um valor.
por exemplo idades = 0
