### ISSUE TITLE
Problema para desinstalar o Portugol Studio no Ubuntu

### ISSUE THREAD

**Issue by joaofaveri** [UNIVALI-LITE/Portugol-Studio#1003]
**Descrição do Problema**:
Tenho o Portugol Studio Instalado no Ubuntu 20.04, porém não consigo desinstalar de forma alguma. Tentei a solução indicada na Issue #504, porém não há script na minha máquina que execute o código de desinstalação. Alguém teria a solução para esse problema?

**Especificações do sistema**:
Ubuntu 20.04 e Portugol Sudio 2.7.4

**Comment by AdsonEsteves** [comment]
@noschang 
Pode ajudar?

**Comment by joaofaveri** [comment]
> **Descrição do Problema**: Tenho o Portugol Studio Instalado no Ubuntu 20.04, porém não consigo desinstalar de forma alguma. Tentei a solução indicada na Issue #504, porém não há script na minha máquina que execute o código de desinstalação. Alguém teria a solução para esse problema?
> 
> **Especificações do sistema**: Ubuntu 20.04 e Portugol Sudio 2.7.4

Pessoal, fiz a atualização da versão instalada (2.7.4) para a mais recente (2.7.5). Com isso, o script de desinstalação ficou disponível e utilizei o seguinte comando:

`sudo /usr/local/portugol-studio/desinstalar`

**Comment by AdsonEsteves** [comment]
@joaofaveri 
Que bom.
Vou fechar a issue então.

**Comment by wsalmeida** [comment]
Removendo dessa forma ainda fica resíduo no sistema, como o lançador, fiz teste no debian xfce.
![2022-02-28_20-39](https://user-images.githubusercontent.com/38542279/156077209-ec3c5a16-ff7d-4513-a700-44e9210a7f93.png)
