### ISSUE TITLE
primeira duvida

### ISSUE THREAD

**Issue by silviomacias80** [UNIVALI-LITE/Portugol-Studio#1010]
**Descrição do Problema**:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by silviomacias80** [comment]
Cordiais saudações.
  Ao baixar o programa e executar nao abre o comando programar. estou fazendo o curso em video com o gustavo guanabara e nao apareceu a autorização para o java.

**Comment by AdsonEsteves** [comment]
@silviomacias80 
Não abre o comando programar? O que exatamente quer dizer? Não consegue abrir a aba de código? Os programas não executam?
É gerada alguma tela de erro?
Qual o sistema operacional?

**Comment by silviomacias80** [comment]
Cordiais saudações. Não tem o comando programar na tela inicial. Somente
armazena os exercícios. O sistema é windows 7 laptop.

Em dom, 9 de jan de 2022 16:06, Adsu ***@***.***> escreveu:

**Comment by AdsonEsteves** [comment]
@silviomacias80 
Pode mostrar um print da sua tela?

**Comment by silviomacias80** [comment]
Em seg, 10 de jan de 2022 16:49, Adsu ***@***.***> escreveu:

**Comment by AdsonEsteves** [comment]
@silviomacias80 
Eu não consigo ver imagens mandadas por e-mail.
Me manda um link, ou entra no github da issue e manda por ali:
https://github.com/UNIVALI-LITE/Portugol-Studio/issues/1010

**Comment by silviomacias80** [comment]
obrigado pela ajuda desculpe estou começando e demoro para entender. Luz e pax.

**Comment by silviomacias80** [comment]
Thank you!

Em ter, 11 de jan de 2022 14:01, Adsu ***@***.***> escreveu:
