### ISSUE TITLE
Execução com query (recurso leia)

### ISSUE THREAD

**Issue by ronaldosc** [UNIVALI-LITE/Portugol-Studio#1012]
**Descrição do Problema**:
Há uma persistência da mensagem "_O programa está aguardando a entrada de dados_" após sucessivas vezes que se executa o código.
A reivindicação é de que esta mensagem desapareça após o valor de entrada na query.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@ronaldosc
Pode ser mais específico? Por aqui, no momento em que é clicado em alguma parte do Portugol a mensagem desaparece.
Qual seu sistema operacional?

**Comment by ronaldosc** [comment]
Resolvido ? @AdsonEsteves
