### ISSUE TITLE
Trava na janela mensagem

### ISSUE THREAD

**Issue by viviguazzelli** [UNIVALI-LITE/Portugol-Studio#1019]
**Descrição do Problema**:
Após um tempo usando, trava na janela mensagem e não consigo trocar para o console, só fechando o programa
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
	Windows 10

**Comment by AdsonEsteves** [comment]
Duplicate of #599
