### ISSUE TITLE
bug no portugol

### ISSUE THREAD

**Issue by vitlord** [UNIVALI-LITE/Portugol-Studio#1020]
**Descrição do Problema**: Não consigo incluir bibliotecas no meu código 

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/99210636/152851848-48281796-eca6-4df2-92b7-134880e1481b.png)

**Especificações do sistema**: Windows 10 64bits

**Comment by AdsonEsteves** [comment]
@vitlord 
A biblioteca deve ser escrita com M maiúsculo.

**Comment by vitlord** [comment]
Muito obrigado , me desculpe pela minha burrice rs

Em seg., 7 de fev. de 2022 às 18:26, Adsu ***@***.***>
escreveu:
