### ISSUE TITLE
versão mac

### ISSUE THREAD

**Issue by caoheebh** [UNIVALI-LITE/Portugol-Studio#1024]
**Descrição do Problema**:
Pessoal, a versão MAC não está permitindo instalação. Há algum pré-requisito? Estou testando na versão 12.0.1

**Mensagem de Erro (se houver)**:
A imagem de disco não pode ser aberta.

**Captura de Tela / Arquivo.por**:
![Captura de Tela 2022-02-14 às 21 17 31](https://user-images.githubusercontent.com/99697503/153968686-be45599d-f7ed-497b-9270-413d6391e33d.png)

**Especificações do sistema**:
MAC OSX 12.0.1

**Comment by AdsonEsteves** [comment]
Duplicate of #990 990
