### ISSUE TITLE
sdad

### ISSUE THREAD

**Issue by DluccaSR** [UNIVALI-LITE/Portugol-Studio#1038]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by DluccaSR** [comment]
meu portugol travou do nda

**Comment by AdsonEsteves** [comment]
@DluccaSR 
Isso acontece sempre? Gerou alguma mensagem de erro?
Qual seu sistema operacional?
