### ISSUE TITLE
ERRO AO INSTALAR PORTUGOL NO MAC PRO M1 MONTEREY

### ISSUE THREAD

**Issue by thedoctorpm** [UNIVALI-LITE/Portugol-Studio#1042]
**Descrição do Problema**:
Alguem consegue solucionar esse problema? ja baixei varios arquivo e versao onde nao tive sucesso.\

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
<img width="999" alt="Captura de ecrã 2022-04-06, às 00 13 15" src="https://user-images.githubusercontent.com/103078971/161866100-7ccf6321-ea88-4f12-aae4-2c315f0aad12.png">

**Especificações do sistema**:
	
MAC PRO M1 32gb OS MONTEREY

**Comment by AdsonEsteves** [comment]
@thedoctorpm 
Ainda não descobrimos como resolver esse problema infelizmente.
Se quiser pode tentar o https://portugol-webstudio.cubos.io/, porém é mais limitado.

**Comment by AdsonEsteves** [comment]
Duplicate of #990

**Comment by thedoctorpm** [comment]
obg
