### ISSUE TITLE
A TELA DO MEU PORTUGOL FICA MULTIPLICANDO AO PASSAR O MOUSE:

### ISSUE THREAD

**Issue by joaozinho07** [UNIVALI-LITE/Portugol-Studio#1044]
A TELA DO MEU PORTUGOL FICA MULTIPLICANDO AO PASSAR O MOUSE:

Windows 10 pro:
	
![Captura de tela 2022-04-17 212931](https://user-images.githubusercontent.com/95665362/163737994-ca423e5a-daae-44bf-98c9-374295930548.png)
![Captura de tela 2022-04-17 212959](https://user-images.githubusercontent.com/95665362/163737996-56516bab-0cc6-461c-a517-9c7585091b82.png)

**Comment by AdsonEsteves** [comment]
@joaozinho07 
Da uma olhada aqui #421

**Comment by joaozinho07** [comment]
Resolvido muito obrigado.

Em seg., 18 de abr. de 2022 15:10, Adsu ***@***.***> escreveu:
