### ISSUE TITLE
Erro palavra ESCREVA

### ISSUE THREAD

**Issue by VanessaNaves** [UNIVALI-LITE/Portugol-Studio#1046]
**Descrição do Problema**: Sistema não reconhece a palavra "Escreva" como um comando (ou variavél)

**Mensagem de Erro (se houver)**: 

**Captura de Tela / Arquivo.por**: 
![image](https://user-images.githubusercontent.com/105394837/167953637-c5dea47a-7e47-4842-ba0c-c6374075d10f.png)

**Especificações do sistema**: Windows 7 ultimate 64bits

**Comment by AdsonEsteves** [comment]
@VanessaNaves 
Você precisa terminar de escrever a funcao para funcionar.
por exemplo:
``
escreva("Ola Mundo")
``
Da uma olhada nos exemplos da aba inicial se tiver duvidas.
