### ISSUE TITLE
 Eu atribui uma variavel do tipo inteiro ao vetor.

### ISSUE THREAD

**Issue by elndutra** [UNIVALI-LITE/Portugol-Studio#1047]
**Descrição do Problema**:
 Eu atribui uma variavel do tipo inteiro ao vetor, mas informa a mensagem "O tamanho do vetor 'verificador" deve ser um valor ou uma constante do tipo inteiro e positivo Ex: vetor[3]"

como pode verificar, eu estou incluindo a bibliote Texto.. e peguei o tamanho do da cadeia, atribuida a varivael numStr, teoricamente a expressão tx.numero_caracteres(numStr) retorna um inteiro, isso pelo que entendi.. Mas o tamanho do vetor não aceita essa variavel inteiro...

o codigo escrito é esse: 

	funcao inteiro numeroDecrescente(inteiro numero)
	{
		
		
		inteiro num = numero
		cadeia numStr = tp.inteiro_para_cadeia(num,10)
	        inteiro countNum = tx.numero_caracteres(numStr)
	   	inteiro verificador[countNum]
		
		para (inteiro contador = 0; contador < countNum; contador++)
		{
				inteiro separarNumero = (num % 10)
				 verificador[contador]= separarNumero
				escreva(verificador[contador])
				num = num / 10

		}
		
		retorne num
		
	}

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![Capturar](https://user-images.githubusercontent.com/99561774/169855097-3bd17bff-cd8b-4531-8cbd-4e66ae422081.PNG)

**Especificações do sistema**:
Windows 10 64x.

**Comment by AdsonEsteves** [comment]
@elndutra 
Os vetores não podem ser inicializados com variaveis. Apenas contantes ou valores diretos.
