### ISSUE TITLE
Rebase or not Rebase that's the question

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#109]
![image](https://cloud.githubusercontent.com/assets/7809511/13650425/62db308e-e621-11e5-94dd-aa2f49528862.png)
@elieserdejesus

**Comment by elieserdejesus** [comment]
cara, que doidera é essa? hehehe  Amanhã a tarde eu estarei por aí, podemos conversar pessoalmente e tentar entender esse desenho complexo :)

**Comment by noschang** [comment]
Rebases... o que são? Como funcionam? De onde vieram? Quem pode fazê-los?

Sexta, no Globo Repórter!!
![images](https://cloud.githubusercontent.com/assets/709553/13657328/20ae06f6-e64d-11e5-8ca0-e9727e3b0e68.jpg)

**Comment by rytix** [comment]
Se você olhar bem parece até que o branch ficou 3D haha

**Comment by AlissonSteffens** [comment]
Rebase
