### ISSUE TITLE
Quebras de linha zoadas

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#111]
Quando o exemplo da Bateria é aberto, aparecem uns retângulos vermelhos. Acreditamos que seja algum problema no caractere de terminação de linha.

![12325639_1265682756780229_885184210_o](https://cloud.githubusercontent.com/assets/709553/13651239/40cdc48a-e625-11e5-99b5-f3e8fca29d20.jpg)

**Comment by rytix** [comment]
Os caracteres vermelhos são explicados no  #75 bug do batman aonde o portugol não se importa com certos caracteres especiais (Apenas os bota em vermelho).

Esses espaços em brancos não são espaços em brancos normais, são caracteres especiais espiões disfarçados de espaços em branco

**Comment by AlissonSteffens** [comment]
São os /r e /n

**Comment by noschang** [comment]
Concordo com o @AlissonSteffens. Linux e Mac usam só \n para final de linha. Windows (tinha que ser o Windows de novo) coloca \r\n como quebra de linha. :-(

Podem deixar essa aqui pra mim que eu vou resolver.

**Comment by elieserdejesus** [comment]
@AdsonEsteves , o @dgadelha mencionou que esse bug não existe mais na versão 2.6. Podes verificar e fechar a issue em caso positivo?

**Comment by AdsonEsteves** [comment]
@elieserdejesus 

O \r e \n existem ainda, mas não tenho como verificar como está nas plataformas não-windows

Provavelmente quem pode testar é você mesmo ou talvez o @andrelms

**Comment by elieserdejesus** [comment]
funcionando!
