### ISSUE TITLE
Analisador semântico ignora chamadas de biblioteca incompletas

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#113]
Parece que a biblioteca ignora algumas coisas como vetores, matrizes e por algum motivo sobrenatural uma virgula

Aceitando uma virgula:
![image](https://cloud.githubusercontent.com/assets/7809511/13684446/7f358d32-e6ea-11e5-934a-5a54e4bb3112.png)

Aceitando vetores e matrizes
![image](https://cloud.githubusercontent.com/assets/7809511/14750296/67d92c6c-089a-11e6-8efd-9508049de7af.png)
![image](https://cloud.githubusercontent.com/assets/7809511/14750504/859fa0ea-089b-11e6-854f-0cca78b2c27a.png)

**Comment by rytix** [comment]
Tua culpa @AlissonSteffens

**Comment by AlissonSteffens** [comment]
Este erro é referente ao núcleo e está sendo resolvido [aqui](https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/96)

**Comment by AdsonEsteves** [comment]
O analisador semântico não consegue encontrar nenhum bloco com o seguinte código:
```
programa
{
	funcao inicio()
	{
		g.
	}
}
```

![image](https://user-images.githubusercontent.com/8836540/35936779-60d148e6-0c2b-11e8-8d7d-aecea5be5b73.png)


Provavelmente deve ser algum problema na sintaxe feita no antlr3
Como o analisador simplesmente não encontra de maneira alguma o trecho com "g." não é possível gerar erro por ele.

Talvez uma possibilidade fosse ler o código do usuário manualmente, e encontrar os lugares(exceto cadeias) em que há um "<qualquer caracter>.<espaço>".

**Comment by AdsonEsteves** [comment]
Movida para #314
