### ISSUE TITLE
Erros na ajuda

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#115]
* [x] Arrumar alguns exemplos do **Tente Você Mesmo** da ajuda estão com erros no código. ( @noschang )
* [x] Descobrir erro nas Listas nas seções retornam um NullPointer
![image](https://cloud.githubusercontent.com/assets/6234230/13754754/ecfb5720-e9f6-11e5-9dd9-d145b1647b9b.png)
* [x] Remover Seção **Ajuda Portugol Studio** pois ela não tem conteúdo
![image](https://cloud.githubusercontent.com/assets/6234230/13754735/e12a40dc-e9f6-11e5-9b56-078e9e3253cf.png)
* [x] Arrumar Problemas com tipo de arquivo

![image](https://cloud.githubusercontent.com/assets/6234230/13754968/c29e7e2a-e9f7-11e5-8e89-d13b8db466b3.png)

**Comment by AlissonSteffens** [comment]
Muito very noice @rytix

**Comment by rytix** [comment]
Danke, Kamerad!
