### ISSUE TITLE
Vetor Infinito 

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#118]
O Portugol permite a criação de vetores e matrizes de **qualquer** tamanho o que leva muito tempo para a alocação, e faz com que o programa pareça travado por um tempo. O swing também para de responder durante a alocação.

```Java 
programa
{
	funcao inicio()
	{
		cadeia vet[999999999]
		escreva("oi")
	}
}

```

É necessário definir como tamanho máximo para os vetores de **16777216** posições e para as matrizes de **4096 x 4096**

**Comment by rytix** [comment]
Se não me engano isso vai mexer na analise semântica do núcleo.

**Comment by AlissonSteffens** [comment]
Resolvido
https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/69
