### ISSUE TITLE
Requisitos para lançar nova versão para atualização

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#119]
* [x] Testar o Atualizador migrando da v 2.2 para a mais atual
* [x] Testar o Atualizador migrando da versão atual para um hotfix
* [x] Testar o Atualizador migrando da v 2.2 para a mais atual em alguns labs da Univali
* [x] Testar se nos labs da Univali a atualização feita por um usuário/código de pessoa é válida para os demais usuários.
* [x] Testar o Depurador
* [x] Ajuda @rytix 
* [x] Verificar Documentação Bibliotecas

**Comment by elieserdejesus** [comment]
@noschang , @rytix , @AdsonEsteves e @AlissonSteffens , quebrei os testes do atualizador em 3 items só para ficar mais claro. Se vocês tiverem outras ideias de testes importantes adicionem na lista também. @noschang , o atualizador já foi testado alguma vez nas máquinas da Univali? Achas que pode dar problema pela falta de privilégios de administrador?

**Comment by noschang** [comment]
@elieserdejesus, não tem problemas com permissões. O Portugol Studio se instala em uma pasta na qual ele tem acesso total de escrita. Isto vale para as 3 plataformas.

**Comment by elieserdejesus** [comment]
@noschang , no caso dos Labs da Univali (e possivelmente isso também vale para outras instituições), é uma instalação/atualização por usuário, ou se atualizar isso vai valer para todos?

**Comment by noschang** [comment]
@elieserdejesus, é uma única atualização pra todo mundo. Configurações como temas, tamanhos de fonte e saves dos jogos de exemplo são separados por usuário.

**Comment by elieserdejesus** [comment]
maravilha @noschang , adicionei mais um teste na lista desse PR para confirmar se a atualização feita por um usuário estará disponível para todos.

**Comment by AlissonSteffens** [comment]
fis o teste da versão 2.2 para a atual... O único problema é bem leve na real, o Atualizador Não muda seu JS?? porque dai a tela de loading ("durante o primeiro load da instalação só") não muda a cor da barra de load (é uma diferença leve, mas é diferente)

como é:
![image](https://cloud.githubusercontent.com/assets/6234230/13884601/6fd0a592-ed0d-11e5-9ae7-47ad7e965314.png)
Como deveria ser:
![image](https://cloud.githubusercontent.com/assets/6234230/13884622/8e44e830-ed0d-11e5-8dcd-20e662c549e0.png)

**Comment by AlissonSteffens** [comment]
@noschang talvez saiba explicar melhor o que acontece

**Comment by AlissonSteffens** [comment]
Fiz a verificação das bibliotecas e suas devidas alterações no pull #120 do Studio

**Comment by rytix** [comment]
Terminei de corrigir os bugs da ajuda.
Assim que o mec parar de nos expulsar do laboratório eu dou commit na Ajuda e no studio @AlissonSteffens :8ball:

**Comment by AlissonSteffens** [comment]
__Parece estar pronto :3__
Vamos terminar os últimos detalhes na interface e se tudo der certo lançamos até Quarta (13/04)

**Comment by elieserdejesus** [comment]
Maravilha pessoal! Então os testes de atualização funcionaram perfeitamente nos labs?

**Comment by AlissonSteffens** [comment]
Funcionaram de boas :+1:

**Comment by AlissonSteffens** [comment]
Moon Lander Maroto
![image](https://cloud.githubusercontent.com/assets/6234230/14397389/75cdadee-fdb3-11e5-89a9-e615cae5258a.png)

**Comment by AlissonSteffens** [comment]
O erro com as cores do atualizador foi resolvido pelo @noschang  e agora o Studio sabe atualizar o inicializador :3
