### ISSUE TITLE
Detalhes da Tela Inicial

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#123]
@noschang , @rytix , @AdsonEsteves  e @AlissonSteffens , notei 2 detalhes na nova tela inicial do PS que gostaria de discutir com vocês:

1 - Quando o PS abre a árvore (lado esquerdo) com os exemplos aparece expandida. Por conta disso somente os primeiros exemplos ficam visíveis, e estes exemplos nem são os "mais legais". Eu acho que iniciar com a árvore "fechada/contraída" deixaria mais claro para o usuário que existem várias "categorias" de exemplos. Na minha opinião, a árvore expandida não deixa claro que existem outras categorias de exemplos. Talvez eu esteja achando isso porque estou executando no notebook, e em uma tela pequena somente os 2 primeiros nós expandidos da árvore são exibidos, e fica um pouco confuso, não fica tão claro que existem outros nós mais abaixo até você usar a rolagem. Talvez vocês não tenham percebido isso porque estão programando em monitores maiores. Gostaria da vossa opinião sobre o tópico :)   Estou botando um print do meu desktop para vocês terem uma ideia de como fica a tela inicial aqui.

2 - A ideia de mostrar uma descrição do exemplo na tela inicial é muito boa. Vi que no caso das aplicações gráficas também é mostrada uma imagem do exemplo executando, o que é muito bom. Entretanto, a grande maioria dos exemplos não tem uma imagem associada, e fiquei com impressão de que mostrar somente um texto descritivo para essa maioria dos exemplos é uma sub utilização desse "painelzão" da tela inicial (me refiro ao painél onde a descrição é apresentada). Acredito que seria muito útil para os alunos terem uma imagem/visualização de todos os exemplos antes de abrirem. Por exemplo, o aluno pode estar apenas querendo tirar uma dúvida rápida sobre sintaxe, ou mesmo verificar como se faz um "se", e apenas olhando um "preview" do exemplo de código ele já resolveria isso, sem a necessidade de "explorar o exemplo". Para fazer esse "preview" dos exemplos eu pensei em duas ideias (fiquem a vontade para pensar em outras possibilidades):
    **1 - Tirar um print de cada exemplo.** Funciona, mas é chato de fazer, e se o código do exemplo mudar o print não muda. Entretanto, é a abordagem mais rápida. Mesmo tendo que abrir cada exemplo e tirar um print do código ainda é mais rápido do que a solução 2.
    **2 - Implementar uma pré-visualização "real" dos código dos exemplos.** Teríamos um editor "somente leitura" na tela inicial onde o código do exemplo é carregado. Acho que esse editor poderia ser exibido somente quando o exemplo não tem uma imagem associada. Por exemplo, no caso dos jogos mostraríamos apenas a imagem, e não o código. Mostrar o código só faz sentido em códigos pequenos. O que acham?

![image](https://cloud.githubusercontent.com/assets/1012741/14016445/428293de-f19f-11e5-8fad-cb2426fe72d3.png)

**Comment by noschang** [comment]
@elieserdejesus, concordo com você em algumas coisas. Também acho estranho a tela inicial vazia. Na verdade se você notar, vai ver que na última versão, ao selecionar um exemplo sem print, é exibido um ícone de lâmpada.

O @AlissonSteffens, colocou este ícone provisoramente, mas a idéia era colocar uma imagem do LITE explorando um exemplo ou apontando para a árvore de exemplos. Mas acho sua idéia bacana também.

Quanto aos nós iniciarem contraídos. Esta era nossa idéia inicial, mas aí o Raabe falou pra mudar e colocar já aberto, então seguimos a orientação dele (meio contrariados, devo dizer, kkkk). Mas eu também acho que deveria vir fechado.

A solução nº 1, apesar de parecer mais rápida no início, pode acabar levando mais tempo do que a nº 2, já que são mais de 30 exemplos ao todo. Talvez implementar um renderer dê bem menos dor de cabeça. Veja que a ajuda já faz isso, então dá pra tentar reaproveitar algum código.

Enfim, vamos conversando...

**Comment by AlissonSteffens** [comment]
Se o MEC deixar, eu implemento isso ainda hoje. Como o @noschang disse, o fato de vir aberto ou fechado ja havia sido debatido. De qualquer forma, achei legal a ideia do código fonte aparecer nesta tela, e vou implementar assim que possível :+1:

**Comment by elieserdejesus** [comment]
Ok pessoal, vamos deixar a árvore aberta então, e acho que o renderer para os exemplos na tela inicial vai ficar show de bola.

Talvez o André tenha visto a árvore aberta no monitor que ele usa no LITE e gostou da ideia, mas em monitores pequenos tem esses problemas que eu mencionei. Podemos tentar convencer ele quando voltar :)
