### ISSUE TITLE
Mensagem Assustadora em operações incorretas que não envolvam reais/inteiros

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#126]
Para qualquer operação (exceto +) que não envolva reais ou inteiros, o portugol manda a mensagem correta e em seguida uma mensagem assustadora com o local da exceção para o aluno.

Parece que este erro está relacionado ao escreva.
######
![image](https://cloud.githubusercontent.com/assets/7809511/14121270/12922b26-f5cd-11e5-86da-3f905221d043.png)
######
![image](https://cloud.githubusercontent.com/assets/7809511/14121299/37006036-f5cd-11e5-978e-a516903ebfe2.png)
######
![image](https://cloud.githubusercontent.com/assets/7809511/14121318/4753ea8e-f5cd-11e5-906a-56cdb7b561c6.png)
######
# Porém não ocorre nos seguintes casos:
![image](https://cloud.githubusercontent.com/assets/7809511/14121658/b9963bbe-f5ce-11e5-85e5-749f8e76eb15.png)
######
![image](https://cloud.githubusercontent.com/assets/7809511/14121685/d772ee34-f5ce-11e5-8a78-4ba1a7de333d.png)
######
![image](https://cloud.githubusercontent.com/assets/7809511/14121732/fcfeffc6-f5ce-11e5-81c7-093439455b5e.png)
######

**Comment by AlissonSteffens** [comment]
Boa @rytix, agora mesmo que o Portugol nunca vai ser lançado!!!

**Comment by rytix** [comment]
:angel:
