### ISSUE TITLE
Nullpointer ao fechar um programa antes de sua execução ser finalizada

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#133]
Mesmo que o Portugol tenha uma maneira de impedir o fechamento caso o programa esteja executando:

![image](https://cloud.githubusercontent.com/assets/8836540/14469913/2e61d0cc-00bd-11e6-812d-03e685c7e4c8.png)

Caso o programa use o ambiente gráfico e o botão fechar da janela seja clicado, o programa pode acontecer de demorar a parar a execução, nesse meio tempo, é possível fechar o programa. Um bom exemplo que isso pode acontecer é o da bateria. O exemplo se fechado enquanto está rodando com muitas batidas tocando:

![image](https://cloud.githubusercontent.com/assets/8836540/14470070/f39912d8-00bd-11e6-9058-5a6d8092f610.png)

Pode acontecer dele demorar a parar a execução, dando a oportunidade de fechar o arquivo:

![image](https://cloud.githubusercontent.com/assets/8836540/14470138/45fc9d60-00be-11e6-9d13-1e9a4ab4df9d.png)

E um tempo após fechar o arquivo nesse meio tempo:

![image](https://cloud.githubusercontent.com/assets/8836540/14470197/827342a8-00be-11e6-831f-b223e3816ef6.png)

**Comment by AlissonSteffens** [comment]
Parece que o erro foi corrigido pelas alterações na biblioteca de audio do @elieserdejesus confere?

**Comment by elieserdejesus** [comment]
Não vi esse erro na última versão @AlissonSteffens , acho que está resolvido.

**Comment by AdsonEsteves** [comment]
Foi verificado que a tela de Null Pointer não ocorre mais.
Porém ainda é possível fechar a aba antes da finalização, e em alguns casos raros, o som continua com o programa finalizado.

**Comment by AlissonSteffens** [comment]
@AdsonEsteves , a versão atual ainda mantém o comportamento?

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 

Acredito que ainda está como no meu comentário acima.
Mas não tenho certeza, preciso testar em um pc lento q

**Comment by elieserdejesus** [comment]
O nome da issue é "Nullpointer ao fechar um programa antes de sua execução ser finalizada". Como isso não acontece mais estou fechando a issue. O problema do som não finalizar seria outra issue caso confirmado. É importante quebrarmos as issues para evitar big issues como "Arrumar tudo que precisa ser arrumado" :)
