### ISSUE TITLE
Aprimorar filtros na árvore de símbolos

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#134]
@noschang , @AlissonSteffens , @rytix , @AdsonEsteves , fui testar a implementação dos filtros da árvore que o Noschang fez. Abri o exemplo da bateria e observei 2 problemas:

1 - Dá um warning em uma das funções da bateria. O núcleo deve ter mudado desde que o código da bateria foi escrito e está fazendo alguma checagem que não fazia antes.

2 - A árvore apareceu vazia, tentei ligar e desligar os filtros e não adiantou. Acredito que não seja problema da árvore, acho que o erro descrito anteriormente está impossibilitando a criação da árvore, ou alguma coisa nesse sentido.

**Comment by noschang** [comment]
@elieserdejesus. O problema do warning já foi detectado e resolvido. Você deve estar com uma versão desatualizada. Dê um pull no projeto Portugol-Studio-Recursos.

Quanto à árvore iniciar vazia, o problema é que eu não tinha incluído no filtro o TipoDado.VAZIO. Daí as funções como "inicio()" que tem retorno vazio não apareciam.

Eu já corrigi isso também e já integrei no master.

Pode dar um pull no master do teu Portugol-Nucleo e do Portugol-Studio e testa novamente, por favor.

**Comment by elieserdejesus** [comment]
Funcionando @noschang , realmente faltava dar o pull no repositório dos recursos.

Os filtros ficaram show de bola. Tenho duas sugestões de melhoria:
1 - Não temos um feedback visual da filtragem. Por exemplo, você clica em um dos botões de filtro e não dá pra ver o que aconteceu com a árvore poque o painél dos botões de filtro cobre a árvore. Não sei como isso poderia ser resolvido, mas a ideia geral seria: **possibilitar que o usuário veja o resultado da filtragem no momento em que ela é selecionada**.

2 - Eu estava com todos os filtros desmarcados. Cliquei em "variáveis" e nada apareceu na árvore. Tive que pensar um pouquinho para descobrir que ainda é necessário marcar um dos filtros de tipo para que as variáveis apareçam na árvore. Minha sugestão é: ao clicar em "variáveis", se nenhum tipo estiver marcado todos os tipos são marcados automaticamente. Talvez eu esteja enganado, mas eu penso que quando eu digo "quero ver as variáveis" está implícito que eu "quero ver as variáveis, todas elas, não importa o tipo".

**Comment by noschang** [comment]
@elieserdejesus, item 2 está feito!

**Comment by noschang** [comment]
@elieserdejesus, o item 1 eu estou com preguiça. Talvez eu faça... mas só, talvez...

**Comment by elieserdejesus** [comment]
hehehe, o item 2 só é problema se o spliter da árvore não for alterado. Se aumentar a largura do spliter eu acredito que a árvore fica visível embaixo do painél dos botões de filtro.

**Comment by AlissonSteffens** [comment]
Não sei o que dizer sobre esta issue. vou fecha-la e marcar para um dia talvez abrir de novo caso alguém queira fazer isso.
