### ISSUE TITLE
Imagem da tela inicial pode ter interpretações diferentes daquelas originalmente imaginadas

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#135]
@noschang , @AdsonEsteves , @AlissonSteffens , @rytix , em primeiro lugar parabéns pelo trabalho na nova interface. Super duper clean!

Um detalhe na tela inicial chamou a minha atenção, é um "negócio" meio engraçado, mas acho que vale a pena discutirmos a questão.  Na tela inicial do PS é mostrada essa imagem:
![image](https://cloud.githubusercontent.com/assets/1012741/14504546/ad5244c4-018b-11e6-9911-a01cd127c4c9.png)
Vejam que um personagem está falando para a parte traseira da cabeça do outro. O personagem que ouve está com atitude de "tô nem aí", de costas para o seu interlocutor :)  A posição dos braços do mascote também pode sugerir coisas que eu prefiro nem comentar aqui, hehehe.

A solução é simples:
![image](https://cloud.githubusercontent.com/assets/1012741/14504760/803e52c4-018c-11e6-9bc1-5ba79d526527.png)

**Comment by AdsonEsteves** [comment]
Bom, é que na teoria, ambos os personagens estariam "olhando"(ao mesmo
tempo que mostrando) os exemplos. E acredito eu que se você virar o menino,
não vai mais parecer que eles estão mostrando os exemplos, e sim falando
entre si. Talvez uma solução boa no caso seria retirar o menino, e deixar o
litebot mais no meio.

2016-04-13 15:29 GMT-03:00 Elieser Ademir de Jesus <notifications@github.com

**Comment by noschang** [comment]
Faz um gif com o menino virado inicialmente pra frente e depois para o outro lado. :-p

**Comment by elieserdejesus** [comment]
@AdsonEsteves , Acho que só o mascote é uma boa solução. 

Outra coisa: o balão de diálogo diz "Aqui você pode ver os exemplos ...".  Esse **Aqui** é um pequeno problema. O mascote está bem longe dos exemplos mesmo em uma tela pequena (imagine em uma tela grande), então esse "Aqui você pode ver" gera umas perguntas: **aqui? onde? Ah, ali no lado...** . Depois de pensar um pouco obviamente as peças se encaixam, mas como você sabe a ideia para uma boa interface é "não me faça pensar". 

Tenho duas sugestões: **1)** fazer o mascote (que ficaria no centro) apontar para os exemplos e mudar o texto para "Ali você pode ver os exemplos ..." e **2)** Deixar o robô/mascote alinhado na esquerda, assim o "Aqui você pode ver ..." fará mais sentido. Mesmo nessa segunda sugestão acho que seria muito bom ter o mascote apontando para os exemplos.
