### ISSUE TITLE
Crise existencial de uma humilde variável (atribuição indireta dela mesma).

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#137]
Ao se criar uma variável global e em sua própria declaração chamar uma função que retorna o valor de sua própria variável.
Ela não sabe se deve existir.
![image](https://cloud.githubusercontent.com/assets/7809511/14684862/440e8c0c-0708-11e6-8dc4-d55d0bd00b72.png)

**Comment by elieserdejesus** [comment]
@AdsonEsteves , o @ggadelha comentou que esse bug também não existe na versão 2.6. Podes confirmar e fechar a issue?

**Comment by AdsonEsteves** [comment]
@elieserdejesus 

Está retornando 0 na variável, porém não tenho certeza se isso estaria certo já que a variável em si deveria estar nula

**Comment by AlissonSteffens** [comment]
Não tá mais dando erro, então eu acho que a Issue tá resolvida... não???

**Comment by AdsonEsteves** [comment]
Não dá erro, mas retornar 0, é o que realmente deveria acontecer?

**Comment by AlissonSteffens** [comment]
O erro não existe mais, estou fechando a issue.

Caso o debate seja sobre 0 ser a melhor solução, criar outra issue
