### ISSUE TITLE
Erro de variável não inicializada aparece dependendo da ordem das funções.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#138]
Permite compilar e é valido:
![image](https://cloud.githubusercontent.com/assets/7809511/14685207/0ef29782-070a-11e6-99cf-9ef330101820.png)
Não permite compilar e é valido:
![image](https://cloud.githubusercontent.com/assets/7809511/14685221/1e59a38c-070a-11e6-98ef-8cbfc9fee40f.png)
--- A contra partida ---
Permite compilar, porém gera um erro em tempo de execução:
![image](https://cloud.githubusercontent.com/assets/7809511/14685259/412dcc6c-070a-11e6-99cc-2d038b70ff01.png)
Não permite compilar, porém geraria um erro em tempo de execução se permitisse:
![image](https://cloud.githubusercontent.com/assets/7809511/14685274/592714d6-070a-11e6-99a7-0a6ffdc6367b.png)

É preciso entrar em um consenso, que independente da ordem que as funções são apresentadas no programa, ele permita compilar uma variável não inicializada ou não permita.

**Comment by AlissonSteffens** [comment]
não acontece mais, o programa retorna 0, quando manda escrever antes de inicializar, sobre isso vale o cementário que fiz na https://github.com/UNIVALI-LITE/Portugol-Studio/issues/137

Por o erro especificado não aparecer mais, estou fechando a issue
