### ISSUE TITLE
Guardar em uma posição de vetor a soma de outro "vetor"

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#141]
Erro:
![image](https://cloud.githubusercontent.com/assets/7809511/14751861/8b6474f4-08a2-11e6-83e4-6b489799b84a.png)

**Comment by AlissonSteffens** [comment]
![image](https://user-images.githubusercontent.com/6234230/30893257-9630923e-a313-11e7-8f69-5133569a043f.png)
Problema resolvido, fechando esta issue

**Comment by AlissonSteffens** [comment]
![image](https://user-images.githubusercontent.com/6234230/30893277-afaeffca-a313-11e7-8871-7fe7193ba88b.png)
problema resolvido, fechando esta issue
