### ISSUE TITLE
Autosave ao compilar (Funcionalidade Nova)

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#143]
No momento que o Portugol compila o código fonte.
Momento aonde ele gera a arvore de variáveis, checa por erros sintáticos/semânticos e etc...
Seria muito interessante ele possuir um Autosave de recuperação.

Isso é importante para quando o PC dele explodir por um ataque de arraias gigantes montadas em Velociraptors com lança granadas e um pequeno esquilo chamado gruffy.

Caso ele recupere seu HD, o programa que ele estava fazendo no Portugol Studio não será perdido :)

Algumas tarefas que seria interessante essa funcionalidade possuir:
- [x] Criar pelo menos 3 Autosaves e revezar a tarefa de salvamento entre eles (salvar no mesmo arquivo pode ser problemático caso o PC dele desligue no meio do save).
- [x] Não salvar em cima do save original (pode ser que o usuário simplesmente queria descartar tudo que fez)
- [ ] Salvar o estado de pelo menos X ações de desfazer (Ctrl Z).
- [ ] Abas diferentes sem serem salvas possuem Autosaves diferentes, abas que possuem já um save original mesmo que ele esteja repetido em diversas abas irá gerar apenas 3 Autosaves.
- [x] Decidir estratégia para se livrar dos Autosaves (por exemplo, antes do programa ser fechado corretamente, destruir os Autosaves / Destruir após 3 vezes que o programa seja fechado corretamente)
- [ ] Sempre abrir o Autosave mais recente em caso de recuperação. Se este estiver corrompido, o próximo, se este tiver corrompido também o próximo. Caso todos estejam corrompidos mostrar um vídeo de auto-ajuda para animar o usuário e ajuda-lo a passar por esta situação difícil.
- [x] Colocar um sistema de detecção de arraias.

**Comment by elieserdejesus** [comment]
+1 , um aluno solicitou isso na semana passada quando o computador travou complemente e ele perdeu o que estava fazendo. Como esperado o aluno ficou super feliz :)

**Comment by AdsonEsteves** [comment]
feito no #214
