### ISSUE TITLE
Suporte à dados estruturados

### ISSUE THREAD

**Issue by ramonchiara** [UNIVALI-LITE/Portugol-Studio#144]
Existe a possibilidade de se ter suporte à dados estruturados (record, struct)?

**Comment by andrepoleza** [comment]
Inclusive: existe a possibilidade de se ter suporte para [funções de ordem superior](https://en.wikipedia.org/wiki/Higher-order_function)?

**Comment by elieserdejesus** [comment]
@ramonchiara , suporte a dados estruturados é algo que está na TODO list, mas não tem uma prioridade alta.

@andrepoleza , as funções de ordem superior estão  fora do escopo da ferramenta no momento. Em algumas disciplinas quando chega o momento dos alunos estudarem funções (as tradicionais) eles já estão usando outras ferramentas (CodeBlocks por exemplo). Acho que seria um esforço desnecessário implementar funcões de ordem superior no PS, pouca gente usaria pelo motivo que mencionei antes (abandono da ferramenta antes que esse assunto torne-se interessante). Claro que tudo isso mudaria se os professores adotassem o paradigma funcional nos 1º períodos, mas aí já estamos falando de uma mudança que vai muito além de uma feature no PS.  De qualquer maneira agradecemos a ideia.
