### ISSUE TITLE
Escolha dentro de escolha de tipos diferentes.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#145]
_Bug relatado pelo Paulo Vieira e descoberto por um estudante dele durante a aula de algoritmos._
1. Você faz um primeiro escolha caso de um tipo (por exemplo inteiro)
2. Dentro do primeiro caso você bota outro escolha caso de outro tipo (por exemplo caracter), e bota quantos casos quiser.
3. Quando você volta para o primeiro escolha caso, e tenta botar outro caso. Ele da um erro falando que esperava o tipo do outro escolha caso.

Eu duvido que alguém tenha entendido a minha explicação, então como uma imagem vale mais que mil palavras segue a imagem do ocorrido:
![image](https://cloud.githubusercontent.com/assets/7809511/15225945/0b17110c-1857-11e6-8648-a41221a56014.png)

Código:
http://pastebin.com/d4dGAhmG

Acho que vale investigar como o analisador sintático está empilhando a função escolha

**Comment by noschang** [comment]
Resolvido no commit f5dff31df5e06ba56068eb8b1a9acc37639ee2c9, conforme tela abaixo:

![bug](https://user-images.githubusercontent.com/709553/30071710-2cb0a370-923e-11e7-9938-9415a465dd92.png)

Fechando a issue
