### ISSUE TITLE
Rever a posição do inspetor?

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#160]
Em sala de aula (usando projetores) é comum que a parte inferior da tela fique cortada por conta do posicionamento dos projetores em relação à tela de projeção. Por esse motivo em algumas situações o inspetor fica parcialmente visível. 
Já tive problemas com isso tentando mostrar vetores no inspetor em um projetor 800 x 600, com a parte inferior da tela cortada. Com uma resolução pequena nem sempre é possível usar o spliter para redimensionar a área do inspetor e tornar visíveis as variáveis inspecionadas. 

Uma solução simples seria deixar o inspetor no topo. Outra (mais complexa) seria permitir que esses blocos (inspetor, árvore, console) sejam arrastáveis, assim cada usuário montaria o seu próprio layout.

**Comment by noschang** [comment]
@elieserdejesus, apenas para registrar o que já conversamos pessoalmente.

Minha sugestão é que transformemos o painel da direita, onde se encontra a árvore e o inspetor em um JTabbedPane, colocando cada componente em uma aba.

Durante a edição de código fonte, o tabbed pane apresenta a árvore estrutural.
Quando porém o código é executado, alternamos automaticamente para a aba do inspetor. 

Por se tratar de um tabbed pane, o usuário pode voltar para a árvore durante a execução se assim desejar. Da mesma forma, pode visualizar o inspetor mesmo estando em modo de edição.

Ao finalizar a execução do programa, alternamos novamente para a ávore estrutural.

Podemos inclusive colocar  opções nos menus de configuração para que o usuário ajuste este comportamento. Por exemplo:

- [x] Exibir inspetor de variáveis ao executar um programa
- [x] Exibir árvore estrutural ao finalizar a execução de um programa

**Comment by elieserdejesus** [comment]
@noschang , acho que vale a pena finalizar aquela ideia de capturar as interações para termos mais certeza sobre como os usuários estão usando a gui atual.

**Comment by AdsonEsteves** [comment]
Acho que faz parte do mesmo assunto que #279

**Comment by AdsonEsteves** [comment]
Duplicate of #279
