### ISSUE TITLE
Biblioteca de sons (possivelmente) influenciando performance dos jogos

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#161]
Depois de comentar os métodos da biblioteca de sons percebi uma leve melhora na performance dos jogos mais pesados (Corrida e Balls). 

Acho que o caminho é uma usar apenas uma thread para o audio e mixar os vários AudioInputStream "on the fly".

**Comment by elieserdejesus** [comment]
@noschang , estou trabalhando na biblioteca de áudio tentando otimizar o máximo, mas mesmo assim estou percebendo que o áudio sempre influencia negativamente a performance dos jogos mais pesados.

Inspecionei o comportamento das threads do PS e surgiram algumas dúvidas que você esclarecer:
![image](https://cloud.githubusercontent.com/assets/1012741/18619124/eef0b864-7dca-11e6-839c-2fa108cc16f3.png)

Veja que existem 4 threads executando o tempo todo na minha máquina, e a julgar pelos nomes das threads eu fiquei com a impressão de que existem threads fazendo a mesma coisa. Tem uma thread chamada **Portugol Nucleo (Thread programa 0)** e outra chamada **Portugol-Studio (Thread principal)**.  Essa thread principal do Portugol Studio é realmente necessária? Estou questionando isso porque me parece que o PS roda quase todo na própria thread do swing, sendo assim, não seria necessária uma outra thread atuando como "principal".

Outra coisa que observei é que "parece" que existem duas threads relacionadas com UI: **AWT-Windows** e **Portugol-Studio (Swing)**. É isso mesmo ou a thread **AWT-Windows** é uma thread padrão do swing (no windows)?

**Comment by noschang** [comment]
@elieserdejesus, a thread AWT-Windows é padrão do SO, não está sendo criada pela gente. Então não há nada a fazer em relação a essa thread.

A thread 'Portugol Studio (Swing)' nada mais é a do que a thread do swing, que também é criada automaticamente pela JVM, a única coisa que eu fiz foi renomear ela pra que ficasse mais fácil de identificar que esta é a thread onde ocorrem as atualizações de tela no Studio.

Já as threads Portugol Studio (Thread principal) e Portugol Nucleo (Thread Programa 0) são threads criadas por nós em Executor Services. Mais especificamente em thread pools.

A thread do núcleo, como o próprio nome diz, serve para rodar os programas. Supondo que o usuário rode 4 programas em 4 abas diferentes ao mesmo tempo, haveria 4 threads dessas, uma para cada programa. Como é o pool que gerencia essas threads, ela acaba ficando 'viva' porém inativa a maior parte do tempo.

Já a thread Portugol Studio (Thread Principal) é a thread responsável pelos processo em segundo plano do Studio. Note que ela não é uma thread redundante com o mesmo propósito da thread Portugol Studio (Swing), na verdade elas fazem coisas diferentes. É mais ou menos assim, a thread Portugol Studio (Thread principal), chama o compilador do núcleo em segundo plano para gerar a árvore abstrata, assim não trava a interface durante o processo, quando o processo termina ela invoca a thread do swing para adicionar e renderizar estes nós na árvore. Esta mesma thread dispara o atualizador automático em segundo plano.

**Comment by AlissonSteffens** [comment]
Já aproveitando a fala sobre o atualizador... O que acham de removermos os códigos relacionados a atualização automática do Portugol, e implementar um "LITE-Updater", um programinha que atualiza os softwares do Lite (já em preparação para os próximos) no mesmo estilo do adobeUpdater. ??? :)

**Comment by noschang** [comment]
@AlissonSteffens, acho a idéia muito boa. Mas se formos fazer um atualizador desses, sugiro fazermos em C++, possivelmente usando QT.

**Comment by elieserdejesus** [comment]
Fechando a issue, depois de algumas inspeções junto com o Noschang vimos que o problema é a atividade frenética do Garbage Collection, o problema não tem relação com a thread de som diretamente.
