### ISSUE TITLE
Exceção ao clicar em indicador de erro

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#163]
O código abaixo

```
programa
{
    funcao inicio()
    {
        inteiro x = 1
        x = x << verdadeiro
    }
}
```

gera um erro em tempo de execução:
![image](https://cloud.githubusercontent.com/assets/1012741/18786351/d222e9f8-8173-11e6-87f4-2e2103ae0bac.png)

Ao clicar no indicador do erro em **Mensagens** acontece uma _BadLocationException_ na console do NetBeans.

**Comment by elieserdejesus** [comment]
Testei isso no Ubuntu e não deu a BadLocationException, talvez isso já tenha sido corrigido em outros commits. 

O que poderíamos rever é essa mensagem que está sendo exibida para o usuário.

**Comment by AlissonSteffens** [comment]
O problema do null pointer já havia sido resolvido!

**Comment by AlissonSteffens** [comment]
Aproveitiei e melhorei a mensagem 👍 
![shifts](https://user-images.githubusercontent.com/6234230/29841966-c74afd88-8cdd-11e7-88bb-d9521840c2a8.gif)
