### ISSUE TITLE
Modificações que não são do exercito mas fazem sentido

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#176]
- [ ] Permitir alocação dinamica de vetores e matrizes
 - [ ] Aceitar ponto e virgula e palavras reservadas em inglês
 - [ ] Permitir estrutura de dados

**Comment by elieserdejesus** [comment]
@AlissonSteffens , cada uma dessas issues dá um trabalho enorme, o ideal seria separar em 3 issues no mínimo.

**Comment by AlissonSteffens** [comment]
Estas modificação já foram debatidas, vou fechar esta Issue

**Comment by noschang** [comment]
> Estas modificação já foram debatidas, vou fechar esta Issue

@AlissonSteffens, e quais foram as conclusões?
Registra aqui por favor, pra gente poder reabrir a issue quando/se for necessário.
