### ISSUE TITLE
Bug no salvamento das configurações

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#178]
@AlissonSteffens, @AdsonEsteves e @noschang , a implementação do **Lancador** gerou efeitos colaterais. 

Agora a **TelaPrincipal** não é mais um JFrame, é apenas um JPanel. Isso faz com que o [listener da janela](https://github.com/UNIVALI-LITE/Portugol-Studio/blob/f8824ca7249ff5421bf561c035c874022eeb6aa0/src/br/univali/ps/ui/telas/TelaPrincipal.java#L106) não seja mais invocado. Consequentemente as configurações não são mais salvas. Se vocês mudarem o tamanho de qualquer fonte e abrirem o PS novamente as alterações não valerão.

Além disso acho que deve ter bugado as features que eram invocadas no evento de abertura da TelaPrincipal. Ou seja, tudo que estava implementado usando eventos de janela (WindowListener) na TelaPrincipal provavelmente não está mais funcionando.

**Comment by AlissonSteffens** [comment]
Eitaaaaaa :octocat:

**Comment by AdsonEsteves** [comment]
Resolvido no e27a402d75b713ffd74a75023dc31dcb3754765e
