### ISSUE TITLE
Exemplos com problemas

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#183]
Subrotinas>Animação
  -Erro de Compilação

Bibliotecas>Arquivos>Selecionar e Ler Arquivo
  -Código Vazio

Bibliotecas>Utils>Gráficos>Fractal Rem
  -Erro de ArrayOutOfBounds ao apertar Enter

**Comment by elieserdejesus** [comment]
@noschang , @AdsonEsteves e @AlissonSteffens , vocês acham que vale a pena trabalhar nessa issue para o release 2.6? 

O exemplo **Bibliotecas>Arquivos>Selecionar e Ler Arquivo** está vazio? Se é isso mesmo não vale a pena dar prioridade para corrigir um exemplo que nem existe, certo?

**Comment by noschang** [comment]
Tem vários arquivos vazios na pasta de exemplos. Fui eu que acrescentei eles lá, mas eles não aparcem na tela pro usuário.

O objetivo de eu ter criado estes arquivos vazios é porque eu queria deixar registrado pra lembrar que queria fazer estes exemplos mas em outro momento.

**Comment by elieserdejesus** [comment]
@noschang , tu achas que vale a pena mexer nessa issue para a versão 2.6? Eu acho que não vale a pena.

**Comment by noschang** [comment]
Não acho que vale a pena. Só quis explicar o motivo, causa, razão e circunstância de existir arquivos vazios dentro da pasta Exemplos.

**Comment by AlissonSteffens** [comment]
Os exemplos citados e que tinham problemas estão funcionando, estou fechando a Issue
