### ISSUE TITLE
Funcionalidade "Arquivos recentes" não está funcionando no Linux Mint

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#184]
O arquivo "arquivos_recentes.txt" é salvo na pasta do usuário, mas quando o Portugol Studio abre, os arquivos não são listados na tela inicial.

Verificar se o problema também ocorre no Mac e em outras versões do Linux (Ubuntu, etc).

**Comment by AdsonEsteves** [comment]
Aparentemente, no MAC, funciona, pelo menos, vi funcionando no do @elieserdejesus

**Comment by elieserdejesus** [comment]
Testei no Ubuntu e funcionou. Como esperado os exemplos não aparecem na lista de arquivos recentes, mas se eu crio um programa e salvo ele aparece na lista de "recentes".

**Comment by AlissonSteffens** [comment]
Gostaria de saber se este problema ainda está ocorrendo, @elieserdejesus @noschang @AdsonEsteves ??

**Comment by elieserdejesus** [comment]
No Ubuntu está funcionando corretamente.

**Comment by AlissonSteffens** [comment]
@AdsonEsteves podes verificar isso?? Acho interessante acabar com esse dúvida de uma vez por todas o mais rápido possível

**Comment by elieserdejesus** [comment]
>  Acho interessante acabar com esse dúvida de uma vez por todas o mais rápido possível

@AlissonSteffens , tenho que discordar de você quanto a prioridade sugerida (**o mais rápido possível**). Acho que isso realmente não tem uma prioridade alta. Quantos usuários de **Mint** o PS tem? Sei que não temos a informação, mas e se você tivesse que fazer uma estimativa?

**Comment by AlissonSteffens** [comment]
@elieserdejesus a questão não é resolver, mas tenho quase certeza que o problema já foi resolvido quando foi resolvido no ubuntu, visto que o Mint usa o ubuntu como core.
Sendo assim temos issue que provavelmente já está resolvida, mas que tá aqui enrolando.

**Comment by AlissonSteffens** [comment]
Ainda sim, pelos dados atuais, cerca de 15% dos usuários desta versão Rc2 usam Linux. Não consigo porém dizer quantos destes usam o Mint.

**Comment by elieserdejesus** [comment]
>  a questão não é resolver, mas tenho quase certeza que o problema já foi resolvido quando foi resolvido no ubuntu, visto que o Mint usa o ubuntu como core.

Entendo Alisson. Se não me falha a memória quem reportou o problema foi o @noschang quando ele usava o Mint. Na mesma época em que o Nochang viu o erro no Mint nós não vimos o erro no Ubuntu, então não tenho certeza se *resolver no Ubuntu == resolver no Mint*. Outra possibilidade seria a conta de usuário do Nochang no Mint ter algum privilégio diferentão. Nesse caso seria um problema do **Mint do Noschang**, e não do Mint 😄 

> cerca de 15% dos usuários desta versão Rc2 usam Linux. Não consigo porém dizer quantos destes usam o Mint.

Eu chutaria de maneira otimista que no máximo 1/4 desses 15% estão usando Mint. E tu @noschang , qual seria o teu chute 😄 ?

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 

Só deixar claro que adoraria resolver, se eu usasse um Linux Mint

**Comment by AdsonEsteves** [comment]
De acordo com o @rytix 

Não há problemas
