### ISSUE TITLE
Versão 2.5 Linux

### ISSUE THREAD

**Issue by Synk0** [UNIVALI-LITE/Portugol-Studio#185]
No Source Forge a ultima atualização para o Linux foi 2.2, pararam de desenvolver para o Linux?

**Comment by noschang** [comment]
Oi @Synk0. Realmente a última versão para Linux foi a versão 2.2.

Nós não paramos de desenvolver para Linux. O que acontece é que tivemos que priorizar a versão para Windows porque ela representa a maior parte do nosso público alvo.

Temos uma equipe pequena (4 pessoas) e nem sempre conseguimos atender a todas as demandas em tempo hábil. Por isso resolvemos pular a versão 2.5 para Linux.

Na próxima versão, lançaremos simultaneamente para Windows, Linux e Mac.
Obrigado por utilizar o Portugol Studio.

**Comment by Searchx01** [comment]
olá, na minha escola os computadores usam windows e tem o software na versão 2.5, existe muita diferença da versão 2.2 do linux, não quero ter que usar wine ou dualboot para estudar em casa

**Comment by elieserdejesus** [comment]
@Searchx01 , vamos lançar a versão 2.6 em breve.
