### ISSUE TITLE
Quebra de linha automático sem \n

### ISSUE THREAD

**Issue by vinycc** [UNIVALI-LITE/Portugol-Studio#190]
A cadeia escrita no escreva está sendo exibida com quebras de linha e tabulação, mesmo sem os caracters especiais \n e \t.

Isso está correto? deve realmente permitir ou não/

![bug portugol](https://cloud.githubusercontent.com/assets/279117/24731621/a53910cc-1a41-11e7-9391-274cdd335f83.PNG)

**Comment by elieserdejesus** [comment]
@vinycc , 
> Isso está correto? deve realmente permitir ou não/

conversamos aqui e achamos que seria melhor corrigir esse comportamento. Apesar de ser prático quebrar as linhas apenas pressionando ENTER o resultado geral pode ser bastante confuso para os alunos iniciantes.

**Comment by edusantana** [comment]
Ruby tem vários mecanismos de string, são tantos que eu nunca decoro. Eu gosto do `<<-` e do `%Q`. 

- https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc
- http://dereke.github.io/multiline-text-and-string-interpolation/

As vezes eu tenho problema quando desejo fazer um string que contém `"` ou `\`. É chato fazer os escapes deles, isso acontece com frequência comigo.
