### ISSUE TITLE
Feedback durante a compilação dos programas

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#194]
Está faltando mostrar algum feedback enquanto o programa está sendo compilado. A ideia era mostrar o ícone de "aguardando" ou o GIF "carregando" que já existe no PS.

@AdsonEsteves , podes assumir essa tarefa?

**Comment by AdsonEsteves** [comment]
okey

**Comment by AdsonEsteves** [comment]
Feito no #197
