### ISSUE TITLE
Avisos desaparecem na abertura e após execução do código

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#198]
Quando um programa com avisos é aberto, poucos segundos depois, os avisos desaparecem.
Porém se uma modificação no código ocorre, os avisos voltam normalmente

![image](https://cloud.githubusercontent.com/assets/8836540/24923362/abfbed14-1ec7-11e7-8d50-64edac16cc8a.png)

**Comment by elieserdejesus** [comment]
@AdsonEsteves , acho isso não é tão prioritário para esse release. O que achas @noschang ?

**Comment by AlissonSteffens** [comment]
Verificar se o problema foi resolvido juntamente com o #212 @AdsonEsteves

**Comment by elieserdejesus** [comment]
@AdsonEsteves , comentando a linha https://github.com/UNIVALI-LITE/Portugol-Studio/blob/f8824ca7249ff5421bf561c035c874022eeb6aa0/src/br/univali/ps/ui/rstautil/SuportePortugolImpl.java#L44

o problema desaparece. Entretanto, lembro que eu e o @noschang tínhamos adicionado esse **forceReparsing** por algum motivo. Talvez ele realmente não seja mais necessário e está gerando esse problema, mas é necessário testar se tirando esse **forceReparsing** a árvore é atualizada corretamente, o inspetor, etc. Tem "muita gente" dependendo do "parsing", se o parsing mudar de comportamento muita coisa pode deixar de funcionar, por isso é necessário testar muito bem.

**Comment by AlissonSteffens** [comment]
![unit-tests-broken](https://cloud.githubusercontent.com/assets/6234230/26788783/b468a972-49e4-11e7-9705-f096971ef954.gif)

**Comment by AdsonEsteves** [comment]
@elieserdejesus 
Comentei a linha, trabalhei com uns 4 exemplos modificando as variaveis, funcoes, etc... e a árvore renderizava perfeitamente o que era modificado

**Comment by elieserdejesus** [comment]
@AdsonEsteves , então acho que dá pra remover todo o método que chamava o forceReparsing. Podes fazer isso?

**Comment by AdsonEsteves** [comment]
Arrumado no commit https://github.com/UNIVALI-LITE/Portugol-Studio/commit/c61d44e41c52de475010c4772bc60074d874c4c2

**Comment by AdsonEsteves** [comment]
Problema ainda ocorre, porém apenas após uma execução.
a adição ou remoção do _forceReparsing_ não fez diferença alguma nesse caso.

Ambos os problemas provavelmente podem estar relacionandos e a remoção do _forceReparsing_ pode ter sido um apenas _workaround_ ao invés da real causa

**Comment by AlissonSteffens** [comment]
Executei o joguinho e após a execução os avisos tinham sumido
![image](https://user-images.githubusercontent.com/6234230/27401318-43d9a0f0-5699-11e7-8d03-b570cf339d3a.png)

**Comment by AdsonEsteves** [comment]
Quando a seguinte condição no Parser é removida, ambos os problemas são resolvidos. Pois quando abre e finaliza um programa, se é recompilado pra analise, assim colocando os avisos novamente.

![image](https://user-images.githubusercontent.com/8836540/27657352-c468a3b8-5c22-11e7-80b4-12a90d9d47b7.png)

@elieserdejesus 

O que acha? Você colocou essa condição pra impedir uma recompilação para analise, caso fosse um código já compilado. Mas o RSyntax, por alguma razão desconhecida, remove os avisos assim que se é aberta a aba ou finalizado uma execução.
Vale a pena remover essa condição? ou seria melhor deixar assim pra próxima versão? Parece demorado achar a causa dessa remoção dos avisos

**Comment by AdsonEsteves** [comment]
Sendo corrigido no #260
