### ISSUE TITLE
Permitir troca para um tema mais claro

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#199]
Pode não ser prioridade, mas foi verificado que o atual tema escuro do portugol pode ser difícil de ler em projetores/data show, ou seja, professores que queiram mostrar códigos em suas aulas no projetores, podem ter dificuldades por causa da cor escura.

**Comment by elieserdejesus** [comment]
Eu projetei no lab semana passada e realmente ficou muito escuro. Acho que na verdade deveríamos tratar essa tema claro como prioridade, o tema escuro vai pode complicar a vida de muitos professores.

**Comment by AdsonEsteves** [comment]
O método mais prático/rápido de se resolver isso seria a troca do tema com a reinicialização do Studio. (alguma opção nas configurações)

Porém, a possível troca de tema atual para um mais claro, não está com as cores balanceadas, e dependendo, pode ser necessário a troca de icones e cores para os temas se balancearem. O que provavelmente levaria um bom tempo e também a ajuda/opinião do @AlissonSteffens e @noschang , que ultimamente estão trabalhando bastante no site do Lite e no Sapi.

Eu não sei até quando você queria que a IDE fosse lançada, mas acredito que essa "funcionalidade", atrasaria mais um pouco.

**Comment by AdsonEsteves** [comment]
resolvido no #201
