### ISSUE TITLE
O botão "interromper" no exemplo The Ball Saga não funciona

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#200]
Quando se executa o exemplo The Ball Saga e em seguida se tenta interromper por fechar a tela ou apertar o botão interromper, o programa não para.

![image](https://cloud.githubusercontent.com/assets/8836540/24928686/a592bca2-1ed9-11e7-9aa6-c59ca348fdf0.png)

Porém se na tela começar a digitar após ser apertado o botão interromper, o programa para normalmente

**Comment by elieserdejesus** [comment]
Corrigido no núcleo: https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/6f7b38ad2be0ab1b83b8528b025f3beb2b46d9ad
