### ISSUE TITLE
Testar instaladores das 3 plafatormas

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#203]
- [x] Instalador do Mac funcionou mas o PS não executa.
- [x] Corrigir problema com caracteres especiais e utf-8 no windows.

- [x] Resolver o problema relatado pelo Andre Santana quando a nova versão é instalada sem desinstalar a versão antiga no Mac.

<a name="treta-list"></a>
- [x] Ajustar os instaladores para que, durante a desinstalação no Linux, a pasta ```/usr/local/share/univali/java``` seja removida, pois atualmente não está sendo

- [x] Ajustar os instaladores para que, o desinstalador seja chamado com o parâmetro "/silent", evitando assim que a remoção da versão antiga necessite da intervenção do usuário

- [x] Mover os arquivos de log gerados para dentro da pasta de instalação do Studio. No momento, else estão sendo criado dentro da pasta home do usuário. [Visualizar treta](#user-content-treta1)

- [x] Arrumar o gerador de código Java do núcleo para não "guspir" mais o código compilado no console. [Visualizar treta](#user-content-treta2)

- [x] Ajustar a biblioteca Graficos para definir o ícone padrão para o ícone do Portugol Studio quando nenhum outro ícone é definido programaticamente pelo usuário. [Visualizar treta](#user-content-treta2)

- [x] Arrumar atalho do Ícone gerado para o Menu Iniciar (Windows)

- [x] Corrigir diretório de trabalho quando o Portugol é aberto por um arquivo (Windows) (ver o erro reportado nessa issue pelo Adson).

- [x] Quando existe a versão 2.5 instalada o ícone antigo ainda fica no desktop (O resultado são 2 ícones do PS no desktop).

**Casos de teste:**

- [x] Instalar em uma máquina onde não existe o PS instalado
- [x] Instalar em um Windows onde existe a versão 2.5 instalada e ver se a atualização para 2.6 funciona.
- [x] Instalar em Linux e Mac onde existe a versão 2.2 e ver se a atualização para 2.6 funciona. A versão antiga é removida?

**Comment by elieserdejesus** [comment]
Gerei o instalador para windows e instalou perfeitamente. Apareceu um problema na execução dos programas onde existem strings com caracteres especiais. Se tentar usar um **escreva("é")** dá um erro de compilação relacionado com utf-8. Basta tirar o acento do é e funciona. Estou desconfiado que o instalador pode estar usando uma outra codificação que não seja utf-8 quando empactoa os arquivos.

**Comment by elieserdejesus** [comment]
Problema com charset resolvido no núcleo: https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/fe2c1248bca2b76dc8896688b7fad7e80907bf1e

**Comment by elieserdejesus** [comment]
@noschang, @AdsonEsteves e @AlissonSteffens , instalador do Mac gerado e funcionando corretamente.

@noschang , atualizei o projeto do BitRock para remover a pasta UNIVALI da instalação. Agora o uninstaller não está fazendo o trabalho dele. Podes dar um pull no repositório do instalador e dar uma ajuda nessa questão do desinstalador?

**Comment by noschang** [comment]
OK @elieserdejesus

**Comment by elieserdejesus** [comment]
@AdsonEsteves , @AlissonSteffens , @noschang , @rytix , @andrelms , coloquei os instaladores do 1º **release candidate** da **versão 2.6** no github. Vocês poderiam testar os instaladores nas máquinas de vocês?

https://github.com/UNIVALI-LITE/Portugol-Studio/releases/tag/v2.6-rc1

**Comment by andrelms** [comment]
Por algum motivo: 

- Quando Instalei no Mac OS Sierra 10.12.5, se eu já tiver a versão antiga ele não sobrescreve o ícone na central de aplicativos. Quando eu abro ele puxa a versão antiga, mas quando eu vou lá no diretório principal. e executo, ele abre a versão nova. Vou fazer outros testes, pra ver se tem algum outro comportamento.

(Edit) Já descobri o motivo! A versão mais antiaga que eu tinha, o Noschang fez a instalação em UNIVALI/Portugol e a mais nova, gera apenas o .app Portugol. Por algum motivo, sem instalação limpa, ele cria dois executados no diretório Aplicativos, mas não apresenta na aba de apps a versão mais nova.

**Comment by andrelms** [comment]
<img width="1280" alt="captura de tela 2017-06-07 as 00 39 23" src="https://user-images.githubusercontent.com/3330769/26861385-d1ce1bd8-4b19-11e7-8a93-5c98abb744c1.png">
<img width="1280" alt="captura de tela 2017-06-07 as 00 39 16" src="https://user-images.githubusercontent.com/3330769/26861391-d8bedce8-4b19-11e7-97fe-674465fe16d8.png">
<img width="1280" alt="captura de tela 2017-06-07 as 00 37 59" src="https://user-images.githubusercontent.com/3330769/26861392-d8caebc8-4b19-11e7-9cb3-11cf975a0530.png">

**Comment by AlissonSteffens** [comment]
Tem como remover esse aviso???
![image](https://user-images.githubusercontent.com/6234230/26861749-75ea0950-4b1c-11e7-9270-93006a02080b.png)

**Comment by elieserdejesus** [comment]
@andrelms 
> (Edit) Já descobri o motivo! A versão mais antiaga que eu tinha teve o instalador feito pelo Noschang, criando um subdiretório em UNIVALI/Portugol. Já a mais nova, gera apenas o .app Portugol. Por algum motivo: sem instalação limpa ele cria dois executados no diretório Aplicativos, mas não apresenta na aba de apps a versão mais nova.

Exatamente, mudamos o comportamento do instalador. Acho que o desinstalador não deve estar funcionando no Mac, vou adicionar uma *task* pra resolver isso.  Obrigado pela ajuda!

**Comment by elieserdejesus** [comment]
> Tem como remover esse aviso???

@AlissonSteffens , na última vez que eu verifiquei isso a solução é usar uma "assinatura digital". Funciona como um "reconhecimento de firma" em um cartório digital. Você paga para alguém certificar que você é você mesmo, assim os arquivos que você fornece podem ser considerados confiáveis. 

Ou seja, tem solução: money! 😄

**Comment by noschang** [comment]
Pessoal, testei aqui no Ubuntu e ficou show de bola.
A equipe toda está de parabéns!! Vocês são demais!!

Seguem minhas considerações:

1. O ícone do Portugol Studio agora está aparecendo corretamente. Magic...

![figura1](https://user-images.githubusercontent.com/709553/26879005-f0cfd282-4b65-11e7-860f-011f79876c57.png)

2. A nova versão foi instalada corretamente e os ícones e atalhos estão todos corretos.

![figura2](https://user-images.githubusercontent.com/709553/26879386-41d8d0e2-4b67-11e7-8b16-3d9fd526329e.png)

3. A versão antiga foi removida "quase" completamente durante a instalação (a pasta /usr/local/share/univali/java não foi removida).  Também durante a desinstalação da versão anterior, eu recebi uma mensagem perguntando se eu queria remover o Portugol antigo. Na verdade isto não deveria acontecer, ele deveria chamar o desinstalador com o parâmetro "/silent" para que a remoção ocorresse sem a intervenção do usuário.

4. O Java está criando os arquivos de log na pasta home do usuário. Isto pode ser bem incômodo, sugiro alterarmos para criar na pasta de instalação, no caso do Linux /usr/share/portugol-studio

![figura3](https://user-images.githubusercontent.com/709553/26879420-6efb665c-4b67-11e7-9c9b-88b265f56251.png)

5. Testei executar o Studio por linha de comando. Tanto o comando "portugol-studio" quanto o "portugol-console" estão funcionando perfeitamente. No entanto, o núcleo está "guspindo" o código compilado no console, isto não pode ocorrer. Além disso, quando roda pelo console, o ícone muda para o ícone do Java. :-(. @AdsonEsteves, acho que tem como resolver isso altrando a biblioteca Graficos e chamando o método setIcon da JanelaGrafica passando a imagem do ícone do Portugol Studio. Assim, se o cara não alterar o ícone programaticamente, ele vai usar o do Studio por padrão.

![figura4](https://user-images.githubusercontent.com/709553/26879815-d8e11d54-4b68-11e7-80a2-17ff8d6cad58.png)

6. A depuração funciona perfeitamente, porém ainda persiste aquele bug da tela de loading. Ela só aparece desta forma quando estou depurando usando o "bug" e clico no botão "Play" para continuar a execução.

![figura5](https://user-images.githubusercontent.com/709553/26879611-22358748-4b68-11e7-9cae-b7eb2741caa9.png)

**Comment by andrelms** [comment]
Na splash screen de dicas, acho que a janela poderia ter um destaque diferente. A borda da direita fica apagada e pode dar uma sensação de que faz parte do contexto na camada de trás 

<img width="1280" alt="captura de tela 2017-06-07 as 10 11 49" src="https://user-images.githubusercontent.com/3330769/26880174-f9438f40-4b69-11e7-8324-62af68ed5536.png">

**_Sugestão_**: O que acham de eu encaminhar os links para o pessoal fazer beta test e encaminhar possíveis falhas?

@elieserdejesus @AlissonSteffens @noschang @AdsonEsteves @rytix

**Comment by noschang** [comment]
@andrelms, na minha opinião já está consistente o suficiente pra liberar pra testes. 
Acho que junto com o link pra download do Studio era bom você mandar o link pra abertura de issues:

https://github.com/UNIVALI-LITE/Portugol-Studio/issues/new

Vamos ver a opinião dos demais integrantes da equipe.

**Comment by andrelms** [comment]
Acompanhando os pedidos, faço uma boa divulgação nas redes sociais e nos forums que participo, acho que seria uma reaproximaçãod o portugol na comunidade. Deixando claro que a **Versão é Beta!**

**Comment by AlissonSteffens** [comment]
@elieserdejesus e @noschang , o negócio de estar cuspindo código é cagada minha, vou arrumar...
![tenor](https://user-images.githubusercontent.com/6234230/26881256-4f420e78-4b6d-11e7-9887-34a5bb717c9b.gif)

**Comment by AlissonSteffens** [comment]
@elieserdejesus 

> Essa noite sonhei que um dia eu ia poder instalar o Portugol na partição do HD que eu quisesse.

Nunca tive um sonho tão feliz

**Comment by noschang** [comment]
Tudo bem Alissonzinho, não chora, foi sem querer (eu acho...)

**Comment by elieserdejesus** [comment]
> Sugestão: O que acham de eu encaminhar os links para o pessoal fazer beta test e encaminhar possíveis falhas?

Concordo, essa é a ideia! Inclusive pensei em pedir para a Julia gravar um vídeo maneiro para o canal do youtube dizendo que temos uma versão de testes e que precisamos da ajuda para testar e relatar falhas.

***
@noschang , poderias adicionar as tuas considerações como *tasks* na descrição da issue? Assim sabemos que estas coisas estão pendentes e temos algum controle do que já foi feito.

**Comment by AlissonSteffens** [comment]
Então... Tava usando ele de boas.. de repente... travou
agora quando tento abrir o Portugol de novo:
![image](https://user-images.githubusercontent.com/6234230/26881908-3cb6f0fa-4b6f-11e7-9d61-265006fd0174.png)

**Comment by noschang** [comment]
@AlissonSteffens, clica com o botão direito em cima do atalho da área de trabalho e verifica qual comando que ele está executando.

Deve ser algo do tipo:


```"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -jar [...] "C:\ProgramData\UNIVALI\Portugol Studio\aplicacao\portugol-studio.jar"```

Certifique-se de que os caminhos para o java e para o JAR estejam entra aspas duplas, como no exemplo acima. Se não estiverem, coloque entre aspas e tente rodar novamente.

Se funcionar, esta é a treta, porque tem espaços em branco (Portugol Studio) nos cmainhos. Neste caso é preciso consertar no gerador dos instaladores.

**Comment by noschang** [comment]
> @noschang , poderias adicionar as tuas considerações como tasks na descrição da issue? Assim sabemos que estas coisas estão pendentes e temos algum controle do que já foi feito.

@elieserdejesus, it's Done!! [Check it out](#user-content-treta-list)!

**Comment by AdsonEsteves** [comment]
@noschang 
>O ícone do Portugol Studio agora está aparecendo corretamente. Magic...

Na verdade esse não era o ícone que era pra aparecer, e sim o "novo" icone que ta na tela de entrada, vou arrumar.
Isso me lembra tbm, que esqueci de arrumar o icone na splash, mi disgurpe

**Comment by AlissonSteffens** [comment]
área de trabalho (funciona)
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -jar -Xms32m -Xmx256m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled "C:\ProgramData\UNIVALI\Portugol Studio\aplicacao\portugol-studio.jar"

menu iniciar (bugado)
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -jar -Xms32m -Xmx256m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled C:\ProgramData\UNIVALI\Portugol Studio/aplicacao/portugol-studio.jar


malditas aspas

**Comment by elieserdejesus** [comment]
@AlissonSteffens , podes criar mais uma task na descrição dessa issue para lembrarmos de arruma isso. É bem fácil de arrumar, mas igualmente fácil de **esquecer de arrumar** 😄

**Comment by noschang** [comment]
> malditas aspas

É um saco mesmo.
Lembro de o @elieserdejesus e eu termos corrigido isso no ícone que é gerado pra área de trabalho, mas realmente nos esquecemos do ícone do menu iniciar. É fácil resolver.

@elieserdejesus, podes resolver essa por favor? Senão vou ter que instalar todos o aparato no meu PC. I'm so lazy.... (:-p)

**Comment by noschang** [comment]
> Na verdade esse não era o ícone que era pra aparecer, e sim o "novo" icone que ta na tela de entrada, vou arrumar.

Olha @AdsonEsteves, eu curti esse ícone aí. Acho que o ícone com as chaves "{}" fica legal na tela inicial do Studio. Mas pra ícone da janela acho melhor esse ali mesmo. Não sei o que os outros acham.

**Comment by AlissonSteffens** [comment]
concordo com o @noschang (por incrível que pareça)

**Comment by elieserdejesus** [comment]
> @elieserdejesus, podes resolver essa por favor? Senão vou ter que instalar todos o aparato no meu PC. I'm so lazy.... (:-p)

xá COM igo 😄

**Comment by AdsonEsteves** [comment]
@noschang 
>Acho que o ícone com as chaves "{}" fica legal na tela inicial do Studio

Bom, a um certo tempo atrás me falaram (mais especificamente o @AlissonSteffens ) pra colocar o com as chaves. O icone na barra de tarefas no windows se me lembro bem é o com as chaves mesmo.
Mas nesse caso é só mudar ele então

**Comment by AdsonEsteves** [comment]
Talvez, mudar as telinhas do instalador do Portugol, pro novo icone, e talvez pro tema escuro

**Comment by AdsonEsteves** [comment]
Abri um arquivo do portugol, sem ainda estar aberto. o Portugol abriu, mas os exemplos não foram carregados, nem a ajuda

![image](https://user-images.githubusercontent.com/8836540/26890101-c93fdb24-4b86-11e7-8a6a-6bb4f3236a41.png)
![image](https://user-images.githubusercontent.com/8836540/26890129-e40fec0a-4b86-11e7-98e8-2d75f4e4af4f.png)


O caminho dos recursos está como o caminho em que foi aberto o arquivo

**Comment by elieserdejesus** [comment]
@AdsonEsteves , adicionei uma task para vermos esse problema do diretório de trabalho.

**Comment by AdsonEsteves** [comment]
@elieserdejesus eu ja tinha criado uma :p

**Comment by dgadelha** [comment]
Bugs presentes na 2.6 (win): #75, #76, #113, #138, #139 (é bug mermo?), #141, #145, #147, #152, #163 (o erro do usuário), #183 (o 2º, o 3º só dá uns warnings, mas nenhum erro), #190, #210
Bugs que não vi presentes na 2.6 (win): #111, #137 (ao invés de dar erro, dá 0, mas deveria dar um warning no editor pelo menos)

Bugs que eu achei (tem umas sugestões aí no meio tb):
- Ao abrir um arquivo e ir à aba dele, às vezes você tem que clicar 2x+ no 'Portugol Studio' pra ir pra aba principal.
- No exemplo Entrada e Saída -> Seu Nome, diz lá na descrição `Logo após, utiliza a saída de dados para exibir o nome digitado.`, mas ele não escreve o nome digitado na tela.
- Quando você abre muitas abas, os botões de scroll ficam atrás das ações da janela (Fechar, Maximizar, Minimizar), tem que clicar um pouco embaixo pra poder dar scroll. E seria legal que a aba principal do 'Portugol Studio' ficasse fixa.
- No Windows, clicar duas vezes em uma parte vazia lá em cima na parte de abas, deveria fazer a janela Maximizar ou Restaurar (o contrário de Maximizar), mas acaba que não dá em nada.
- Às vezes, é preciso clicar o botão Maximizar umas 2 - 3 vezes pra ele maximizar.
- O exemplo Laços de Repetição -> Média de Dez Números vem com uns pontos de parada integrados.
- Muitas vezes, é preciso dar muito mais que 2 cliques no item da TreeView dos exemplos para abrir o exemplo. E algumas vezes, quando você já tem um item selecionado  e clica duas vezes em outro, ele não abre o outro, mas sim o selecionado. (Isso porque não dá pra selecionar um item clicando no espaço vazio à direita do nome)
- No exemplo Subrotinas -> Parâmetros por Referência (faltou acento até), o vetor final sai todo '5 5 5 5...'
- Sdds UTF-8: emojis dão um número maior no `Texto.numero_caracteres`
- No exemplo Jogos -> Corrida, ao clicar a tecla D, o dano sobe (isso era esperado?)
- Poderia ter um menu de contexto (assim como no Firefox) nas abas, com opções parecidas ao dele 'Fechar abas à direita', 'Fechar as outras abas', 'Reabrir aba' (não é exatamente necessário, mas seria legal), 'Fechar aba'
- No Windows, ele deveria instalar em `%ProgramFiles(x86)%\UNIVALI\Portugol Studio` (64-bit), `%ProgramFiles%\UNIVALI\Portugol Studio` (32-bit), e não em `%ProgramData%\UNIVALI\Portugol Studio`. Eu até pensei que era porque o ProgramData não tinha espaços no nome, mas a própria pasta `Portugol Studio` tem espaços no nome então acho que deveria instalar no lugar correto.
- O Portugol Studio é o único app que vi até hoje que distribui um JRE de 320 MB. O do Android Studio é 135 MB e o Portugol Studio funcionou perfeitamente com ele.

**Comment by AlissonSteffens** [comment]
@dgadelha obrigado pelos testes 👍 
Algumas Explicações:
* Sobre o Charset eu já abri uma issue pra fazer isso na próxima versão #225 
* A pasta de instalação é a '%ProgramData%' por uma decisão relacionada ao método como funciona o sistema da **Univali**, os usuários de aluno não tem permissão de escrita na pasta '%ProgramFiles%' e gente deixa no data pra poder atualizar coisas etc (mesmo assim, a gente não vai mais atualizar automaticamente então acho que dá de mudar o local não acha @elieserdejesus e @noschang ???)

De qualquer maneira vamos tentar corrigir os bugs, e estas novas funcionalidades são muito interessantes 😄 se for possível vamos integrar algumas delas à essa ou à próxima versão

**Comment by noschang** [comment]
@dgadelha, ainda complementando o que o @AlissonSteffens falou:

> No exemplo Jogos -> Corrida, ao clicar a tecla D, o dano sobe (isso era esperado?)

Sim isto era esperado. O jogo da corrida ainda não está totalmente finalizado, então ainda tem alguma funcionalidades de teste, como essa que você viu. O "D" serve para testar o incremento da barra de dano, enquanto que o "A" server para testar o incremento do combustível.

> O Portugol Studio é o único app que vi até hoje que distribui um JRE de 320 MB. O do Android Studio é 135 MB e o Portugol Studio funcionou perfeitamente com ele

Na versão anterior, o Portugol Studio distribuía somente a JRE, pois usava o Java somente para rodar os programas de maneira interpretada. Na versão atual, compilamos internamente os programas para obter ganho de performance e isso nos obriga a utilizar o JDK ao invés do JRE, o qual, por sua vez ocupa mais espaço que o JRE.

De todo modo, agradecemos os testes e sugestões.

**Comment by elieserdejesus** [comment]
todas as tasks foram corrigidas! Vou fechar a issue, se surgirem novos problema no instalador é melhor criarmos novas issues, menores e focadas apenas no problema. Esta issue já "inchou" o suficiente :)

Abrigado a todos pela ajuda, vou gerar uma nova versão dos instaladores (RC2) na segunda feira.

**Comment by elieserdejesus** [comment]
pessoal, versão RC2 disponível, por favor ajudem a testar essa versão. Assim que tivermos testado "internamente" eu divulgo para meus alunos que já estão usando a versão nova.
https://github.com/UNIVALI-LITE/Portugol-Studio/releases/tag/v2.6-rc2
