### ISSUE TITLE
Sair programando -> Iniciar programação

### ISSUE THREAD

**Issue by edusantana** [UNIVALI-LITE/Portugol-Studio#205]
Oi Pessoal, recomendo trocar o texto de *Sair programando* para *Iniciar programação*.

`Sair` está associado fechar o programa. Ficou estranho que para *Iniciar a programação* eu tenha que clicar num botão chamado *sair*.

**Comment by noschang** [comment]
Oi @edusantana. Excelente observação. Acho bastante pertinente. Vamos conversar entre a equipe e se a maioria estiver de acordo com a mudança faremos a implementação.

Obrigado pela colaboração. 
:-)

**Comment by elieserdejesus** [comment]
@edusantana e @noschang , eu não achei esse texto "Sair Programando" na versão atual. Onde fica esse texto?

@edusantana , caso essa alteração ainda seja válida na versão atual, você poderia fazer essa alteração? 
Nós podemos fazer a modificação como você sugeriu, mas acho importante incentivar a participação de outras pessoas, é sempre mais interessante receber contribuições de novas pessoas. 😄

**Comment by edusantana** [comment]
@elieserdejesus e @noschang realmente, eu estava utilizando a versão 2.2 no linux. Na versão 2.5, a entrada foi alterada, é como @elieserdejesus disse, não há esse string na versão 2.5.

**Comment by elieserdejesus** [comment]
Ok @edusantana , vou fechar essaa issue então. Estamos planejando a próxima versão para as próximas semanas, então essa alteração também estará disponível para Linux.
