### ISSUE TITLE
Submissão de bugs

### ISSUE THREAD

**Issue by edusantana** [UNIVALI-LITE/Portugol-Studio#208]
O link de submissão de erros (no aplicativo) leva para um formulário do google docs, talvez fosse melhor apontar para a criação de issues no github.

Se o propósito do formulário fosse requerer informações do usuário, você pode fazer isso criando um template de issue, veja um [exemplo de criação do issue no limarka](https://github.com/abntex/limarka/issues/new).

- [ISSUE_TEMPLATE.md](https://github.com/abntex/limarka/blob/master/ISSUE_TEMPLATE.md)

**Comment by AlissonSteffens** [comment]
Acredito que possamos utilizar esta abordagem para a próxima versão, iremos analisar as condições e reportaremos mais tarde nesta issue o resultado das discuções
