### ISSUE TITLE
Operador Auto incremento ++, comparado ao Java

### ISSUE THREAD

**Issue by erickweil** [UNIVALI-LITE/Portugol-Studio#210]
o código em java:

	public static void main(String[] args) {
		int x = 10;
		
		System.out.println(" Operação AutoIncrement x++:");
		System.out.println(x++);
		System.out.println(x);
		
		System.out.println(" Operação AutoIncrement ++x:");
		System.out.println(++x);
		System.out.println(x);
	}
	
	resultado:
	 Operação AutoIncrement x++:
	10
	11
	 Operação AutoIncrement ++x:
	12
	12

quando comparado ao equivalente em portugol:

	funcao inicio()
	{		
		inteiro x = 10

		escreva(" Operação AutoIncrement x++:\n")
		escreva(x++,"\n")
		escreva(x,"\n")

		//escreva(" Operação AutoIncrement ++x:\n")
		//escreva(++x,"\n")
		//escreva(x,"\n")
	}
	
	resultado:
	 Operação AutoIncrement x++:
	11
	11

observa claramente a diferença, o operador de auto incremento ( x++ ) tem essa característica no java, onde retorna o valor na expressão, e só depois incrementa, achei que talvez seria interessante que o portugol tivesse esse mesmo comportamento, já que a idéia é preparar o terreno para se utilizar outras linguagens, o operador postfix e prefix ++, --, seriam ótimas adições.

**Comment by elieserdejesus** [comment]
@erickweil , realmente essa é uma falha do PortugolStudio. Assim que possível vamos tentar resolver essa problema. Obrigado por reportar o problema!

**Comment by noschang** [comment]
Este problema ainda persiste. Além disso a operação de incremento com operador na esquerda não é suportada pela gramática do Portugol, conforme pode-se ver abaixo:

![bug](https://user-images.githubusercontent.com/709553/30068897-869b7fc6-9235-11e7-8848-42551e6df1ef.png)

**Comment by AlissonSteffens** [comment]
@noschang tem que mexer no ANTLR pra arrumar isso?

**Comment by noschang** [comment]
Sim.

:'-(

**Comment by AlissonSteffens** [comment]
Depende da #314 , vou fechar por enquanto, visto que só poderá ser feito quando a issue em questão for resolvida
