### ISSUE TITLE
Declarar vetor dinamicamente

### ISSUE THREAD

**Issue by jffsn** [UNIVALI-LITE/Portugol-Studio#211]
Tentei declarar um vetor dinamicamente conforme exercicio em sala de aula, porém declarando a váriavel como inteiro não foi possível, segue a mensagem de erro:

O tamanho do vetor 'valores' deve ser um valor ou uma constante do tipo inteiro

Código:

                inteiro qtd = 0
		inteiro i, pares = 0, impares = 0, cont = 1
		
		escreva ("\nInforme a quantidade de valores que deseja digitar: ")
		leia (qtd)

		inteiro valores[qtd]
		
		para (i = 0; i < qtd; i++ ) {
			escreva ("\nEntre com o ", cont, "º valor ")
			leia(valores[i])

			cont++
		}

		para (i = 0; i < qtd; i++ ) {
			
			se (valores[i] % 2 == 0) {
				pares++
			} senao {
				impares++
			}
		}

		escreva ("\nDos valores informados ", pares, " são pares e ", impares," são impares.\n")

Declarando a váriavel qtd como: const inteiro qtd o código funciona, porém o valor de uma váriavel constante não deveria sofrer alteração do valor, certo?

Obrigado

**Comment by elieserdejesus** [comment]
@jffsn , realmente não é possível usar a variável **qtd** para definir o tamanho do vetor, a menos que ela seja constante. 

> Declarando a váriavel qtd como: const inteiro qtd o código funciona, porém o valor de uma váriavel constante não deveria sofrer alteração do valor, certo?

Exatamente, a constante não pode ter o valor alterado.

No momento não é possível declarar vetores dinamicamente. Um "workaround" seria declarar um vetor com um tamanho grande o suficiente usando uma constate e depois utilizar apenas uma parte desse "vetorzão". Não é bonito, mas funciona :)
