### ISSUE TITLE
Erro de caracteres especiais na Distribuição do Portugol

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#213]
![image](https://cloud.githubusercontent.com/assets/8836540/26014735/4af801ee-3734-11e7-9085-3bf17e54d9ab.png)

Uma imagem vale mais que mil palavras

Isso acontece com qualquer programa com caracteres especiais

**Comment by elieserdejesus** [comment]
@AdsonEsteves , eu já tinha resolvido um problema como esse. Teus repositórios estão atualizados? A tua branch tem a correção de charset que eu fiz anteriormente?

**Comment by AdsonEsteves** [comment]
@elieserdejesus tem razão, não tinha atualizado o núcleo
