### ISSUE TITLE
Abrir arquivos no inicio do Portugol não funciona

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#218]
Se passarmos algum caminho de arquivo Portugol, como parâmetro na execução, ele deveria abrir os arquivos assim que o portugol studio é iniciado.
Só que não acontece.
Como testar:
![image](https://cloud.githubusercontent.com/assets/8836540/26510482/ddacf2ce-4233-11e7-88aa-122f738316c0.png)

Uma possível causa seria o OutSidePanel ou o Lancador que o @AlissonSteffens fez, não estaria com a TelaPrincipal correta. Modifiquei o OutsideSidePanel para receber a TelaPrincipal da instancia do PortugolStudio e nada aconteceu, feijoada.

O Problema ocorre nesta função:

![image](https://cloud.githubusercontent.com/assets/8836540/26510697/eebc6e0e-4234-11e7-9cf0-20b329ea2360.png)

que deveria abrir os arquivos iniciais (cujo links estão corretos), mas não os abre. Infelizmente não consegui entender como funciona para ajudar.

É importante que seja resolvido até a próxima versão pois isso que permite abrir o portugol studio diretamente a partir de um arquivo ".por" em um diretorio, abrindo o arquivo assim que o portugol é iniciado

**Comment by elieserdejesus** [comment]
Corrigido, faltava apenas setar os arquivos iniciais na tela principal.
