### ISSUE TITLE
Adicionar Guia de Compilação e dados sobre versões na documentação

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#224]
É necessário para demais desenvolvedores que queiram usar partes do Portugol em seus trabalhos

**Comment by elieserdejesus** [comment]
Concordo, mas é melhor fazer isso depois da integração dos repositórios. Com os repositórios integrados vai ficar mais fácil para novos desenvolvedores.

**Comment by AlissonSteffens** [comment]
@elieserdejesus to adicionando um link nos outros repositórios para o **Portugol Studio**, assim como já feito no Núcleo (https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/master/README.md), e vou colocar toda a documentação aqui. Sendo assim, quando for feita a integração basta mudar os links.

**Comment by AlissonSteffens** [comment]
Iniciado em https://github.com/UNIVALI-LITE/Portugol-Studio/commit/b30f39e19278edde5d7c75a574143c83b20b148b

**Comment by AlissonSteffens** [comment]
@elieserdejesus , preciso da tua ajuda para fazer um guia de como utilizar a nova versão do núcleo nos projetos que utilizavam a anterior, como o [Cria](https://rioinfo.com.br/cria/participe/regulamento/) e o [Portugol WebStudio](https://github.com/dgadelha/Portugol-Webstudio)

**Comment by elieserdejesus** [comment]
> @elieserdejesus , preciso da tua ajuda para fazer um guia de como utilizar a nova versão do núcleo nos projetos que utilizavam a anterior, como o Cria e o Portugol WebStudio

@AlissonSteffens , achei que não tinha mudado nada em relação a isso. Acho que o núcleo já está compilando para execução. Não sei se tem alguma coisa especial para comentar. @noschang ?

**Comment by noschang** [comment]
@elieserdejesus e @AlissonSteffens. Acredito que a única coisa que mudou para o usuário no núcleo foram algumas bibliotecas.

Foram adicionadas novas funções, mas pelo que e lembro nenhuma função foi retirada. Sendo assim, acho improvável que vá gerar algum problema.

Quanto ao fato de estar compilando agora, deve impactar somente na performance, mas não na forma como o núcleo é chamado.

**Comment by noschang** [comment]
@AdsonEsteves  e @elieserdejesus. Ao reorganizar o repositório, atualizei o [README.md](https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/README.md) com instruções de como compilar usando o Gradle. 

Ainda está incompleto, mas dá pra partir daí. Nos lugares onde está marcado **TODO: Tutotorial...**, a idéia é fazer um GIF com o passo a passo, colocar na pasta ```docs``` e linkar para que o usuário possa acessar.

**Comment by AlissonSteffens** [comment]
Acho que o @noschang já adiantou bastante isso, e com o gradle tá tudo mais simples.
To fechando esta issue. XOXO :kiss: :kiss:
