### ISSUE TITLE
Erro na inicialização gerado pelo recuperador de arquivos

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#227]
**Descrição do Problema**:
Instalei a versão mais atual no Mac e quando inicializei o PS não abriu quando cliquei no ícone. Rodando o executável diretamente e tive os erros abaixo:

**Mensagem de Erro (se houver)**:
```
Exception in thread "main" java.lang.NullPointerException
	at br.univali.ps.nucleo.PortugolStudio.readRecuperaveis(PortugolStudio.java:139)
	at br.univali.ps.nucleo.PortugolStudio.<init>(PortugolStudio.java:113)
	at br.univali.ps.nucleo.PortugolStudio.getInstancia(PortugolStudio.java:202)
	at br.univali.ps.ui.Lancador.start(Lancador.java:138)
	at br.univali.ps.ui.Lancador.main(Lancador.java:43)
logout
```

**Especificações do sistema**:
Mac OSX

**Comment by elieserdejesus** [comment]
@AdsonEsteves , deu uma treta na recuperação de arquivos no Mac. Isso aconteceu quando instalei do zero. Talvez algum arquivo necessário não tenha sido criado? Dê uma olhada na stacktrace que postei e veja se dá uma luz.

**Comment by AdsonEsteves** [comment]
@elieserdejesus 

A função que gerou esse erro é essa aqui.
Antes de mexer diretamente na pasta, eu criou qualquer pasta que esteja faltando.
Poderia mkdirs não funcionar no MAC OSX?
![image](https://user-images.githubusercontent.com/8836540/26849974-54f16d6e-4adc-11e7-828e-464d431b1ad1.png)

**Comment by elieserdejesus** [comment]
@AdsonEsteves , criei um PR corrigindo isso. O problema é que o diretório temporário estava sendo criado em um diretório onde não existe permissão de escrita (dentro do app). 

Podes testar esse PR e ver se outras coisas que dependem do diretório temporário ainda estão funcionando?
