### ISSUE TITLE
Comportamento Inesperado ao resolver expressões

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#229]
Testando o Release do @elieserdejesus descobri que:

O código 
```
movimento_horizontal_middle = (m.posicao_x()/forca_mouse_meio)-LARGURA_TELA/(forca_mouse_meio*2)
```
funciona perfeitamente,
porém se eu fizer:
```
movimento_horizontal_middle = - (m.posicao_x()/forca_mouse_meio)-LARGURA_TELA/(forca_mouse_meio*2)
```
o portugol trava

interessante que:
```
inteiro a = 1
inteiro b = - a
escreva (b)
```
funciona normal

**Comment by elieserdejesus** [comment]
Acho que esse problema dá tempo de resolver antes do release final.

**Comment by AlissonSteffens** [comment]
acho que o que acontece é que ele tá tentando resolver
`- (m.posicao_x()/forca_mouse_meio)`
antes de
`(m.posicao_x()/forca_mouse_meio)-LARGURA_TELA/(forca_mouse_meio*2)`
o menos nesse caso deveria ser a última operação a ser feita
isso
```
programa
{
	funcao inicio()
	{
		inteiro a = 1
		inteiro b = - a + 2
		escreva (b)
	}
}
```
deveria dar -3 não???
mas o resultado obtido é 1

**Comment by noschang** [comment]
Provavelmente quando o ANTLR encontra o código ```inteiro b = - a + 2``` ele "engole" os espaços em branco e entende a expressão como ```inteiro b = (-a) + 2``` ao invés de ```inteiro b = -(a + 2)```.

Além disso:

![figura1](https://user-images.githubusercontent.com/709553/26883798-900ce11a-4b74-11e7-8489-6ba42d9ccef9.png)

**Comment by AlissonSteffens** [comment]
eita, ok @noschang aceito

**Comment by elieserdejesus** [comment]
issue resolvida certo? 😄
