### ISSUE TITLE
PS travando quando aba é fechada com programa gráfico executando

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#230]
**Descrição do Problema**:
Durante a aula os alunos perceberam que o PS 2.6 RC1 trava se você executar uma aplicação gráfica e tentar fechar a aba com a aplicação em execução.

**Captura de Tela / Arquivo.por**:
```
programa
{
inclua biblioteca Graficos
inclua biblioteca Teclado
inclua biblioteca Util
inclua biblioteca Mouse
inteiro imagem_de_fundo
inteiro x_fundo = 0
inteiro imagem_da_arma = 0
inteiro tamanho_da_mira = 20

funcao inicializacao(){
Graficos.iniciar_modo_grafico(verdadeiro)
imagem_de_fundo = Graficos.carregar_imagem("imagens/dust.jpg")
Graficos.definir_dimensoes_janela(1200, 675)
imagem_da_arma = Graficos.carregar_imagem("imagens/teste2.png")
}
funcao processamento(){
Graficos.desenhar_imagem(0, 0, imagem_de_fundo)

Graficos.desenhar_imagem(400, 400, imagem_da_arma)
inteiro mouse_x = Mouse.posicao_x()
inteiro mouse_y = Mouse.posicao_y()

Graficos.definir_cor(Graficos.COR_VERMELHO)
Graficos.desenhar_linha(mouse_x, mouse_y - tamanho_da_mira, mouse_x, mouse_y + tamanho_da_mira)
Graficos.desenhar_linha(mouse_x - tamanho_da_mira, mouse_y, mouse_x + tamanho_da_mira, mouse_y)
Graficos.renderizar()
Mouse.ocultar_cursor()

}
funcao inicio()
{
inicializacao()
inteiro tecla= Teclado.TECLA_ESC
enquanto(nao Teclado.tecla_pressionada(tecla)){
processamento()
}
}

}
```
**Especificações do sistema**:
Windows

**Comment by noschang** [comment]
@elieserdejesus, não sei se é exatamente um bug. O problema é ocasionado por um JOptionPane que fica por tras da tela do jogo. Parece que está travado, mas na verdade é porque está com foco no JOptinPane escondido.

![figura1](https://user-images.githubusercontent.com/709553/26974834-83af0c6a-4cf3-11e7-97ec-fad7789b19ce.png)


Não sei como resolver isso.

**Comment by elieserdejesus** [comment]
@noschang , acho que a solução é encerrar a execução quando o usuário fechar a aba ao invés de "pedir que o usuário encerre a execução". 

Se o usuário está executando um programa e fecha a aba desse mesmo programa eu penso que a intenção do usuário é clara: ele não tem mais interesse nesse programa, logo o melhor a fazer (na minha opinião) é encerrar a execução automaticamente quando a aba for fechada. 

O que achas @noschang ? Tem alguma outra situação onde faz mais sentido pedir para o usuário encerrar a execução manualmente?

**Comment by noschang** [comment]
@elieserdejesus, pode ser, acho que não tem problema.
