### ISSUE TITLE
Erro de Renderização ao inserir acentos em Windows Preview

### ISSUE THREAD

**Issue by ren3d** [UNIVALI-LITE/Portugol-Studio#231]
**Descrição do Problema**:
Instalei o programa, abri e executei os algoritmo de exemplos, funcionaram perfeitamente.
Clico em Programar e na janela para inserir um algoritmo, quando eu seguro a tecla Shift para digitar uma aspas por exemplo as minhas janelas "bugam". Não volta mais ao normal onde eu passar o mouse fica chamando janelas. Esse bug me impossibilita de usar o programa :'(.
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
http://ap.imagensbrasil.org/image/0pA5LU

**Especificações do sistema**:
Windows 10 Pro Insider Preview
Build 16199 pre_release
I5 2300
8 gb Ram
Gtx 750 ti

**Comment by AlissonSteffens** [comment]
@ren3d obrigado pelo retorno, irei investigar o problema, e vou relatar os possíveis causadores/soluções aqui nesta Issue

**Comment by AlissonSteffens** [comment]
@elieserdejesus Parece ser o mesmo erro #80 , @ren3d verifique se seus driver de vídeo está atualizado.

**Comment by AdsonEsteves** [comment]
@ren3d poderia verificar também, se o mesmo erro ocorre na versão 2.5?

**Comment by ren3d** [comment]
Ola pessoal! Na versão 2.5 tbm fica esse erro. Atualizei meu windows pra Build mais recente 16215, continuou na mesma.  Ontem eu havia atualizado o Java e havia resolvido o problema. Depois que atualizei o windows o problema voltou, atualizei o problema novamente e não resolveu dessa vez. 

Eu seguro o Shift e aperto " (aspas ou !, forma os dois que testei) começa a dar esse bug da tela. Essa janela  
fica aparecendo onde eu passo o mouse

Bug na 2.5
http://ap.imagensbrasil.org/image/0p7BPD

**Comment by AlissonSteffens** [comment]
@ren3d você está usando o Portugol em duas telas?
Sabe me dizer a versão do seu driver de vídeo?

**Comment by ren3d** [comment]
Estou usando em uma tela somente ultrawide de 2560 x 1080

Nvidia Driver Versão 382.05

**Comment by ren3d** [comment]
Descobri uma coisa. Esse bug só acontece quando digito caracteres especiais como '  " ! @ # $ ` ´ ? (pode haver mais). Fiz um teste adicionando esses caracteres pelo teclado virtual e o problema continuou acontecendo.

**Comment by AdsonEsteves** [comment]
@ren3d 

Tente primeiramente atualizar o driver da sua placa de vídeo
Aqui tem o link do driver da sua placa: http://www.nvidia.com.br/download/driverResults.aspx/119986/br

Se não der certo tente isso:

1. Entre nas variáveis de ambiente do seu sistema
  - abra o executar (![](https://i.stack.imgur.com/T0oPO.png)+R)
  - escreva `control sysdm.cpl,,3` e dê ok
  - na janela aberta clique em Variáveis de ambiente

2. Coloque a variável `sun.java2d.d3d` como `false` nas variáveis do sistema(se não tiver, crie uma nova)
 - Deve ficar como nas imagens abaixo 
![image](https://user-images.githubusercontent.com/8836540/27052153-241c606a-4f8f-11e7-8340-6967921d8003.png)

- Assim deve terminar: ![image](https://user-images.githubusercontent.com/8836540/27052176-3c414ebc-4f8f-11e7-9c0c-28792bdd4d0c.png)

**Comment by ren3d** [comment]
Fiz o procedimento nao resolveu

**Comment by ren3d** [comment]
Estou achando que e problema ´´e por causa dessa build fast do windows. Por que o problema acontece quando eu adiciono as acentuacoes. Nessa build os acentos estao todos bugado. Quando eu vou colocar um acento sai assim ... ´´ `` ~~ ^^ tudo multiplicado.

**Comment by ren3d** [comment]
Com a atualização do windows 10 para a nova build preview 16226 veio a correção com o problema dos símbolos de acentuação e também corrigiu o problema de renderização. Muito obrigado pela atenção :)

**Comment by AdsonEsteves** [comment]
@ren3d 

ótimo, então resolvido, obrigado :)
