### ISSUE TITLE
Destaque da linha com problema quando executando com break points

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#233]
**Descrição do Problema**:
Quando o código tem vários break points e o botão de "play" vai sendo clicado para pular de um break point para outro algumas linhas não ficam destacadas quando o break point é alcançado. Isso deixa o usuário sem feedback visual sobre qual linha o programa está "parado", pois a linha onde o programa parou não está sendo destacada.

**Especificações do sistema**:
Observei esse erro no Windows e no Linux. Não testei no Mac mas acho que não é específico de alguma plataforma.

**Comment by elieserdejesus** [comment]
@AdsonEsteves , poderias usar o arquivo .por em anexo para testar essa issue e tentar descobrir onde o problema foi introduzido? Minha sugestão é tentar reverter os últimos commits e ver se o problema ainda existe no código mais antigo. Se não existir vá tentando cada commit para ver onde o problema foi introduzido.
[teste.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1066681/teste.zip)

**Comment by AdsonEsteves** [comment]
@elieserdejesus 

Começou quando o loader foi colocado https://github.com/UNIVALI-LITE/Portugol-Studio/commit/4c8d74435f578f0540d869a5dbd6335d66b7ff9d

Será que poderia ser pela compilação acontecer em thread?

**Comment by AdsonEsteves** [comment]
deve ter algo a ver com a compilação acontecendo em uma thread separada ou o editor.iniciarExecucao(depurando) estar acontecendo em uma thread do swing

**Comment by elieserdejesus** [comment]
obrigado @AdsonEsteves , vou dar uma investigada nesse commit que você mencionou assim que possível.  Também acho que tem relação com essas threads que você mencionou.
