### ISSUE TITLE
Erro quando a função Graficos.renderizar não é chamada

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#235]
**Descrição do Problema**:

Se o usuário esquecer de invocar a função **Graficos.renderizar()** as operações de desenho vão acumular e o erro da imagem abaixo será gerado.

**Captura de Tela / Arquivo.por**:

![screenshot from 2017-06-12 10 07 09](https://user-images.githubusercontent.com/1012741/27035319-4139777e-4f57-11e7-8340-6a304a6f1dba.png)

**Comment by elieserdejesus** [comment]
@noschang , acho que daria pra resolver esse problema chamando **renderizar()** dentro da biblioteca Graficos sempre que a "coisa ficar feia". O que achas? 

É comum os alunos iniciantes esquecerem de chamar a função de renderização, então esse problema deverá aparecer pra muita gente.

**Comment by noschang** [comment]
@elieserdejesus. A observação é válida, mas como faremos isso? O problema é que esta função tem que ser chamada no momento certo. Ela tem que ser chamada logo após a última operação de desenho, que geralmente está dentro de um loop.

Como vamos detectar isso? Além disso, em alguns casos, a função renderizar pode não ser chamada em um loop.

Não vejo uma forma fácil de fazer isso. Talvez a melhor abordagem não seja resolver o problema para o usuário, mas sim mostrar o caminho.

Então penso que, a melhor coisa a se fazer é capturar esta exceção em específico e quando ela ocorrer exibir uma mensagem do tipo:

"A função Graficos.renderizar não foi chamada nenhuma vez em seu código. Se você não chamar esta função, seus desenhos não aparecerão na tela. Inclua uma chamada para esta função após a última operação de desenho que seu prorama estiver executando".

Enfim, dá pra melhorar esta mensagem, mas é mais ou menos por aí.

**Comment by elieserdejesus** [comment]
> Então penso que, a melhor coisa a se fazer é capturar esta exceção em específico e quando ela ocorrer exibir uma mensagem

Concordo @noschang , é uma boa estratégia para o caso mais geral.

Você perguntou como detectar o momento de chamar a função **renderizar**. Eu estava pensando em chamar a função **renderizar** automaticamente SOMENTE quando o array de operações de desenho estiver prestes a "estourar". Ou seja, minha proposta não é eliminar a necessidade da invocação de **renderizar**, a proposta seria apenas **evitar o estouro do array de operações chamando a função renderizar quando o array estiver "cheio"**. 

Veja que estou assumindo que a chamada para **renderizar** vai "limpar" todas as operações de desenho acumuladas e resolver o problema do "estouro" do array, e não sei se realmente é o caso. O que achas?

**Comment by noschang** [comment]
@elieserdejesus. Em tese "resolveria". O problema é que eu penso que isto vai gerar um resultado incorreto do ponto de vista do usuário. Imagine que ele chame as sgeuintes operações em Loop:

```
g.definir_cor(g.COR_AZUL)
g.limpar()
g.definir_cor(g.COR_AMARELO)
g.desenhar_retangulo(0, 0, 50, 50, verdadeiro, falso)
g.definir_cor(g.COR_PRETO)
g.desenhar_elipse(100, 100, 30, 30, verdadeiro)
```

Agora imagine que implementemos a chamada automática como você falou. Isso faria com que a chamada ocorresse após cada uma das linhas anteriores de forma aleatória. Isso faria com que em um momento, o renderizar fosse chamado após o ```limpar```, em outro momento, após o ```desenhar_elipse```, em outro momento após o ```definir_cor(g.COR_PRETO)```.

Algumas coisas poderiam acabar nunca sendo desenhadas na tela, ou então em uma ordem que não é a predefinida pelo usuário. Ou seja, em alguns momentos, o código anterior poderia fazer com que o  retângulo fosse desenhado sobre o círculo e não o contrário.

Dependendo do tipo de aplicação que se está desenvolvendo, a ordem dos desenhos, por exemplo, pode ser muito importante.

É por isso que eu acho melhor irmos pra uma abordagem de apontar o erro ao invés de tantar corrigí-lo automaticamente. Pois isso poderia causar mais erros e mais confusão para o usuário.

**Comment by elieserdejesus** [comment]
Tens razão @noschang. Vamos usar essa ideia da exceção customizada e mostrar uma mensagem amigável.

**Comment by elieserdejesus** [comment]
Feito em https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/389ba22b37f1709ad86080900654ba2c5a0bb3f2

![image](https://user-images.githubusercontent.com/1012741/27095337-ac03c1da-5043-11e7-8f95-7b879a5e1a19.png)
