### ISSUE TITLE
Break Points causam ArrayOutOfBounds se arquivo anterior tinha um número menor de linhas

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#236]
**Descrição do Problema**:
- Abra o exemplo "Olá mundo", deixe a árvore renderizar e depois feche
- Agora Abra um arquivo com um numero de linhas maior e que tenha breakpoints ativados nas mesmas 
- ArrayOutOfBounds ocorre

**Mensagem de Erro (se houver)**:
![image](https://user-images.githubusercontent.com/8836540/27102424-99e5c558-505b-11e7-8ed5-321842be264e.png)

**Arquivo.por**:
[Código Exemplo](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1072770/teste.zip)

**Comment by elieserdejesus** [comment]
corrigido em https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/cdc24c6aae0be308a2626751c8e1e6ddb3754cd0
