### ISSUE TITLE
Icone do arquivo .por não funciona no Mac

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#237]
**Descrição do Problema**:
A associação do arquivo .por com o PS está funcionando no Mac, porém o ícone dos arquivos .por não está sendo reconhecido (ver imagem)

**Captura de Tela / Arquivo.por**:
![screen shot 2017-06-13 at 9 36 33 pm](https://user-images.githubusercontent.com/1012741/27110595-cb0530b8-5080-11e7-965b-8507749ac833.png)

**Especificações do sistema**:
Mac OSX (Maverics)

**Comment by noschang** [comment]
Esta issue foi integrada com a issue #239 e será resolvida junto com a mesma.
