### ISSUE TITLE
Mac - problema com associação do .por com o PS

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#238]
**Descrição do Problema**:
Clicando com o botão direito no mouse em um arquivo .por aparecem duas opções de execução. Parece que a associação com a versão anterior (2.2) não está sendo desfeita na instalação da versão 2.6

**Captura de Tela / Arquivo.por**:
![screen shot 2017-06-13 at 9 40 11 pm](https://user-images.githubusercontent.com/1012741/27110621-ee8abc92-5080-11e7-99dc-1cc67caa3dec.png)

**Especificações do sistema**:
Mac OSX (Maverics)

**Comment by noschang** [comment]
Esta issue foi integrada com a issue #239 e será resolvida junto com a mesma.
