### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#240]
@elieserdejesus você deu um novo release do portugol?? onde estão os assets do antigo?
Acabamos perdendo todos os dados de downloas, ect do release anterior 😢 
Sabe se tem como recuperar?

**Comment by elieserdejesus** [comment]
Eu substitui os assets @AlissonSteffens  (bad idea). Acho que não tem como recuperar.

**Comment by AlissonSteffens** [comment]
Ok, vamos combinar de sempre comunicar antes de um major update. E sempre manter os releases antigos. Fechando essa Issue
