### ISSUE TITLE
É "permitido" comparar Strings com "maior e menor", causando um erro de compilação

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#242]
**Descrição do Problema**:
Erro não é encontrado pela analise quando uma comparação de strings é feita, e quando o código é compilado gera um erro de compilação

**Mensagem de Erro (se houver)**:
![image](https://user-images.githubusercontent.com/8836540/27148299-2304f7e0-5116-11e7-8694-93f2b121bd54.png)

** Arquivo.por**:
[comparacao.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1075548/comparacao.zip)

**Comment by elieserdejesus** [comment]
corigido em https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/2017f258b5ffe55668a5bc271ef54b0bb057771d

![image](https://user-images.githubusercontent.com/1012741/27161730-bb79a934-5153-11e7-9f79-e8804700be90.png)

**Comment by noschang** [comment]
@elieserdejesus. Acredito que o melhor lugar para implementar esta solução é no AnalisadorSemantico e não no Helper de geração de código como você colocou.

Isso porque, colocando no semântico, faz mais sentido e, além disso, implementando no analisador semântico faz com que além de gerar a mensagem de erro na aba "Mensagens" gere também o sublinhado vermelho sob a expressão no editor de código fonte.

Além disso, sugiro adotar o padrão de mensagens de erro que o núcleo adota para outros erros similares:

https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/master/src/br/univali/portugol/nucleo/analise/semantica/erros/ErroTiposIncompativeis.java#L346

**Comment by elieserdejesus** [comment]
Ok @noschang , mas isso fica para o próximo episódio 😄 . Para o release 2.6 a implementação atual é suficiente.

**Comment by noschang** [comment]
OK
