### ISSUE TITLE
Mover Solução de comparação de Strings para Analisador Semantico

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#247]
De acordo com @noschang (2017),
> Acredito que o melhor lugar para implementar esta solução é no AnalisadorSemantico e não no Helper de geração de código como você colocou.

Visto a situação a resolução da Issue #242 deve ser mudada da Classe **Helper** para a classe **AnalisadorSemantico**

Além de alterar a mensagem para que seja compatível com as outras [mensagens do núcleo ](https://github.com/UNIVALI-LITE/Portugol-Nucleo/blob/master/src/br/univali/portugol/nucleo/analise/semantica/erros/ErroTiposIncompativeis.java#L346)

**Comment by AlissonSteffens** [comment]
o @noschang já moveu, estou fechando esta issue. XOXO :kiss: :kiss:

**Comment by noschang** [comment]
Movi?

**Comment by AlissonSteffens** [comment]
Vc disse que tinha movido, não?

**Comment by noschang** [comment]
Não lembro. Eu digo muitas coisas. Kkkkkk. Mas se eu disse, devo ter movido.
