### ISSUE TITLE
Bug na depuração de Matrizes

### ISSUE THREAD

**Issue by JuliaPeronMetzger** [UNIVALI-LITE/Portugol-Studio#248]
**Descrição do Problema**:
Não é possível ver todos os valores no debug das Matizes, mesmo nos momentos onde é incluído um novo valor na Matriz. O bug é possível ser identificando quando estamos incluindo valores nas linhas maiores que 5.

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/28781764/27298320-85db41c6-54fe-11e7-9bdf-85028f2d13f9.png)

**Comment by AlissonSteffens** [comment]
@elieserdejesus esse bug não tinha resolvido na issue https://github.com/UNIVALI-LITE/Portugol-Studio/issues/156 ???

**Comment by noschang** [comment]
@elieserdejesus. A linha 4 da matriz é exibida, porém, atrasada.
Tipo, o usuário dá um continuar, no programa e a matriz é alterada na linha 4, mas não é exibida.
Quando o usuário dá um continuar de novo, a matriz é alterada na linha 5 e então é exibida a linha 4.

**Comment by elieserdejesus** [comment]
Valeu pelas informações adicionais @noschang !

> @elieserdejesus esse bug não tinha resolvido na issue #156 ???

@AdsonEsteves , acho que com a mudança do núcleo (compilando em java), e baseado no que o @noschang comentou, o lugar onde o núcleo chama o método de parada deve ter mudado. Vou ter que olhar esse código com uma lupa assim que possível 😄 

@JuliaPeronMetzger , obrigado pelo report!

**Comment by elieserdejesus** [comment]
Acho que esse bug está corrigido, durante a correção percebi outros, mas esse outros resolvemos depois 😄 

![corrigido bug depuracao matriz](https://user-images.githubusercontent.com/1012741/27414054-4c2f0268-56d5-11e7-80d2-9cbee3acaf5b.gif)

**Comment by AlissonSteffens** [comment]
nice @elieserdejesus 
se for possível, cria depois as Issues destes outros problemas, porque as vezes a gente pode ir resolvendo 👍

**Comment by JuliaPeronMetzger** [comment]
Que legal que ficou!!!! Parabéns galera!!!

Em 21 de jun de 2017 15:07, "Alisson Steffens" <notifications@github.com>
escreveu:

nice @elieserdejesus <https://github.com/elieserdejesus>
se for possível, cria depois as Issues destes outros problemas, porque as
vezes a gente pode ir resolvendo 👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/UNIVALI-LITE/Portugol-Studio/issues/248#issuecomment-310255373>,
or mute the thread
