### ISSUE TITLE
Analise não pega atribuição de vetores ou  matrizes vazios

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#249]
**Descrição do Problema**:
Quando um vetor ou matriz é declarado e lhes é atribuído valores vazios, o analisador não encontra erro, e quando se é executado gera uma exceção na geração de matriz/vetor em Java

**Captura de Tela / Arquivo.por**:
```
programa
{
	funcao inicio()
	{
		inteiro x[] = {}
	}
}
```

**Comment by elieserdejesus** [comment]
resolvido no núcleo: https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/dd377c510dceee38ffe804c4004f539062648994
