### ISSUE TITLE
Parâmetros na funcao Inicio causam Erro na Compilação

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#259]
**Descrição do Problema**:
Ao se colocar parâmetros na função inicio, e executá-lo normalmente, gera um erro de compilação, consequentemente, todos os botões da aba ficam desativados.
A tela Opções de Execução, atualmente removida, permitia colocar os parâmetros da função inicio. Além de que no modo console, aparentemente ainda se pode fazer isso.

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/8836540/27496429-3c7023a4-582c-11e7-9052-78ae2f579431.png)

**Comment by elieserdejesus** [comment]
@noschang , considerando que a tela de opções foi removida, ainda existe algum uso para os parâmetros na função início? O pessoal do CRIA usa isso?  E se tiver um uso, vale a pena implementar isso agora que faltam aproximadamente 4 semanas para o início de um novo semestre (nosso dead line) ?

**Comment by noschang** [comment]
@elieserdejesus. A tela de opções foi removida, mas se executar o programa pelo portugol-console enviando parâmetros, este parâmetros serão colocados no vetor da fução início.

Não sei se alguém de fato usa este recurso. Se julgarem que não, então removam.

**Comment by elieserdejesus** [comment]
@noschang , me parece uma funcionalidade útil (passar parâmetros pela linha de comando) que alguém pode explorar. **Mas acho que não é algo para resolvermos nesse momento**, temos pouco tempo e coisas com mais prioridade (que vão afetar mais usuários).

**Comment by AlissonSteffens** [comment]
@AdsonEsteves ainda existe o problema?

**Comment by noschang** [comment]
Existe, acabei de testar. :-)
Vou resolver essa.

**Comment by noschang** [comment]
Resolvido no commit 8102d13dfd0e74184315b965913f1e6fa68df851.

![bug](https://user-images.githubusercontent.com/709553/30068368-fd17215c-9233-11e7-8efd-8a8273057cbb.png)
