### ISSUE TITLE
Possível problema de performance no processamento de dados

### ISSUE THREAD

**Issue by PedroWin** [UNIVALI-LITE/Portugol-Studio#261]
Olá, Boa tarde!
Venho entre vós relatar que após a atualização, a interface piorou consideravelmente, as cores não são muito agradáveis importantemente as palavras reservadas. Também se aumentou consideravelmente o tamanho do arquivo.exe para windows. Também o tempo de compilação tem demorado muito, após iniciar               o processamento de dados e lento, as vezes bugando em computadores inferiores. A base do programa e muito boa, agradeço se lerem está issue, e verificarem o programa para sua melhora.
Abraços!

**Comment by AlissonSteffens** [comment]
@PedroWin , algumas coisas devem ser levadas em consideração.
 * **Interface:** Você pode facilmente mudar como demonstrado no exemplo abaixo
![temas](https://user-images.githubusercontent.com/6234230/27748449-e6df2208-5da5-11e7-99db-51e076e8fe25.gif)

 * **Tamanho do Instalador:** O tamanho do instalador mudou devido ao fato de que agora inserimos a JDK junto com o projeto, e não somente a JRE. Isso nos permitiu compilar os programas Portugol e agora podemos criar aplicações bem mais robustas como por exemplo a abaixo.
![3d2](https://user-images.githubusercontent.com/6234230/27748728-d82da4c2-5da6-11e7-98fd-4ca404b7ce35.gif)

 * **Tempo de Compilação:** Este problema realmente existe no RC2 e já foi resolvido em #246, esta versão será publicada em breve.

Sobre a demora no processamento de dados, ainda não pudemos perceber este problema, caso possível relatar melhor quando e como ela ocorre, ficaremos felizes em poder ajudar

**Comment by PedroWin** [comment]
Muito obrigado pela ajuda!! Espero que o portugol prospere mais e mais!
Abraço!

Em 30 de junho de 2017 15:18, Alisson Steffens <notifications@github.com>
escreveu:
