### ISSUE TITLE
Botões de navegação entre abas

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#262]
**Descrição do Problema:**
Após abrir uma quantidade elevada de abas e fecha-las da direita para esquerda até as que estão visíveis acabarem as anteriores não são mostradas e os botões de navegação estão em baixo do 'X' de fechar, quase invisíveis.

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/21344756/27748933-bb2da1d2-5da7-11e7-9d28-ae4b16983576.png)
![image](https://user-images.githubusercontent.com/21344756/27748946-c5e20eb0-5da7-11e7-87f7-c4e66ac81f42.png)

**Comment by AlissonSteffens** [comment]
Comportamento estranho, em alguns computadores, mesmo com o erro da navegação, as abas ainda são renderizadas:
![image](https://user-images.githubusercontent.com/6234230/27749038-23d0ad56-5da8-11e7-93cd-1d280b258b58.png)

**Comment by AlissonSteffens** [comment]
o problema é importante, mas não acho que dê para resolver para esta versão. Anyway, temos que nalisar qual o melhor modo de resolve-lo.
Atualmente, o problema acontece pois o **gridbag layout** está colocando os botões de controle da janela por cima do **tabbedpane**, temos assim algumas opções:
 1. Limitar as abas para só irem até os botões
![limitar](https://user-images.githubusercontent.com/6234230/27799051-199e63ac-5fea-11e7-9b92-458a7c21e4c8.jpeg)
2. Separar a área dos botões da área das abas, e assim ganhamos uma barra de título
![separar](https://user-images.githubusercontent.com/6234230/27799068-2b180066-5fea-11e7-92e4-11bb0b5c91b4.jpeg)
 3. Compactar as abas (igual o chrome faz)
![compactar](https://user-images.githubusercontent.com/6234230/27799133-6e8ab73a-5fea-11e7-88cd-0dc0b746a227.jpeg)

**Comment by AdsonEsteves** [comment]
@Rafaelfcosta 
Podes tentar resolver essa?
É um pouco mais dificil que a outra que você resolveu, mas igualmente tente resolver no seu tempo :)

O Alisson já deu umas ideias de possíveis soluções, tente ver se consegue implementar uma delas

**Comment by AlissonSteffens** [comment]
Eu acho o opção número 1 a melhor escolha, visto que não é tão complexa para o @Rafaelfcosta resolver, e ainda mantém o layout do portugol da maneira que foi projetado para

**Comment by Rafaelfcosta** [comment]
Posso tentar sim, só gostaria de algumas dicas como:
- O que terá que ser feito para limitar as abas
- Quais arquivos devem ser modificados

**Comment by AlissonSteffens** [comment]
Acho que os arquivos são:

https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/src/br/univali/ps/ui/abas/AbaInicial.java
https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/src/br/univali/ps/ui/window/BorderPanel.java
https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/src/br/univali/ps/ui/window/OutsidePanel.java

Tens que mexer no GridBagLayout se não me engano.
