### ISSUE TITLE
Instruções de instalação para usuário Linux

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#264]
@elieserdejesus, conforme havíamos conversado pessoalmente, considero de suma importância disponibilizar um mini tutorial de instalação do Portugol Studio para os usuários de Linux.

Sendo assim, segue em anexo um TXT com algumas instruções simples para serem anexadas ao instalador da versão Linux. Sugiro criar um ZIP contendo o arquivo de instalação (.run) e o arquivo TXT com as instruções.

Favor revisar e ajustar o que considerares necessário antes de anexar o arquivo.

[leia.txt](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1121914/leia.txt)

**Comment by elieserdejesus** [comment]
@noschang , passei a tarefa de gerar o próximo instalador para o @AdsonEsteves .

Adsson, podes incluir essas instruções no release oficial?

**Comment by AlissonSteffens** [comment]
@AdsonEsteves já resolveu o problema:
![image](https://user-images.githubusercontent.com/6234230/28042250-e21d643c-65a2-11e7-86b4-009130ac167b.png)
