### ISSUE TITLE
Modificar link de reportar bug

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#265]
> O fato de usuário ter que criar a issue no Github pode ser assustador.
>-Jesus 2017

O novo link, ao invés de criar issues, deve enviar para o canal no [Discord](https://discordapp.com/)
O link é: https://discord.gg/fRW7Vq2

Para comentar no discor **não** é necessário criar conta

**Comment by elieserdejesus** [comment]
@AlissonSteffens , cliquei no link que você postou e caí nessa tela:

![image](https://user-images.githubusercontent.com/1012741/27890366-8d056428-61c8-11e7-87b7-1de250fe0571.png)

O que voces acham @noschang , @AdsonEsteves e @Rafaelfcosta ?

**Comment by AlissonSteffens** [comment]
Isso, aceita, põe um nome e manda bala

**Comment by AdsonEsteves** [comment]
Eu sou 100% de apoio.
Fico dia inteiro nessa coisa.
Como também, vários grupos(de software ou não) que frequento estão mudando pro discord, infelizmente, a maioria não é do Brasil, já que não é muito popular por aqui.

Eu adoraria que o pessoal do Brasil mudasse do Whatsup pro discord, mas ainda todo mundo é muito ligado nele :\

**Comment by AlissonSteffens** [comment]
![thumbs-up_o_109639](https://user-images.githubusercontent.com/6234230/27890711-e7f30906-61ca-11e7-8b32-eb79cf2e853d.gif)

**Comment by Rafaelfcosta** [comment]
Pode ser uma boa ideia, já que o discord vem a ser mais familiar pra muitos do que o Github

**Comment by elieserdejesus** [comment]
> infelizmente, a maioria não é do Brasil, já que não é muito popular por aqui.
> Eu adoraria que o pessoal do Brasil mudasse do Whatsup pro discord, mas ainda todo mundo é muito ligado nele :\

E vocês não vêem nenhum problema em propor uma ferramenta que **não é popular no Brasil** para um público brasileiro?

**Comment by AlissonSteffens** [comment]
## Pontos positivos:
 1. Não precisa de conta
 2. Público que é acostumado com jogos já conhece o programa *(muitos alunos de computação?)*
 3. É gratuito e não tem propagandas
 4. Permite criação de canais para melhor compreensão dos assuntos
![image](https://user-images.githubusercontent.com/6234230/27892637-4c71a48a-61d7-11e7-9bf0-d91c5818d9ab.png)
 5. Permite fixar mensagens para informar novos usuários
 6. É **realmente** multiplataforma, rodando no navegador, ou instala e tem app para celular
 7. Compatível com APIs e bots, como os webhooks do github
![image](https://user-images.githubusercontent.com/6234230/27892709-9c955a38-61d7-11e7-8d29-c335a4062cc0.png)
 8. Muitos grupos, páginas e comunidades estão migrando para ele *(inclusive [foruns](http://boards.4chan.org/vg/thread/181620384))*

**Comment by AdsonEsteves** [comment]
Se formos falar por popular no brasil, o certo seria usar ou WhatsUp ou Facebook.
Usar o GitHub pra reportar issues, tbm não é popular no Brasil.

De qualquer maneira, o principal ponto, não enviesado aqui, é que, o discord permite que você entre nele sem ter uma conta. Apenas precisa colocar um "nick" e entrar no servidor.

Acredito que o único possível problema dele possa ser ele ser informal(já que é um chat) e portanto a pessoa não criaria a issue direto aqui.

Não acredito ser um problema pois se a pessoa perceber um bug, podemos resolver com ela diretamente se já foi reportado isso ou não, ou se foi algum erro dela, e caso seja realmente um bug, pedir os detalhes.

**Comment by AlissonSteffens** [comment]
Nem lançamos o release oficial com o link para criar issues e já foram criadas issues que na verdade são dúvidas de uso, como a #261 e outra que nem era erro do portugol como a #231, poderiamos evitar que este tipo de problema viesse para o git, resolvendo eles no chat

**Comment by elieserdejesus** [comment]
Tenho 2 perguntas para vocês:

1 - Qual é o problema que temos para resolver?
2 - Qual é a solução mais simples (do ponto de vista do usuário)?

Se vocês refletirem sobre essas 2 questões verão que nenhuma das coisas que foram mencionadas anteriormente como sendo **pros** ajudam a resolver o problema. Na verdade algumas coisas mencionadas (como discutir bugs no chat com os usuários) até criaram novos problemas e demandas.

> Usar o GitHub pra reportar issues, tbm não é popular no Brasil.

Exatamente, e trocar uma ferramenta que não é popular por outra (igualmente impopular) não resolve o problema.

Pergunto novamente: **qual é o problema que temos?**

**Comment by noschang** [comment]
1. O problema que temos é que o GitHub obriga a criação de uma pra repostar a issue

2. A solução mais simples do ponto de vista do usuário é a ferramenta não ter bugs. Se a ferramente não tiver bugs ele não vai precisa relatar nada

**Comment by elieserdejesus** [comment]
> O problema que temos é que o GitHub obriga a criação de uma pra repostar a issue

@noschang , esse é o problema que temos **usando o github** como ferramenta de comunicação entre o **usuário** e o PS. 

E se você **esquecer o github**? e esquecer também qualquer outra ferramenta já mencionada? **o que sobra** do problema? Ainda existe um problema?

**Comment by noschang** [comment]
@elieserdejesus. Se quisermos que os usuários reportem os bugs, teremos que ter um canal de comunicação.

Concordo que o Github não seja o meio mais eficiente e adequado, pelos motivos já citados. E assim como você, penso que devemos buscar uma solução que seja mais popular aqui no Brasil. No entanto, não consigo pensar em uma ferramenta que seja melhor pra isso.

E se a melhor solução for permitir o usuário relatar um bug ou propor uma soluação diretamente no Portugol Studio? Pensa bem. Ele clicaria na opção "Relatar um bug" e abriria uma tela bem simples com um campo pra por o título do problema e um campo de texto pra digitar. Ao clicar em enviar, o PS transformaria os dados e enviaria para onde for melhor pra nós (seja Github, Gitter, Discord, Slack, etc).

Ou seja, simplificamos a interface com o usuário, pois ele não precisa usar uma ferramenta externa à qual não está habituado. Também vale lembrar que no momento o PS é mais usado no Brasil, mas em algum momento ele tende a atingir outros países. Neste caso, ter a solução implementada na própria ferramenta poderia evitar que tenhamos vários canais de comunicação (um para cada país/ região).

**Comment by elieserdejesus** [comment]
> E se a melhor solução for permitir o usuário relatar um bug ou propor uma solução diretamente no Portugol Studio? Pensa bem. Ele clicaria na opção "Relatar um bug" e abriria uma tela bem simples com um campo pra por o título do problema e um campo de texto pra digitar. Ao clicar em enviar, o PS transformaria os dados e enviaria para onde for melhor pra nós (seja Github, Gitter, Discord, Slack, etc).

@noschang , onde eu clico para te dar todo meu dinheiro? 😄 

É exatamente isso que eu penso, nós já tínhamos uma solução boa (um formulário dentro do próprio PS), o problema não era o formulário, o problema era outra coisa, e nem envolvia software. Inclusive eu ouvi o @AdsonEsteves dizendo exatamente as palavras **"... o problema é que ninguém ..."**. 

Lembras disso @AlissonSteffens , consegues completar a frase?

**Comment by noschang** [comment]
@elieserdejesus, conforme seu pedido:

![button_give-all-my-money-to-noschang](https://user-images.githubusercontent.com/709553/27916923-e0c81132-6240-11e7-8ce8-5c5b5e486d8e.png)

**Comment by AdsonEsteves** [comment]
"O problema é que ninguém fica vendo os reportes" -q
Acho que foi isso que disse.

Bom, acredito que além deste problema, de ninguém ver. Também não temos contato com o usuário, uma vez mandado o bug. Assim, não poderíamos sanar as dúvidas em uma conversa com o mesmo.
Isso poderia ser resolvido pedindo o e-mail da pessoa no formulário, mas vamos voltar com o formulário?

**Comment by AlissonSteffens** [comment]
# Usando a abordagem do @noschang , vejo algumas dúvidas
 1. E esse formulário que vamos implementar, vai estar pronto para esta versão?
 2. Como faremos para enviar as mensagens?
 3. O servidor para os reports vai estar aonde?
 4. Como iremos responder os usuários?
 5. Qual a probabilidade de várias pessoas mandarem report do mesmo erro?
 6. Quem vai ter acesso a esses reports?
 7. Vai funcionar em todas as plataformas?
 8. Além de bugs, caso o usuário tenha uma dica para a IDE, como ele deve proceder?
 9. E se ele tiver uma dúvida?
 10. Ainda mais específico, se ele estiver querendo ajudar no código, onde ele pode contatar-nos?

**Comment by elieserdejesus** [comment]
> E esse formulário que vamos implementar, vai estar pronto para esta versão?

Com certeza não @AlissonSteffens , essa versão fechou. Poderia ser feito para a 2.6.1.

Para todas as outras questões é resposta é **49** 😄 .  

Acho que precisamos conversar pessoalmente sobre esta questão da comunicação entre usuário e equipe do PS, e acho que o buraco é até mais embaixo, a ponto do tema merecer uma reunião.

**Comment by AlissonSteffens** [comment]
Este tema será abordado posteriormente e esta issue não é mais válida por sua função inicial
