### ISSUE TITLE
Inspeção de variáveis 

### ISSUE THREAD

**Issue by edilsonlcjr** [UNIVALI-LITE/Portugol-Studio#268]
Na inspeção de variáveis, quando atribuímos um valor pelo método LEIA, o valor dessa variável não é carregado na janela de inspeção na versão 2.6 (link: https://github.com/UNIVALI-LITE/Portugol-Studio/releases/tag/v2.6)

**Comment by elieserdejesus** [comment]
Corrigindo essa issue em  https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/113

![portugol inspetor leia](https://user-images.githubusercontent.com/1012741/28120479-8676766c-66ee-11e7-8f91-e13416fda795.gif)

**Comment by elieserdejesus** [comment]
obrigado por reportar o bug @edilsonlcjr !

**Comment by elieserdejesus** [comment]
resolvido em https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/113
