### ISSUE TITLE
Abrir 4 Portugois ao mesmo tempo joga Exceções na cara do usuário.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#270]
**Descrição do Problema**:
Quando o Portugol é aberto através dos arquivos .por (com ele não inicializado) e se abre 4 ao mesmo tempo (selecionando varios arquivos .por e apertando enter), mensagens de erro são cuspidas na tela e ele só abre um dos arquivos.

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/7809511/28081480-c90d5dfa-6645-11e7-9698-7eee25600d19.png)
![image](https://user-images.githubusercontent.com/7809511/28081503-d9816a8c-6645-11e7-80a9-4a4f59af28ce.png)
[Bomberman.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1139752/Bomberman.zip)
(Tente abrir 4 arquivos ou + ao mesmo tempo (selecione todos os arquivos .por e aperte enter.)

**Especificações do sistema**:
Windows

**Comment by AlissonSteffens** [comment]
Para mais informações : #272

**Comment by AdsonEsteves** [comment]
Com 2 portugois abertos ao mesmo tempo o erro não acontece

**Comment by AlissonSteffens** [comment]
Tá tenso erro, e está se repetindo muito!!!
**1**. A primeira abertura do Portugol demonstra este erro:
![image](https://user-images.githubusercontent.com/6234230/29978646-7926aeb2-8f18-11e7-9e75-00b93d96333c.png)
**2**. Depois:
![gif](https://user-images.githubusercontent.com/6234230/29046957-169a82ea-7ba0-11e7-834b-03550d34d3fe.gif)
