### ISSUE TITLE
Unreachable Statement com enquanto(verdadeiro)

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#271]
**Descrição do Problema**:
enquanto(verdadeiro) com código compilavel em baixa é aceito pelo Portugol, porém negado pelo java
Solução 1: criar uma variável antes de cada laço de repetição booleana para enganar o compilador  (@noschang) 
Solução 2: achar um compilador que ignore isso
Solução 3: Função que filtre todas as expressões

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/7809511/28082210-331510e2-6648-11e7-89a6-a13fb6809f62.png)
[Bomberman (2).zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1139794/Bomberman.2.zip)

**Especificações do sistema**:
Windows

**Comment by AdsonEsteves** [comment]
![image](https://user-images.githubusercontent.com/8836540/29834553-912fa176-8cc5-11e7-838b-b1354470d933.png)
