### ISSUE TITLE
Erro ao alterar codigo

### ISSUE THREAD

**Issue by Mcymb** [UNIVALI-LITE/Portugol-Studio#272]
**Descrição do Problema**:
Sempre que faço qualquer alteração no código, por menor que seja,abro o programa, um arquivo, ou crio um novo arquivo, aparece o seguinte erro:
**Mensagem de Erro (se houver)**:
java.lang.NullPointerException
**Captura de Tela / Arquivo.por**

![image](https://user-images.githubusercontent.com/6234230/28177877-aacaf60c-67d2-11e7-990a-b280fcbb7d94.png)

[Preço com desconto.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/1143013/Preco.com.desconto.zip)

**Especificações do sistema**:

Intel Celeron E3400 2,60 GHz 2.59GHz
2GB RAM
Intel G41 Express Chipset (integrada)
Windows 7 ultimate service pack 1 32 bits

**Comment by noschang** [comment]
Aqui rodou normalmente. Bug não confirmado. Alguém mais da equipe pode verificar?
A imagem que o usuário anexou também está offline.

**Comment by AlissonSteffens** [comment]
não consegui reproduzir o erro, @Mcymb , pode me dar mais informações sobre como você fez com que isso acontecesse???
![possivelerro](https://user-images.githubusercontent.com/6234230/28141415-db7ce9ae-6732-11e7-89e8-a1dacfc56319.gif)

**Comment by Mcymb** [comment]
Ola pessoal, sinto muito pela demora, estava viajando, acho que deve ser um erro em meu computador, o erro acontece quado eu altero qualquer linha, ate msm uma letra, porem tem vezes que eu abro o portugol studio e roda normal e tem vezes que da esse erro.

Novamente desculpem-me pela demora...
Agradeço desde já!

**Comment by AlissonSteffens** [comment]
Acho que consegui reproduzir o erro após tentar abrir um arquivo **.por** insanamente.
![ad](https://user-images.githubusercontent.com/6234230/29046957-169a82ea-7ba0-11e7-834b-03550d34d3fe.gif)

**Comment by AlissonSteffens** [comment]
Erro relacionado pode estar à #270 se esta mensagem aparecer para o @Mcymb 
![](https://user-images.githubusercontent.com/7809511/28081503-d9816a8c-6645-11e7-80a9-4a4f59af28ce.png)

Pode confirmar??

**Comment by AlissonSteffens** [comment]
duplicate of #270

**Comment by AlissonSteffens** [comment]
Duplicate of #270
