### ISSUE TITLE
Breakpoints ativados estão sendo "desativados"

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#273]
**Descrição do Problema**:

Quando o código é alterado os breakpoints que estavam "ativados" não continuam dessa maneira.
Para reproduzir o erro
1 - Ative um breakpoint.
2 - Faça qualquer alteração no código.
3 - O breakpoint que estava ativado ficará desativado.

**Captura de Tela / Arquivo.por**:
![portugol breakpoints](https://user-images.githubusercontent.com/1012741/28136907-a2061206-6721-11e7-8036-7be9af3a9a3e.gif)

**Comment by AdsonEsteves** [comment]
A seguinte lógica foi adicionada para resolver o problema dos pontos de parada não serem removidos quando uma linha era removida. E é essa mesma lógica que está causando o problema desta issue.

![image](https://user-images.githubusercontent.com/8836540/28187238-51af65ea-67f4-11e7-9a42-d64ecc4fcf39.png)

Aparentemente o MarkedOffset do GutterInfo do IconeDeParada sempre muda quando há uma alteração no código, ou seja, a função `markerOffsetMudou()` vai sempre retornar verdadeira quando há alterações em qualquer parte do código.

E na área especificamente marcada, os icones são "removidos", quando ele esta ativado e o marked mudou, então por isso quando um código é removido o ponto de parada desativa.

Tem que se buscar uma maneira de verificar a linha ao invés desse markedOffSet pois é de uma classe de fora que não temos controle.

Vou tentar buscar uma solução
