### ISSUE TITLE
[Inspetor] - Matriz 1 x 1 não é renderizada corretamente

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#274]
**Descrição do Problema**:
Matriz de tamanho 1 x 1 não aparece corretamente no inspetor.

**Captura de Tela / Arquivo.por**:
![portugol matriz](https://user-images.githubusercontent.com/1012741/28137056-497df35a-6722-11e7-81ad-4772204bd13b.gif)

**Comment by AlissonSteffens** [comment]
uma matriz de [1][1] não é um vetor [1]?
Talvez fosse interessante o Portugol avisar isso pro usuário, não?
Se ele está criando esta matriz, existe uma grande chance de ele não saber o que está fazendo.

**Comment by elieserdejesus** [comment]
Concordo @AlissonSteffens , criei uma nova issue para emitir esses avisos https://github.com/UNIVALI-LITE/Portugol-Studio/issues/276

**Comment by elieserdejesus** [comment]
Corrigido:
![portugol matriz 1x1 corrigido](https://user-images.githubusercontent.com/1012741/28192217-0370e7d4-680b-11e7-91c6-a7bc4b1e8599.gif)
