### ISSUE TITLE
Emitir avisos para matrizes que seriam mais simples se fossem vetores ou variaveis

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#276]
**Descrição do Problema**:

- uma matriz de [1][1] é um vetor [1]
- uma matriz [1][100] é um vetor [100]
- uma matriz[100][1] também é um vetor[100]

Ideia: emitir avisos informando isso para o estudante. É possível que o estudante esteja criando estruturas de dados desnecessariamente complicadas.

**Comment by AlissonSteffens** [comment]
@elieserdejesus inclusive ao invés de 
uma matriz de [1][1] é um vetor [1]

* uma matriz de [1][1] é uma variável
* um vetor [1]  é uma variável

**Comment by elieserdejesus** [comment]
Concordo @AlissonSteffens !

@noschang , no momento o único jeito de dar "dicas" para o estudante é emitindo um warning? Ou existe uma categoria de mensagem que não seja erro ou warning?

**Comment by noschang** [comment]
@elieserdejesus. Depende de que qual notificação você se refere. Se você está se referindo a notificações do tipo "JOptionPane", então eu acho que exitem 3 categorias que o Portugol Studio permite: ERROR, WARNING e INFO.

Se você está se referindo a notificações utilizando o WebPopup, então acredito que não haja restrição nenhuma.

**Comment by elieserdejesus** [comment]
@noschang , acho que não me expressei adequadamente sobre as "dicas". A pergunta seria: temos como exibir dicas **na console do PS**? 

Essas dicas não são erros nem warnings, são uma categoria "mais leve" de avisos.  Temos algo assim implementado? Como o Pelz dava/apresentava as dicas no corretor dele?

**Comment by elieserdejesus** [comment]
Ótimo @noschang , acho que esse é o caminho. Inclusive acho bem provável que no futuro outras "dicas" úteis sejam fornecidas.
