### ISSUE TITLE
Modo debug do Portugol facilitado para usuário

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#277]
Atualmente no Portugol para ativar o modo debug é necessário passar como um dos parâmetros de inicialização um `-debug` .
O modo debug permite que quando uma exceção é gerada, um Dialog é criado mostrando o Stack trace da exceção.
Facilitar a ativação do modo debug, permitiria que caso um erro aconteça com algum usuário, e este erro não seja replicável em nossas máquinas, poderíamos pedir que o usuário mostrasse o Stacktrace que é gerado no modo debug, assim, facilitando a identificação do erro.

Uma maneira ideal de facilitar isso, seria colocar juntamente dentre essas opções, a opção "Executar em modo debug".

![image](https://user-images.githubusercontent.com/8836540/28178206-f448650c-67d3-11e7-9326-84d27e435c49.png)

**Comment by AlissonSteffens** [comment]
Layout da tela para o novo modo Debug:
![relatarbug](https://user-images.githubusercontent.com/6234230/29229656-f8bfcf1e-7eb5-11e7-834b-0ca71e3c211a.jpeg)

**Obs:** O arrendondamento de cantos do botão pode ser feito [aqui](https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/src/br/univali/ps/ui/swing/weblaf/WeblafUtils.java#L350) para que seja aplicado em todos os botoes do portugol

**Comment by AlissonSteffens** [comment]
Abaixo, os ícones para a página:

![face](https://user-images.githubusercontent.com/6234230/29229873-ecdea39a-7eb6-11e7-922b-86b43018daa1.png)
![issue](https://user-images.githubusercontent.com/6234230/29229874-ecec8a5a-7eb6-11e7-8522-c3db0b33e6c2.png)
![debug](https://user-images.githubusercontent.com/6234230/29229877-ecefa2e4-7eb6-11e7-9874-9cab2ea30086.png)
![discord](https://user-images.githubusercontent.com/6234230/29229875-ececeb76-7eb6-11e7-934c-ab35f88f787a.png)
![mail](https://user-images.githubusercontent.com/6234230/29229876-ecee2856-7eb6-11e7-9c4f-ef0a9b581507.png)

**Comment by AlissonSteffens** [comment]
Botões arredondados inseridos aqui https://github.com/UNIVALI-LITE/Portugol-Studio/commit/4fee9c9de6b8e730ed52ad8ced1b01ef76aa6f6b

**Comment by elieserdejesus** [comment]
Pessoal, acho que usar o termo "modo debug" pode ser confuso, já que em todas as IDEs modo debug significa uma coisa bem diferente disso que está sendo proposto.  Por exemplo, na maioria das IDEs (a verdade acho que em todas as que eu já trabalhei) você só vê um breakpoint funcionando se executar no "modo debug". 

> O modo debug permite que quando uma exceção é gerada, um Dialog é criado mostrando o Stack trace da exceção.

É possível deixar isso sempre ativo (sem ter que usar um outro botão)? É possível deixar isso mais transparente para o usuário? 

**Algo como:** se uma exceção não tratada for capturada mostramos uma tela com a stacktrace e um botão "relatar erro para a equipe de desenvolvimento"?

**Comment by AlissonSteffens** [comment]
Tenho que lembrar de arrumar // comentário -> https://github.com/UNIVALI-LITE/Portugol-Studio/commit/4fee9c9de6b8e730ed52ad8ced1b01ef76aa6f6b

**Comment by AdsonEsteves** [comment]
@elieserdejesus 
Gostei da ideia, o problema de não mostrar o Stack e ter esse modo "escondido", era pra não assustar o usuário com uma mensagem com erros estranhos.

Discutimos aqui, e foi decidido manter o "modo debug" sempre ativo, e deixar a tela com o Stack Trace mais amigável.

Por exemplo um texto explicando o que aconteceu, e pedindo ao usuário que poste o erro no nosso repositório e o Stack Trace em uma tela diminuida para não assusta-lo muito.

**Comment by elieserdejesus** [comment]
maravilha @AdsonEsteves , acho que é uma ótima ideia.
