### ISSUE TITLE
Comportamento não natural ao depurar

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#278]
Quando estamos depurando o valor só é atribuído a variável no inspetor após o comando ter passado, acho entretanto que isso devesse ser feito enquanto estiver "parado" naquela linha:
(um gif vale mais que milhões de palavras)
![estranho](https://user-images.githubusercontent.com/6234230/28179708-21ffcb8e-67d9-11e7-9917-b6e22f563322.gif)

**Comment by elieserdejesus** [comment]
@AlissonSteffens ,concordo que sua ideia é mais interessante do que a atual.

@noschang , me corrija se eu estiver enganado:
Para termos o comportamento descrito pelo @AlissonSteffens a solução é mudar o momento em que o núcleo faz a "parada" na execução, certo?

**Comment by noschang** [comment]
@elieserdejesus. Está correto. É só chamar o realizarParada após a execução da instrução e não antes.

Porém existem alguns cuidados que devem ser tomados. Como isso se comportaria no caso de um retorno de função, por exemplo?

**Comment by noschang** [comment]
@elieserdejesus. Aproveitando o bonde, o que acontece se o cara tiver duas funções, as duas com uma variável local chamada "a" e ele arrastar ambas variáveis para o inspetor?

O inspetor mostra duas variáveis "a"? Como o usuário sabe de qual função/escopo se trata a variável? Será que não seria interessante abrir uma nova issue para investigar isso e ver se podemos melhorar também?

**Comment by elieserdejesus** [comment]
> O inspetor mostra duas variáveis "a"? Como o usuário sabe de qual função/escopo se trata a variável? Será que não seria interessante abrir uma nova issue para investigar isso e ver se podemos melhorar também?

Acho que é muito válido mostrar o escopo @noschang , mas somente no caso que você mencionou (variáveis com nomes iguais mas escopos diferentes), assim evitamos poluição visual.

**Comment by noschang** [comment]
@elieserdejesus estou abrindo uma nova issue para discutirmos estas alterações.

**Comment by AlissonSteffens** [comment]
Foi decidido em #480 que não faria sentido mostrar em sequencia diferente da das IDEs comuns, logo esta issue não é mais válida
