### ISSUE TITLE
Criar mecanismo de notificação de atualizações

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#280]
A ideia é implementar dentro do Portugol Studio um mecanismo que permita comunicarmos ao usuário quando uma nova versão está disponível para ser baixada (além de outras informações que podem surgir ao longo do tempo).

- [x] Definir como vamos alimentar estas informações: formato dos dados no servidor, onde será esse servidor (lite?, github?)

- [x] Definir como vamos apresentar estas notificações aos usuários dentro do Portugol Studio (WebPopup, JOpitonPane, painel na tela inicial)

- [x] Tratar casos de erro e falhas de comunicação com o servidor

- [x] Como identificar quais notificações já foram lidas pelo usuário

**Comment by elieserdejesus** [comment]
>  como vamos alimentar estas informações: formato dos dados no servidor, onde será esse servidor (lite?, github?)

Sempre que fazemos um release no github uma nova tag é criada automaticamente. Acho que vale a pena usar a [API do github](https://developer.github.com/v3/repos/releases/#get-the-latest-release) para verificar a **tag do último relese** e comparar com uma tag embutida no PS. Essa ultima parte (tag embutida no PS) tenho algumas ideias, nem tão boas assim:
1 - A tag ficará no código, hardcoded, teremos que lembrar de mudá-la no código antes de gerar um release. Bastante sujeito a erros.
2 - A tag poderia ser gerada pelo **Ant**, o Ant gera um arquivo com o **build number**. lembro que usamos isso uma vez. Acho que diminuiu um pouco a chance de erros em reação a opção 1, mas ainda tem uma boa chance de erros.

**Comment by noschang** [comment]
@elieserdejesus eu pensei em algo que pudesse ser controlado pelo lado servidor e só consumido pelo Studio. Poderíamos ter no servidor um Json meio que autodescritivo, algo do tipo:

```json
{
    "notifications": [{
        "id": "2", 
        "date": "13/03/2018", 
        "type": "INFO", 
        "message": "Uma mensagem informativa qualquer",
        "data": {
            "campo1": "Dado adicional da mensagem",
            "campo2": "Dado adicional da mensagem"
        }
    },
    {
        "id": "1", 
        "date": "05/02/2018", 
        "type": "RELEASE", 
        "message": "Uma nova versão Portugol Studio já está disponível para Download",
        "data": {
            "version": "2.6.1", 
            "downloadUrl": {
                "windows": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.windows.exe",
                "mac": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.osx.zip",
                "linux_32": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.linux.zip",
                "linux_64": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.linux.x64.zip",
                "multiplatform_32": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.multi-plataforma.zip",
                "multiplatform_64": "https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.6.1/portugol-studio.2.6.1.multi-plataforma.x64.zip",
             },
            "releaseNotes": [{
                    "type": "FEATURE",
                    "note": "Novo recurso de conclusão de código"
                },
                {
                    "type": "BUG",
                    "message": "Corrigido bug no inspetor de variáveis ao ler uma variável"
                },
                {
                    "type": "SAMPLES",
                    "note": "Jogo de batalha naval multiplayer usando a biblioteca Rede"
                }]
        }
    }]
}
```

Note que vai ter um campo "id" para cada notificação. Podemos usar esse campo para gravar quais notificações já foram lidas pelo usuário. E se quisermos, podemos depois remover as notificações mais antigas.

Em geral, todas as notificações teriam o mesmo formato básico, com exceção do campo "data". Este campo poderia mudar de acordo com o tipo de notificação. Isso é facilmente tratável pelo Portugol Studio, pois bastaria ele ler o campo "type" e dependendo do tipo de notificação, processar o campo "data" de um jeito ou de outro.

Enfim, acho que nesse formato temos bastante dinamismo pra adicionar novos tipos de notificação futuramente, sem complicar muito a vida.

**Comment by AlissonSteffens** [comment]
@noschang, acho essa ideia realmente muito boa, e também penso que devemos ter uma API assim, porém, tem que pensar se teremos um servidor bom o suficiente pra isso ✌️

**Comment by noschang** [comment]
Então @AlissonSteffens. Não sei se vamos automatizar isso ou fazer manualmente. Mas eu pensava em criar esse arquivo dentro do site do Portugol-Studio, no branch gh-pages.

Daí ficaria "hosteado" no próprio Github. No caso o endereço seria:
https://univali-lite.github.io/Portugol-Studio/notifications.json

**Comment by AlissonSteffens** [comment]
![thumbs_up_waynes_world](https://user-images.githubusercontent.com/6234230/28216529-65be7b04-6888-11e7-921d-87afcaf89ced.gif)

**Comment by elieserdejesus** [comment]
> Mas eu pensava em criar esse arquivo dentro do site do Portugol-Studio, no branch gh-pages.

> Daí ficaria "hosteado" no próprio Github. No caso o endereço seria:
https://univali-lite.github.io/Portugol-Studio/notifications.json

Também acho uma boa idea, o github deve aguentar o tranco :)

**Comment by AdsonEsteves** [comment]
@UNIVALI-LITE/portugol-studio 

Vou fazer o sistema de notificação de release usando a APi do Github mesmo.
Isso pode ser feito mais rapidamente e a ideia do noschang pode ser implementada quando realmente precisarmos usar o sistema para outros tipos de notificações
