### ISSUE TITLE
Erro com variável do tipo caracter

### ISSUE THREAD

**Issue by inacioMattos** [UNIVALI-LITE/Portugol-Studio#286]
**Descrição do Problema**:
Portugol Studio não aceitando variável do tipo caracter com o valor de: '\\'.

Java:
```java
public static void main(String[] args) 
{
	System.out.println('\\');
}

resultado: "\"
```

Enquanto o equivalente desse código no Portugol Studio produz diferentes erros.
![erro-portugol](https://user-images.githubusercontent.com/24547963/29004537-55ea0814-7a9f-11e7-9b35-f1d7cc97663d.png)

**Comment by inacioMattos** [comment]
Achei uma maneira de contornar o problema: converter de cadeia para caracter.
```
programa
{
	inclua biblioteca Tipos
	
	funcao inicio()
	{
		escreva(Tipos.cadeia_para_caracter("\\"))
	}
}
```
Apesar disso, acredito que o ideal seja corrigir de vez o erro, considerando que essa solução é uma clara gambiarra :p.

**Comment by AlissonSteffens** [comment]
Corrigido em:
https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/5063a26ce778a923f8214718471b6db21c8513b4
