### ISSUE TITLE
Problemas com as escapes sequences 

### ISSUE THREAD

**Issue by inacioMattos** [UNIVALI-LITE/Portugol-Studio#287]
**Descrição do Problema**:
Percebi um comportamento inesperado e um problema causado por esse comportamento, achei melhor também incluir ambos em um só issue já que estão relacionados.

O comportamento inesperado é com todas as escapes sequences, se colocado, por exemplo "\\\\n", o Portugol realiza ambas escapes sequences presentes na string, nesse caso: coloca o caracter "\\" mas também realiza a quebra de linha, o que é um comportamento diferente da maioria das linguagens e causa um outro problema que vou detalhar mais abaixo.
```java
Java:

public static void main(String[] args) 
{
	System.out.println("string1 \\n string2");
}

resultado: 
"string1 \n string2"
```
Já no Portugol o resultado é diferente, como citado acima parece estar realizando ambas escapes sequences.
![erro-portugol02](https://user-images.githubusercontent.com/24547963/29005258-5dfab824-7aad-11e7-983c-1106126fa43a.png)

Problema com o "\r": não sei se o mesmo foi implementado ou não, mas parece ser tratado como se fosse implementado, pois ao tentar usa-lo é dado uma mensagem de erro diferente de ao tentar usar uma escape sequence não implementada ("\i", por exemplo):
![erro-portugol03](https://user-images.githubusercontent.com/24547963/29005810-f30181c6-7ab9-11e7-9748-94dbcb5e2c86.png)

Contudo, devido ao primeiro problema descrito acima do Portugol realizar todas as escapes sequences presentes na string, ao tentar utilizar o caracter "r" logo após um "\\" ("\\\\r") ocorre um erro. Isso acaba causando um sério problema na biblioteca Arquivos, pois impossibilita de abrir um arquivo ou diretório que comece com "r".
![erro-portugol04](https://user-images.githubusercontent.com/24547963/29005909-31aaf07c-7abc-11e7-9be5-8070eafeef16.png)

**Comment by noschang** [comment]
Olá @inacioMattos. Muito obrigado por relatar o problema. Vamos verificar e solucioná-lo assim que possível.

Para que você não precise aguardar a solução do problema, por enquanto, você pode utilizar outro meio de abrir arquivos nos seus programas. Utilize o caracter ```"/"``` ao invés de ```"\"```. Desta forma não será preciso fazer escape do caracter. 

Vai funcionar pois o Portugol Studio aceita ambos os caracteres para caminhos de arquivos. Logo, ao invés de informar o caminho do arquivo assim:

```
inteiro endereco = Arquivos.abrir_arquivo("D:\\raspberry.txt")
```

Informe o caminho do arquivo assim:

```
inteiro endereco = Arquivos.abrir_arquivo("D:/raspberry.txt")
```

**Comment by AlissonSteffens** [comment]
Corrigido em:
https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/b9d66ca9f11390794dcb660a67dd713320059ec2
