### ISSUE TITLE
Bug ao executar o programa utilizando o atalho do teclado

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#288]
Quando o programa é executado através do botão "Executar" da interface, o programa roda normalmente. Porém, quando o usuário tenta executar pressionando o atalho do teclado (Shift+F6) o programa não roda.

Além de não executar o programa, os botões de "Executar", "Passo a passo" e "Interromper" ficam desabilitados, sendo necessário realizar uma alteração no código fonte para que os botões voltem a ser habilitados.

**Comment by AlissonSteffens** [comment]
Duplicate of #269
