### ISSUE TITLE
Melhorias no sistema de build

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#290]
O que acham de incorporarmos esse cara no nosso sistema de build? Ele consegue gerar um EXE nativo ao lado da JVM, fazendo com que a aplicação rode como uma aplicação nativa do SO. Além disso, ele consegue compactar os JREs removendo coisas não utilizadas, reduzindo o tamanho de 160MB para 70MB.

https://github.com/libgdx/packr

Se não formos utilizar ele, ao menos podemos seguir algumas práticas recomendadas pela Oracle nesse link:

http://www.oracle.com/technetwork/java/javase/jre-8-readme-2095710.html

**Comment by elieserdejesus** [comment]
> reduzindo o tamanho de 160MB para 70MB.

Já gostei dele :)

Gera somente exe ou também gera executáveis para outras plataformas?

**Comment by noschang** [comment]
@elieserdejesus. Não lembro, tem que ler a descrição do software no link que eu coloquei. Mas acho que gera para as 3 plataformas.

**Comment by noschang** [comment]
Iniciarei a implementação hoje, se possível
