### ISSUE TITLE
Área de desenho no modo gráfico menor que as dimensões definidas para a janela na 1ª renderização

### ISSUE THREAD

**Issue by alyppyo** [UNIVALI-LITE/Portugol-Studio#291]
**Descrição do Problema**:
Ao definir uma janela de grandes dimensões, a área disponível para desenho não acompanha essa alteração. Em um monitor Full HD (1920x1080) a área máxima de desenho disponível é algo em torno de 1280x780. Essa área se altera de acordo com a resolução da tela.

O mesmo problema se repetiu em pelo menos 3 versões diferentes do Portugol Studio que temos instaladas em nosso laboratório. Para reproduzir o erro, basta limpar a janela com uma outra cor. Uma porção dela permanecerá preta. A região preta também não recebe desenhos de qualquer tipo.

**Mensagem de Erro (se houver)**:
Erro visual. Não há mensagens.

**Captura de Tela / Arquivo.por**:
Tela 1920x180 - Janela 1300x900 
![ps_erro1](https://user-images.githubusercontent.com/561215/29474126-bc3c9f9c-8430-11e7-850e-a861c97ef2de.png)
Tela 1280x720 - Janela 1000x650 
![ps_erro2](https://user-images.githubusercontent.com/561215/29474140-cb609c12-8430-11e7-9f0f-a9659c7ccebd.png)

```
programa
{
	// Bibliotecas
	inclua biblioteca Graficos --> grf
	inclua biblioteca Teclado  --> tcl
	inclua biblioteca Util --> ut

	// Função principal
	funcao inicio()
	{
		// Declaração de variáveis
		inteiro larguraJanela = 1000
		inteiro alturaJanela  = 650

		// Iniciar modo gráfico
		grf.iniciar_modo_grafico(falso)

		// Definir dimensões da janela
		grf.definir_dimensoes_janela(larguraJanela, alturaJanela)

		// Limpar a tela com outra cor
		grf.definir_cor(grf.COR_BRANCO)
		grf.limpar()

		// Renderizar tela
		grf.renderizar()

		// Aguardar o usuário pressionar uma tecla
		tcl.ler_tecla()
		tcl.ler_tecla()

		// Encerrar o modo gráfico
		grf.encerrar_modo_grafico()
	}
}
```
**Especificações do sistema**:
Windows 10 e Windows 7. As configurações das máquinas do laboratório são bem diversas, mas a grande maioria possui processadores i3, sem placa de vídeo dedicada e com 4 GB de memória RAM.

**Comment by AlissonSteffens** [comment]
@alyppyo 
O problema realmente acontece, porém, apenas na 1ª renderização, ou seja, no seu código como renderiza apenas 1 vez, esse erro acontece.

É um erro nosso, porém como uma "solução provisória", você pode colocar a renderização em loop, desta maneira:

```
programa
{
// Bibliotecas
inclua biblioteca Graficos --> grf
inclua biblioteca Teclado --> tcl
inclua biblioteca Util --> ut

// Função principal
funcao inicio()
{
	// Declaração de variáveis
	inteiro larguraJanela = 1300
	inteiro alturaJanela  = 1200

	// Iniciar modo gráfico
	grf.iniciar_modo_grafico(falso)

	// Definir dimensões da janela
	grf.definir_dimensoes_janela(larguraJanela, alturaJanela)

	enquanto(nao tcl.alguma_tecla_pressionada())
	{
		// Limpar a tela com outra cor
		grf.definir_cor(grf.COR_BRANCO)
		grf.limpar()
	
		// Renderizar tela
		grf.renderizar()
		
		
		
	}
//	// Aguardar o usuário pressionar uma tecla
//	tcl.ler_tecla()
//	tcl.ler_tecla()
	
	// Encerrar o modo gráfico
	grf.encerrar_modo_grafico()	

}
}
```

Obrigado pelo feedback

**Comment by AlissonSteffens** [comment]
Reproduzindo o erro:
![erroloko](https://user-images.githubusercontent.com/6234230/29476677-7c7fa024-843b-11e7-96a3-22c4e987541a.gif)
Código:

```
programa
{
	// Bibliotecas
	inclua biblioteca Graficos --> grf
	inclua biblioteca Teclado --> tcl
	inclua biblioteca Util --> ut
	
	// Função principal
	funcao inicio()
	{
		// Declaração de variáveis
		inteiro larguraJanela = 1300
		inteiro alturaJanela  = 900
	
		// Iniciar modo gráfico
		grf.iniciar_modo_grafico(falso)
	
		// Definir dimensões da janela
		grf.definir_dimensoes_janela(larguraJanela, alturaJanela)
	
		// Limpar a tela com outra cor
		grf.definir_cor(grf.COR_BRANCO)
		grf.limpar()
	
		// Renderizar tela
		grf.renderizar()
	
		// Aguardar o usuário pressionar uma tecla
		tcl.ler_tecla()
		tcl.ler_tecla()
	
		// Limpar a tela com outra cor
		grf.definir_cor(grf.COR_BRANCO)
		grf.limpar()
	
		// Renderizar tela
		grf.renderizar()
	
		// Aguardar o usuário pressionar uma tecla
		tcl.ler_tecla()
		tcl.ler_tecla()
	
		// Encerrar o modo gráfico
		grf.encerrar_modo_grafico()
	}
}
```

**Comment by alyppyo** [comment]
Grato pela rápida resposta, Alisson!

De fato, usando o loop para renderizar soluciona o problema. Na realidade, esse algoritmo é provisório, pois ainda não passei o conteúdo de laços para meus alunos. Então tive que fazer algo provisoriamente, e me deparei com o erro. Avisarei para eles na próxima aula!

A propósito, parabéns pelo ótimo trabalho com a ferramenta. Até mais!

**Comment by AlissonSteffens** [comment]
@alyppyo A equipe do @UNIVALI-LITE/portugol-studio está sempre à disposição :+1: 
Sinta-se livre para sempre nos enviar problemas / dúvidas / perguntas.
Para qualquer outra informação / dica de como utilizar o Portugol Studio em suas aulas você pode entrar em contato através do [discord](https://discord.gg/fRW7Vq2), e sempre tem alguma coisa legal lá no nosso [site](lite.acad.univali.br/portugol)

**Comment by elieserdejesus** [comment]
olá @alyppyo, você mencionou que usa o Portugol Studio com seus alunos. Você poderia nos dar mais informações sobre isso? Que tipo de curso você leciona? Qual a faixa etária dos estudantes? Quantos estudantes? Estamos tentando entender o(s) contexto(s) em que o Portugol Studio vem sendo utilizado. 

Até+ e obrigado pelo feedback positivo sobre a ferramenta!

**Comment by alyppyo** [comment]
Olá @elieserdejesus,

Claro! Fiquem a vontade para perguntar o que desejar. Sou professor substituto na UFRN e já venho usando o Portugol Studio com sucesso creio que por uns 2 anos. 

Dou aulas de introdução à programação para diversos cursos aqui: Física, Estatística, Matemática, Engenharia Civil, Engenharia Química, Engenharia de Materiais, Engenharia de Produção, entre outros. Como é uma disciplina do ciclo básico, vários cursos de exatas possuem essa disciplina na grade.

Antes trabalhava apenas com o console, mas desde o semestre passado venho introduzindo o modo gráfico para estimular os alunos. O resultado tem sido bastante satisfatório até o momento. A faixa etária é bem distinta, mas poderia dizer que a grande maioria está entre os 17 e os 22 anos.

A propósito, gostaria de aproveitar a deixa para tirar uma dúvida. Nessa nova versão do Portugol Studio só tem dois temas, não é? Vocês pretendem incluir mais nas próximas versões? Gostei bastante do novo tema escuro, mas os comentários também com fonte escura dificultam a leitura pelos alunos quando projeto durante a aula. O tema Dark II da versão passada era perfeito nesse aspecto. Existe alguma forma de ativá-lo nessa nova versão?

Agradeço uma vez mais pelo rápido retorno! Até mais!

**Comment by AdsonEsteves** [comment]
@alyppyo 

Futuramente planejamos, não ter mais temas, e sim o usuário poder escolher as cores que quiser para o Portugol Studio. Claro, ainda não temos uma versão definida para isso, mas já foi discutida a possibilidade. Mas muito obrigado pela sugestão sobre os comentários escuros no tema Dark, isso podemos ajustar, não temos como trazer o tema Dark II no momento (pelo menos não para a proxima versão), mas podemos ajustar a cor dos comentarios dele, ou de onde precisar dele, vamos ver como podemos melhorar :)

Obrigado pela sugestão!

**Comment by elieserdejesus** [comment]
Obrigado pelas informações @alyppyo !

**Comment by AlissonSteffens** [comment]
Observação legal
```
programa
{
	// Bibliotecas
	inclua biblioteca Graficos --> grf
	inclua biblioteca Teclado  --> tcl
	inclua biblioteca Util --> ut

	// Função principal
	funcao inicio()
	{
		// Declaração de variáveis
		inteiro larguraJanela = 1300
		inteiro alturaJanela  = 900

		// Iniciar modo gráfico
		grf.iniciar_modo_grafico(falso)

		// Definir dimensões da janela
		grf.definir_dimensoes_janela(larguraJanela, alturaJanela)
		ut.aguarde(100)
		// Limpar a tela com outra cor
		grf.definir_cor(grf.COR_BRANCO)
		grf.limpar()

		// Renderizar tela
		grf.renderizar()

		// Aguardar o usuário pressionar uma tecla
		tcl.ler_tecla()
		tcl.ler_tecla()

		// Encerrar o modo gráfico
		grf.encerrar_modo_grafico()
	}
}

```

funciona

**Comment by AlissonSteffens** [comment]
Este erro ocorre devido a animação de abrir janela dos sistemas operacionais; quando desenhamos, durante a animação, parte da tela pode acabar ficando de fora, e ai ficará tudo preto mesmo.
@elieserdejesus , acho que não há um jeito de resolver isso, o que vc me diz?

**Comment by elieserdejesus** [comment]
> @elieserdejesus , acho que não há um jeito de resolver isso, o que vc me diz?

Nunca tive que lidar com isso, mas talvez seja possível alterar a classe que está controlando as operações de desenho para esperar por evento de **janela ativada**. Enquanto o evento de janela ativada não é recebido as operações de desenho são enfileiradas, mas não consumidas. Elas serão consumidas na próxima renderização, assim que a janela estiver ativa.  

O que achas @noschang ?

**Comment by noschang** [comment]
@elieserdejesus e @AlissonSteffens. Essa é uma treta antiga que já ocorria no Linux Mint. No Ubuntu ocorria raramente e no Windows não havia ocorrido até o momento.

Não sei  se há uma maneira simples de resolver isso. Mas vou dar uma pista, o problema não está no tamanho da janela e sim no tamanho da superfície de desenho.

Quando a janela é criada (antes de ser exibida), a superfície de desenho é criada com o tamanho padrão definido na biblioteca (800x600 se não me engano).

Em seguida, quando a janela é exibida e redimensionada, a superfície de desenho também é redimensionada de acordo: https://github.com/UNIVALI-LITE/Portugol-Studio/blob/a28f2f72c6b4be10c8fb9f508c6433943761309b/core/src/main/java/br/univali/portugol/nucleo/bibliotecas/graficos/JanelaGraficaImpl.java#L212

Como pode ser visto logo abaixo, ao redimensionar a superfície de desenho, o buffer tem que ser recriado:

https://github.com/UNIVALI-LITE/Portugol-Studio/blob/a28f2f72c6b4be10c8fb9f508c6433943761309b/core/src/main/java/br/univali/portugol/nucleo/bibliotecas/graficos/SuperficieDesenhoImpl.java#L129

É aí que entra o problema. Por motivos que desconheço, em alguns sistemas operacionais, se houver alguma animação da janela expandindo ou abrindo, o buffer é recriado com o tamanho antigo, mesmo que um novo tamanho tenha sido definido.

Me parece também que o problema só ocorre se o buffer for expandido, ou seja, se aumentar as dimensões. Se as dimensões forem diminuídas, o buffer parece ser recriado corretamente.

**Comment by AlissonSteffens** [comment]
Aparentemente não acontece mais @AdsonEsteves @noschang @Rafaelfcosta podem testar?

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 

É realmente, parece que está consertado

Será que ainda acontece no Linux que nem o @noschang falou

**Comment by Rafaelfcosta** [comment]
@AlissonSteffens 
Funcionando perfeitamente.
It's magic ~

**Comment by AlissonSteffens** [comment]
Aparentemente a versão atual da JVM ou do Windows (não faço a menor ideia) resolveu a treta;
Abraços 🤗
