### ISSUE TITLE
Destacar mais os comentários (trocar cor do comentários)

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#293]
Esta seria mais uma Issue de discussão do que uma Issue com um problema em si.
Foi comentado pelo usuário na issue #291 que nesta versão, especificamente na versão Dark, os comentários estariam muito escuros, dificultando a visualização quando é projetado, como também citou o tema da versão 2.5 Dark II que era ótimo nesse aspecto.

Tema Dark II:
![image](https://user-images.githubusercontent.com/8836540/29584662-d8e189e6-875a-11e7-8acd-e628848d35d3.png)

Com isso temos um relato que alguns professores usam os comentários nos programas em suas aulas, e comentários mais apagados seriam difíceis de visualizar durante a projeção.

Com isso trago a questão:
Seria melhor deixar os comentários com uma cor "vívida" em contraste com o fundo, como era no Dark II e no Portugol Studio? ou apenas clareamos um pouco os comentários da versão Dark para resolver o problema do usuário?

@noschang @elieserdejesus @AlissonSteffens @Rafaelfcosta @ivanFilho

**Comment by AlissonSteffens** [comment]
Vou clarear o comentário da versão dark e resolver o problema / ao menos por enquanto.
Depois podemos discutir criar outros temas/etc

**Comment by AdsonEsteves** [comment]
Tecnicamente resolvido em b93063394324c6ac1aefcaee3c11506535a98a55
