### ISSUE TITLE
Programa não roda caso se use constantes nos casos "escolha"

### ISSUE THREAD

**Issue by alyppyo** [UNIVALI-LITE/Portugol-Studio#294]
**Descrição do Problema**:
E aqui estou eu de novo, pessoal. Neste caso, fui dar um exemplo aos meus alunos sobre o uso do escolha e apresentá-los ao conceito de constantes. Entretanto, quando usei constantes em substituição aos valores diretamente nos casos do bloco "escolha", o programa simplesmente não roda. Não aparece nenhuma mensagem de erro e o botão de execução fica cinza, assim como o de interrupção.

Vale salientar que esse problema não acontecia nas versões anteriores. Comigo ocorreu apenas na versão mais atual.

**Mensagem de Erro (se houver)**:
Não há mensagem alguma. Apenas os botões de execução e interrupção ficam desativados.

**Captura de Tela / Arquivo.por**:
// Algoritmo: Formas de pagamento
// Função: dado o valor de um produto e a forma de pagamento escolhida pelo
//		 cliente, indica qual o valor final pago.
// Autor: Alyppyo Coutinho
// Data: 24/08/2017
```
programa 
{
	// Função principal
	funcao inicio()
	{
		// Declaração de constantes
		const inteiro BOLETO = 1
		const inteiro CARTAO_A_VISTA = 2
		const inteiro CARTAO_ATE_3X  = 3
		const inteiro CARTAO_MAIS_3X = 4
		
		// Declaração de variáveis
		real valorProduto
		inteiro opcao

		// Apresentação do programa
		escreva("-- Formas de Pagamento --\n")

		// Solicitar valor do produto
		escreva("- Entre com o valor do produto (R$): ")
		leia(valorProduto)

		// Imprimir menu de opções
		escreva("\n- Opções de Pagamento -\n")
		escreva("1) Boleto (15% de desconto)\n")
		escreva("2) Cartão - À vista (10% de desconto)\n")
		escreva("3) Cartão - Até 3x (Sem desconto)\n")
		escreva("4) Cartão - Mais de 3x (20% de acréscimo)\n")

		// Solicitar forma de pagamento
		escreva("- Entre com uma opção de pagamento (1-4): ")
		leia(opcao)

		// Divulgar resultado
		escreva("\n> Total pago: R$ ")

		// Calcular total final
		escolha(opcao) {
			caso BOLETO: // 15% de desconto
				escreva(valorProduto*0.85)
				pare
			caso CARTAO_A_VISTA: // 10% de desconto
				escreva(valorProduto*0.9)
				pare
			caso CARTAO_ATE_3X: // Sem desconto
				escreva(valorProduto)
				pare
			caso CARTAO_MAIS_3X: // 20% de acréscimo
				escreva(valorProduto*1.2)
				pare
			caso contrario:
				escreva("\n> Opção inválida! Encerrando o programa...")
		}
	}
}
```
**Especificações do sistema**:
Windows 10, versão mais atual do Portugol Studio.

**Comment by noschang** [comment]
Testei na versão 2.6.1 do Portugol Studio e o bug foi confirmado. O problema está na instrução ```caso contrario```.

Quando esta instrução está presenta, ocorre o erro relatado. Se esta instrução é removida do código o programa compila e executa normalmente. 

Tentei incluir a instrução ```pare``` após o ```caso contrario```, porém o problema persiste.

Acredito que o bug esteja ocorrendo no gerador de código. Possivelmente ele está gerando um código inválido e não consegue compilar, motivo pelo qual os botões são desabilitados.

Lembro que recentemente o @rytix esteve solucionando um problema relacionado ao ```escolha```. É possível que ele tenha ocasionado um novo bug?

**Comment by rytix** [comment]
@noschang o problema aconteceu no gerador de código java =/
https://github.com/UNIVALI-LITE/Portugol-Studio/commit/2a1a8b67e67020304c84606806f5694cb64526f6

https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/6c3789d73b892dd60fee162ebd95070bb1105c27

Esses são os ultimos commits antes do gerador de código java, depois disso este caso não funciona mais :v

**Comment by AlissonSteffens** [comment]
O problema está no Gerador mais especificamente:
quando existem variáveis, o gerador faz:
```
if(!___sw_break___ && opcao == BOLETO)
    {
        realizarParada(42, 4);
        escreva(valorProduto * 0.85);
        realizarParada(43, 4);
        ___sw_break___ = true;

    }
```
e quando não exitem:
```
case 1:
    realizarParada(40, 4);
    escreva(valorProduto * 0.85);
    realizarParada(41, 4);
    break;
```

A questão é que o caso contrario está botando default: nas duas situações, quando na verdade deveria por o senão em casos de variáveis;

obs: talvez precise de um help do @elieserdejesus para terminar isso

**Comment by rytix** [comment]
"O Portugol aceita variáveis no escolha caso"
Observando esse trecho de código eu pensei em algo que já poderia dar treta na hora executar o programa, como este exemplo abaixo:

```
programa
{
	funcao inicio()
	{
		inteiro caso1 = 1, caso42 = 42
		inteiro x = 1,y = 42
		escolha(x){
			caso caso1:
				escolha(y){
					caso caso42:
						escreva("42 ")
				}
				escreva("1 ")
		}
	}
}

```
Erro Gerado:
![image](https://user-images.githubusercontent.com/7809511/29787901-0992020e-8c07-11e7-8bdd-99f75e897f3a.png)

**Comment by elieserdejesus** [comment]
Essa variável **___sw_break___ ** que está sendo redeclarada foi ideia do @noschang , e eu não lembro exatamente o motivo. Noschang, acho que relembrar o motivo da inserção desta *___sw_break___ ** pode ajudar a mapear a solução dessa isssue.

**Comment by AlissonSteffens** [comment]
resolvido em https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/f3a80b85eeec0cb9813b0084c2d682da6d5945d2  🥇

**Comment by parisprogrammer** [comment]
Olá pessoal.
Estou tentando fazer o algoritmo abaixo, mas não consigo tratar entradas alternativas que levam a uma mesma mensagem de saída. É possível fazer isso?

/* Fonte: Lógica de Programação - Forbellone e Ebersächer, p. 46, Ex. 2.6
 * Enunciado: Escreva um algoritmo que leia o código de um determinado
 * produto e mostre a sua classificação:
 * 
 * Código					Classificação
 * 1						Alimento não-perecível
 * 2, 3 ou 4				Alimento perecível
 * 5 ou 6					Vestuário
 * 7						Higiente pessoal
 * 8 até 15				Limpeza e utensílios domésticos
 * Qualquer outro código		Inválido 
 * 
 * Autor: Paris Programmer
 * Data: 24/10/2017
 */
programa
{
	funcao inicio()
	{
		// Declaração de variáveis
		inteiro codigoProduto

		//Entrada de dados
		escreva("Entre com o código do produto: ")
		leia(codigoProduto)
		// Processamento e Saída de dados
		escolha (codigoProduto)
		{
			caso 1:
				escreva("Alimento não-perecível")
				pare
			caso 2..4:
				escreva("Alimento perecível")
				pare
			caso 5..6:
				escreva("Vestuário")
				pare
			caso 7:
				escreva("Higiente pessoal")
				pare
			caso 8..15:
				escreva("Limpeza e utensílios domésticos")
				pare
			caso contrario:
				escreva("Código inválido")												
		}
	}
}

**Comment by noschang** [comment]
Oi @parisprogrammer. Sim, é possível fazer o que você deseja.

No entanto, o canal do Github é destinado exclusivamente para assuntos relacionados ao desenvolvimento da ferrementa, ou seja, o registro de bugs e sugestões de novas funcionalidades.

Para obter a ajuda que você precisa, por favor, entre em contato conosco no chat do Disccord e será um prazer ajudá-lo:

https://discord.gg/fRW7Vq2

**Comment by frahedler** [comment]
@alyppyo consegui realizar o algoritmo, veja se é dessa forma que você desejava:

programa {
	funcao inicio() {
		// Declaração de constantes
		const inteiro BOLETO = 1
		const inteiro CARTAO_A_VISTA = 2
		const inteiro CARTAO_ATE_3X  = 3
		const inteiro CARTAO_MAIS_3X = 4
		
		// Declaração de variáveis
		real valorProduto
		real ValorTotal1
		real ValorTotal2
		real ValorTotal3
		real ValorTotal4
		inteiro opcao

		// Apresentação do programa
		escreva("-- Formas de Pagamento --\n")

		// Solicitar valor do produto
		escreva("- Entre com o valor do produto (R$): \n")
		leia(valorProduto)

		// Imprimir menu de opções
		escreva("\n- Opções de Pagamento -\n")
		escreva("1) Boleto (15% de desconto)\n")
		escreva("2) Cartão - À vista (10% de desconto)\n")
		escreva("3) Cartão - Até 3x (Sem desconto)\n")
		escreva("4) Cartão - Mais de 3x (20% de acréscimo)\n")

		// Solicitar forma de pagamento
		escreva("- Entre com uma opção de pagamento (1-4): ")
		leia(opcao)

		// Divulgar resultado
	   escolha(opcao)
	   {
			caso 1: // 15% de desconto no Boleto
				ValorTotal1 = valorProduto*0.85
				escreva("\n O Valor a ser pago é: R$", ValorTotal1)
				pare
			caso 2: // 10% de desconto
				ValorTotal2 = valorProduto*0.9
				escreva("\n O Valor a ser pago é: R$", ValorTotal2)
				pare
			caso 3: // Sem desconto
				ValorTotal3 = valorProduto
				escreva("\n O Valor a ser pago é: R$", ValorTotal3)
				pare
			caso 4: // 20% de acréscimo
				ValorTotal4 = valorProduto*1.2
				escreva("\n O Valor a ser pago é: R$", ValorTotal4)
				pare
			caso contrario:
				escreva("\n> Opção inválida! Encerrando o programa...")
		}
	}
}
