### ISSUE TITLE
Aninhamento de escolha-caso não funciona se os casos forem com variáveis.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#295]
**Descrição do Problema**:
Aninhamento de escolha caso não funciona caso ambos os escolhas-casos usem variáveis no lugar de constantes.
**Mensagem de Erro (se houver)**:
Variável já declarada.
**Captura de Tela / Arquivo.por**:
```
programa
{
	funcao inicio()
	{
		inteiro caso1 = 1, caso42 = 42
		inteiro x = 1,y = 42
		escolha(x){
			caso caso1:
				escolha(y){
					caso caso42:
						escreva("42 ")
				}
				escreva("1 ")
		}
	}
}

```
Erro Gerado:
![image](https://user-images.githubusercontent.com/7809511/29787901-0992020e-8c07-11e7-8bdd-99f75e897f3a.png)
**Especificações do sistema**:
Windows 7

**Comment by elieserdejesus** [comment]
Estou assumindo esta issue, só para avisar 😄

**Comment by noschang** [comment]
Eficiência!!!

**Comment by rytix** [comment]
<3
