### ISSUE TITLE
Testando JARs relacionados ao áudio.

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#296]
Ao remover os seguintes JARs que estão no núcleo, os arquivos de MP3 continuam sendo reproduzidos normalmente.
* jlayer-1.0.1.jar
* mp3spi1.9.5.jar
* tritonus_share.jar

Apenas ao remover o **mp3plugin.jar** do PS os sons param de funcionar.
Utilizando o plugin da maven **jmf-fs-3.0.jar** ao invés do **mp3plugin.jar** dentro do PS funciona normalmente, já ao trocar também no núcleo para o **jmf-fs-3.0.jar** os sons param novamente.

**Comment by noschang** [comment]
Muito obrigado @Rafaelfcosta. Vou aplicar as alterações aqui no projeto que eu estou fazendo

**Comment by AlissonSteffens** [comment]
Tem que ver se os pause / avançar audio e talz também continuam funcionando

**Comment by AlissonSteffens** [comment]
Confirmado, não estavam nem inseridos no projeto

**Comment by AlissonSteffens** [comment]
fixed @ https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/66ab3c521c7677f139d7f65c5a98afb9885f61f9

**Comment by noschang** [comment]
Pessoal, no meu Linux, ao remover qualquer um dos JARs da pasta de instalação do Portugol Studio os sons param de funcionar.

Talvez isso signifique que dependendo do SO, uma ou outra lib está sendo chamada. Além disso, acredito que cada lib seja responsável por reproduzir um formato de áudio diferente (WAV, MIDI, MP3).

Acho melhor mantermos todas as libs no projeto para não termos problemas futuramente. @AlissonSteffens, reverta o commit que você fez e adicione novamente as libs no núcleo. Acredito que elas não estavam sendo adicionadas no projeto do Netbeans porque elas não são necessárias pra compilar o projeto, são usadas apenas em tempo de execução.

**Comment by AlissonSteffens** [comment]
eitaaaa

**Comment by AlissonSteffens** [comment]
Done

**Comment by noschang** [comment]
Decidi manter todas as libs pelos motivos mencionados anteriormente. Com a utilização do Gradle no repositório e a compressão do JDK que pretendo implementar no processo de build, o espaço utilizado pelo Portugol Studio diminuirá drasticamente e estas libs não farão muita diferença.

Por segurança prefiro mantê-las. Estou fechando esta issue.
