### ISSUE TITLE
Novo repositório

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#297]
Pessoal, criei uma versão do Portugol Studio integrando os projetos com Gradle.
Coloquei em um novo repsitório de testes, aqui:

https://github.com/UNIVALI-LITE/Validate-Portugol-Studio

Por favor clonem o repositório e testem nas IDEs de vocês.
Aqui eu testei e está quase tudo funcionando.

A única coisa que vamos ter que refazer com mais calma são os scripts que geram as distribuições. Mas fora acredito que vai ser tranquilo.

Este repositório já integra o site também:
https://univali-lite.github.io/Validate-Portugol-Studio/

**Comment by rytix** [comment]
Yuuuuuuuuuuupi o/

**Comment by elieserdejesus** [comment]
@noschang , testei aqui e funcionou. Testei apenas o projeto **ide**.  Ficou muito legal!!

A única coisa que observei é que o splash não está funcionando.

**Comment by AdsonEsteves** [comment]
Noice

**Comment by noschang** [comment]
@elieserdejesus. Sim, sim. Percebi isso também. Detalhes a serem ajustados. Já estou trabalhando nisso.

**Comment by noschang** [comment]
@elieserdejesus. Sim, sim. Percebi isso também. Detalhes a serem ajustados. Já estou trabalhando nisso.

**Comment by noschang** [comment]
Consegui gerar um patch das últimas alterações do núcleo e aplicar na versão com Gradle. Ou seja, vai ser bem de boa ir ajustando a versão Gradle enquanto a equipe trabalha na versão atual.

Depois é só gerar os patches e ser feliz.

**Comment by AlissonSteffens** [comment]
@noschang pronto?

**Comment by noschang** [comment]
Sim. A parte de código está pronto. Agora é só ajustar as issues e outros detalhes. Mas já podem clonar este repositório e trabalhar nele. 

Faça um teste na sua máquina. Clone o projeto e tente rodar no NetBeans. Se tudo funcionar pode fechar a issue.

**Comment by AlissonSteffens** [comment]
Aqui deu certo, já testei 👍 
vou fechar
