### ISSUE TITLE
java.lang.nullpointerException

### ISSUE THREAD

**Issue by leandrogneis** [UNIVALI-LITE/Portugol-Studio#300]
**Descrição do Problema**:
Crio um novo arquivo, ao clicar na tela da a mensagem java.lang.NullPointerException. Se mexo com o cursor do teclado da mensagem. Ao tentar abrir outro arquivo aparece a mensagem .  Estou digitando um código e mal termino aparece a mensagem.

**Mensagem de Erro (se houver)**:
java.lang.NullPointerException

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
	Windows 10, memoria 16gb , processador AMD FX-8320- Eight-Core 3.5 e jdk 8 instalado.
![erro](https://user-images.githubusercontent.com/12827735/29954508-d631a5ae-8eae-11e7-9d01-b50479262e08.PNG)

**Comment by AlissonSteffens** [comment]
Olá, @leandrogneis , você pode testar se o problema está relacionado com a issue: https://github.com/UNIVALI-LITE/Portugol-Studio/issues/270 ?
Para isso só preciso saber: 
**1**.  É assim que acontece?
![gif](https://user-images.githubusercontent.com/6234230/29046957-169a82ea-7ba0-11e7-834b-03550d34d3fe.gif)
**2**. A primeira abertura do Portugol demonstra este erro:
![image](https://user-images.githubusercontent.com/6234230/29978646-7926aeb2-8f18-11e7-9e75-00b93d96333c.png)

Agradeço desde já por audar a tornar o Portugol Studio um programa cada vez melhor 👍

**Comment by leandrogneis** [comment]
Boa noite,  Alisson. O Erro que ocorreu é igual da primeira tela. Mas
imagina essa mensagem aparecendo o tempo todo ao clicar em qualquer parte
do código, ou digitando ele. Esse segundo erro ocorreu uma vez só.

Abraços

Leandro Gustavo Neis

Junior Full Stack Java Developer.

MSN: leandrogneis@hotmail.com
Email: lgn200@gmail.com
Cel: 48 998550003

Em 1 de setembro de 2017 13:23, Alisson Steffens <notifications@github.com>
escreveu:

**Comment by AlissonSteffens** [comment]
@leandrogneis , então é realmente Duplicate of #270 , já estamos trabalhando neste problema e em breve lançaremos uma nova versão com este problema resolvido. Fique atento às novas versões do Portugol Studio, por aqui, pelo [face](https://www.facebook.com/univalilite/) ou em nosso [site](http://lite.acad.univali.br/portugol/)

**Comment by AlissonSteffens** [comment]
Duplicate of #270
