### ISSUE TITLE
Mensagem "ruim" para o usuário

### ISSUE THREAD

**Issue by andrelms** [UNIVALI-LITE/Portugol-Studio#301]
<img width="992" alt="captura de tela 2017-09-01 as 17 02 42" src="https://user-images.githubusercontent.com/3330769/29985935-963e242a-8f37-11e7-9ce3-77b8f2c777c4.png">

**Comment by AdsonEsteves** [comment]
Fixed in 7702e5dd9aee2688a6cb67180b2ff4c629a3aca5
