### ISSUE TITLE
Sempre dá erro na compilação

### ISSUE THREAD

**Issue by Daniel13Caldeira** [UNIVALI-LITE/Portugol-Studio#303]
**Descrição do Problema**:
Todos os códigos escritos por mim não são compilados 
**Mensagem de Erro (se houver)**:
![image](https://user-images.githubusercontent.com/31595829/30005432-d2a81b0a-90b8-11e7-9e13-bdfc71066cc5.png)

**Captura de Tela / Arquivo.por**:

![image](https://user-images.githubusercontent.com/31595829/30005449-2d139d58-90b9-11e7-8c3c-5c1d10e27044.png)

**Especificações do sistema**:

**Comment by AlissonSteffens** [comment]
O problema está em "inicializar" vetores e matrizes sem o tamanho definido. Temos que arrumar esta mensagem de erro @AdsonEsteves

**Comment by AdsonEsteves** [comment]
@Daniel13Caldeira 

A mensagem de erro na nova versão foi melhorada. Portanto seria bom atualizar o portugol.

Além disso, Vetores e Matrizes precisam ser inicializados antes de serem utilizados e não tem tamanhos flexíveis, apenas tamanhos fixos que devem ser definidos na inicialização. Como por exemplo:

```
inteiro x[] = {0,0,0,0,0,0,0}

inteiro y[][] = {{0,0,0,0,0,0},
                 {0,0,0,0,0,0},
                 {0,0,0,0,0,0}}
```

**Comment by Daniel13Caldeira** [comment]
Obrigado.

Em 3 de set de 2017 11:36 PM, "Alisson Steffens" <notifications@github.com>
escreveu:
