### ISSUE TITLE
#importante - Sistema de Ajuda com uma série de funções depreciadas!

### ISSUE THREAD

**Issue by andrelms** [UNIVALI-LITE/Portugol-Studio#305]
**Descrição do Problema**: Sistema de ajuda apresenta funções da biblioteca com as assinaturas de chamada antiga!

Sugiro algumas coisas:

(1) Criar uma estratégia para depreciação das funções indicando a nova (flexibiliza pros usuários exige de nós)
(2) Atualizar a documentação sempre (isso independe de qual opção seguir)
(3) Deixar bem claro as mudanças na alteração de versão

Exemplo: Função de deixar as letras em caixa alta:

_No ajuda_: t.caracteres_maiusculos("texto")
**No exemplos:** t.caixa_alta("texto")

Classificaria isso como urgente!

**Comment by AlissonSteffens** [comment]
@AdsonEsteves @elieserdejesus @noschang @rytix 
Criei essa nova label chamada prioritária. São coisas que DEVEM ser feitas antes da nova versão ser lançada, pois afetam muito o uso do sistema.

**Comment by elieserdejesus** [comment]
Tenho uma ideia para evitar a revisão manual dos arquivos de ajuda sempre que alguma função das bibliotecas for alterada:

- Criar um teste unitário que "entra" em cada arquivo de ajuda de biblioteca, obtêm as funções e compara seus nomes, tipo de retorno e lista de parâmetros com o que está definido na biblioteca correspondente. Parecido com o que foi feito nos testes automatizados do gerador de código. O teste é considerado válido se o que existe no arquivo de ajuda estiver exatamente igual ao que está codificado na biblioteca.

Com testes automatizados a revisão manual (extremamente sujeita a erros) desapareceria. Sempre que uma função fosse alterada em alguma biblioteca os testes acusariam o erro, pois a ajuda desta mesma biblioteca estaria com informações diferentes.

O que acham? Dá algum trabalho, mas pode valer a pena. Alguém se habilita?

**Comment by AlissonSteffens** [comment]
Eu posso fazer, talvez precise de alguma ajuda tua @elieserdejesus , mas quero aprender a fazer isso 👍

**Comment by elieserdejesus** [comment]
> Eu posso fazer, talvez precise de alguma ajuda tua @elieserdejesus , mas quero aprender a fazer isso

Conte comigo!

Eu começaria investigando como obter todos os dados (nome, atributo, tipo de retorno) de todas as funções das bibliotecas. Depois teria que ver como fazer o mesmo nos arquivos de ajuda correspondentes.

@noschang , no caso das bibliotecas, existem anotações que permitem extrair o nome, tipo de retorno e parâmetros esperados em uma função, certo?

**Comment by AlissonSteffens** [comment]
@elieserdejesus , só aproveitando aqui sua presença pra avisar que ficaremos sem commitar até que o @noschang atualize para graddle

**Comment by AlissonSteffens** [comment]
👍
