### ISSUE TITLE
Mensagens de erro que não fazem sentido [Fixo]

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#308]
_From @rytix on June 9, 2017 19:39_

Esta Issue conterá todas as mensagens de erro que não fazem sentido.

- [x] Mensagem de erro nº 1
- [x] Mensagem de erro nº 2

--- Mensagem de erro nº 1 ---
![image](https://user-images.githubusercontent.com/7809511/26991776-1e55fab0-4d32-11e7-8be3-64923992004f.png)
```
programa
{
   funcao inicio()  {
      inteiro a.
      escreva("teste")
   }
}
```
--- Mensagem de erro nº 2 ---
![image](https://user-images.githubusercontent.com/7809511/26991959-e260087e-4d32-11e7-9c84-aa0b367b3985.png)
```
programa
{
   funcao inicio()  {
      inteiro a = (2,5 - 3,78)
   }
}
```

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#112_

**Comment by noschang** [comment]
Estes erros serão bem chatos de corrigir. Não sei nem se é possível antes de recriarmos a gramática em ANTLR 4.

**Comment by AdsonEsteves** [comment]
![image](https://user-images.githubusercontent.com/8836540/30931655-b70cd6c4-a39b-11e7-9060-8ac0a66e2ca2.png)

**Comment by jothbc** [comment]
O problema da primeira foto é o "inteiro a."... Esse ponto vai da erro no que vier a frente;
O da segunda foto não se pode usar virgula para escrever um numero real, se fosse ponto daria certo;
o da terceira.. bom..depende o que voce quer criar ai com 3 colchetes...

**Comment by Rafaelfcosta** [comment]
Pontos não geram mais mensagens de erro, apenas são ignorados
![image](https://user-images.githubusercontent.com/21344756/60684870-7f43f380-9e76-11e9-91cb-b6143bab1d24.png)

Números com vírgula ao invés de ponto geram apenas uma mensagem de erro aguardando um ')'
![image](https://user-images.githubusercontent.com/21344756/60684708-b6fe6b80-9e75-11e9-8070-d3eaeac0e2cf.png)

Colchetes sem valores definidos não geram mensagens de erro
![image](https://user-images.githubusercontent.com/21344756/60684818-3ee47580-9e76-11e9-9a0c-d2752963e5fc.png)
