### ISSUE TITLE
Escolha caso, expressões do caso deveriam ser apenas constantes

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#310]
_From @erickweil on May 12, 2017 0:0_

```
		inteiro teste = 5

		inteiro vale_1 = 1
		inteiro vale_entrada

		leia(vale_entrada)
		
		
                escolha(teste)
		{
			// 1º problema: não deveria aceitar uma variável como teste
			caso vale_1:
				escreva("Executou 1º Opção")
			pare
			caso vale_entrada:
				escreva("Executou 2º Opção")
			pare

			//2º problema: não deveria aceitar casos iguais
			caso 5:
				escreva("Executou 3º Opção")			 
			pare
			caso 5:
				escreva("Executou 4º Opção")
			pare
			
		}
```

pelo menos o java não permite tal coisa, e nenhuma linguagem tipada deveria.

a ideia do switch é ter os labels definidos em compile-time, de forma que na execução se pula para uma tabela com os goto's para o caso certo, que é exatamente o que impede o switch de ter valores que não sejam int, ou que não possam ser implicitamente convertidos para int.
https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-3.html#jvms-3.10

o switch de strings em java usa o resultado do hashmap da string para fazer o switch(int), e os casos são os hashmaps pré-computados, seguidos de if-elses para comparação completa da string, ou de mais que colidirem o hash,
http://stackoverflow.com/questions/338206/why-cant-i-switch-on-a-string

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#95_

**Comment by noschang** [comment]
Escolhemos permitir o uso de variáveis e constantes no escolha por uma questão que acreditamos ser didática. O objetivo primário o Portugol Studio é facilitar para os iniciantes.

A questão é, manter este comportamento facilita realmente? Acho que isso precisa ser reavaliado.

Quanto ao segundo problema apontado. Testei o programa informado no Portugol Studio e ele está compilando e rodando. Isso indica que o compilador Java permite a repetição do caso? Alguém poderia confirmar?

**Comment by AlissonSteffens** [comment]
Acho que devemos manter assim como está, o que acha @AdsonEsteves ?

**Comment by AdsonEsteves** [comment]
dunno

**Comment by AlissonSteffens** [comment]
foi decidido que o escolha caso, continuará aceitando variáveis; estou fechando a issue
