### ISSUE TITLE
Erro de Compilação em resultados previsíveis pelo compilador Java

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#312]
_From @noschang on February 23, 2017 13:18_

Quando o usuário escreve um laço enquanto com uma condição cujo resultado é previsível pelo compilador o programa gera um erro de compilação.

Ex.:

```
enquanto (verdadeiro)
{
     ...
}

escreva("Olá mundo")
```

Este código gera erro, pois o compilador Java detecta que a condição sempre será verdadeira e consequentemente o laço é infinito. Logo, todo código após o enquanto nunca será executado e isso gera um UnreachebleCodeError no compilador.

Outro exemplo:

```
enquanto (2 < 3)
{

}
```

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#88_

**Comment by Rafaelfcosta** [comment]
_From @AlissonSteffens on February 23, 2017 15:5_

e isso não está certo?

**Comment by Rafaelfcosta** [comment]
_From @noschang on February 24, 2017 12:20_

Está certo do ponto de vista lógico.
Porém, o Portugol Studio só apresenta uma mensagem genérica: "Erro ao compilar".

Temos duas opções, ou damos um bypass nessa verificação e ignoramos o erro ou exibimos uma mensagem melhor para o usuário, do tipo:

"Linha: X, Coluna: Y. O laço 'enquanto' vai executar infinitamente, pois sua condição é sempre verdadeira. Todos os comandos a partir da linha Z nunca serão executados."

**Comment by Rafaelfcosta** [comment]
_From @rytix on June 9, 2017 19:58_

Esta Issue é um pouco mais séria, Todos os eventos que o compilador Java consegue prever e o Portugol Studio não irão gerar um Erro de Compilação. 
Exemplos:
```
programa{

    funcao inicio()
    {
        inteiro x = 5
        escolha(x){
        	caso 1: 
        	pare
        	retorne
       }
    }
}
```
```
programa{

    funcao inicio()
    {
        enquanto (verdadeiro){
        	
        }
        escreva("oi")
    }
}
```
```
programa{

    funcao inicio()
    {
        	retorne
        	retorne
    }
}
```

**Comment by noschang** [comment]
Resolvido na issue #271. Todos os programas acima foram testados e estão gerando as mensagens de erro corretas para o usuário.
