### ISSUE TITLE
Remover uma parte do parenteses na função tela cheia cria estados inconsistentes no Portugol

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#313]
_From @rytix on February 22, 2017 20:30_

No windows 7 a tela começa a piscar, no windows 10 ela reduz de tamanho, isso pode ter efeitos diferentes em diversos tipos de sistema operacional

![image](https://cloud.githubusercontent.com/assets/7809511/23230738/dfb78862-f923-11e6-9371-7cf5b9d2fde7.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/7809511/23230960/aa518e2e-f924-11e6-921f-f7b62c572913.png)

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#84_

**Comment by Rafaelfcosta** [comment]
_From @rytix on June 9, 2017 19:49_

@AlissonSteffens isso ainda está acontecendo ? fiz um teste aqui e parece estar tudo bem...

**Comment by Rafaelfcosta** [comment]
_From @AlissonSteffens on June 10, 2017 0:7_

Acho que não acontece mais, @AdsonEsteves pode confirmar??

**Comment by noschang** [comment]
Aparentemente está resolvido. Uma mensagem de erro é apresentada ao usuário:

![bug](https://user-images.githubusercontent.com/709553/30064271-9bd9ce32-9227-11e7-9d03-29195d18813a.png)
