### ISSUE TITLE
Converter do ANTLR3 para o ANTLR4

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#314]
_From @rytix on April 6, 2016 18:56_

Alguns bugs relatados, envolvem mexer no léxico do Portugol.
Como dar manutenção em um código ANTLR3 é relativamente complexo por possuir código java junto com a gramática, o código de gramática será convertido do ANTLR3 para o ANTLR4 a fim de separar o código java da gramatica e melhorar a manutenibilidade do sintático do núcleo.

_Copied from original issue: UNIVALI-LITE/Portugol-Nucleo#72_

**Comment by Rafaelfcosta** [comment]
_From @rytix on June 8, 2017 19:49_

![image](http://i.imgur.com/VopMrVG.gif)

**Comment by rytix** [comment]
Ainda vale 2 salgados pra quem fazer a conversão de forma descente (leia-se descente removendo todo o código java do arquivo .g4)

**Comment by AdsonEsteves** [comment]
Problemas gerados com o atual ANTLR:

Issue #113 
Issue #139 
Issue #76

**Comment by elieserdejesus** [comment]
> Ainda vale 2 salgados pra quem fazer a conversão de forma descente (leia-se descente removendo todo o código java do arquivo .g4)

@rytix , pode ser duas empadinhas, ok? 👍   De preferência de palmito!

**Comment by noschang** [comment]
@rytix. Prometeu tem que cumprir hein??
