### ISSUE TITLE
Erro com vetores.

### ISSUE THREAD

**Issue by SrRandom** [UNIVALI-LITE/Portugol-Studio#315]
**Descrição do Problema**:
Este erro aparece quando eu tento executar um algoritmo com vetores.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/31636994/30040445-a0f270f8-91b5-11e7-9870-24dbcc3c7eb6.png)

**Especificações do sistema**:

**Comment by AlissonSteffens** [comment]
olá @SrRandom pode mandar o código que gera o erro?

**Comment by noschang** [comment]
@AlissonSteffens. Testei aqui e o problema parece ocorrer para qualquer algoritmo que acessa posição de vetor com índice fora dos limites:

```
programa
{
	funcao inicio()
	{
		inteiro vetor[5]

		escreva(vetor[5])
	}
}
```

```
programa
{
	funcao inicio()
	{
		inteiro vetor[5]

		escreva(vetor[-1])
	}
}
```

**Comment by AlissonSteffens** [comment]
Duplicate of #337
