### ISSUE TITLE
Ajustar mecanismo de envio de issues para evitar duplicações

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#320]
Temos um problema complicado aqui.
O tiro saiu pela culatra, pois todo mundo está reportando os mesmos bugs repetidas vezes.

Acredito que isso se deve ao fato de o mecanismo de envio de issues criar uma issue com o nome "Erro numero xxx".

E se nós gerássemos um hash MD5 do stacktrace e usássemos no título da issue? Assim saberíamos de cara que se trata do mesmo erro. Poderíamos usar a API do GitHub para consultar se já existe uma issue com esse hash e em caso afirmativo, informamos para o usuário que este bug já foi reportado e está sendo resolvido.

**Comment by AlissonSteffens** [comment]
Eu até to achando interessante o fato de estarem sendo criadas várias, porque mostra que o problema está realmente afetando muita gente

**Comment by noschang** [comment]
Sim, sim. Concordo contigo neste ponto @AlissonSteffens. Mas se a gente não fizer algo em relação a isso, cada novo bug que surgir vai ser um inferno pra manter a lista de issues. A gente vai passar o dia todo só resolvendo duplicates.

Talvez não precisemos adotar algo tão drástico como sugeri, mas definitivamente precisamos fazer alguma coisa a respeito.

**Comment by AlissonSteffens** [comment]
Não ter erros seria uma ótima solução 👍

**Comment by AlissonSteffens** [comment]
meio que fiz, gero o hash e ponho a versão. O resto talvez deva ser feito, mas não sei se agr :) fechando aqui esta issue
