### ISSUE TITLE
Portugol não executa as vezes mesmo com erro de código corrigido.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#340]
**Descrição do Problema**:
Algumas vezes o Portugol não permite executar o programa mesmo depois de corrigido o erro de compilação.

**Comment by elieserdejesus** [comment]
Não tem muita informação nessa issue, estou assumindo que foi resolvida na issue #358

**Comment by AlissonSteffens** [comment]
Duplicate of #358
