### ISSUE TITLE
Erro nos caminhos quando o PS é aberto clicando em um .por

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#342]
## Um velho amigo está de volta
Este problema aparentemente está de volta a vida, e temos que novamente unir-nos em prol do bem maior, e destruí-lo para que a litelandia volte a ser como era antes;

https://github.com/UNIVALI-LITE-BACKUP/Portugol-Studio/commit/6aee793e28142ab27e4445ef0c503a660823c0d1

**Comment by AlissonSteffens** [comment]
@elieserdejesus acho que vou precisar de ajuda

**Comment by elieserdejesus** [comment]
@AlissonSteffens , amanhã podemos ver isso.

**Comment by AdsonEsteves** [comment]
Problema ainda existe no Linux e possivelmente no MAC
