### ISSUE TITLE
Não é possível arrastar variáveis da árvore para o inspetor de variáveis.

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#348]
**Descrição do Problema**:
As variáveis não são mais colocadas no inspetor quando se arrasta elas da árvore, porém ainda podem ser colocadas no inspetor se arrastar elas do código.
	
Problema ocorreu na versão instalada do Portugol Studio

**Comment by elieserdejesus** [comment]
Rodando no NetBeans está ok,então acho que o problema está relacionado com a minificação do JDK. Acho que é o mesmo problema que está acontecendo na issue #346. Vamos ver se resolvendo a minificação resolve essa duas issues também.

**Comment by noschang** [comment]
Isso mesmo @elieserdejesus. Também desconfio disso. Já abri um pull request #349 revertendo as alterações no JDK. Resta vocês testarem pra ver se resolve estes dois bugs.
