### ISSUE TITLE
Tamanho da tela de atualizações incorreto

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#355]
Na minha resolução, a tela de atualizações aparece com parte do título "cortado". Vejam imagem abaixo:

![tela_update](https://user-images.githubusercontent.com/709553/30543696-6fb1726e-9c5a-11e7-9fde-b65bbf0c0200.png)

**Comment by AlissonSteffens** [comment]
ok. vou tentar descobrir o motivo

**Comment by AdsonEsteves** [comment]
O mesmo problema acontece na tela de erro desconhecido
