### ISSUE TITLE
Instalador não remove desinstalador da versão anterior se foi instalado em cima dela.

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#359]
**Descrição do Problema**:
Instalador não remove desinstalador da versão anterior se foi instalado em cima dela, fazendo com que 2 desinstaladores fiquem disponíveis.

**Comment by AlissonSteffens** [comment]
além disso, o portugol não roda pois há conflito entre as JDKs e JREs

**Comment by AlissonSteffens** [comment]
obs, não acontece mais

**Comment by noschang** [comment]
Resolvido no pull request #380
