### ISSUE TITLE
PS DUPLICANDO 

### ISSUE THREAD

**Issue by Herdyz** [UNIVALI-LITE/Portugol-Studio#371]
**Descrição do Problema**: Meu Portugol Studio,fica duplicando quando eu coloco (" "),e isso me atrapalha pra eu fazer uma programação,já tentei diversos métodos.

**Mensagem de Erro (se houver)**:

**Captura de Tela / [Arquivo.por**:]
![portugolerror](https://user-images.githubusercontent.com/32146571/30669764-deacf3aa-9e35-11e7-92d7-d0d223b448bc.PNG)

**Especificações do sistema**: Win10

**Comment by AlissonSteffens** [comment]
olá @Herdyz , isso parece problema de JVM em versão beta do Windows 10 Insider, podes me passar a versão do teu windows e do teu driver de vídeo?

**Comment by Herdyz** [comment]
Meu windows é o 10 pro ,meu drive é um amd

**Comment by AlissonSteffens** [comment]
@Herdyz sabe me dizer a versão do build deles?
ex:

Windows 10 Pro Insider Preview
Build *???* pre_release
processador versão
*???*gb Ram
modelo placa de vídeo
AMD Driver Versão *???*

Resolução do PC:

**Comment by Rafaelfcosta** [comment]
Esse problema também acontece comigo e parece que está relacionado ao swing do java, pois tive problemas semelhantes usando o MARS.

Minha configuração:
Windows 10 Education 
Versão: 1703
Build: 15063.608
Processador: AMD FX-8300
8Gb Ram
Vídeo: GTX 1050 Ti 4gb
Resolução da tela: 2560x1080

![image](https://user-images.githubusercontent.com/21344756/30877154-3ed548b6-a2cf-11e7-96e7-68817831edaa.png)

![image](https://user-images.githubusercontent.com/21344756/30877578-795bfe02-a2d0-11e7-8a45-a5889d879eda.png)

**Comment by AlissonSteffens** [comment]
parece que um velho amigo está de volta #80

**Comment by AlissonSteffens** [comment]
Creio que seja treta do Java nestas versões earlybuild do Windows 10, não faço a menor ideia de se sequer existe uma solução para isso.
@elieserdejesus ou @noschang alguém tem um palpite?

**Comment by noschang** [comment]
Segundo [esta thread](https://stackoverflow.com/questions/34316000/swing-ui-multiplying-panel-ghosting) o erro parece ocorrer principalmente quando é exibida uma tooltip, como no screenshot acima.

O pessoal discute na thread que a provável causa seja a renderização de algum componente fora da thread do Swing. Então acho que vale a pena investigar isso.

[Esta outra thread](https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7), apresenta duas outras possibilidades.

A primeira está relacionada a um bug já conhecido do JDK, na qual deve ser criada uma variável de ambiente para resolver o problema. 

![figura](https://user-images.githubusercontent.com/709553/30912072-8c990cda-a361-11e7-83fb-fd45d3baf07e.png)

A segunda, está relacionada a um problema com dirvers de vídeo da NVidia. Na thread mostra como solucionar.

Enfim, acho que vale a pena investigar estas 3 hipóteses. Eu começaria pela variável de ambiente, parece ser a mais rápida e fácil de implementar e testar. Alguém se habilita, já que suo Linux?

**Comment by AlissonSteffens** [comment]
@noschang na issue https://github.com/UNIVALI-LITE/Portugol-Studio/issues/231, eu e o @AdsonEsteves já investigamos muitas destas opções, e parece que o cara resolveu mudando a versão do driver de vídeo dele

**Comment by AlissonSteffens** [comment]
Não sei se temos como resolver esse tipo de coisa

**Comment by noschang** [comment]
@AlissonSteffens. Investigou a da variável de ambiente também?

**Comment by AlissonSteffens** [comment]
olha o comentário do @AdsonEsteves no dia 12 de Jun

**Comment by noschang** [comment]
Sim @AlissonSteffens. Ele testou uma variável de ambiente. Mas a que ele testou o nome é diferente da variável que eu achei no fórum. Acho que vale a pena testar também para descartar, pois pode ser que o nome da variável é diferente dependendo da versão do JDK.

**Comment by AdsonEsteves** [comment]
@Herdyz 
Estou fechando essa issue e colocando uma principal (#421) com os possíveis problemas e soluções.
