### ISSUE TITLE
[Mac] Problemas na geração do instalador do Mac

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#373]
**Descrição do Problema:**

O novo sistema de build está quebrando o instalador do Mac. Os problemas encontrados são

1. O instalador está com problema de permissão (não acontecia nas versões anteriores). Para executar o instalador foi necessário usar o commando: 
 ```
sudo chmod -R 777 {Caminho instalador}
```
Parece que a ordem dos parâmetros do **chmod** é diferente no Mac e no Linux. @noschang,  poderíamos mudar o comando chmod no instalador para cada plataforma ou simplesmente tentar o comando acima no Linux. Acho provável que o Linux também aceite os parâmetros nessa ordem, assim evitaríamos um "IF" nos scripts do instalador.

2. Depois de modificadas as permissões do instalador a instalação funcionou corretamente, porém o PS não executou. Tentei rodar o executável pela linha de comando e tive o seguinte erro:
```
-bash: ./Portugol Studio: /bin/sh^M: bad interpreter: No such file or directory
```
Já vi esse erro antes quando o git estava mudando o formato da quebra de linha. Acho que o instalador está sendo gerado com as quebras de linha no formato windows.

**Especificações do sistema**:
Mac (problema encontrado em mais de uma versão)

**Comment by elieserdejesus** [comment]
**Confirmardo**: O problema do app era a quebra de linha. Usei esse comando para converter as quebras de linha e funcionou:
```
tr -d '\r'  < Applications/Portugol\ Studio   > PS_Corrigido
```

**Comment by AlissonSteffens** [comment]
@elieserdejesus falta muito será pra deixar funcionando?
Queria mandar um release

**Comment by elieserdejesus** [comment]
@AlissonSteffens , para hoje não tenho como mexer nessa issue. Não esqueça de upar o repositório backup do instalador, tem um commit nele que é metade da solução dessa issue aqui (a parte das quebras de linha).  A outra parte do problema é a questão da permissão, tem que mudar o **chmod** no arquivo to bitrock e testar.

**Comment by AlissonSteffens** [comment]
tá ai https://github.com/UNIVALI-LITE-BACKUP/Portugol-Instalador

**Comment by elieserdejesus** [comment]
Solved! Fix duas coisas:

1 - modifiquei o .gitattibutes para sempre deixar os scripts com a quebra de linha correta
2 - O instalador está setando a quebra de linhas rodando o comando **sed**. Os '\r' são deletados do executável e comandos arquivos .command.
