### ISSUE TITLE
Uma dica

### ISSUE THREAD

**Issue by riandziuba** [UNIVALI-LITE/Portugol-Studio#384]
Poderia na hora de salvar o arquivo, ser aberta a última pasta utilizada pelo usuário.

**Comment by AdsonEsteves** [comment]
@riandziuba 

Isso já foi adicionado no Portugol Studio, e estará disponível no próximo release.

**Comment by AlissonSteffens** [comment]
obs: tkx to @Rafaelfcosta 👍

**Comment by Rafaelfcosta** [comment]
![image](https://media.giphy.com/media/3o85xwxr06YNoFdSbm/giphy.gif)
