### ISSUE TITLE
Aba inicial não inicializa corretamente ao abrir um .por

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#389]
Pessoal, estou usando a versão 2.6.3 beta e percebi que ao abrir um **.por** a aba inicial não é inicializada como deveria.
Alguém mais pode verificar?

![image](https://user-images.githubusercontent.com/21344756/30995630-01c0a2f8-a492-11e7-85cc-334dd16a4cb4.png)

**Comment by AlissonSteffens** [comment]
mas ué; tem certeza que tais com a versão certa?? baixasse essa de onde?

**Comment by Rafaelfcosta** [comment]
Baixei a que foi liberada pro pessoal do discord, pelo link do mega inclusive.

**Comment by AlissonSteffens** [comment]
:(
ok

**Comment by noschang** [comment]
Testei aqui no Ubuntu e está normal. A propósito @Rafaelfcosta, procurei no Disccord inteiro e não achei essa versão que você falou.

**Comment by AdsonEsteves** [comment]
Corrigido em #294
