### ISSUE TITLE
AutoFormatação do código

### ISSUE THREAD

**Issue by erickweil** [UNIVALI-LITE/Portugol-Studio#411]
No netbeans, eclipse e outras IDE's só temos uma opção que é a auto-formatação do código. no netbeans há até um atalho( ctrl+shift+F ), onde que por mais que o código esteja mal organizado toda a identação do código é corrigida. 

Essa funcionalidade facilitaria muito a utilização do portugol.

**Comment by Rafaelfcosta** [comment]
Valeu pela sugestão @erickweil , vamos conversar e verificar a possibilidade de adicionar esta funcionalidade.

**Comment by AlissonSteffens** [comment]
closed at 0edef237d81005f0dbe68bda69a2673f72d92b84

**Comment by rafaelreiscda** [comment]
algoritmo "reapostas" 
var  

	i: inteiro    
	a: real    
	b: real    
	c: real 
	
inicio    
escreva("Informe a forma de classificacao: ")    
leia(i)    
escreva("Informe a: ")    
leia(a)    
escreva("Informe b: ")    
leia(b)    
escreva("Informe c: ")    
leia(c)    
se (i = 1) entao       
	se (a < b) e (a < c) entao          
		escreva(a, " ")          
			se (b < c) entao             
				escreva(b, " ", c)          
			senao             
				escreva(c, " ", b)          
			fimse       
		senao          
			se (b < a) e (b < c) entao             
				escreva(b, " ")             
				se (a < c) entao                
					escreva(a, " ", c)             
				senao                
				escreva(c, " ", a)             
				fimse          
			senao             
				escreva(c, " ")             
				se (b < a) entao                
					escreva(b, " ", a)             
				senao                
					escreva(a, " ", b)             
				fimse          
			fimse       
		fimse    
	fimse

se (i = 2) entao       
	se (a > b) e (a > c) entao          
		escreva(a, " ")          
		se (b > c) entao             
			escreva(b, " ", c)          
		senao             
			escreva(c, " ", b)          
		fimse       
	senao          
		se (b > a) e (b > c) entao             
			escreva(b, " ")             
			se (a > c) entao                
				escreva(a, " ", c)             
			senao                
				escreva(c, " ", a)             
			fimse          
			senao             
				escreva(c, " ")             
			se (b > a) entao                
				escreva(b, " ", a)             
			senao                
			escreva(a, " ", b)             
			fimse          
			fimse       
			fimse    
			fimse    
			se (i = 3) entao       
			se (a > b) e (a > c) entao          
			escreva(b, " ", a, " ", c)       
			senao          
			se (b > c) e (b > a) entao             
			escreva(a, " ", b, " ", c)          
			senao             
			escreva(a, " ", c, " ", b)          
			fimse       
			fimse    
			fimse    
			se (i < 1) ou (i > 3) entao       
			escreva("Classificacao Invalida!!!")    
			fimse 

			fimalgoritmo

**Comment by profRafaelRibas** [comment]
Essa funcionalidade foi implementada? Utilizo em aula com os alunos e seria legal um atalho como esse
