### ISSUE TITLE
Problema de permissão no Mac SIERRA não permite executar Javac

### ISSUE THREAD

**Issue by davidmirandar** [UNIVALI-LITE/Portugol-Studio#413]
**Descrição do Problema**:
Na hora de compilar não executa e aparece a mensagem abaixo. Creio que pode não estar encontrando o caminho especificado do javac, devido o ESPAÇO no nome "Portugol Studio.app"
.
**Mensagem de Erro (se houver)**:
Cannot run programa "/Applications/Portugol Studio.app/Contents/Resources/IDE/java/java-mac/bin/javac" (in directory "."): error=0, spawn failed

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by Rafaelfcosta** [comment]
![erro](https://user-images.githubusercontent.com/21344756/32011134-a31608ae-b992-11e7-8e07-23397470d410.png)
Mesmo após remover o espaço o erro permaneceu.

**Comment by noschang** [comment]
@davidmirandar, pode nos informar por favor qual a versão do Portugol Studio que você está utilizando?

**Comment by davidmirandar** [comment]
A versão que foi indicada direto pelo download do site:  "portugol-studio-2.6.3-osx.dmg"

**Comment by AdsonEsteves** [comment]
Encontrei o problema
É simplesmente problema de permissão. Enquanto não resolvemos o problema, o workaround que encontrei foi esse:

1. Entre no terminal e escreva "sudo chmod -R go+x /Applications/Portugol\ Studio.app/Contents/" sem aspas

2. depois execute o Portugol pelo terminal "sudo /Applications/Portugol\ Studio.app/Contents/Resources/IDE/executar-studio-mar.command" sem aspas

**Comment by romanonatacha** [comment]
@AdsonEsteves pode me ajudar sendo mais claro?
Eu sou super iniciante, comecei agora um curso online onde pedem para usar o visualG, mas uso mac, e i que recomendaram o Portugol Studio, mas no meu primeiro exercício já aconteceu esse mesmo erro na hora de executar, vi que deu a solução, mas como disse, sou iniciante mesmo, e não tenho ideia do que seja terminal e onde tenho que escrever isso, se puder me ajudar sendo mais claro agradeço muito pois procurei em outros lugares e não achei solução.

**Comment by AdsonEsteves** [comment]
Movido para #520

**Comment by nynonet** [comment]
Baixei a versão 2.6.7 e mesmo assim o erro ocorreu.

depois executei o comando: 

`Entre no terminal e escreva "sudo chmod -R go+x /Applications/Portugol\ Studio.app/Contents/" sem aspas
`
conforme o colega tinha dito, reiniciei e tudo funcionou numa boa.
