### ISSUE TITLE
Erro de instalação

### ISSUE THREAD

**Issue by jmapsimoes** [UNIVALI-LITE/Portugol-Studio#430]
**Descrição do Problema**:
Após instalar com sucesso a versão para MacOS, quando tento correr um programa ou um dos exemplos já existentes, surge esta mensagem que está no ficheiro anexo.
Aparentemente, não encontra o compilador de java … 
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![captura de ecra 2017-10-27 as 15 45 59](https://user-images.githubusercontent.com/9195015/32373589-da1336d2-c091-11e7-84b1-e7b706c09b40.png)

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@jmapsimoes 

O seu é um MAC Sierra também? Como na #413 ?

**Comment by jmapsimoes** [comment]
Sim, Mac OS Sierra versão 10.12.6.
O ficheiro que descarreguei foi a versão portugol-studio-2.6.3

**Comment by jmapsimoes** [comment]
O erro é o mesmo da #413

**Comment by AdsonEsteves** [comment]
@jmapsimoes 

Ok, como é o mesmo problema vou fechar essa aqui e citar lá

**Comment by AdsonEsteves** [comment]
Duplicate of #413
