### ISSUE TITLE
O operador unário não é interpretado corretamente com chamadas de função

### ISSUE THREAD

**Issue by whbogado** [UNIVALI-LITE/Portugol-Studio#433]
**Descrição do Problema**:
Aparentemente existe um problema na gramática do operador - unário quando combinado com chamadas de função.

Já o operador + unário parece não estar definido pois acusa que espera dois operandos.

Por exemplo, no seguinte código

```
programa
{
	inclua biblioteca Matematica --> mat
	
	funcao inicio()
	{
		real r = 1.0
		r = -mat.raiz(4.0, 2.0)
		escreva(r)
	}
}
```
O operador unário não é interpretado corretamente

**Mensagem de Erro (se houver)**:
```
error: cannot find symbol
r = -mat.raiz(4.0, 2.0)
^
symbol variable mat
```

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/2821192/32406187-dee7b22c-c15a-11e7-9e19-f5405690ff9f.png)

**Especificações do sistema**:
Windows 10/Linux Mint	
Portugol Studio 2.6.3

**Comment by noschang** [comment]
Olá @whbogado. Iremos verificar o problema. Como solução provisória, você pode colocar um parenteses ao redor da expressão. Isso deve resolver. Ex.:

```
r = -(mat.raiz(4.0, 2.0))
```

**Comment by AdsonEsteves** [comment]
@noschang 

Mesmo colocando entre parênteses ainda não funciona

**Comment by AdsonEsteves** [comment]
Arrumado em #435
