### ISSUE TITLE
Erro ao executar um Programa no app para MacOS

### ISSUE THREAD

**Issue by mateusocana** [UNIVALI-LITE/Portugol-Studio#436]
**Descrição do Problema**:
Ao tentar executar um programa um erro é printado na tela e o programa não roda.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
http://prntscr.com/h7fet9

**Especificações do sistema**:
Mac OS HIgh Sierra 10.13

**Comment by AdsonEsteves** [comment]
Duplicate of #413

**Comment by AdsonEsteves** [comment]
@mateusocana 

Estamos trabalhando para resolver este problema, na issue #413, descrevi uma possível solução temporária.
