### ISSUE TITLE
Erro Portugol Mac

### ISSUE THREAD

**Issue by juliobianco** [UNIVALI-LITE/Portugol-Studio#439]
**Descrição do Problema**:
Ao iniciar algum programa (novo ou já salvo) é apresentado o erro:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
<img width="1089" alt="screen shot 2017-11-16 at 23 10 55" src="https://user-images.githubusercontent.com/3975875/32924372-71d90f14-cb23-11e7-8141-2ad7a2287bc1.png">

**Especificações do sistema**:
	Mac OS High Sierra
Java 9 instalado

**Comment by juliobianco** [comment]
Utilizei a dica que o @AdsonEsteves deu no outro tópico:

Entre no terminal e escreva "sudo chmod -R go+x /Applications/Portugol\ Studio.app/Contents/" sem aspas

Execute o Portugol pelo terminal "sudo /Applications/Portugol\ Studio.app/Contents/Resources/IDE/executar-studio-mac.command" sem aspas


Funcionando aqui.

**Comment by AdsonEsteves** [comment]
Duplicate of #413
