### ISSUE TITLE
Mensagem de renomear elementos não é exibido corretamente.

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#443]
Após mudanças nos jOptionPanes o aviso não aparece por inteiro.
![aviso_renomear](https://user-images.githubusercontent.com/21344756/33142492-e2b7bef0-cf9d-11e7-9220-0ec0d806a076.png)

**Comment by AdsonEsteves** [comment]
@Rafaelfcosta 

Pode me dar um exemplo onde isso acontece?

**Comment by Rafaelfcosta** [comment]
@AdsonEsteves Ao abrir o PS pela primeira vez, ou mudando para **exibirAvisoRenomear=true** no arquivo de configurações.

**Comment by AdsonEsteves** [comment]
closed in bd54535
