### ISSUE TITLE
Renomear funções de biblioteca gera erros

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#444]
**Descrição do Problema**:
Quando se tenta renomear uma função de biblioteca, acaba se gerando um erro, quando deveria aparecer uma mensagem de aviso.

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/8836540/33185463-e90aec24-d069-11e7-9984-a38d336936bb.png)

**Comment by jothbc** [comment]
![image](https://user-images.githubusercontent.com/30815072/33230026-4e50b4de-d1c2-11e7-9ce6-4c8a2ce1c91b.png)


estranho...
