### ISSUE TITLE
Bug no ambiente de desenvolvimento

### ISSUE THREAD

**Issue by Wendell22** [UNIVALI-LITE/Portugol-Studio#453]
**Descrição do Problema**:
Boa tarde,

Quando utilizo o portugol o meu ambiente de desenvolvimento fica todo alterado e não consigo programar. Confirme em anexo.

**Captura de Tela / Arquivo.por**:
![portugol erro](https://user-images.githubusercontent.com/34281327/33621290-26bf26d0-d9e2-11e7-8650-90fa7398af71.png)

**Especificações do sistema**: Windows 10 64 bits

**Comment by AdsonEsteves** [comment]
@Wendell22 

Estamos trabalhando pra achar alguma solução para esse problema
criamos uma issue sobre isso aqui: #421
Ela traz algumas possíveis soluções, mas elas não são 100% de certeza que irá funcionar.

Obrigado pelo reporte.
