### ISSUE TITLE
Melhorar a documentação de pacotes convertendo arquivos package.html para package-info.java

### ISSUE THREAD

**Issue by manoelcampos** [UNIVALI-LITE/Portugol-Studio#456]
O formato de arquivos de documentação de pacotes `package.html` é um formato legado, anterior ao Java 5. [Tal formato não permite incluir anotações nem tags JavaDoc](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#packagecomment). Por exemplo, não é possível:

- usar uma tag `@link` para referenciar uma determinada classe;
- incluir informações de autor com `@author`; 
- ou informar desde que versão o pacote existe com a tag `@since`.

Como não é possível usar tags `@link` para referenciar outras classes, caso o nome de uma classe seja referenciado dentro do package.html, se a classe for renomeada, as referências a ela no html não serão atualizadas.

O uso do formato `package-info.java` para documentação de pacotes dá mais poder para a documentação de pacotes e minimiza inconsistências entre a documentação de pacotes e as classes/métodos referenciados.

Adicionalmente, este é o [formato recomendado pela Oracle](https://blogs.oracle.com/darcy/javadoc-tip:-prefer-package-info-to-packagehtml).

A conversão dos arquivos `package.html` para `package-info.java` pode ser feita automaticamente no IntelliJ para todo o projeto.

Caso achem adequado, me encarrego de tal refatoração.

**Comment by noschang** [comment]
Oi @manoelcampos. Acho uma excelente ideia

**Comment by noschang** [comment]
@manoelcampos, apenas um lembrete. Quando abrir as issue, por favor, marque ela com a label apropriada

**Comment by manoelcampos** [comment]
Eu não tenho permissão pra definir labels. Acho que só vocês podem fazer isso.

**Comment by noschang** [comment]
Hum. Vou verificar @manoelcampos.
