### ISSUE TITLE
Comando limpa no console

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#459]
**Descrição:** _Ao executar o programa sem abrir o Portugol Studio(em modo console), o comando limpa não limpa o console(como faz com o Portugol Studio aberto)._

**Captura de Tela:**
![2017-12-12_22-14-48](https://user-images.githubusercontent.com/32302914/33915350-f231805e-df89-11e7-9574-ed61b2530607.png)
![2017-12-12_21-55-35](https://user-images.githubusercontent.com/32302914/33915476-b45b786a-df8a-11e7-987f-b899c49d8f27.png)

**Exemplo do que ocorre:**
`enquanto(1 + 1 == 2){`
`//Simulando o que ocorre:`
`escreva("Imagens colocadas com sucesso!")`
`limpa()`
`}`

**Comment by noschang** [comment]
@AdsonEsteves. Dei uma pesquisada aqui e acredito que para fazer funcionar é só colocar esta linha na [implementação](https://github.com/UNIVALI-LITE/Portugol-Studio/blob/29122f3797ecae01be3af49e5dd55f7a9295fcfc/console/src/main/java/br/univali/portugol/Console.java#L445) da função ```limpar()``` do Portugol-Console.

```new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();```

Basta criar um ```else``` para a plataforma Windows e em seguida colar este código.
Poderias fazer isso por favor? Estou com outras demandas e não vou conseguir ver isso.

**Comment by LogikozRC** [comment]
como eu faço para abrir o console do windows pelo portugol? como ai na imagem.

**Comment by noschang** [comment]
Oi @LogikozRC. Se você tem a versão instalada do Portugol Studio, você pode abrir uma janela do console (cmd) e digitar ```portugol-console <caminho do programa>```. Exemplo:

```portugol-console C:\Users\Joao\Desktop\fatorial.por```

**Comment by LogikozRC** [comment]
![image](https://user-images.githubusercontent.com/37851168/47058544-f2e48a00-d19b-11e8-8895-dc6959ad114f.png)

apareceu isso '-'

**Comment by noschang** [comment]
Oi @LogikozRC. Tente um dos seguintes comandos então:

```C:\ProgramData\UNIVALI\Portugol Studio\executar-console-windows.bat <caminho do programa>```

```C:\ProgramData\Portugol Studio\executar-console-windows.bat <caminho do programa>```

**Comment by LogikozRC** [comment]
tambem nao da '-' diz que

![image](https://user-images.githubusercontent.com/37851168/47106932-4c8d9880-d21e-11e8-80ee-0da00ae1718d.png)

**Comment by LogikozRC** [comment]
nao seria porque o diretorio do portugol tem "espaço"?

**Comment by LogikozRC** [comment]
mesma coisa '-' 

![image](https://user-images.githubusercontent.com/37851168/47132235-4d074d00-d279-11e8-907b-7425a2d40799.png)

**Comment by LogikozRC** [comment]
tentei colocar o arquivo direto no disco C, e ainda da a mesma coisa '-'

**Comment by noschang** [comment]
Oi @LogikozRC. Na imagem acima, você colocou o comando "cd" na frente dos outros comandos, então o terminal está tentando entrar no diretório ao invés de executar o arquivo

**Comment by Nodimus** [comment]
Boa tarde como é que se faz o mesmo no Linux, quando tento aparece um monte de letras e não executa

**Comment by Mateus-Hirt** [comment]
> @Logikoz 
> tentei colocar o arquivo direto no disco C, e ainda da a mesma coisa '-'

Clicando com o botão direito no arquivo, você pode executar ele no modo gráfico ou console, sem ter que abrir o Portugol :)
![Sem título](https://user-images.githubusercontent.com/32302914/109810619-83ef1b00-7c08-11eb-9ff9-354be4aa0732.png)
