### ISSUE TITLE
Erros na Ajuda

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#469]
Direto do nosso discord:

![image](https://user-images.githubusercontent.com/8836540/35652240-efeb7568-06c9-11e8-8d4f-7295d8a34585.png)

**Comment by elieserdejesus** [comment]
@AdsonEsteves , seria legal pedir para o Taarak corrigir. Aponte os 2 arquivos que precisam ser alterados e quem sabe ele pode se torna um contribuidor.
