### ISSUE TITLE
Erro de caminho no exemplo de vestir personagem

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#477]
Ao tentar executar no Linux ocorre um problema de caminho, conforme a imagem abaixo.

![figura1](https://user-images.githubusercontent.com/709553/35840236-18bed8ac-0adc-11e8-8e91-7eac2b90cc6f.png)

É necessário verificar as letras maiúsculas e minúsculas. Além disso, deve-se incluir "./" no início do caminho para garantir que o caminho seja relativo ao local do programa.

**Comment by Jtinha2000** [comment]
usign Rocket,nid
