### ISSUE TITLE
PS trava se biblioteca Teclado for incluída antes de Graficos

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#487]
Este código funciona corretamente:
```
programa
{
	inclua biblioteca Graficos
	inclua biblioteca Teclado
	
	funcao inicio() {}
}
```
	
Já este código abaixo **(apenas inverti a ordem das bibliotecas)** trava a execução do programa. Colocando um trace/escreva na função início é possível observar o programa nem é iniciado. O problema está antes mesmo do início da execução, alguma coisa relacionada com a ordem das bibliotecas:

```
programa
{
	inclua biblioteca Teclado
	inclua biblioteca Graficos
	
	funcao inicio() {}
}
```

**Comment by noschang** [comment]
@elieserdejesus. Você testou isso em qual versão? No master? Pergunto isso porque se não me engano o @AdsonEsteves já havia detectado e corrigido este problema.

**Comment by elieserdejesus** [comment]
Tinha testado na versão instalada @noschang , realmente está corrigido no master https://github.com/UNIVALI-LITE/Portugol-Studio/commit/3854dbfe963a8188c0745b8015fa96d29bfeecf8

Valeu @AdsonEsteves !

**Comment by noschang** [comment]
@elieserdejesus ou @AdsonEsteves . Um dos dois por favor encontre a issue anterior e marque esta com a label "duplicate".

**Comment by AdsonEsteves** [comment]
Duplicate of #465
