### ISSUE TITLE
Exemplo Robos "Aleatorios" da biblioteca internet gera erros

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#501]
![image](https://user-images.githubusercontent.com/8836540/37220226-b79682d2-23a4-11e8-9512-68b940742c93.png)

**Comment by AdsonEsteves** [comment]
@AlissonSteffens @Rafaelfcosta 

GRIM REMINDER

![](https://i.ytimg.com/vi/_yxAYDtg2_A/maxresdefault.jpg)

**Comment by Rafaelfcosta** [comment]
![ok](https://media.giphy.com/media/R459x856IfF6w/giphy.gif)

**Comment by Rafaelfcosta** [comment]
Closed via 6d9eac84c888fef7fb4d6d0e18af06aa12c71ef9
