### ISSUE TITLE
Como desinstalar?

### ISSUE THREAD

**Issue by Rykoh** [UNIVALI-LITE/Portugol-Studio#504]
Não consigo desinstalar o programa no ubuntu

Ubuntu 16.04 LTS

**Comment by noschang** [comment]
Abra um terminal e digite:

```sudo /usr/local/portugol-studio/desinstalar```

Ou

```sudo /usr/local/univali/portugol-studio/desinstalar```

Dependendo da versão do Portugol Studio que estiver instalada.
Por favor responda aqui no GitHub se conseguir, para que possamos fechar a issue.

**Comment by Rykoh** [comment]
Funcionou para mim o segundo, mas o diretório é:

sudo /usr/localportugol-studio/desinstalar

Sem o univali
