### ISSUE TITLE
quando utilizo as aspas("),a tela fica toda bugada,e começa a se mexer para todos os lados

### ISSUE THREAD

**Issue by Fulanoo** [UNIVALI-LITE/Portugol-Studio#507]
**Descrição do Problema**:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@Fulanoo 

Tem algo a ver com este erro?
https://github.com/UNIVALI-LITE/Portugol-Studio/issues/421
