### ISSUE TITLE
Aspas

### ISSUE THREAD

**Issue by Fulanoo** [UNIVALI-LITE/Portugol-Studio#512]
**Quando utilizo aspas("),a tela fica se mexendo e bugando**:

**Não tem**:

**![arquivo](https://user-images.githubusercontent.com/37639956/38179424-97550f9a-35f9-11e8-9fbc-d049f7ed13ca.png)
**:

**Especificações do sistema
![image](https://user-images.githubusercontent.com/37639956/38179437-b31288a2-35f9-11e8-9166-48d8a075cd53.png)
**:

**Comment by AdsonEsteves** [comment]
@Fulanoo 

Dá uma olhada aqui #421
