### ISSUE TITLE
O portugol studio não compila no linux mint 32bits

### ISSUE THREAD

**Issue by arturcotemig** [UNIVALI-LITE/Portugol-Studio#515]
**Descrição do Problema**:
Não consigo compilar os exercícios da erro de compilação 
**Mensagem de Erro (se houver)**:
Error: missing 'client' jVM at '/usr/local/portugol-studio/java/java-linux/jre/lib/i386/client/libjvm.so'.

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
Linux mint 17 32bits

**Comment by arturcotemig** [comment]
Pessoal,

testei com esta nova versão que o Alisson indicou e ainda não consigo compilar da o mesmo erro de falta de biblioteca

**Comment by AdsonEsteves** [comment]
Aparentemente esse erro voltou e também no Xubunto

![image](https://user-images.githubusercontent.com/8836540/44803823-ee392780-ab95-11e8-98a7-aadc35041a9f.png)


![image](https://user-images.githubusercontent.com/8836540/44803742-b4682100-ab95-11e8-9332-aa8235bd879a.png)

**Comment by YpsYlonY** [comment]
Pesquisando aqui notei que pode ser que haja algum engano no instalador da versão 32 bits deste programa.
O que notei é que o arquivo solicitado pelo programa não existe na pasta indicada "client" porém o mesmo está dentro de uma pasta chamada "server"
resolvi o problema aqui da seguinte forma via console

`cd /usr/local/portugol-studio/java/java-linux/jre/lib/i386/`
`sudo cp -r server/ client`

**Comment by YpsYlonY** [comment]
> **Descrição do Problema**:
> Não consigo compilar os exercícios da erro de compilação
> **Mensagem de Erro (se houver)**:
> Error: missing 'client' jVM at '/usr/local/portugol-studio/java/java-linux/jre/lib/i386/client/libjvm.so'.
> 
> **Captura de Tela / Arquivo.por**:
> 
> **Especificações do sistema**:
> Linux mint 17 32bits

Pesquisando aqui notei que pode ser que haja algum engano no instalador da versão 32 bits deste programa.
O que notei é que o arquivo solicitado pelo programa não existe na pasta indicada "client" (esta nem existe) porém o mesmo está dentro de uma pasta chamada "server"
resolvi o problema aqui da seguinte forma via console

`cd /usr/local/portugol-studio/java/java-linux/jre/lib/i386/`
`sudo cp -r server/ client`

**Comment by AdsonEsteves** [comment]
O Problema foi corrigido e sera arrumado na proxima versao que saira semana que vem
