### ISSUE TITLE
Highlight.js com suporte ao Portugol Studio

### ISSUE THREAD

**Issue by marcoaugustoandrade** [UNIVALI-LITE/Portugol-Studio#524]
Para quem tem a necessidade de inserir código do Portugol Studio em documentos HTML (posts ou apresentações como Reveal.js, por exemplo) desenvolvi um fork do conhecido plugin Highlight.js.

Está disponível em [highlight.js-portugol](https://github.com/marcoaugustoandrade/highlight.js-portugol)

**Comment by AlissonSteffens** [comment]
Opa, obrigado @marcoaugustoandrade , iremos começar a utilizar 👍 
Vou deixar esta issue aberta para duvidas e complementos que possam surgir.
