### ISSUE TITLE
[Ideia] Disponibilizar campo de busca para os exemplos

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#551]
**Descrição do Problema**:

Atualmente não é possível pesquisar os exemplos. A ideia seria digitar uma palavra chave em um campo "localizar" (como o que existe para pesquisar na árvore estrutural) e trazer exemplos que contém o termo pesquisado no título do exemplo (acho que não daria muito certo pesquisar os termos no código fonte, teríamos muitas ocorrências).

**Comment by noschang** [comment]
@UNIVALI-LITE/portugol-studio gostaria de sugerir algo a mais.

Todos os exemplos têm (ou pelo menos deveriam ter) um cabeçalho padrão em forma de comentário, o qual contém o nome dos autores, data de criação e descrição.

Sugiro que inicialmente façamos a pesquisa baseada apenas no título do exemplo, mas que futuramente criemos um índice processando o cabeçalho de cada um desses exemplos e daí utilizando esse índice na pesquisa.

Podemos inclusive incluir no cabeçalho de cada exemplo uma seção contendo tags ou keywords para facilitar esta busca/indexação.
