### ISSUE TITLE
Template para novos Projetos

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#557]
Ao criar um novo projeto, atualmente o usuário é levado a um codigo em branco:
![image](https://user-images.githubusercontent.com/6234230/39885179-57a20254-5462-11e8-91dc-7e542d1c3106.png)
Eu acredito que possamos entregar um código melhor adaptado ao usuário com algumas alterações simples no jeito em que isso funciona.
## A seguir algumas mudanças que que possam ser Significativas

Ao clickar no botão novo ou adicionar aba, o usuário deve passar por uma tela intermediária onde ele possa escolher as bibliotecas inseridas no programa inicial que entregaremos a ele:
![image](https://user-images.githubusercontent.com/6234230/39887350-69a111ec-5468-11e8-8f57-d1caae373f19.png)

Além disso, acho que devamos mudar o Porgrama padrão para;
```javascript
programa
{
	funcao inicio()
	{
		escreva("Olá Mundo")
	}
}
```

E caso o usuário escolha a Opção Gráfico:
```javascript
programa
{
	inclua biblioteca Graficos --> g
	inclua biblioteca Teclado --> t
	
	funcao processamento(){
		
	}

	funcao desenhar(){
		g.definir_cor(g.COR_BRANCO)
		g.limpar()
		g.definir_cor(g.COR_VERDE)
		g.desenhar_retangulo(100, 100, 600, 400, verdadeiro, verdadeiro)
		g.renderizar()
	}
	
	funcao inicio(){
		g.iniciar_modo_grafico(verdadeiro)
		g.definir_dimensoes_janela(800, 600)
		enquanto(nao t.tecla_pressionada(t.TECLA_ESC)){
			processamento()
			desenhar()
		}
	}
}
```
ou by @elieserdejesus 
```javascript
programa
{
	inclua biblioteca Graficos --> g
	inclua biblioteca Teclado --> t
	
	funcao desenhar(){
		g.definir_cor(g.COR_BRANCO)
		g.limpar()
		g.definir_cor(g.COR_VERDE)
		g.desenhar_retangulo(100, 100, 600, 400, verdadeiro, verdadeiro)
		g.renderizar()
	}
	
	funcao inicio(){
		g.iniciar_modo_grafico(verdadeiro)
		g.definir_dimensoes_janela(800, 600)
		enquanto(nao t.tecla_pressionada(t.TECLA_ESC)){
			desenhar()
		}
	}
}
```

Quem gostar manda um 👍 quem achar nada a ver manda um 👎 , se gostou mas tem ideias de coisas que poderiam ser diferentes põe ai em baixo nos comentários 😄

**Comment by rytix** [comment]
A versão de baixo acho melhor :)

**Comment by AlissonSteffens** [comment]
Fechado em #561
