### ISSUE TITLE
Ah... Isso pode acontecer?

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#562]
Uma função com o nome escreva... Pode isso?
![funcao escreva(cadeia str){ escreva(str) }](https://user-images.githubusercontent.com/32302914/40148535-d9498354-5944-11e8-8ea1-c47959c5bc1e.png)

:computer: **SO**: Windows 7
:computer: **Versão**: 2.6.4

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 

Isso está corrigido na versão atual 2.6.9

**Comment by Mateus-Hirt** [comment]
@AdsonEsteves Oh, sério? Minha nossa... Mil desculpas... Eu não sabia disso...
