### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by EnzzoHosaki** [UNIVALI-LITE/Portugol-Studio#563]
**Descrição do Problema**: Recebo uma mensagem dizendo que a variável não foi dlerada, sendo que foi declarada nos mesmo detalhes

**Mensagem de Erro (se houver)**

**Captura de Tela / [Arquivo.por**
![2018-05-19](https://user-images.githubusercontent.com/39446235/40273543-2383c3ee-5b98-11e8-882f-8a5f980d59ef.png)

**Especificações do sistema**:

Intel Core i5 4430 CPU 3.0 GHZ
8,0 Ram
64 Bits
Windows 10 Pro

**Comment by AlissonSteffens** [comment]
Boa noite @EnzzoHosaki  a mensagem diz que a variável não foi INICIALIZADA, o que de fato não foi. para dizer **nao bethVai** vc precisa antes atribuir um valor à variável
