### ISSUE TITLE
Instalador via linha de comando (CLI)

### ISSUE THREAD

**Issue by samirfor** [UNIVALI-LITE/Portugol-Studio#567]
Olá, eu preciso instalar o Portugol Studio em várias máquina de um laboratório com sistema linux.

Como faço para instalar via linha de comando de forma automatizada?

**Comment by samirfor** [comment]
Descobri:

```
./portugol-studio-2.6.6-linux-x64.run --mode unattended
```

**Comment by noschang** [comment]
Ola @samirfor. Muito espertinho você hehehehe. Foi mais rápido que a gente. 
Obrigado por compartilhar sua solução.
