### ISSUE TITLE
PS sugere funções de uma biblioteca mesmo se ela não for incluida ou estiver com o atalho "errado"

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#572]
**Imagem de atalho "errado"**:
![image](https://user-images.githubusercontent.com/32302914/40623264-5770829c-627c-11e8-9250-68041e53f080.png)

**Imagem de não incluição**:
![image2](https://user-images.githubusercontent.com/32302914/40623607-266a6b48-627e-11e8-8110-8b068fb7c80a.png)

v**2.6.4**... ;-;

**Comment by noschang** [comment]
Oi @Mateus-Hirt. Obrigado por relatar o bug. Já confirmamos que ele ocorre e pretendemos corrigí-lo para a próxima versão.
