### ISSUE TITLE
Alias/atalhos de bibliotecas não geram erros se ficarem sozinhos

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#575]
![nenhum_erro](https://user-images.githubusercontent.com/32302914/40944023-9e4b44f6-6829-11e8-8696-b3fb833d9789.png)
Na imagem acima,`tx.`não gera erro se ficar sozinho no código, o que deveria ocorrer, já que acontece com expressões que não fazem sentido sozinhas no código, como esta.

**Comment by AlissonSteffens** [comment]
Duplicate of #113

**Comment by AlissonSteffens** [comment]
Duplicate of #314
