### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by renanmoraesz** [UNIVALI-LITE/Portugol-Studio#581]
**ao executar uma aplicação de exemplo, o programa buga aparecendo varias paginas em cima da outra**:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![aaaa](https://user-images.githubusercontent.com/40249699/41378597-e4e95318-6f35-11e8-9bac-ca9332447196.png)

**windows 10, 64 bits**:

**Comment by noschang** [comment]
Muito obrigado por relatar o erro @renanmoraesz. Este é um [problema já conhecido](https://github.com/UNIVALI-LITE/Portugol-Studio/issues/421) e que não sabemos como resolver ainda. 

Percebi pela imagem que você tem o Discord instalado. Recentemente eu tive problemas com alguns programas que travavam quando o Discord estava aberto.

Você poderia por favor testar se o erro ocorre quando o Discord está fechado?

**Comment by AlissonSteffens** [comment]
Duplicate of #421
