### ISSUE TITLE
Fechar com Command+Q no Mac não encerra corretamente

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#600]
**Descrição do Problema**:

Ao fechar o portugol utilizando "Commnado +Q" ele não fechar corretamente.
Isso pode gerar problemas caso arquivos recuperaveis estejam na pasta temp e a pasta temp apenas é deletada caso o portugol encerre corretamente

**Comment by elieserdejesus** [comment]
Para reproduzir o problema eu fiz os seguintes passos:
1 - abri um arquivo
2 - Alterei o arquivo (aparece o asterisco ao lado do nome na tab)
3 - Fechei o PS usando **Command + Q**

**Resultado**: O PS não pergunta se eu quero salvar os arquivos (isso acontece se eu fechar a janela) e quando abro o PS novamente aparece a mensagem de que tem um arquivo recuperado.

**Comment by elieserdejesus** [comment]
@AdsonEsteves , o fechamento da aplicação está acontecendo quando a janela é fechada:

https://github.com/UNIVALI-LITE/Portugol-Studio/blob/0aa9bb3c8e22e1f16a925f7a14f9fb19ab99d9bf/ide/src/main/java/br/univali/ps/ui/telas/TelaPrincipal.java#L140

Sugiro chamar o método **fecharAplicativo** em um listener da própria JVM (shutdown listener): 

[https://itsiastic.wordpress.com/2013/01/19/how-to-add-a-java-jvm-shutdown-close-exit-listener/ ](https://itsiastic.wordpress.com/2013/01/19/how-to-add-a-java-jvm-shutdown-close-exit-listener/ )
