### ISSUE TITLE
Chaves dentro de comentários interferem no programa 

### ISSUE THREAD

**Issue by RobsonAndraDev** [UNIVALI-LITE/Portugol-Studio#603]
**Descrição do Problema**:
Ao colocar uma chave dentro de qualquer tipo de comentário  ela não está sendo ignorada pelo programa

**Mensagem de Erro (se houver)**:

> Não são permitidas expressões fora do escopo do programa. Para corrigir o problema, remova o seguinte  trecho de código '}'

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/11702737/43494400-004bb44a-9509-11e8-9fc4-6ed2ba37a5cd.png)

**Especificações do sistema**:

> Ubuntu 18.04 x64
Portugol Studio Lite v2.6.9

**Comment by AdsonEsteves** [comment]
Duplicate of #314
