### ISSUE TITLE
Biblioteca Objetos buga com o tema Dark

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#609]
Estava vendo alguns arquivos relacionados a bibliotecas do Portugol, até que achei uma biblioteca que até então eu não conhecia, a biblioteca `Objetos`. Resolvi testar ela no Portugol.
Após ter executado uma vez o programa contendo a biblioteca e abrir uma nova aba, percebi um comportamento estranho do Portugol, como pode ver na imagem:

![Uma imagem](https://user-images.githubusercontent.com/32302914/43985418-b63dc3e8-9cdd-11e8-9ef9-fdffc86b6a02.png)

Eu sei que dificilmente um usuário vai fazer isso, mas resolvi relatar mesmo assim.
**OBS**: Por algum motivo, somente funciona com o tema Dark.

> v. 2.6.9, SO: Windows

**Comment by AdsonEsteves** [comment]
Pode postar o código que você usou pra testar?

**Comment by Mateus-Hirt** [comment]
@AdsonEsteves 
`programa`
`{`
`	inclua biblioteca Arquivos --> a`
`	inclua biblioteca Objetos --> o`
`	funcao inicio()`
`	{`
`		cadeia arquivos[] = {"|"}`
`		a.selecionar_arquivo(arquivos, falso)`
`		o.criar_objeto()`
`	}`
`}`

> 1. Execute o programa acima;
> 2. Feche a janela de erro;
> 3. Abra uma nova aba no Portugol;
> 4. Abra mais uma aba no Portugol;
> 5. Observe a aba bugada.

**Comment by AdsonEsteves** [comment]
@Mateus-Hirt 

Isso na verdade é um problema da biblioteca Arquivos.
O erro que você postou antes (#608) foi o que causou isso.
Esse erro será corrigido prana próxima versão.

A função `selecionar_arquivo` não aceita "|" como parâmetro pra extensão. Acredito que você tentou fazer com que a função aceitasse qualquer arquivo. Para isso faça um `cadeia arquivos[0]` e passe como parâmetro. Deve funcionar.

Estou unindo esta issue á #608
