### ISSUE TITLE
A tela fica se multiplicando sozinha

### ISSUE THREAD

**Issue by feliperiosbatera** [UNIVALI-LITE/Portugol-Studio#612]
**Descrição do Problema**: A tela fica se multiplicando sozinha ao executar o programa projetado.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**: Processador Pentium G4560, 12Gb RAM, Placa de Video GTX 1050TI, 1TB HD.

**Comment by Rafaelfcosta** [comment]
@feliperiosbatera 
Execute algumas das possíveis soluções descritas em (#421).
Não é certeza de que funcione, mas pode ajudar.
