### ISSUE TITLE
As funções escreva e leia poderiam ter destaque no tema Dark

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#616]
"As funções escreva e leia poderiam ter destaque no tema Dark"

**Comment by AdsonEsteves** [comment]
Você quer dizer que elas recebam destaque comparado ao resto do texto?

**Comment by Mateus-Hirt** [comment]
Exatamente isso, Adson.
Estas funções só recebem destaque com o tema Light, e com o Dark não ficam destacadas.

**Comment by AdsonEsteves** [comment]
Adicionado à opção de alterar as cores do Editor em f3d6984334caebd77bfa1b6383a0388bc347c10b
