### ISSUE TITLE
Portugol Studio 2.6.9 linux 32 _ Erro na Compilação

### ISSUE THREAD

**Issue by alexbksv** [UNIVALI-LITE/Portugol-Studio#625]
**Descrição do Problema**:
Apresenta erro na compilação ao executar o código

**Mensagem de Erro (se houver)**:
Error: missing 'client' JVM at '/usr/local/portugol-studio/java/java-linux/jre/lib/i386/client/libjvm.so'

**Captura de Tela / Arquivo.por**:
[Tela e Terminal](https://photos.app.goo.gl/VyjAfpgwxoAT3Lcn7)

**Especificações do sistema**:
LinuxMint 19 i386
Xubuntu 18.04 i386

**Comment by AdsonEsteves** [comment]
Duplicate of #515
