### ISSUE TITLE
Erro numero 25420add80cdf79f5ae43ee6fde89239029d8330 v2.6.9

### ISSUE THREAD

**Issue by GabrielGamer66** [UNIVALI-LITE/Portugol-Studio#633]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
@GabrielGamer66 

Pode dizer como ocorreu o erro e se consegue repetir ele
