### ISSUE TITLE
Ajustar imagens da ajuda para ficarem dentro do tema

### ISSUE THREAD

**Issue by AdsonEsteves** [UNIVALI-LITE/Portugol-Studio#635]
**Descrição do Problema**:
As imagens na ajuda ficam destoadas do tema por serem imagens de cor fixa, possivelmente alterar para código HTML CSS para se adequar ao tema

**Captura de Tela / Arquivo.por**:
![image](https://cdn.discordapp.com/attachments/316345900513492995/496390542997848075/unknown.png)

**Comment by AlissonSteffens** [comment]
Testei usar SVG e não parece uma boa opção para esse renderizador;

btw;

 UP
