### ISSUE TITLE
Divisão de Numero Real por zero.

### ISSUE THREAD

**Issue by vinycc** [UNIVALI-LITE/Portugol-Studio#638]
**Descrição do Problema**:

Ao realizar a divisão de variáveis ou numero inteiros por zero, apresenta erro em tempo de execução.
Com números reais apresenta Infinity, e NaN no caso da divisão 0.0/0.0

Este comportamento está correto?, ou também deveria apresentar erro em tempo de execução?

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
real a=2.0,b=0.0
		escreva(a/b)  //Infinity
		escreva(b/b)  //NaN

**Especificações do sistema**:

**Comment by noschang** [comment]
Oi @vinycc.

Este comportamento é normal e pode ser explicado matematicamente aqui:
https://pt.khanacademy.org/math/algebra/introduction-to-algebra/division-by-zero/v/why-dividing-by-zero-is-undefined

A única razão pela qual a divisão por inteiro gera uma exceção é porque ao contrário do real que pode armazenar números muito próximos do zero (ex. 0,0000000000001) o inteiro só pode armazenar o próprio zero e neste caso o resultado não se torna um número infinito, mas sim uma indeterminação conforme mencionado no vídeo.
