### ISSUE TITLE
Variável com nome 'null'

### ISSUE THREAD

**Issue by jetao** [UNIVALI-LITE/Portugol-Studio#639]
**Descrição do Problema**:
Se você define uma variável nomeada como "null" você recebe um erro na hora de compilação (provavelmente porque é uma palavra reservada do Java).
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![Erro](https://i.imgur.com/BJJU3ZY.png)

**Especificações do sistema**:
Windows 10 Education

**Comment by lribeiro2115** [comment]
escreva("\nEscreva o nome do convidado: ")
                    leia(nome)
                    para (i = 0; i < 100; i++) {
                       //como resolvo a linha de baixo???
                       se (lista[i] == "") {
                            lista[i] = nome
                            pare
                        }
                    }
