### ISSUE TITLE
Renderização da arvore ao abrir arquivo acontece mais de uma vez. (investigar)

### ISSUE THREAD

**Issue by fpelz** [UNIVALI-LITE/Portugol-Studio#64]

**Comment by AlissonSteffens** [comment]
@noschang Confirma?

**Comment by noschang** [comment]
Não lembro se já resolvemos isso!

**Comment by AlissonSteffens** [comment]
@rytix pode confirmar isso na nova versão?

**Comment by AlissonSteffens** [comment]
Recebidas explicações sobre o treta malévola

**Comment by AlissonSteffens** [comment]
Vou trabalhar em um meio de resolver isso via XML

**Comment by elieserdejesus** [comment]
@AdsonEsteves , acho essa issue foi resolvida com as últimas alterações. Podes verificar se a árvore ainda é gerada mais de uma vez quando um arquivo é aberto?

**Comment by AdsonEsteves** [comment]
verificarei

**Comment by AdsonEsteves** [comment]
Dei uma olhada, e não acontece 2 vezes durante a abertura de um arquivo.
Porém acontece 1 vez quando abre e 1 vez quando se fecha um arquivo.
Conversei com o Noschang, e acontece pois o código é modificado para um padrão, durante o fechamento de uma aba.
Decidimos que é normal e não afeta tanto.
o que acha @elieserdejesus ?

**Comment by elieserdejesus** [comment]
òtimo @AdsonEsteves , então acho que essa issue está resolvida. Esse comportamento que você descreveu é totalmente aceitável. 

Uma pequena otimização que poderia ser feita (baixa prioridade) é não gerar a árvore quando o programa for um programa vazio. O programa vazio é uma instância única que é retornada pela classe Programa, poderíamos comparar o programa atual com essa instância do programa vazio antes de gerar a árvore. Só gera a árvore se o programa NÃO for o programa vazio.

**Comment by AdsonEsteves** [comment]
Acredito que seja bem rápido fazer essa otimização, só preciso ver onde está a String do programa vazio e com isso, provavelmente consiga fazer a comparação no código.

**Comment by elieserdejesus** [comment]
@AdsonEsteves , acho que é melhor comparar a própria instancia da classe ProgramaVazio ao invés de comparar a String desse programa. Basta pegar a instância atual do programa e comparar com a instância única da classe ProgramaVazio.

**Comment by noschang** [comment]
@elieserdejesus e @AdsonEsteves. Quando a aba é fechada, o algoritmo da AbaCodigoFonte é setada para o padrão, que é o programa vazio, como vocês já mencioaram. Neste ponto, o Parser gera a árvore de novo, pois não faria sentido ter um código de programa vaizo no editor, mas exibir árvore do programa anterior.

No entanto, todo objeto da classe Programa, tem uma instância da sua própria árvore guardada em um atributo, a qual pode ser acessada chamando programa.getArvoreSintaticaAbstrata(). Sendo assim, uma solução é prevenir o reparsing, como vocês já comentaram, porém utilizar esta instância já existente da ASA para exibir no painel da direita.

Não sei se fui claro na minha explanação.

**Comment by elieserdejesus** [comment]
resolvida  a questão da geração da árvore quando a aba é fechada: https://github.com/UNIVALI-LITE/Portugol-Studio/commit/130cf822aeed05b9a707f9cea6eff8209b81bea6

**Comment by AlissonSteffens** [comment]
Este commit https://github.com/UNIVALI-LITE/Portugol-Studio/commit/130cf822aeed05b9a707f9cea6eff8209b81bea6 , gera o comportamento inesperado @AdsonEsteves

**Comment by AdsonEsteves** [comment]
desnecessário reabrir, sem certeza @AlissonSteffens
