### ISSUE TITLE
Erro Portugol Studio no Mac

### ISSUE THREAD

**Issue by bksrocks** [UNIVALI-LITE/Portugol-Studio#640]
**Descrição do Problema**:
Toda vez que inicio o PS no meu note o programa abre com todos os arquivos que já abri no computador desde que comecer a utilizá-lo. Mesmo eu tendo fechado e salvo os arquivos na ultima vez que utilizei o programa.

**Mensagem de Erro (se houver)**:
"Houve um problema no encerramento do Portugol.."

**Captura de Tela / Arquivo.por**:
![screen shot 2018-10-04 at 7 41 08 pm](https://user-images.githubusercontent.com/37941329/46507156-88cbfc80-c80d-11e8-92fa-e70062a79f75.png)

**Especificações do sistema**:
MacBook Air (13-inch, 2017)
1.8 GHz Intel Core i5
8 GB 1600 MHz DDR3

**Comment by noschang** [comment]
Oi @bksrocks. Este é um bug que já vimos ocorrer, mas não lembro agora se ele já foi corrigido, alguém da equipe deve saber.

Basicamente o erro ocorre pela forma que você fecha o Portugol Studio. Se você fechá-lo com Cmd+Q, ao abrir ele tentará recuperar os arquivos. Mas se você fechá-lo pelo "X" na perte superior direita da janela, então o erro não deve ocorrer.

Enquanto não temos a correção do bug, tente fazer desta forma e veja se funciona.

**Comment by AdsonEsteves** [comment]
Duplicate of #600
