### ISSUE TITLE
Incluir nomes dos colaboradores

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#65]
Incluir o nome do Roberto, da Paula, do Nereu, do Elieser e demais colaboradores do projeto na tela inicial do Portugol Studio.

**Comment by AlissonSteffens** [comment]
Ok, trabalharei nisso

**Comment by AlissonSteffens** [comment]
Feito 
![sobre](https://cloud.githubusercontent.com/assets/6234230/13119566/f864a262-d590-11e5-811a-0557031f12f2.jpg)
