### ISSUE TITLE
Problema de Instalar a partir do código fonte

### ISSUE THREAD

**Issue by edgabaldi** [UNIVALI-LITE/Portugol-Studio#66]
Vocês possuem algum tutorial de como instalar o portugol studio no ubuntu? Baixar o .run, dar permissão de execução e executa-lo não funciona.

Como rodar ele a partir do código fonte?

**Comment by noschang** [comment]
Bom dia Edgar!

Em primeiro lugar queremos agradecer pelo interesse no Portugol Studio.
Esperamos que ele possa estar lhe auxiliando no seu aprendizado e/ou ensino.

Iremos lhe ajudar no que for preciso para que consigas instalar e executar o Portugol Studio.

Primeiro, precisamos que você nos envie algumas informações sobre seu sistema operacional para que possamos lhe dar um atendimento mais direcionado.

Por favor, instale e execute um dos seguintes softwares no seu sistema:

hwinfo - Digite no terminal: sudo apt-get install hwinfo
hardinfo - Digite no terminal: sudo apt-get install hardinfo

![figura1](https://cloud.githubusercontent.com/assets/709553/13047223/b7c613bc-d3c4-11e5-93c4-f999d2ea5d4b.png)

Ambos são o mesmo software, mas dependendo da sua versão do Ubuntu ele pode estar com nomes diferentes. Tente o "hwinfo" primeiro, se o Ubuntu não encontrar o software no repositório, tente instalar o "hardinfo".

Após instalar o software e executá-lo, será exibida uma tela com vários itens informativos sobre seu sistema operacional. Nesta tela, selecione a opção "Generate report", localizada na barra de ferramentas no topo da tela.

![figura2](https://cloud.githubusercontent.com/assets/709553/13047234/c17fb8e0-d3c4-11e5-9365-2363e76136c7.png)

Uma nova tela será aberta. Selecione as opções "Computer", "Devices" e desmarque as demais opções. Clique em "Generate report".

![figura3](https://cloud.githubusercontent.com/assets/709553/13047237/c598a612-d3c4-11e5-83d4-69151a10232e.png)

Selecione um local para salvar o relatório. Após o salvamento, verifique se o relatório foi gerado corretamente. Navegue até o diretório e clique com o botão direito do mouse sobre o arquivo. Selecione a opção "Abrir com" e escolha o seu navegador preferido.

O relatório gerado será exibido. Visualize o relatório e verifique que ele não possui nenhuma informação pessoal, apenas dados referentes ao seu hardware e sistema operacional.

![figura4](https://cloud.githubusercontent.com/assets/709553/13047241/c9dbd41a-d3c4-11e5-84d6-03d485313ea7.png)

Novamente, clique com o botão direito do mouse sobre o arquivo e selecione a opção "Comprimir". Arquive o relatório em formato "ZIP" e nos envie repondendo a este comentário ou enviando diretamente para o email "noschang@univali.br".

Com estas informações em mãos, iremos verificar a causa do problema e lhe retornaremos o mais breve possível com uma solução.

Atenciosamente, a equipe do Portugol Studio

**Comment by AlissonSteffens** [comment]
@edgabaldi de fato existia um problema no builder do **Portugol Studio**, este problema já foi resolvido e agora você pode compilá-lo facilmente. Caso alguma dúvida ainda permaneça, favor entrar em contato.
