### ISSUE TITLE
Múltiplas abas de arquivos recuperados aparecem sempre que abro o Portugol Studio

### ISSUE THREAD

**Issue by alyppyo** [UNIVALI-LITE/Portugol-Studio#660]
**Descrição do Problema**: Sempre que abro o Portugol Studio, ele abre várias janelas de recuperação de arquivos indicando que o programa não foi encerrado corretamente. Entretanto, não só o programa foi encerrado normalmente como os arquivos são todos antigos, elaborados vários dias antes.

**Mensagem de Erro (se houver)**: "Ouve algum problema no encerramento do Portugol, mas temos arquivos recuperados". A propósito, na mensagem deveria ser "Houve" ao invés de "Ouve".

**Captura de Tela / Arquivo.por**:
![ps erro](https://user-images.githubusercontent.com/561215/48306765-bf3c1c00-e51d-11e8-9fce-f588161d83ab.png)

**Especificações do sistema**: Windows 10, Portugol Studio v2.7.0

**Comment by AdsonEsteves** [comment]
@alyppyo 
Isso acontecia na versão anterior?

Vá na pasta C:\Users\[NomeDoSeuUsuário]\.portugol
Veja se tem uma pasta chamada temp lá e apague ela
Abra o portugol, abra algum código e depois feche o portugol
Abra o portugol novamente e veja se continua o erro.

Se acontecer denovo, feche o portugol e mande aqui o ps-log.txt existente na pasta .portugol

**Comment by alyppyo** [comment]
@AdsonEsteves 
Isso não acontecia na versão 2.6. Entretanto, desde que atualizei para a nova versão isso vinha acontecendo em todas as vezes que iniciei o programa.

Verifiquei a pasta que você indicou e não havia uma pasta temp. Entretanto, havia um arquivo de configuração denominado arquivos_recentes.txt. Abri o arquivo e os nomes listados lá eram exatamente os que apareciam para mim. Apaguei o conteúdo do arquivo e o problema parou de acontecer.

A propósito, vi a pasta temp aparecer enquanto o Portugol Studio estava aberto. Entretanto, ela foi apagada devidamente alguns segundos após ele se encerrar.

Obrigado pela resposta rápida! Vou até aproveitar e abrir um novo issue sobre outro problema que venho enfrentando desde a versão 2.6. Até mais!

**Comment by AdsonEsteves** [comment]
@alyppyo 
Se resolveu então ótimo, mas não deveria ser por causa do arquivos_recentes.txt

Esse txt, apenas grava os ultimos arquivos que você abriu para aparecer na tela inicial. (Os arquivos recentes abaixo da logo)

O que causa os arquivos recuperaveis são arquivos que ficam dentro da pasta temp, que é criada na inicialização do portugol e removida na finalização correta (como você mesmo viu).
Caso o portugol não feche corretamente, o temp não é removido e quando o portugol abre novamente ele acusará isso (causando a abertura dos arquivos como você viu).

Talvez alguma coisa da 2.6 pra 2.7, impediu o temp de ser removido, não sei, mas se voltou a funcionar, então ótimo.
