### ISSUE TITLE
Problema na versão 2.7.0 para OSX (identificado no Escolha-caso)

### ISSUE THREAD

**Issue by brunoharnik** [UNIVALI-LITE/Portugol-Studio#663]
**Descrição do Problema**:
Não dá run no algoritmo da própria biblioteca.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/13284680/48446760-41784a80-e781-11e8-89b9-c057218c100f.png)

**Especificações do sistema**:
Mac OS X Mojave 10.14.1

**Comment by AdsonEsteves** [comment]
Duplicate of #657
