### ISSUE TITLE
Incluir o Logo do Lite no Splash Screen

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#67]
É necessário incluir o logo do LITE no splash screen do Portugol para referenciar o nosso laboratório.

Veja também se não há a possibilidade de bota-lo do lado do logo da Univali na tela inicial do Portugol.

Responsáveis:
@AlissonSteffens 
@ Adson

**Comment by noschang** [comment]
Resolvi assim, assim assado!

**Comment by rytix** [comment]
Como é impossível remover um issue.
Este será editado como uma nova tarefa.

**Comment by AlissonSteffens** [comment]
Feito
![done](https://cloud.githubusercontent.com/assets/6234230/13085576/12d3176c-d4c6-11e5-86b6-71b1d5496611.png)
