### ISSUE TITLE
Matrizes não aceitam contas matemáticas

### ISSUE THREAD

**Issue by Mateus-Hirt** [UNIVALI-LITE/Portugol-Studio#672]
**Descrição do Problema**:
Matrizes geram um erro quando são iniciadas com expressões matemáticas.

**Captura de Tela / Arquivo.por**:
![Captura de tela](https://user-images.githubusercontent.com/32302914/52748025-8607c200-2fcc-11e9-9323-48e3a4445e1b.png)

**v. 2.6.9**

**Comment by noschang** [comment]
Oi @Mateus-Hirt. Obrigado por reportar o erro. Vamos investigar e solucionar assim que possível. Enquanto isso, a solução é realizar as operações antes de inicializar a matriz e depois passar o valor:

```java
programa
{
	
	funcao inicio()
	{
		inteiro x = 10 + 1 // Realizando a expressão
		inteiro matriz[2][2] = {{x, 0}, {0, 0}}
	}
}
```
