### ISSUE TITLE
Erro sintático não interpretado

### ISSUE THREAD

**Issue by jeanklann** [UNIVALI-LITE/Portugol-Studio#673]
**Descrição do Problema**:
Um aluno meu encontrou um "Problema muito louco". Foi ver o código e vi que na instrução "para" dele não havia uma inicialização de uma variável, e sim uma comparação.
Poderia tratar este tipo de erro no portugol já, e não estourar na compilação do java fazendo com que o aluno demore muio para encontrar o erro.

**Mensagem de Erro (se houver)**:
java:29: error: not a statement
for(a == 0; a <= 10; a = a + 1)
^
1 error

**Captura de Tela / Arquivo.por**:
inteiro a = 0
para(a==0;a<=10;a++){
	escreva("erro")
}

**Especificações do sistema**:
Versão 2.7.0

**Comment by noschang** [comment]
Oi @jeanklann. Obrigado por repostar esse erre. Vamos investigar e assim que possível solucioná-lo. Em uma futura versão ele deverá estar corrigido, portanto fique atento às atualizações que serão lançadas.

Aproveitando a oportunidade, gostaria que você comentasse aqui um pouco mais sobre você. Em qual instituição você trabalha, quais disciplinas leciona, quantos alunos tem. Essas informações são úteis para compreendermos melhor o público que utiliza a ferramenta e assim tomar melhor as decisões de como podemos aperfeiçoá-la.

Se você quiser, é claro!!

**Comment by jeanklann** [comment]
Boa tarde. Dou aula na Cetelbras em Blumenau. Tenho 2 turmas atualmente (começaram em bem mais alunos) com 4 alunos. Ambas as turmas são de Desenvolvimento de jogos, ensino o básico de programação no portugol Studio e depois leciono no unity.

**Comment by noschang** [comment]
Oi @jeanklann. Muito obrigado pelas informações. Ficamos felizes em saber que o Portugol Studio está sendo útil.

Eu sou apaixonado por desenvolvimento de jogos e já mexi com Unity. Acho uma ferramenta bem bacana pra quem quer começar no segmento, pois simplifica muitas coisas. Parabéns pelo trabalho ensinando essa galerinha a programar!!
