### ISSUE TITLE
Problema com a quantidade de memória RAM

### ISSUE THREAD

**Issue by jpmouracodex** [UNIVALI-LITE/Portugol-Studio#674]
**Descrição do Problema**:
   

 Após algum momento o programa para e exibe uma mensagem de erro.
**Mensagem de Erro (se houver)**:
    "Ocorreu um erro durante a execução do programa: O programa atingiu a quantidade máxima de memória RAM permitida.
Verifique se o programa não está utilizando muitos recursos (imagens, sons, etc) e se estes recursos não são muito grandes.
Linha: 38, Coluna: 5"
**Captura de Tela / Arquivo.por**:
```
programa
{
	inclua biblioteca Graficos --> g
	inclua biblioteca Util --> u
	
     const inteiro TELAx = 1000
     const inteiro TELAy = 700
	const inteiro TOPO_TELA = 0
	const inteiro ESQ_TELA = 0
     const cadeia LOCAL_DVD[7] = {"DVD_IMAGEM1.png", "DVD_IMAGEM2.png", "DVD_IMAGEM3.png", "DVD_IMAGEM4.png", "DVD_IMAGEM5.png", "DVD_IMAGEM6.png", "DVD_IMAGEM7.png"}

     inteiro INF_TELA = TELAy
	inteiro dvd_x = TELAx/2, dvd_y = TELAy/2
	inteiro DIR_TELA = TELAx 
	
	funcao vazio desenhar(inteiro endereco){
		g.limpar()
		g.desenhar_imagem(dvd_x, dvd_y, endereco)
		g.renderizar()
	}

	
	funcao inicio(){
		
		g.iniciar_modo_grafico(verdadeiro)
		g.definir_dimensoes_janela(TELAx, TELAy)
		inteiro dvd
		inteiro sentido_x = -1
          inteiro sentido_y = -1
          dvd = g.redimensionar_imagem(g.carregar_imagem(LOCAL_DVD[u.sorteia(0, 6)]), 200, 0, falso)
 		g.transformar_imagem(dvd, falso, falso,0, g.criar_cor(255, 0, 255) )
          
		enquanto(verdadeiro){
			desenhar(dvd)
			se (dvd_x == ESQ_TELA ou dvd_x + g.largura_imagem(dvd) == DIR_TELA){
				sentido_x *= -1 
				g.liberar_imagem(dvd)
				dvd = g.redimensionar_imagem(g.carregar_imagem(LOCAL_DVD[u.sorteia(0, 6)]), 200, 0, falso)
				g.transformar_imagem(dvd, falso, falso,0, g.criar_cor(255, 0, 255) )
			}
			se (dvd_y == TOPO_TELA ou dvd_y + g.altura_imagem(dvd) == INF_TELA){
				sentido_y *= -1
				g.liberar_imagem(dvd)
				dvd = g.redimensionar_imagem(g.carregar_imagem(LOCAL_DVD[u.sorteia(0, 6)]), 200, 0, falso)
				g.transformar_imagem(dvd, falso, falso,0, g.criar_cor(255, 0, 255) )
			}
			
			
			dvd_x += sentido_x
			dvd_y += sentido_y
			u.aguarde(2)
		}
		g.encerrar_modo_grafico()
	}	
}
```
**Especificações do sistema**:
Windows 10 
Intel core i3 sétima geração
4 GB de RAM
1 TB de HD

**Comment by noschang** [comment]
Oi @jpmouracodex. Por favor, anexe aqui no Github as imagens que você está usando no seu programa

**Comment by jpmouracodex** [comment]
![dvd_imagem1](https://user-images.githubusercontent.com/47841392/53240805-7f3d1700-367e-11e9-8fad-4da31ae84c24.png)
![dvd_imagem2](https://user-images.githubusercontent.com/47841392/53240806-7f3d1700-367e-11e9-96fa-6b2c10e85d02.png)
![dvd_imagem3](https://user-images.githubusercontent.com/47841392/53240807-7fd5ad80-367e-11e9-92f0-de68b22d7247.png)
![dvd_imagem4](https://user-images.githubusercontent.com/47841392/53240808-806e4400-367e-11e9-8ad6-fb72b57a0b03.png)
![dvd_imagem5](https://user-images.githubusercontent.com/47841392/53240810-806e4400-367e-11e9-95f0-50b10f5ae744.png)
![dvd_imagem6](https://user-images.githubusercontent.com/47841392/53240811-806e4400-367e-11e9-9518-2edbaf3c1a76.png)
![dvd_imagem7](https://user-images.githubusercontent.com/47841392/53240813-8106da80-367e-11e9-95a0-1252060a6b0b.png)
![enem-2019-organograma-de-estudos](https://user-images.githubusercontent.com/47841392/53240814-8106da80-367e-11e9-86d7-40e44e1926fd.jpg)

**Comment by noschang** [comment]
Oi @jpmouracodex. O seu código tinha alguns problemas:

Primeir, você estava carregando, redimensionando e transformando as imagens o tempo todo, em cada iteração do laço de repetição. Estas operações são pesadas e consomem bastante memória e não devem ser feitas em um laço de repetição. Na verdade, nem é necessário, basta voc6e fazer estas operações uma única vez no início do programa e depois você pode só reutilizar as imagens já prontas

O segundo problema é que, você estava liberando uma parte da memória, mas outra não. A chamada pra função ```g.transformar_imagem()``` estava sendo feita, mas você não estava atribuindo o resultado em nenhuma variável. Desta forma, a imagem criada com esta função nunca era liberada, causando o problema que você descreveu

Estou anexando uma versão do código modificada, que resolve estes problemas. Eu fiz bastante comentários pra você entender o que foi feito e como está funcionando. Também estou enviando um arquivo "bônus" (prog2.por) que tem uma função especial pra resolver um outro probleminha do seu código ;-)

[Você pode baixar essa nova versão clicando aqui](https://github.com/UNIVALI-LITE/Portugol-Studio/files/2894180/dvd.zip)

**Comment by jpmouracodex** [comment]
Muito obrigado, amei a linguagem de vocês, e agradeço imensamente a
atenção. Espero que continuem o projeto, e adicionem a criação de tipos de
dados como o "struct" em C.

Em sex, 22 de fev de 2019 10:19, Luiz Fernando Noschang <
notifications@github.com> escreveu:
