### ISSUE TITLE
Portugol não está abrindo 

### ISSUE THREAD

**Issue by BrotherPlayerBR** [UNIVALI-LITE/Portugol-Studio#675]
**Descrição do Problema**: Erro na iniciação do Portugol

**Mensagem de Erro (se houver)**: Error occurred during initialization of VM. Could not reserve enough space for 2048000KB object heap

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/43423458/53212793-23926f80-3625-11e9-9ade-daa2489df97d.png)

**Especificações do sistema**: Processador: Amd e-350
Ram: 4GB
HD: 500GB

**Comment by noschang** [comment]
Oi @BrotherPlayerBR. Por favor, acesse a pasta `C:\ProgramData\UNIVALI\Portugol Studio` e anexe aqui no Github os seguintes arquivos:

`executar-studio-windows.bat`
`executar-console-windows.bat`

Pra acessar a pasta você deve abrir o Windows Explorer e colar o caminho ba barra navegação. Se você tentar navegar até a pasta não vai encontrá-la porque ela fica oculta no computador.

Caso o endereço acima não funcione, tente trocar por `C:\ProgramData\Portugol Studio`, pois dependendo da versão do Portugol Studio ele instala em locais diferentes.

Se tiver algum dúvida ou dificuldade comente nesta issue.
Aguardamos seu retorno

**Comment by BrotherPlayerBR** [comment]
como eu faço para anexar os arquivos?

**Comment by noschang** [comment]
É só arrastar os arquivos pra essa caixa de texto

**Comment by BrotherPlayerBR** [comment]
os arquivos presentes nesta pasta são:
portugol-studio.jar
portugol-console.jar

**Comment by noschang** [comment]
@BrotherPlayerBR. Poderia tirar um print da sua tela pra que eu possa ver quais arquivos estão na pasta? Assim posso identificar a versão do Portugol Studio e lhe orientar melhor

**Comment by BrotherPlayerBR** [comment]
![image](https://user-images.githubusercontent.com/43423458/53260515-6fd6c180-36b0-11e9-9781-162dabf2b7ec.png)
![image](https://user-images.githubusercontent.com/43423458/53260534-77966600-36b0-11e9-8e14-9dce4716c46c.png)

**Comment by noschang** [comment]
OK. @BrotherPlayerBR. Por favor verifique se o ícone do Portugol Studio está aparecendo na sua Área de Trabalho. Se estiver, clique com o botão direito no ícone e acesse a opção `Propriedades`. Depois, procure por um campo que tenha um comando similar a este:

`"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -jar -server -Dvisualvm.display.name=Portugol-Studio -Xms32m -Xmx256m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled aplicacao\portugol-studio.jar "%1"`

Copie este comando e cole aqui pra eu analisar, por favor

**Comment by BrotherPlayerBR** [comment]
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -server -jar -Xms32m -Xmx256m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled "C:\ProgramData\UNIVALI\Portugol Studio\aplicacao\portugol-studio.

**Comment by BrotherPlayerBR** [comment]
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\javaw.exe" -server -jar -Xms32m -Xmx256m -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled "C:\ProgramData\UNIVALI\Portugol Studio\aplicacao\portugol-studio.

**Comment by noschang** [comment]
@BrotherPlayerBR. Verifiquei o comando e está tudo correto. Porém na imagem inicial que você mandou, um dos parâmetros está diferente

Como você está iniciando o Portugol Studio?  Através do ícone na área de trabalho ou de outra forma?

**Comment by BrotherPlayerBR** [comment]
estou iniciando pelo arquivo portugol-studio.jar pois o portugol não está abrindo pela área de trabalho

**Comment by noschang** [comment]
Oi @BrotherPlayerBR. Acredito que este seja o problema então

Por gentileza, baixe o arquivo `executar-studio-windows.zip` que estou anexando [aqui](https://github.com/UNIVALI-LITE/Portugol-Studio/files/2895752/executar-studio-windows.zip). Depois extraia ele e coloque o arquivo `executar-studio-windows.bat` dentro da pasta do Portugol Studio: `C:\ProgramData\UNIVALI\Portugol Studio`

Feito isso, sempre que você quiser abrir o Portugol Studio, dê dois cliques nesse arquivo.
Me avise se funcionar pra eu poder fechar esta issue. OK?

**Comment by BrotherPlayerBR** [comment]
nao funcionou

**Comment by BrotherPlayerBR** [comment]
Não funcionou

Em sex, 22 de fev de 2019 17:51, Luiz Fernando Noschang <
notifications@github.com> escreveu:

**Comment by noschang** [comment]
Bom dia @BrotherPlayerBR. Poderia por favor anexar aqui um print com o erro que está dando ao tentar executar pelo arquivo que te enviei?

**Comment by noschang** [comment]
@AdsonEsteves. O @BrotherPlayerBR não respondeu faz 27 dias. Vou assumir que ele conseguiu resolver o problema. Estou fechando a issue, qualquer coisa se precisar reabrimos
