### ISSUE TITLE
Erro a executar programas

### ISSUE THREAD

**Issue by jmapsimoes** [UNIVALI-LITE/Portugol-Studio#676]
**Descrição do Problema**: Erro a executar programas (que funcionavam na versão anterior)

**Mensagem de Erro (se houver)**:
Erro na compilação!

**Captura de Tela / Arquivo.por**:
![captura de ecra 2019-02-28 as 09 59 53](https://user-images.githubusercontent.com/9195015/53558399-de4bd180-3b3f-11e9-87ac-15cab2febd68.png)

**Especificações do sistema**: MAC OS High Sierra 10.13.6, Portugol Studio 2.7.1

**Comment by noschang** [comment]
Bom dia @jmapsimoes poderia por favor anexar aqui o algortimo em Portugol pra que nós possamos analisar?

**Comment by jmapsimoes** [comment]
Bom dia,
Obrigado pela resposta rápida.
O problema acontece com qualquer programa. Os programas que funcionavam na versão que tinha anteriormente e também funcionam no Web Studio, deixaram de funcionar na versão que instalei agora.
Envio em anexo um exemplo.
Obrigado,
Jorge

**Comment by noschang** [comment]
Oi @jmapsimoes. Acho que você esqueceu de anexar o arquivo, pois não está aparecendo pra mim

**Comment by jmapsimoes** [comment]
Eu anexei o ficheiro. De qualquer forma, o conteúdo é este:

**************
programa {
	funcao inicio() {
		inteiro x
		leia( x )
		enquanto( x != 0)
		{
		    escreva( x, "\n" )
		    leia( x )
		}
	}
}
****************

**Comment by AdsonEsteves** [comment]
@jmapsimoes 

Tente desinstalar o Portugol Studio e instala-lo novamente.

**Comment by AdsonEsteves** [comment]
Duplicate of #657

**Comment by jmapsimoes** [comment]
Ficou resolvido.
Obrigado

**Comment by noschang** [comment]
Obrigado pelo auxílio @AdsonEsteves
