### ISSUE TITLE
Retorno de vetores

### ISSUE THREAD

**Issue by lslv1243** [UNIVALI-LITE/Portugol-Studio#677]
O Portugol está permitindo definir o retorno de uma função como vetor de um tipo, porém percebi alguns problemas ao tentar utilizar essa funcionalidade. Primeiramente a sintaxe, não é necessário definir o tamanho do vetor, sendo que ao declarar uma variável é. Dentro da função é possível retornar um vetor, porém não é possível utilizar o valor retornado, como na imagem abaixo:

![whatsapp image 2019-03-01 at 18 24 23](https://user-images.githubusercontent.com/23214418/53670487-acc72900-3c59-11e9-9133-f595016781f6.jpeg)

Gostaria de saber é possível retornar vetores ou é apenas um bug ele deixar definir o retorno e retornar o valor.

Estou rodando no MacOS 10.14.3, Portugol Studio v2.6.9

**Comment by AdsonEsteves** [comment]
fixed on 49103fbd9e8e7664ffe385c84932f12a13ef2dd5
