### ISSUE TITLE
Documentar a biblioteca teclado e mouse

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#68]
Documentar que a biblioteca teclado e mouse não funcionam no console, apenas no modo gráfico.

Responsáveis:
@AlissonSteffens 
@ Adson

**Comment by AlissonSteffens** [comment]
Já está documentado
![image](https://cloud.githubusercontent.com/assets/6234230/13328156/f252bb34-dbcb-11e5-875c-6e15348d0014.png)

**Comment by noschang** [comment]
OK! Só adicionem na descrição que ela não pode ser usada no console, pra isso ficar bem explícito. 

Por exemplo: IMPORTANTE: Esta biblioteca não funciona no console de entrada e saída de dados do Portugol Studio, ela só funciona com a biblioteca Graficos, se o modo gráfico estiver iniciado

**Comment by noschang** [comment]
Façam o mesmo para a biblioteca teclado.

**Comment by AlissonSteffens** [comment]
Feito
![image](https://cloud.githubusercontent.com/assets/6234230/13359951/6c98a9de-dc95-11e5-975f-8d66adbfc5a4.png)
