### ISSUE TITLE
Ctrl+espaço  com estruturas padrões

### ISSUE THREAD

**Issue by eltonricelli** [UNIVALI-LITE/Portugol-Studio#681]
**Descrição do Problema**:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by eltonricelli** [comment]
Bom dia.
Utilizo a versão 2.7.1 do Portugol Studio e o mesmo não está exibindo os modelos ao pressionar "Ctrl+Espaço". Por exemplo: Gostaria que já fosse criada a estrutura padrão do laço de repetição PARA, pressiono ctrl+espaço, até aparece um pop-up menu, mas ao digitar o comando "para" ele some.

Desde já, grato.

Elton Ricelli.

**Comment by AdsonEsteves** [comment]
@eltonricelli 
O Auto-complete do Portugol foi colocado recentemente nele, portanto ainda não temos estruturas padrões nele apenas as variáveis e funções disponíveis do código.
Mas vamos colocar isso como adições futuras
Obrigado!

**Comment by eltonricelli** [comment]
Boa tarde.

Desculpe-me... pensei que já havia este recurso, pois vi um vídeo do
Portugol 2.0 que auto completava com a utilização do "ctrl+espaço".

Muito obrigado pelo pronto atendimento.

Att.


         ELTON RICELLI FERREIRA DE REZENDE
           http://lattes.cnpq.br/9102409359799540
                   br.linkedin.com/in/eltonricelli
_____________________________________________________________________________
*Antes de imprimir pense na responsabilidade com o meio ambiente. / *Use
material reciclável.


Em seg, 11 de mar de 2019 às 17:41, Adsu <notifications@github.com>
escreveu:

**Comment by AdsonEsteves** [comment]
Havia antigamente, porém devido a muitos problemas causados por ele, foi desativado em algumas versões, sendo só recentemente adicionado novamente.
