### ISSUE TITLE
Bug do número inteiro

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#69]
Existe um bug envolvendo o número inteiro.
Peço para que alguém edite este issue relatando um pouco mais sobre o que está acontecendo.

**Comment by AlissonSteffens** [comment]
Bug Resolvido

![erro resolvido](https://cloud.githubusercontent.com/assets/6234230/13083211/24a8412a-d4bb-11e5-83b9-5d4859873688.jpg)
