### ISSUE TITLE
Travamentos momentâneos na interface

### ISSUE THREAD

**Issue by erickweil** [UNIVALI-LITE/Portugol-Studio#709]
**Descrição do Problema**:
Este problema foi identificado assim que instalei a nova versão 2.7.3 ( atualizei o java e instalei novamente porem não resolveu o problema. ). Em versões anteriores não existia este problema.

Conforme se utiliza o portugol, a cada 7 ou 8 segundos a interface inteira trava por 1 segundo inteiro. Basicamente tornando terrível a experiência de se escrever um código, pois apenas após destravar que o texto é escrito, a janela aberta, etc...

Este travamento momentâneo afeta todas a interface, janelas e abas do portugol, edição de código, ajuda, inclusive a execução do código no console fica travada, onde que ao ser executado o exemplo de animação da lagarta, trava por um momento no meio da animação.

Não foi possível observar travamento algum nas janelas utilizadas pela biblioteca graficos. onde que todos os jogos e exemplos que utilizam graficos funcionam perfeitamente sem travamento algum, aparentemente o travamento afeta apenas a interface do portugol studio.

**Especificações do sistema**:
Portugol studio versão 2.7.3
PC Desktop, intel core i3, 8gb RAM. java 1.8.0_221,

**Comment by AdsonEsteves** [comment]
@erickweil 
Obrigado pelo reporte, estamos vendo os possíveis problemas
Se estiver incomodando muito, sugiro baixar a versão anterior por hora:
https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.7.2/portugol-studio-2.7.2-windows.exe
