### ISSUE TITLE
Baixa precisão em operações simples

### ISSUE THREAD

**Issue by henmenck** [UNIVALI-LITE/Portugol-Studio#717]
**Descrição do Problema**:
Baixa precisão em operações simples. Problema acontece quando o subtraendo é real e próximo do minuendo. Também acontece em algumas multiplicações.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![captura](https://user-images.githubusercontent.com/53951314/62801280-c8154a80-babb-11e9-89d3-2749d291192f.png)

**Especificações do sistema**:
Windows 7 Professional x64, i3-7100, 4GB RAM
v2.7.4

**Comment by ArthurAssuncao** [comment]
O problema é do Java, na verdade do tipo Double do Java, na verdade mesmo é da forma como o tipo é armazenado que em binário não fica perfeito, assim caso o programa queira ter uma precisão perfeita deveria mudar o tipo para BigDecimal, mas pode ter um impacto na IDE/linguagem como um todo.
Caso queira testar, jogue os mesmos valores no Java.

**Comment by Guialpoim** [comment]
e como resolve no portugol?

**Comment by ArthurAssuncao** [comment]
Creio que só se alterarem no código-fonte do Portugol Studio para utilizar o BigDecimal, então só esperando eles verificarem e decidirem pela alteração.

**Comment by Guialpoim** [comment]
Não entendi, simplifica por favor.

**Comment by AdsonEsteves** [comment]
Duplicate of #448

**Comment by AdsonEsteves** [comment]
Você pode resolver utilizando a biblioteca de arredondamento.

```
programa
{
	inclua biblioteca Matematica --> mat
	
	funcao inicio()
	{
		real numero = 1.25673245
		real arredondamento

		// Arredonda o número para 3 casas decimais, isto é,
		// 3 casas depois da vírgula
		arredondamento = mat.arredondar(numero, 3)
		escreva("O número com 3 casas decimais é: ", arredondamento, "\n")
		

		// Arredonda o número para 2 casas decimais, isto é,
		// 2 casas depois da vírgula
		arredondamento = mat.arredondar(numero, 2)
		escreva("O número com 2 casas decimais é: ", arredondamento, "\n")
		

		// Arredonda o número para 1 casa decimal, isto é,
		// 1 casa depois da vírgula
		arredondamento = mat.arredondar(numero, 1)
		escreva("O número com 1 casa decimal é: ", arredondamento, "\n")

		// Arredonda o número removendo todas as casas decimais
		arredondamento = mat.arredondar(numero, 0)
		escreva("O número sem casas decimais é: ", arredondamento, "\n")
	}
}

```

**Comment by Guialpoim** [comment]
Obrigado! Onde estão todos os comandos das bibliotecas?

Em seg, 27 de jan de 2020 17:00, Adsu <notifications@github.com> escreveu:

**Comment by AdsonEsteves** [comment]
@Guialpoim 
Estão na aba "Ajuda"
O ponto de interrogação da aba inicial e na aba de código.

**Comment by herbyDev** [comment]
valeu pela dica.
