### ISSUE TITLE
Método leia faz leituras indevidas.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#72]
Duplicata do Issue no Núcleo: UNIVALI-LITE/Portugol-Nucleo#56

**Comment by rytix** [comment]
Foi descoberto que ele não existe restrição para a leitura, o método se comporta como uma função normal.
![image](https://cloud.githubusercontent.com/assets/7809511/13474250/e97b7db4-e09b-11e5-8c7f-9275c3142e2a.png)

**Comment by noschang** [comment]
Acredito que seja uma duplicata da issue https://github.com/UNIVALI-LITE/Portugol-Nucleo/issues/56 do Portugol-Nucleo.

Devemos fechar uma das issues e manter só a outra. Como é um bug no núcleo, acredito que seja melhor fechar esta do Portugol-Studio.

@rytix, você pode fazer isso pra gente, mas antes de fechar esta issue aqui, copie os textos e as imagens que você colocou aqui lá pra issue do núcleo. Obrigado!

**Comment by rytix** [comment]
Issue repetida.

**Comment by rytix** [comment]
Por algum motivo, todas as correções feitas no pull request não estão mais validas.
É como se a verificação criada tivesse parado de funcionar completamente.

**Comment by AlissonSteffens** [comment]
Este erro é referente ao núcleo e está sendo resolvido [aqui](https://github.com/UNIVALI-LITE/Portugol-Nucleo/pull/96)
