### ISSUE TITLE
Declaração de arrays com operadores aritméticos.

### ISSUE THREAD

**Issue by Logikoz** [UNIVALI-LITE/Portugol-Studio#722]
**Descrição do Problema**: nao é possivel atribuir o tamanho do array com algum operador aritmético, ex: inteiro teste[CONSTANTE_INTEIRA_QUALQUER * 2]

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**: 
![image](https://user-images.githubusercontent.com/37851168/64929771-e9bacd80-d7ef-11e9-8645-fbc3bd89625b.png)

**Especificações do sistema**:

**Comment by Logikoz** [comment]
Em demais linguagens isso é possível, já que eu estou usando o operador com uma constante.

**Comment by Rosiberto** [comment]
Logikoz,
Você pode usar assim:
const inteiro numBotoes = 4
inteiro botoes[numBotoes][2]

E dentro de inicio, por exemplo, fazer: botoes[numBotoes*2][2]

Não dará erro de sintaxe e terás o resultado que queres.

**Comment by Logikoz** [comment]
nao tem o minimo sentido oq vc falou @Rosiberto

**Comment by Logikoz** [comment]
não ha como alterar o tamanho da matriz ou de um vetor depois da inicialização.

**Comment by Rosiberto** [comment]
@Logikoz se você está tentando alterar tamanho, de fato, não dá. Mas pela sua pergunta, você estava querendo usar operador aritmético e isso é possível com o exemplo que passei. Eu não me referi a aumentar tamanho se foi isso que você entendeu e sim, de utilizar operador aritmético. Até mesmo porque o vetor/matriz já teriam suas dimensões já definidas. Talvez da forma que escrevi não ficou claro para você, da mesma forma que sua pergunta, considerando seu questionamento.  Entendo agora que você quer é definir é o tamanho.

**Comment by Logikoz** [comment]
sim, é o tamanho da matriz com operadores aritméticos, acho que o Portugol Studio deveria dar suporte para isso.
