### ISSUE TITLE
Suporte para Criação de Registros

### ISSUE THREAD

**Issue by Rosiberto** [UNIVALI-LITE/Portugol-Studio#723]
**Descrição do Problema**:

Em muitos casos é necessário trabalhar com um conjunto de dados de tipos distintos. Por exemplo: armazenar na memória os dados de um livro. Precisaremos armazenar o nome do livro (uma cadeia), o preço (um valor real) e o número de páginas (um inteiro) e etc. 

Usar variáveis individuais, vetores e/ou matrizes é inviável. Dessa forma, uma variável COMPOSTA, no caso um REGISTRO facilita a organização e uso em diversas situações.

Att,

**Comment by AdsonEsteves** [comment]
Duplicate of #559
