### ISSUE TITLE
Bug de interface

### ISSUE THREAD

**Issue by Chiago150** [UNIVALI-LITE/Portugol-Studio#726]
Quando executa um código a interface do programa fica toda desfigurada e o bug persiste em todo o programa e precisando reiniciar o Portugol Studio.

Não tem mensagem de erro.

![bugPortugol](https://user-images.githubusercontent.com/52419546/66654058-c7aa4480-ec0f-11e9-885b-a5df48fc7be6.jpg)

![bugPortugol2](https://user-images.githubusercontent.com/52419546/66654179-0a6c1c80-ec10-11e9-8784-1f8ca9c8cc65.jpg)

Windows 10 Education 64 bits
Processador: AMD Ryzen 5 1400 Quad-Core Processor 3.20GHz
Memoria RAM: 16 GB
placa de video: GTX 1060

**Comment by AdsonEsteves** [comment]
@Chiago150 
Da uma olhada aqui: https://github.com/UNIVALI-LITE/Portugol-Studio/issues/421
