### ISSUE TITLE
Problema no ENQUANTO

### ISSUE THREAD

**Issue by powilliam** [UNIVALI-LITE/Portugol-Studio#727]
**Descrição do Problema**:
Ao usar uma operação lógica com OU/E no ENQUANTO o programa continua em loop, independente do lógico ser verdadeiro ou falso
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
[Bug no ENQUANTO do portugol.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/3720156/Bug.no.ENQUANTO.do.portugol.zip)

**Especificações do sistema**:
Intel(R) Core(TM) i3-2330M
CPU @2.20GHz x4
OS: Deepin 15.11 x64

**Comment by noschang** [comment]
Olá @powilliam.

Verifiquei o código que você mandou e percebi que não há nenhum bug.
Foi apenas um erro de lógica, acontece nas melhores famílias, hehehe.

Estou anexando uma versão modificada do código com alguns comentários pra que você possa entender onde está o erro: [Compra com acrescimo caso.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/3721326/Compra.com.acrescimo.caso.zip)

Vou fechar a issue, mas depois deixe um comentário aqui pra eu saber se você entendeu qual foi o problema. Boa sorte!!

**Comment by powilliam** [comment]
Nooooooossa, é mesmo! Não tem como fugir de erros kkkkkkkkkkk

Obrigado pelos comentários e principalmente pelo comentário bonus

**Comment by noschang** [comment]
> Nooooooossa, é mesmo! Não tem como fugir de erros kkkkkkkkkkk
> 
> Obrigado pelos comentários e principalmente pelo comentário bonus

Oi @powilliam, já que você gostou do comentário bônus, vou te dar mais uma dica. Quando se trabalha com porcentagens, geralmente se usa números fracionários variando do **0.00** ao **1.00**.

Neste caso, o valor **0.00** equivale a **0%** e o valor **1.00** equivale a **100%**. Os demais valores intermediários representam os percentuais equivalentes ao número.

Por exemplo, o valor **0.25** representa **25%**, o valor **0.10** representa **10%**, o valor **0.62** representa **62%** e assim por diante.

Usando esse tipo de representação, fica mais fácil de aplicar descontos e juros, pois basta fazer uma multiplicação.

Por exemplo, se você quer aplicar juros de **10%** basta multiplicar o valor por **1.10**, pois:
```1.00 (100%) + 0.10 (10%) = 1.10 (110%)```

Da mesma forma, se você quer dar um desconto de **10%**, basta multiplicar por **0.90**, pois:
```1.00 (100%) - 0.10 (10%) = 0.90 (90%)```

Estou anexando alguns exemplos, pra você dar uma olhada e entender melhor: [Exemplos porcentagem.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/3735774/Exemplos.porcentagem.zip)
