### ISSUE TITLE
O portugol studio não abre corretamente

### ISSUE THREAD

**Issue by PatriotaBR51** [UNIVALI-LITE/Portugol-Studio#729]
**Descrição do Problema**:
O problema é que o meu portugol studio não abre com o atalho da área de trabalho, eu tenho que ir até a pasta aplicação para executar.  obs: o atalho da área de trabalho leva até uma pasta com um javaw.jar (C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin)
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by noschang** [comment]
Oi @PatriotaBR51.

Você pode por gentileza realizar o procedimento abaixo?

1. Clique com o botão direito do mouse em cima do atalho da área de trabalho
2. No menu que vai aparecer, clique em **Propriedades**
3. Copie e cole aqui os valores que aparcem nos campos **Destino** e **Iniciar em**

Por gentileza copie os valores exatamente como aparecem no campo, incluindo as aspas ```"``` (se houver) e cole um em cada linha com a identificação do campo. Exemplo:

**Destino:** "C:\Program Files\Mozilla Firefox\firefox.exe"
**Iniciar em:** "C:\Program Files\Mozilla Firefox"

**Comment by AdsonEsteves** [comment]
Fechado por inatividade de resposta
