### ISSUE TITLE
Bug no mac

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#73]
O Seguinte código apresenta um bug no mac relacionado com a biblioteca gráficos:
[Bug no Mac.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/132894/Bug.no.Mac.zip)

**Comment by elieserdejesus** [comment]
@rytix @noschang , testei no Mavericks aqui e o código em anexo rodou sem problemas. Apareceu uma imagem com 4 quatro caras me dizendo que eu era fera :)  

Será que o problema com a biblioteca gráficos não está relacionado com alguma versão especifica do Mac?

**Comment by noschang** [comment]
É possível @elieserdejesus. Segundo o que o @rytix e o @AlissonSteffens relataram, o exemplo abre normalmente, mas quando usuário clica no botão "Interromper" o programa não finaliza. Outros códigos que utilizam a biblioteca Graficos foram executados e não geraram o mesmo bug.

Sendo assim, nossa conclusão inicial é de que este código em específico está gerando bug por algum motivo. Acreditamos que a causa seja as chmadas excessivas à função "Graficos.renderizar()". Esta função deveria ser chamada uma única vez após tudo ser desenhado, mas no código ela é chamado o tempo todo (inclusive isto acaba causando um efeito de flickering no exemplo).

**Comment by elieserdejesus** [comment]
Entendi Luis, eu não cheguei a interromper, por isso não vi o problema.

**Comment by AlissonSteffens** [comment]
Vou tentar reimplementar o código em anexo e ver se o erro continua, caso contrário, saberemos que o erro é de implementação no código portugol. Desconfio que como o @noschang disse, o proble esteja no fato de o programar ficar renderizando demais, isso pode causar algum conflito no controlador de render do MAC.

**Comment by AlissonSteffens** [comment]
Como prometido, refatorei o código que gerava o erro [testeMac.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/136554/testeMac.zip) , acredito que o problema era mesmo no fato de existirem muitos renderizar, e o modo gráfico ser iniciado, fechado, iniciado e fechado novamente durante a execução do programa.

**Comment by AlissonSteffens** [comment]
Mesmo com o Código refatorado e em completo funcionamento no Windows, o Programa ainda continua a executar infinitamente no Mac, é necessário investigar melhor a causa do problema.

**Comment by noschang** [comment]
@AlissonSteffens , você já resolveu essa treta?

**Comment by AlissonSteffens** [comment]
Preciso que alguém com uma Mac termine os teste :|

**Comment by elieserdejesus** [comment]
vou fazer o teste no meu super mac :)

**Comment by elieserdejesus** [comment]
Testei aqui, o erro ainda existe. Depois que a imagem é exibida o programa não fecha mais. Nenhum erro foi gerado na console.

**Comment by noschang** [comment]
Baphomet ataca novamente!!

**Comment by elieserdejesus** [comment]
Corrigido no núcleo: https://github.com/UNIVALI-LITE/Portugol-Nucleo/commit/81b8a8b1a2f88422721b47c18d4dec0efb6869f2

O problema estava relacionado com a finalização da Thread de execução do programa no Mac. O codigo *currentThread().isInterrupted()* sempre estava retornando *false* no mac. Agora o exemplo mencionado nessa issue funciona corretamente.

**Comment by noschang** [comment]
A pergunta que não quer calar é: como você resolveu @elieserdejesus? Você recompilou a JVM pra sempre retornar true nesse método? Aposto que sim, não esconda nada de mim!!

**Comment by elieserdejesus** [comment]
@noschang , usei uma flag (interrupcaoSolicitada) no programa. Quando o programa é finalizado a flag é setada. Na verdade muitas implementações de interrupção de thread usam isso. 

Eu acredito que existe algum bug na JVM do Mac, mas não cheguei a pesquisar o suficiente. Testei a ideia da flag, funcionou nas 3 plataformas e me dei por satisfeito :)

**Comment by noschang** [comment]
@elieserdejesus. Entendi. Então quando o usuário chama o método programa.interromper(), você não está mais chamando executorService.cancel() e sim programa.setInterrupcaoSolicitada(). Algo do tipo?

**Comment by elieserdejesus** [comment]
exato @noschang , mas acabei de verificar que isso tem uma falha grave: fui testar um erro que o @AdsonEsteves reportou no The Ball Saga e vi que a função Teclado.ler_tecla() chama o **wait()**. Como eu não estava mais chamando o *interrupt()* da thread de execução do programa esse wait estava esperando eternamente. Então não tem jeito, a solução é interromper a thread. O que fiz (já vou integrar a nova correção) foi interromper a thread como estava sendo feito antes **e também** setando essa flag que eu criei. Um mix das duas soluções. Não é bonito, mas está funcionando nas 3 plafatormas :)

Eu achei que isso não resolveria o problema no Mac, mas resolveu. Ou seja, mesmo quando o *wait()* é chamado e cancelamos a tarefa de execução (fechando a tela inicial do The Ball Saga) o **interrupt()* da Thread está sendo invocado e o programa finaliza corretamente. Sendo assim, não existe nenhum bug no Mac em relação à interrupção das threads. Deve ter algum problema no nosso código que só está bugando no Mac. Como não consegui identificar o problema vou usar essa solução "band-aid/durepox". :)

**Comment by noschang** [comment]
Maravilha @elieserdejesus. Lembre-se:

"Se é gambiarra, mas funciona, então não é gambiarra!", Autor desconhecido

**Comment by noschang** [comment]
@elieserdejesus dei uma pesquisada e descobri algo interessante. Existe diferença entre isso:

```java
if (Thread.interrupted())
{
   ...
}
```
E isso:

```java
if (Thread.currentThread().isInterrupted())
{
   ...
}
```

Segundo o Javadoc, ```Thread.interrupted()``` verifica se a Thread está interrompida e em seguida limpa a flag de estado interrompido. Ou seja, múltiplas chamadas em sequência farão com que, na primeira vez a expressão avalie como true, mas em chamadas subsequentes avalie como false.

Já a expressão ```Thread.currentThread().isInterrupted()```, segundo o Javadoc, verifica se a Thread foi interrompida e não altera a flag de estado interrompido. Logo, chamadas em sequência serão sempre avaliadas como true. 

Ou seja, é bem possível que estejamos utilizando a chamada de método errada para verificar o status da thread. Por que funciona em um SO e no outro não? **Baphomet!!** É bem provável que um dos sistemas implemente isto de forma errada na JVM, por questões éticas não vou falar qual **Windows** faz isso.

Referências:

[Thread.interrupted()](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#interrupted())
[Thread.currentThread().isInterrupted()](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#isInterrupted())

**Comment by elieserdejesus** [comment]
@noschang , eu sabia dessa questão e a primeira coisa fiz foi procurar por "interruped()" no código, não encontrei nada. Então acho que o problema é mais complexo. Minha suspeita é que tem alguma combinação complicada de chamadas para wait() e isInterrupted(). Ou então alguma coisa complicada dentro do executor que pode estar mantendo a thread "não interrompida". Eu vi que você usou um Executor customizado, cheguei até a usar um Executor padrão no lugar dele mas não mudou nada, então descartei a hipótese.
