### ISSUE TITLE
Pacotes para a distribuição Arch Linux

### ISSUE THREAD

**Issue by marceloschuler** [UNIVALI-LITE/Portugol-Studio#730]
Necessito instalar o aplicativo Portugol Studio para fins universitários, entretanto, utilizo a distribuição Arch Linux, que possui seu próprio gerenciador de pacotes (pacman), mas que não disponibiliza o programa em questão nos seus repositórios (tanto oficiais quanto o repositório de usuários - AUR). A página no Github do Portugol fornece duas alternativas para o Linux: um instalador (portugol-studio-2.7.4-linux-x64.run.zip) ou o código fonte do programa. A fim de instalar o programa de forma nativa à distribuição que utilizo, bem como proporcionar aos demais usuários dela uma forma simplificada (e nativa) de solucionar o problema, eu estou tentando criar um PKGBUILD (script com as instruções de instalação de programas no Arch Linux) para automatizar o processo. O problema reside no fato de eu não ter localizado para baixar os arquivos contidos no pacote de instalação do Portugol Studio para Linux (apenas o pacote binário portugol-studio-2.7.4-linux-x64.run, do qual eu não consigo extrair os arquivos de instalação). Pensei, então, em compilar o projeto a partir do código fonte, mas não encontrei informações sobre como fazê-lo, e minhas tentativas com o "gradle" resultaram em erros. Gostaria de saber, portanto, se existe a possibilidade de disponibilizar um pacote (.tar.gz, .zip, ou similar) com os arquivos avulsos de instalação para Linux contidos no binário (os que serão instalados no diretório /usr, como o programa propriamente dito, o arquivo .desktop, e outros necessários ao seu funcionamento).

**Comment by noschang** [comment]
Oi @marceloschuler, recebemos seu email também, mas vamos responder por aqui para que fique registrado e outras pessoas possam adotar a solução.

Criei um zip com os arquivos que você necessita para gerar pacote de instalação. Na raiz do zip você vai encontrar um arquivo ```leia.txt```. Leia atentamente o arquivo para compreender como funciona o processo de instalação pra que você possa replicar no seu pacote. Qualquer dúvida poste aqui que tentaremos auxiliar

Clique nesse link para baixar: https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.7.4/portugol-studio-2.7.4-linux-x64-standalone.zip

**Comment by marceloschuler** [comment]
Obrigado pelas informações, @noschang! Foram muito úteis! Consegui desenvolver um pacote para o Arch Linux, e agora o Portugol Studio pode ser instalado nativamente através do repositório de usuários da distribuição (AUR). Espero que futuramente ele possa ser melhor integrado com o java da própria distro (atualmente, OpenJDK 13), e não depender do fornecimento de uma versão pré-compilada. Sem utilizar o java que vem empacotado com o o próprio programa, só consegui rodá-lo usando uma versão mais antiga do OpenJDK (versão 11), mas o Portugol Studio é bastante dependente da versão que o acompanha, pois apesar de conseguir abrir o programa, ele falhava ao tentar rodar qualquer projeto.

De qualquer maneira, agradeço mais uma vez pela grande ajuda, e parabéns pelo excelente trabalho!

Caso alguém queira instalar o pacote, ele está disponível neste link: https://aur.archlinux.org/packages/portugol-studio-bin/

**Comment by noschang** [comment]
Oi @marceloschuler.

Em primeiro lugar, parabéns pela sua iniciativa e pelo trabalho! Ficamos felizes em saber que o Portugol Studio está sendo útill e motivando a comunidade a melhorá-lo.

Como você mencionou, realmente o Portugol Studio depende de uma versão do Java que vai junto no pacote de instalação, mas isso é intencional, pois no passado tentamos usar o Java que vinha instalado no computador do usuário e tivemos problemas.

Muitas vezes o usuário não tinha o Java instalado, ou tinha a versão 32 bits, quando a necessária era a de 64 bits e, por isso, havia conflitos e erros de versão. Além disso, o Portugol Studio funcionava no momento da instalação, mas após o Java se atualizar parava de funcionar. Ou então, por desconhecimento, o usuário resolvia remover o Java do computador e quebrava o Portugol Studio.

O cenário ainda era pior porque muitas vezes se tratavam de instituições de ensino onde o usuário não tinha privilégios para instalar programas no computador, ficando dependente da TI para efetuar qualquer correção na versão do Java. Só que para a TI das instituições nem sempre é viável atualizar o Java em centenas de computadores dos laboratórios no meio do semestre, durante as aulas.

Enfim, levando em conta todos os problemas enfrentados, chegamos à conclusão de que a melhor opção era inbutir o Java como parte do programa. Consideramos que é melhor aumentar o tamanho do pacote de instalação de 25MB para 125MB e oferecer um programa estável e funcionando, do que economizar algumas dezenas de MB e entregar um programa cheio de problemas. Hoje em dia, com computadores cada vez mais robustos, 100MB a mais não chegam a fazer diferença. ;-)

E pra finalizar, eu sou usuário Linux e particularmente gostaria de facilitar a vida dos usuários de Linux  disponibilizando pacotes nos repositórios oficiais, mas não tem como ficar mantendo pacotes para cada distribuição: .deb, .rpm, .snap, .flatpak. Além disso, 85% dos nossos usuários usam Windows e não podemos ignorar isso.

Então optamos pela solução mais simples que foi o uso do Bitrock Installbuilder, um programa que promete gerar um instalador que funcione nativamente em todas essas plataformas. O que tem funcionado muito bem, com raras exceções, como no seu caso.
