### ISSUE TITLE
Criar novos exemplos para as bibliotecas

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#74]
Criar novos exemplos para representar o uso das bibliotecas do portugol.

O Manual das Bibliotecas criado para o campeonato de jogos:
[Manual das Bibliotecas.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/132916/Manual.das.Bibliotecas.zip)
Possui exemplos para cada função das bibliotecas e pode ser usado.

Responsáveis:
@AlissonSteffens 
@rytix

**Comment by AlissonSteffens** [comment]
Foram criados alguns Exemplos novos... Sem chance de documentar todos os exemplos do Manual até o prazo definido

**Comment by noschang** [comment]
@AlissonSteffens 

Esta issue está no milestone "Backlog" e tem prioridade 3, ou seja mais baixa.
Portanto, não precisa se preocupar com a criação destes exemplos agora.

No entanto, existem alguns exemplos que já estão prontos, como os de detecção de colisão e os jogos de programar enviados pelos alunos. 

Estes exemplos vale a pena documentar e já incluir na próxima release.
Porém, dêem prioridade à solução de bugs e melhorias que vão ter impacto mais direto no projeto, como por exemplo o autocomplete.

**Comment by AlissonSteffens** [comment]
O jogo MoonLander foi atualizado

**Comment by AlissonSteffens** [comment]
![image](https://cloud.githubusercontent.com/assets/6234230/14468664/0f24585c-00b7-11e6-833a-7f9041979a27.png)

**Comment by AlissonSteffens** [comment]
acho que já criamos bastante exemplos, estou fechando esta issue.
