### ISSUE TITLE
Tem alguma forma de gerar o código de Pseudocódigo para Java ou outra linguagem?

### ISSUE THREAD

**Issue by Windows87** [UNIVALI-LITE/Portugol-Studio#743]
Boa noite,

Estou desenvolvendo um corretor automático de exercícios e queria implementar o Portugol como uma dessas linguagens, mas um desafio para implementar o Portugol é que não é possível (ou se tem como, me explique) rodar o código pelo terminal.

Por isso acho mais fácil transpilar o Portugol para outra linguagem, mas demoraria um pouco mais do meu tempo para criar um transpilador e provavelmente haveria um bom número de erros. Por isso, existe algum método de fazer essa geração de código (pelo terminal) ou há alguma forma mais fácil de fazer esse meu objetivo?

**Comment by AdsonEsteves** [comment]
@Windows87 

Pra sua primeira duvida: É possível rodar o Portugol pelo terminal, você precisa de um arquivo.por na máquina e rodar o seguinte:

```
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\java.exe" -jar "C:\ProgramData\UNIVALI\Portugol Studio/aplicacao/portugol-console.jar" <caminho-do-arquivo>
```

Ex:

```
"C:\ProgramData\UNIVALI\Portugol Studio\java\java-windows\bin\java.exe" -jar "C:\ProgramData\UNIVALI\Portugol Studio/aplicacao/portugol-console.jar" C:\Users\Joao\Desktop\fatorial.por
```
Era para ser possível rodar um código portugol atraves do console pelo comando `portugol-console`, entretanto ele está com problemas e vamos tentar resolver assim que possível.



Pra sua segunda: O Portugol Studio dentro dele transforma a linguagem portugol em JAVA para a compilação.
Isso é feito aqui (o código comentado printa o código java):
https://github.com/UNIVALI-LITE/Portugol-Studio/blob/master/core/src/main/java/br/univali/portugol/nucleo/compilador/Compilador.java#L134
Atualmente não tem nenhuma funcionalidade que acesse o código java gerado pelo usuário através da versão instalada.
Estamos pensando em se vale a pena e como podemos adicionar isso.
Sugiro fazer uma modificação no código fonte do Portugol-Studio, fazer um pull-request e geramos um instalador com essa modificação para você.
