### ISSUE TITLE
Problema na mudança entre console e mensagens.

### ISSUE THREAD

**Issue by Algajunior42** [UNIVALI-LITE/Portugol-Studio#746]
**Descrição do Problema**: Em alguns momentos aleatórios o Portugol Studio fica travado na opção mensagens, não retornando para o console

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**: Windows 7 Ultimate

**Comment by AdsonEsteves** [comment]
Duplicate of #599

**Comment by AdsonEsteves** [comment]
Obrigado pelo reporte
Já tivemos reportes sobre isso, estamos trabalhando pra resolver.
