### ISSUE TITLE
Problema com Chaves em Strings na Pilha

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#76]
http://pastebin.com/QudhUSMV
![image](https://cloud.githubusercontent.com/assets/7809511/13123385/03f63336-d5a3-11e5-9066-ba47af4b1a5f.png)

**Comment by AlissonSteffens** [comment]
Lembrando que o problema não é o fato de o programa não aceitar chaves mas sim a quantidade de chaves, visto que para resolução de um outro problema, o @noschang passou a gerar um pilha que verifica a quantidade de chaves abertas e fechadas, sendo assim um programa como este: 

![image](https://cloud.githubusercontent.com/assets/6234230/13147432/25c40a40-d640-11e5-8857-490b01f692b3.png)

Não gera nenhum tipo de erro.

O que deve ser tratado é na criação da pilha de chaves, temos que simplesmente não contar as chaves que estejam entre aspas e assim resolvemos o problema :smiley:

**Comment by noschang** [comment]
Correto @AlissonSteffens. Na verdade precisa ignorar não somente as chaves entre aspas, mas também em comentários e dados do tipo caracter.

Segue alguns exemplos:

// Isso aqui dá problema }
/* Isso aqui também dá problema } */
"E isso }"
'}' // Isso aqui também

**Comment by AdsonEsteves** [comment]
Movida para #314
