### ISSUE TITLE
Execução por linha de comando

### ISSUE THREAD

**Issue by ArthurAssuncao** [UNIVALI-LITE/Portugol-Studio#763]
**Descrição do Problema**:
Não encontrei forma de executar um código (extensão .por) por linha de commando.
Existe a opção de passar parametros como é em Java (não há qualquer documentação sobre, descobri por meio de um slide na internet), porém parece que o código não é executado como linha de comando, apenas é aberta uma tela do programa, mas os parâmetros não são passados, tentei as seguintes linhas:
```
portugol-studio teste.por "valor"
portugol-studio teste.por valor
```
Assim, queria saber como testar a passagem de parâmetros para a 'função inicio'.

**Mensagem de Erro (se houver)**:
Não há

**Captura de Tela / Arquivo.por**:
```
programa
{
	inclua biblioteca Util
	
	funcao inicio(cadeia parametros[])
	{
		inteiro numeroParametros = Util.numero_elementos(parametros)
		escreva("Número de parâmetros: ", numeroParametros)
		para(inteiro i = 0; i < Util.numero_elementos(parametros); i++){
			escreva(parametros[i])
		}
	}
}
```

**Especificações do sistema**:
Mint 19.3 rodando Linux 4.18.0 x64.

**Comment by noschang** [comment]
@ArthurAssuncao me parece que você está executando a linha de comando incorreta. O seu comando vai abrir o programa no Portugol Studio ao invés de executá-lo no console. Acredito que o comando que você quer seja o **portugol-console**:

```bash
portugol-console teste.por "valor"
```

O uso das aspas nos parâmetros é opcional, só é necessário quando o parâmetro possui espaços:

```bash
portugol-console teste.por sem_espacos "com espacos"
```

**Comment by ArthurAssuncao** [comment]
Perfeito, eu estava testando errado, obrigado e desculpa pela minha confusão.

**Comment by noschang** [comment]
Oi @ArthurAssuncao, não tem problema!

Se tiveres mais alguma dúvida pontual pode colocar no nosso Discord que iremos responder assim que possível: https://discord.gg/3ak7JC
