### ISSUE TITLE
Renomear variáveis não funciona

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#770]
Ao tentar renomear qualquer variável, seja através do ```Ctrl+R``` ou dando duplo clique na árvore estrutural, o Portugol Studio apresenta dois comportamentos distintos:

1. Nada acontece e a tela de renomear variáveis não aparece
2. Ocorre um NullPointerException e é exibida a tela para reportar bugs

A primeira situação é a que ocorre com mais frequencia, sendo que a segunda ocorreu apenas uma vez, mas não consegui reproduzir o erro.

Acredito que este bug esteja relacionado com a issue #728

**Comment by AdsonEsteves** [comment]
@noschang Isso ocorre em todos os computadores? Acredito que desde a issue #728 não deve ter acontecido nenhuma atualização.
Assim que puder verifico aqui.

**Comment by noschang** [comment]
@AdsonEsteves não sei dizer, só testei no meu Ubuntu

**Comment by AdsonEsteves** [comment]
Fechando a issue até o erro poder ser identificado novamente.
