### ISSUE TITLE
Erro com caracteres do portugol (38e11c2227ed58401349e38cc3a2c5e3ce2bad9c) v2.7.4

### ISSUE THREAD

**Issue by Zaidan-BR** [UNIVALI-LITE/Portugol-Studio#779]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by Zaidan-BR** [comment]
pq aparece tudo com caracteres ao inves de aparecer o texto? Alguem pode me ajudar?
![portugol](https://user-images.githubusercontent.com/62918998/77978769-e17c3880-72d0-11ea-92c3-095a5479297b.jpg)
![portugol_2](https://user-images.githubusercontent.com/62918998/77978776-e214cf00-72d0-11ea-840b-8d3ee3a65aad.jpg)

**Comment by AlissonSteffens** [comment]
@AdsonEsteves isso ai parece configuração de SO

**Comment by AdsonEsteves** [comment]
@Zaidan-BR 
Não sabemos muito bem o que possa ser.
Imagino que possa ter algo relacionado com a região do seu sistema.
Tente ir no painel de controle e ver a região do seu sistema.
Se o formato e o idioma dele está no formato Brasileiro.

**Comment by noschang** [comment]
@AdsonEsteves, será que não é a fonte? Tente ver qual fonte o PS usa no editor e passe o nome pra ele verificar se a fonte existe no sistema dele. Pode ser que a fonte não exista e daí o SO está tentando usar uma fonte alternativa

**Comment by AdsonEsteves** [comment]
@noschang pode ser.

@Zaidan-BR Pode ver se no seu sistema tem a fonte "Consolas" também?
Você pode ver as fontes do seu sistema indo em:
Painel de Controle > Aparencia e Personalização > Fontes
