### ISSUE TITLE
Erro Buscador de Linhas Paráveis

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#78]
Testanto algumas aplicações feitas pelos alunos, encontrei um novo bug. No projeto 
[Maze Bot.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/136426/Maze.Bot.zip), tentando abri o projeto o Portugol 2.5 me retorna o seguinte erro
![image](https://cloud.githubusercontent.com/assets/6234230/13148306/ea257f24-d643-11e5-9df8-1027db3b88d7.png)
Que pode ser lido na integra aqui http://pastebin.com/REaHAUjg .

**Comment by AlissonSteffens** [comment]
Observação, o programa funciona normalmente na versão anterior do Portugol Studio

**Comment by Shinjisky** [comment]
Se um retorne é colocado em uma função que não retorna nada, uma exceção é jogada na tela, e essa exceção continua a aparecer enquanto o retorne não é retirado. Porém em si, ela não causa nenhum problema a outras funções do portugol(aparentemente).

![print2](https://cloud.githubusercontent.com/assets/8836540/13360496/54b8434e-dc98-11e5-9756-fed2db0198b6.png)
![print1](https://cloud.githubusercontent.com/assets/8836540/13360510/5948d7f2-dc98-11e5-898d-c2f23c467b79.png)

**Comment by rytix** [comment]
@AlissonSteffens Funciona pois na versão anterior não tinha linhas paráveis.
Foi descoberto também que os pontos de parada dependem da correção do semântico.

Porém no caso do retorne em funções que retornam vazio, o semântico considera como valido (e é valido) e em casos de for sem nada dentro "for(;;)" o semantico também considera como valido, e o buscador não está pronto para aguentar estes casos (aonde o conteúdo de dentro deles é null).

![image](https://cloud.githubusercontent.com/assets/7809511/13581917/05dac9de-e488-11e5-8415-4a84d4cb142c.png)

Uma das soluções possiveis é verificar se o conteudo destes é diferente de null, e o problema será resolvido. Como no exemplo abaixo que corrige o retorne em casos de funções com retorno vazio.
![image](https://cloud.githubusercontent.com/assets/7809511/13581934/1a8075a0-e488-11e5-869f-92c3f5018aa0.png)

Porém vocês acham que é a melhor solução, fazer estas verificações de Null ?, os valores que surgem realmente podem ser nulos.

Existe alguma função/classe que faz estas verificações ?
Se @elieserdejesus e o @noschang puderem opinar sobre essa solução também seria bom, não sei se é elegante ficar fazendo verificações de null ou existe uma solução melhor :x

**Comment by elieserdejesus** [comment]
@rytix , a única solução mais elegante que eu consigo imaginar para esse caso é o padrão [Null Object](https://en.wikipedia.org/wiki/Null_Object_pattern#Java). Mas eu acho que no momento a melhor solução é verificar o null mesmo, usar o padrão NullObject vai gerar uma uma refatoração bem grande. Estaríamos trocando uma solução super simples por uma bem mais complexa, teríamos que mexer em vários outros lugares do código para remover todas as verificações de null, etc. 

O "search" do NetBeans aceita expressões regulares. É possível fazer uma busca por todas as ocorrências de testes com null. Se o número de ocorrências não for tão grande é possível fazer essa refatoração com calma usando essa ajuda da IDE.

**Comment by rytix** [comment]
Está certo, irei corrigir comparando com null mesmo xD
