### ISSUE TITLE
Versão Mac: Problemas de acesso às pastas do usuário

### ISSUE THREAD

**Issue by reborges** [UNIVALI-LITE/Portugol-Studio#794]
**Descrição do Problema**:
Aplicativo não consegue acessar subpastas do usuário. Provavelmente por causa das novas regra de segurança do macOS Catalina.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
macOS Catalina 10.15.4

**Comment by AdsonEsteves** [comment]
Movido para #876
