### ISSUE TITLE
NullReference no AnalisadorSemantico.obterNomeParametro a partir de uma linha de portugol que usa "escreva" e uma função como parâmetro

### ISSUE THREAD

**Issue by gustavodort** [UNIVALI-LITE/Portugol-Studio#795]
**Descrição do Problema**:
Um aluno meu fez esse código e deu um nullRef no método obterNomeParametro da classe AnalisadorSemantico, linha 604. Isso acontece a partir da existência da linha 17 do código.

**Mensagem de Erro (se houver)**:
Não consegui acessar o texto do erro, portanto estou enviando um screenshot.
![image](https://user-images.githubusercontent.com/6497943/81478165-f0200e80-91f1-11ea-9787-72ad8138794b.png)

**Captura de Tela / Arquivo.por**:
Tive que zipar por restrições de extensão:
[erro-ex7.zip](https://github.com/UNIVALI-LITE/Portugol-Studio/files/4603893/erro-ex7.zip)

**Especificações do sistema**:
	
[DxDiag.txt](https://github.com/UNIVALI-LITE/Portugol-Studio/files/4603909/DxDiag.txt)

**Comment by AdsonEsteves** [comment]
@gustavodort 
Obrigado, vamos tratar esse erro nas próximas versões.
Isso ocorreu pois a função Ex7 não retorna nenhum valor para o escreva quando chamada
![image](https://user-images.githubusercontent.com/8836540/81588796-51c9af80-938f-11ea-81da-d4cda90a69a6.png)

**Comment by gustavodort** [comment]
Ué, retorna sim. Um valor real.

**Comment by AlissonSteffens** [comment]
@gustavodort ela escreve no console, não retorna. São coisas diferentes.

Quando você escreve algo no console, esse valor não é retornado para a chamada de função, ele é apenas enviado para o componente renderizador de texto.

É possível escrever e retornar "ao mesmo tempo", para isso primeiro escreva e depois retorne (já que todo código após o retorno de função é ignorado.

```js
funcao real Ex7 (real salario, inteiro vendas){
  escreva(salario+vendas*0.15)
  retorne (salario+vendas*0.15)
}
```

espero ter ajudado 🙂

**Comment by AlissonSteffens** [comment]
@gustavodort já que você já escreve na função, não há poque escrever na início também. Senão ficaria ```escreva(escreva(valor))```. Então, se quiser economizar trabalho, pode fazer assim também:

```js
programa
{
    funcao inicio ()
    {
        cadeia nome
        escreva("Digite seu nome: ")
        leia(nome)
        
        real salario
        escreva("\nDigite seu salário fixo: ")
        leia (salario)
        
        inteiro vendas
        escreva("\nDigite as vendas efetuadas: ")
        leia (vendas)

        escreva("\nSeu salário é de: R$")
        Ex7(salario,vendas)

    }
    
    funcao Ex7(real salario, inteiro vendas)
    {
        escreva (salario+vendas*0.15)
    }
}
```

**Comment by gustavodort** [comment]
Perdão, você tem toda razão!
Eu pensei que a correção que você tinha me enviado era o que meu aluno tinha feito.
