### ISSUE TITLE
Bug Renderização Aleatório de Baphomet

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#80]
Então, encontrei um bug na renderização dos componentes do Portugol Studio no Windows 10.

![image](https://cloud.githubusercontent.com/assets/6234230/13204604/baa627dc-d8b2-11e5-86e3-e98188152c24.png)

Não sei exatamente aonde esta o erro, talvez seja um problema um problema no próprio WebLaF, mas o interessante é que o bug só acontece enquanto a mensagem de atualização do Portugol ainda não apareceu... depois de a mensagem de atualização ser mostrada, o programa passa a magicamente renderizar tudo corretamente

**Comment by elieserdejesus** [comment]
Alisson, estou usando Windows 10 aqui também e não vi esse bug. Podes dar mais detalhes? Basta abrir o PS e o bug já aparece?

**Comment by noschang** [comment]
Pessoal, acho que sei o que pode estar acontecendo.

O fato de o bug só ocorrer quando a notificação é exibida me leva a crer que de alguma forma a AbaCodigoFonte está sendo adicionada dentro do ToolTip.

Talvez tenha sido um mero engano na hora de programar, ou então é um bug mesmo, mas o fato é que tem tudo pra ser isso.

Quando o ToolTip é exibido com a aba de código dentro, ele fica quase do tamanho da tela e aí da impressão que é um bug de renderização, mas não é.

@AlissonSteffens, dá uma investigada nisso!

**Comment by AlissonSteffens** [comment]
Eu acho que o @noschang tem razão... pelo visto a classe responsável pelas notificações em tela tem alguns problemas... ela não tá sabendo onde renderizar. Um exemplo é que se abrirmos o portugol e em seguida a tela de sobre, a notificação de atualização do portugol aparecerá na tela de sobre e não na AbaInicial. 
![image](https://cloud.githubusercontent.com/assets/6234230/13220427/e7c41e98-d954-11e5-8b35-3492e97af584.png)
Vou investigar esta implementação mais afundo hoje a tarde

**Comment by elieserdejesus** [comment]
Eu vi outro bug que acho está relacionado com esse. Eu abro o portugol, depois abro um jogo, e depois de alguns segundos aparece a notificação de que existem atualizações que serão instaladas na próxima inicialização. Desse ponto em diante não aparece mais a tela do jogo. Os sons continuam funcionando, mas a renderização já era. Acho que essa notificação está realmente muito zuada, e resolvendo o bug dessa issue vai resolver esse bug que eu mencionei também.

**Comment by AlissonSteffens** [comment]
As coisas estão ficando cada vez mais assustadoras

![image](https://cloud.githubusercontent.com/assets/6234230/13236705/d94d8cdc-d9a4-11e5-9dd7-411e0503bd5b.png)

**Comment by AlissonSteffens** [comment]
Mesmo tendo comentado a parte responsável por procurar as atualizações do Portugol...
![image](https://cloud.githubusercontent.com/assets/6234230/13236948/afaa07c8-d9a6-11e5-85df-af66eff7619b.png)
Ainda assim persiste o problema de renderização por volta do primeiro minuto de execução do Portugol Studio.
![image](https://cloud.githubusercontent.com/assets/6234230/13236946/a47903cc-d9a6-11e5-926c-e7e014e14ecc.png)
Vou investigar mais o problema

**Comment by AlissonSteffens** [comment]
@noschang preciso saber o que está acontecendo nesta parte do código
![image](https://cloud.githubusercontent.com/assets/6234230/13237039/514aee6c-d9a7-11e5-9821-40fbfee36d95.png)

**Comment by AlissonSteffens** [comment]
Removi a instalação dos Observadores da Tela e não adiantou, ao contrário, fez com que o Bug passasse a continuar ocorrendo mesmo após o programa aberto um tempo. **O problema não está na parte das Notificações**. Porem por algum motivo, após retomar os observadores, o problema de renderização acaba após a notificação de atualização ser mostrada.
![image](https://cloud.githubusercontent.com/assets/6234230/13238501/3552eb5a-d9b2-11e5-9455-2c6b6754254d.png)

**Comment by noschang** [comment]
OK! Sentaremos juntos e tentaremos encontrar uma solução!

**Comment by AlissonSteffens** [comment]
Definitivamente o bug não é no Windows 10, talvez algo no meu computador... Talvez o mesmo erro que bugue os gifs no meu PC... É necessário investigar mais a fundo o motivo do erro.

**Comment by noschang** [comment]
Após várias tentativas de solução sem sucesso, começamos a acreditar que este bug é gerado pelo capeta. Mas ainda faremos mais alguns testes antes de acusá-lo injustamente

**Comment by elieserdejesus** [comment]
huahuahauhauhauha. Rindo até 2035  :)

**Comment by AlissonSteffens** [comment]
Alguns erros foram resolvidos no pull #105

**Comment by noschang** [comment]
Porra Paulo (@rytix)!!! 

![captura de tela de 2016-03-10 11 10 34](https://cloud.githubusercontent.com/assets/709553/13671837/0030b2d4-e6b1-11e5-9acc-9aa3d0e257a7.png)

**Comment by rytix** [comment]
Tem gente que consegue resolver os problemas com 139 linhas de código, já outros precisam de 4200...
SHuiSHuSHiushis

Alguns dos meus passados commits não estão linkados a essa conta não sei porque :P
Como os da implantação do CSSBox.

E as vezes em alguns projetos que fazia com minha turma quando eu commitava um tal de mr-bean aparecia no meu lugar...

É bem bizarro

**Comment by AlissonSteffens** [comment]
É pessoal, ele continua a bugar nos primeiros 45 segundos do Portugol, ele buga... E depois pega normalmente.

**Comment by AlissonSteffens** [comment]
Parece que ele está no meio de nós não é mesmo?!?!?!
![baphomet-yuri-leitch](https://cloud.githubusercontent.com/assets/6234230/13858501/ba49136c-ec5d-11e5-882f-f348e9a9dcb9.jpg)

**Comment by AlissonSteffens** [comment]
Bug Resolvido!!!! 
![image](https://cloud.githubusercontent.com/assets/6234230/14468576/a3df425a-00b6-11e6-9bad-9ab19ead8384.png)
