### ISSUE TITLE
Problemas gerais rodando no MacOs

### ISSUE THREAD

**Issue by tiberio13** [UNIVALI-LITE/Portugol-Studio#801]
**Descrição do Problema**:
Encontrei varios problemas usando Portugol Studio para Mac, mas os maiores e que tornam o programa quase inutilizável no Mac são o aplicativo não conseguir visualizar documentos, na parte de salvar ou abrir arquivo o programa so consegue ver pastas mas não consegue ver nenhum arquivo, tornando-se impossível abrir um arquivo salvo, ate por que abrir o aplicativo clicando em um arquivo salvo não abre-o. O segundo e a impossibilidade de mover a janela na maioria das vezes, ela e fixa, não consegue-se mover, reduzir de tamanho ou mudar de monitor, ela fica presa onde esta.

**Especificações do sistema**:
macOS Catalina 10.15.4
iMac, 2,7GHz Intel Core i5 Quad-Core
8GB DDR3 RAM
Intel Iris Pro

**Comment by AdsonEsteves** [comment]
Movido para #876
