### ISSUE TITLE
Erro numero ccffbba4ed72ac334c3c402154c6db6d4724314c v2.7.4

### ISSUE THREAD

**Issue by janarygentil** [UNIVALI-LITE/Portugol-Studio#802]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
@janarygentil 
Qual foi o erro que ocorreu,como aconteceu?
