### ISSUE TITLE
Portugol Studio-Erro

### ISSUE THREAD

**Issue by kelwingarcia** [UNIVALI-LITE/Portugol-Studio#804]
**A interface do programa esta apresentando deeito **:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![Sem título](https://user-images.githubusercontent.com/65830954/82740170-4c1b8480-9d14-11ea-9f89-dfc759d7b6ee.png)

**windows 10 pro**:

**Comment by AdsonEsteves** [comment]
@kelwingarcia 

Olha aqui #421
