### ISSUE TITLE
Criar exemplos na tela principal

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#81]
A tela inicial do portugol precisa ter os exemplos.

**Comment by AlissonSteffens** [comment]
Em andamento ![image](https://cloud.githubusercontent.com/assets/6234230/13328087/8869dfcc-dbcb-11e5-8fdf-3c5adca59866.png)

**Comment by AlissonSteffens** [comment]
Finalizado

**Comment by noschang** [comment]
Parabéns Equipe!
