### ISSUE TITLE
Aumentar o limite de ram portugol

### ISSUE THREAD

**Issue by tgcmv** [UNIVALI-LITE/Portugol-Studio#815]
**Descrição do Problema**:
Alguns exemplo do portugol com erro por limite de ram
Uma solução simples seria nas configurações poder aumentar a ram.

**Mensagem de Erro (se houver)**:
Ocorreu um erro durante a execução do programa: O programa atingiu a quantidade máxima de memória RAM permitida.
Verifique se o programa não está utilizando muitos recursos (imagens, sons, etc) e se estes recursos não são muito grandes.
Linha: 731, Coluna: 4

**Captura de Tela / Arquivo.por**:
- Jogo Programe (disponível nos exemplos)
- Player de musica (disponível  nos exemplos)

**Especificações do sistema**:
- Win 10 ram mais que suficiente.

**Comment by AdsonEsteves** [comment]
@tgcmv 
O problema, não ocorreu aqui. O uso de memória do Portugol deveria ser suficiente.
Precisaria de mais informações da ram do seu computador para podermos simular mais possibilidades.
Isso ocorre mesmo com o Portugol rodando sozinho na máquina?

Você pode testar o problema de uso de memória do Portugol fazendo seguinte:
1. Abra as propriedades do icone de atalho do Portugol Studio
2. No Campo "Destino" encontre o seguinte texto: `-Xmx256m`
3. Altere o valor de 256m, para o valor de memória que deseja dar ao Portugol Studio e tente novamente. use m ou g para definir se é mega ou giga.
![image](https://user-images.githubusercontent.com/8836540/84446869-e4729e00-ac1c-11ea-8534-2a4a9aa372ce.png)


Dito isso, configurações para aumentar a ram no futuro serão consideradas.

**Comment by tgcmv** [comment]
O portugol não estava rodando sozinho, porém tem 16gb e tem memória sobrando.
Aumentei para 512 o máximo de ram e funcionou.
O erro ocorria ao selecionar o personagem do jogo 'programe' e ao tocar uma musica externa pelo player de musica.
