### ISSUE TITLE
Erro numero 3ef4aaa5e67dafcf91ae6f621c4045220bca3990 v2.7.4

### ISSUE THREAD

**Issue by madeiraantonio97** [UNIVALI-LITE/Portugol-Studio#817]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
@madeiraantonio97 
Qual erro ocorreu? Consegue repetir ele?
