### ISSUE TITLE
possibilidade de criar 'registro' - feature -discussion 

### ISSUE THREAD

**Issue by tgcmv** [UNIVALI-LITE/Portugol-Studio#819]
Estou analisando o código do Portugol para incluir registros (similar as struct do C)
O objetivo é eu ter uma variável do tipo registro mais ou menos com a sintaxe:

> registro aluno{
>    cadeia nome
>     inteiro idade
>}
>aluno.nome = "Teste" 
>//....

ou então poder criar 'classes' mais ou menos assim
>programa{
>	funcao inicio(){}
>}
>//...
>classe{
>//...
>}

Acham que não vale a penas ter isso no portugol?
Se sim qual das duas abordagem acham melhor?

**Comment by AdsonEsteves** [comment]
Essa sugestão já está em pauta a um bom tempo no Portugol Studio. #559
É um desejo nosso adicionar isso seja structs ou registros
Como é uma mudança direta na estrutura da linguagem, necessita de um tempo exclusivo a resolver ela. Então ainda está meio longe de se tornar realidade.

**Comment by AdsonEsteves** [comment]
Duplicate of #559

**Comment by matheus-ndc** [comment]
Infelizmente pelo que percebi na estrutura do sistema feito pela comunidade, foi que o sistema foi criado apenas para exemplificações simples descartando tipos complexos como registros, então demandaria muito tempo refazer uma grande parte das classes e arquivos para aceitar e estruturar a utilização dos mesmos no Portugol Studio. Uma pena... mesmo assim é o meu sistema favorito para os outros tipos de dados mais comuns. Continuem com o excelente trabalho, todos nós temos afazeres e serviços de prioridade elevada, mas revisem e coloquem em pauta essa feature, o importante é começar.
