### ISSUE TITLE
Perca de precisão 40*3.14 == 125.600000000001

### ISSUE THREAD

**Issue by tgcmv** [UNIVALI-LITE/Portugol-Studio#821]
**Descrição do Problema**:
Um aluno fez um código que era para retornar 125.6 e retornou 125.6000000001
Provavelmente se dá devido a conversão de valores float's e double's
No java por exmeplo 0.7 == 0.7f dá falso pois (double) 0.7f é 0.6999999......
Para evitar esse tipo de problema quando se espera algo com precisão grande, é comum usar sempre o BigDecimal

O problema piora quando comparo 40*3.14 == 125.6 ele retorna falso quando era para retornar verdadeiro

Aproveitando, como feature, uma forma de limitar as casas decimais ao escrever um numero seria bom .

>real raio, perim,area; 
>const real pi =3.14;
>escreva("Digite o raio do círculo: \n");
>leia (raio); 
>perim = 2 * pi *raio; 
>escreva (perim);

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/5677568/84581583-1de01080-adb9-11ea-8cfa-c48439f43b99.png)

![image](https://user-images.githubusercontent.com/5677568/84581580-17ea2f80-adb9-11ea-98c1-f7c3cd30579c.png)

**Comment by AdsonEsteves** [comment]
Você pode usar a função arredondar da biblioteca matemática.
Ela limita o número de casas como você quer.
![image](https://user-images.githubusercontent.com/8836540/84960486-23e73180-b0d8-11ea-8fec-c2c1e597f68f.png)

**Comment by tgcmv** [comment]
![image](https://user-images.githubusercontent.com/5677568/85031973-ac57e780-b155-11ea-8672-3e0a18fa64c6.png)

Nessa imagem não deveria retornar verdadeiro? pois 40*3.14 = 125.6?

porém ao executar esse código retorna falso
> real a = 40*3.14, b = 125.6
> escreva(a == b)

**Comment by AdsonEsteves** [comment]
@tgcmv 
Não pois ele passa pelo problema da linguagem JAVA, não exatamente de conversão, mas do armazenamento binário, já tivemos issues sobre isso: #717 #448 
Isso pode ser resolvido no JAVA utilizando big decimal, mas havíamos decidido que utilizar objetos para os cálculos reduziria drasticamente a performance do Portugol Studio.

O que falei ali, é sobre o seu pedido de opção de reduzir as casas decimais que é possível com a biblioteca matemática.

	programa
	{
		inclua biblioteca Matematica --> m
		
		funcao inicio()
		{
			real a = 40*3.14, b = 125.6
			escreva(a+"\n")
			escreva(b+"\n")		

			escreva((a == b) +"\n")

			escreva(m.arredondar(a, 3)+"\n")
				
			escreva(m.arredondar(a, 3) == b)
		
		}
	}
