### ISSUE TITLE
Estou com bug no portugol

### ISSUE THREAD

**Issue by AMGuirra** [UNIVALI-LITE/Portugol-Studio#823]
**Descrição do Problema**:
Estou com bug no portugol

**Mensagem de Erro (se houver)**:
nao tem mensagem de erro, fica somente assim conforme imagem

**Captura de Tela / Arquivo.por**:

![bug2](https://user-images.githubusercontent.com/66978858/84717259-50b61000-af43-11ea-9c66-2b9997ac0ce6.jpg)
![bug](https://user-images.githubusercontent.com/66978858/84717260-514ea680-af43-11ea-8627-f58eb5776b0a.jpg)

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@AMGuirra 
Olha essa thread #421
