### ISSUE TITLE
Erro de compilação mais de um "enquanto"

### ISSUE THREAD

**Issue by GAHB30** [UNIVALI-LITE/Portugol-Studio#828]
**Descrição do Problema**:
Quando ponho mais de um "enquanto" para validação de dados, não deixa.
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**: windows 10
	
![Capturar](https://user-images.githubusercontent.com/67174897/85213140-4d12f680-b352-11ea-80db-37174812de8a.PNG)

**Comment by AdsonEsteves** [comment]
Obrigado pelo reporte.
Sugiro tentar usar uma variável lógica no local do verdadeiro por enquanto.
