### ISSUE TITLE
Bug da popup de aviso aparecer em outro componente.

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#83]
Passos:
1 - Abrir o portugol studio
2 - Rapidamente (antes de aparecer a popup de atualização) realizar os seguintes passos:
2.1 - Abrir uma nova aba para digitar o código fonte
2.2 - Digitar qualquer coisa
2.3 - Tentar fechar o portugol (até aparecer a janela perguntando se quer salvar o código) e esperar.
3 - A popup de atualização irá aparecer dentro da janela perguntando se quer salvar o código.
![image](https://cloud.githubusercontent.com/assets/7809511/13259482/4b166e24-da36-11e5-8360-06426498cb4c.png)

Ou como visto na Issue #80 parece que o bug não pertence só ao windows 10.
![image](https://cloud.githubusercontent.com/assets/6234230/13220427/e7c41e98-d954-11e5-8b35-3492e97af584.png)

**Comment by AlissonSteffens** [comment]
Qualquer janela que for aberta antes da notificação, a notificação vai aparecer nela, o problema é que a notificação é posta lá pelo gerenciador de notificação do próprio JAVA **NotificationManager**, que é utilizado pela classe **FábricaDicasInterface**

**Comment by AlissonSteffens** [comment]
Não encontrei nenhuma forma de fazer com que as notificações ficasse "presas" a algum componente

**Comment by AlissonSteffens** [comment]
Resolvido, ver PullRequest #105
