### ISSUE TITLE
O projeto foi abandonado?

### ISSUE THREAD

**Issue by Superxicao** [UNIVALI-LITE/Portugol-Studio#830]
Bug do menu no app android.
Alem disso, não tem manual completo das funcionalidades dele em lugar nenhum.

**Comment by AdsonEsteves** [comment]
@Superxicao 
O projeto não foi abandonado, estamos apenas com uma baixa de pessoal com outros projetos.
Sobre app de android, não temos nenhum suporte oficial a algum atualmente. Se deseja saber sobre eles sugiro procurar os desenvolvedores respectivos.
