### ISSUE TITLE
Erro de travamento minutos após instalação

### ISSUE THREAD

**Issue by evaristo7912** [UNIVALI-LITE/Portugol-Studio#832]
**Descrição do Problema**:
O computador travou, tive de reiniciar 4x e aplicar a desinstalação do programa.
A versão instalada do Portugol e 2.4.7
**Mensagem de Erro (se houver)**:
Na instalação apareceu a mensagem, esse programa pode danificar seu sistema, deseja prosseguir?
**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
	core i3 itautec

**Comment by AdsonEsteves** [comment]
@evaristo7912 
Essa mensagem na instalação é normal a primeira vez.
O computador travou logo após a instalação, ou chegasse a tentar abrir o Portugol?
Qual o tamanho da sua RAM?

você pode tentar a versão sem instalação aqui: https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.7.4/Portugol.Studio.Windows-standalone.zip
Apenas execute o portugol-studio.bat

Caso ainda não der certo, sugiro a versão: https://portugol-webstudio.cubos.io/
Tem bibliotecas mais limitadas, mas pode te ajudar ainda.

**Comment by evaristo7912** [comment]
Utilizei por alguns minutos e depois travou, consegui desinstalar o programa e o pc voltou a funcionar normalmente, irei instalar essa 2º opção, e depois passo feedback.
