### ISSUE TITLE
PS aceitando mais de um senao nos comandos SE

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#834]
**Descrição do Problema**:

PS está aceitando mais de um **senao**. Quando um comando **SE** tem mais de um **senao** o programa executa "normalmente".

**Código exemplo (não gera erros nem avisos)**:
`
programa
{
	
	funcao inicio()
	{
		se (verdadeiro) {
			
		}
		senao {
			
		}
		senao {
			
		}
	}
}

**Comment by AdsonEsteves** [comment]
@noschang 

Poderia isso estar relacionado com a issue #759 ?
Estive trabalhando no Pull request #851 , e percebi que o PortugolParser ignora alguns erros do senao que deveriam ser capturados por ele por serem problemas sintáticos.
Será que é um problema do lexico?

**Comment by noschang** [comment]
> @noschang
> 
> Poderia isso estar relacionado com a issue #759 ?
> Estive trabalhando no Pull request #851 , e percebi que o PortugolParser ignora alguns erros do senao que deveriam ser capturados por ele por serem problemas sintáticos.
> Será que é um problema do lexico?

@AdsonEsteves, dei uma olhada na gramática e parece estar tudo certo com a regra do ```se-senao```. Isso parece ser um problema parecido com o que ocorria no ANTLR3. O ANTLR possui um mecanismo de auto-recuperação no qual, em alguns casos, ele simplesmente "exclui" os tokens inváidos e continua fazendo o parsing. Não sei como desativar esse comportamento

Eu dei uma pesquisada e uma possível solução é forçar o parser a executar até o final do arquivo.
Tenta alterar a gramática nessa sessão aqui:

https://github.com/UNIVALI-LITE/Portugol-Studio/blob/2a12511ae84e96675cf860399dabb487b0c4e3e4/core/src/main/antlr/Portugol.g4#L5

Mude disso
```antlr4
arquivo 
    :   PROGRAMA ABRE_CHAVES 
        inclusaoBiblioteca* (declaracaoFuncao | listaDeclaracoes)* 
        FECHA_CHAVES ;
```        

Para isso:     
```antlr4        
arquivo 
    :   PROGRAMA ABRE_CHAVES 
        inclusaoBiblioteca* (declaracaoFuncao | listaDeclaracoes)* 
        FECHA_CHAVES EOF;
```

Não sei se vai funcionar, mas tenta fazer o teste, Se der certo, possivelmente vai solucionar alguns outros problemas similares

**Comment by AdsonEsteves** [comment]
@noschang 
Essa issue é uma das que o pull #871 ajuda a resolver.
Quando fiz o comentario dessa issue, ainda não tinha achado o problema.

Quando fiz as modificações do pull, apliquei esse código da issue, que acabou gerando o erro "o nome da funcao não foi retornado" que cito no pull. Ou seja, o erro provavelmente pode ser facilmente capturado criando um contexto pro `senao`.
