### ISSUE TITLE
Bugando a tela ao usar carácter especial

### ISSUE THREAD

**Issue by RodrigoBrandao-Git** [UNIVALI-LITE/Portugol-Studio#836]
**Ao usar qualquer caracter especial a tela começa a bugar**:

![image](https://user-images.githubusercontent.com/67930442/86859553-45b15400-c099-11ea-9594-7558d4b5ae25.png)

Processador: AMD RYZEN 3600
Ram: 16Gb 3066mhz
GPU: Nvidia GTX 1660Ti
OS: Windows10 ver 2004

**Comment by AdsonEsteves** [comment]
Da uma olhada aqui, ve se ajuda: #421

**Comment by RodrigoBrandao-Git** [comment]
Obrigado resolvi o problema fechando o MSI Afterburner e o RivaTuner
