### ISSUE TITLE
Duvida - Raspberry PI (Processadores ARM)

### ISSUE THREAD

**Issue by NandoSalvaterra** [UNIVALI-LITE/Portugol-Studio#839]
**Duvida - Raspberry PI (Processadores ARM)**:

Senhores, bom dia!

Gostaria de saber se o Portugol-Studio roda em processadores ARM como no raspberry Pi, como se trata de uma IDE para educação e aprendizado, e os raspberries são uma ótima solução custo-beneficio, ficou a duvida.

Attt

**Comment by noschang** [comment]
Oi @NandoSalvaterra. Nunca testamos o Portugol Studio no Raspberry, mas o PS é desenvolvido em Java então existem grandes chances de ele funcionar. 

O que você deve fazer é substituir o JDK 8 padrão do Portugol Studio pelo JDK 8 específico da versão ARM.

Para isso, primeiro, baixe o JDK para ARM nesse link: https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html. Se você não tiver uma conta da Oracle será necessário criar uma antes de baixar.

Deves baixar a versão **Linux ARM 32 Hard Float ABI** ou a versão **Linux ARM 64 Hard Float ABI**, dependendo se o seu raspberry for 32 ou 64 bits.

Depois de baixar o JDK, baixe essa versão aqui do Portugol Studio: 
https://github.com/UNIVALI-LITE/Portugol-Studio/releases/download/v2.7.4/portugol-studio-2.7.4-linux-x64-standalone.zip

Após baixar os arquivos, sigas os seguintes passos:

1. Descompacte o arquivo do Portugol Studio
2. Acesse a pasta do Portugol Studio e vá até o diretório ```/portugol-studio/java```
3. Apague a pasta ```/java-linux```
4. Descompacte o arquivo do JDK dentro da pasta ```/portugol-studio/java```
5. Renomeie a pasta do JDK de ```jdk1.8.0_261``` para ```java-linux```
6. Por fim certifique-se de que a estrutura de diretórios está da seguinte forma:

```
   -- portugol-studio-2.7.4-linux-x64-standalone
        -- arquivos-auxiliares
        -- portugol-studio
            -- java-linux
                -- bin
                -- include
                -- jre
```
Para executar o Portugol Studio, siga as instruções que se encontram no arquivo ```leia.txt``` na raiz da pasta do Portugol Studio.
