### ISSUE TITLE
Reativar o autocomplete

### ISSUE THREAD

**Issue by rytix** [UNIVALI-LITE/Portugol-Studio#84]
Bugs detectados:
1 - Variáveis globais duplicadas:
![image](https://cloud.githubusercontent.com/assets/7809511/13361161/ca939412-dc9b-11e5-8af4-5818e1644914.png)
2 - Variáveis dentro de escopos podem ser vistas em escopos diferentes de mesma profundidade.
![image](https://cloud.githubusercontent.com/assets/7809511/13361245/371ee49c-dc9c-11e5-8bb5-bd6225b13b7b.png)

**Comment by noschang** [comment]
Imagens e exemplos, por favor!
O que você quer dizer com "inconsistente"?

Precisamos de mais informações. Descreve melhor o que está ocorrendo, please!
Valeu @rytix! Só estou citando seu nome no comentário pra dar um beep no teu Slack! Kkkkkkk
