### ISSUE TITLE
Erro no "array"

### ISSUE THREAD

**Issue by LucasKPinheiro** [UNIVALI-LITE/Portugol-Studio#845]
**Descrição do Problema**:
Não consigo por uma contante do tipo "inteiro" no vetor

**Mensagem de Erro (se houver)**:
O Tamanho do vetor 'vt' deve ser um valor ou uma constante do tipo inteiro
**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:
programa
{	inclua biblioteca Texto --> converte
	
	
	funcao inicio()
	{
		cadeia nome
		leia(nome)
		inteiro carac = converte.numero_caracteres(nome)
		inteiro vt[carac]
	
		
	}
}

**Comment by LucasKPinheiro** [comment]
![image](https://user-images.githubusercontent.com/70076320/90984047-f50e9100-e548-11ea-8ccc-316350f1a35b.png)

**Comment by AdsonEsteves** [comment]
@LucasKPinheiro 
Você está utilizando uma variável, não uma constante. use assim:
![image](https://user-images.githubusercontent.com/8836540/90986226-897ff000-e557-11ea-9cec-395f1960adeb.png)

Em futuras atualizações, os vetores poderão utilizar variaveis também.
