### ISSUE TITLE
Modificações no High Light 

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#85]
Pull Request Respectivo: https://github.com/UNIVALI-LITE/Portugol-Studio/pull/92

Melhorar o Sistema de temas do portugol Studio, fazendo com que o marcador da linha durante a depuração dependa do tema.
![image](https://cloud.githubusercontent.com/assets/6234230/13359722/58442df6-dc94-11e5-8770-b5e78829d9d1.png)
Além de adequar as cores ao novo layout do Portugol.
![image](https://cloud.githubusercontent.com/assets/6234230/13359731/6f6a93ee-dc94-11e5-8718-943e6aa629a1.png)

**Comment by AlissonSteffens** [comment]
Grande parte dos problemas aqui já foram arrumados, o único que falta é separar por tipo a cor, o que depende de uma refatoração no .flex da linguagem (que o @rytix vai fazer??)

**Comment by elieserdejesus** [comment]
@AlissonSteffens , não é melhor fechar essa issue? O que ficou pendente poderia ser uma nova issue caso o esforço realmente valha a pena.

**Comment by AlissonSteffens** [comment]
Deve ser feito somente após a gramática ser passada para o Antlr4
