### ISSUE TITLE
Erro numero 1af646ed6b67bf137b191247684f34c81ea4393e v2.7.4

### ISSUE THREAD

**Issue by TndJhon** [UNIVALI-LITE/Portugol-Studio#852]

**Comment by AdsonEsteves** [comment]
@TndJhon 

Qual a versão do seu sistema operacional?

**Comment by TndJhon** [comment]
@AdsonEsteves estou no ubuntu 20.04

**Comment by AdsonEsteves** [comment]
@TndJhon 
De acordo com #793 você pode não ter permissão como usuário para escrever arquivos
utilizando o comando
``$ sudo chown -R $USER nomedodiretorio``
pode resolver

**Comment by AdsonEsteves** [comment]
Duplicate of #793
