### ISSUE TITLE
Portugol studio erro de compilação

### ISSUE THREAD

**Issue by JohnynFuly** [UNIVALI-LITE/Portugol-Studio#854]
**Toda vez que eu escrevo um código da erro de compilação*:]]()

**Mensagem de Erro (Erro na compilação)**:

**[/CKImagens/Aluno/2821581/file/pp.png](url)**

**Windows 7 memória 4gb ram 330 hd **:
	
[/CKImagens/Aluno/2821581/file/pp.png](url)

**Comment by AdsonEsteves** [comment]
Pode fazer o upload das imagens novamente?
Arraste elas arrastando o arquivo até a caixa de comentários ou copiando e colando o arquivo na caixa
