### ISSUE TITLE
Bug na exibição do último valor de um vetor no inspetor

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#86]
Na **execução passo a passo**, se a última posição de um vetor é alterada essa alteração não aparece no inspetor. As outras posições do vetor aparecem corretamente, o problema acontece somente na última posição.

A imagem abaixo mostra que a posição **28** está sendo exibida, quando a posição correta seria a **29**.

![image](https://cloud.githubusercontent.com/assets/1012741/13381426/bc88f38a-de3a-11e5-85c4-c201477ff066.png)

**Comment by noschang** [comment]
@elieserdejesus , isto pode estar relacionado com o timer de repintura do componente. Lembra que não repintamos o tempo todo, mas somente a cada x milisegundos?

Algo parecido acontece se você criar um laço de 1 a 1000 atualizando uma variável do tipo inteiro. Dependendo do momento em que o timer de repintura é disparado, as últimas alterações não são refletidas e o inspetor mostra a variável com o valor 982, por exemplo. No entanto, ao passar o mouse por cima do componente, um novo evento de pintura é disparado e a tela é atualizada mostrando o valor real da variável, no caso: 1000.

**Comment by noschang** [comment]
Foi corrigido nos commits do Pull Request #106.
Foi validado e está funcionando.

![corrigido](https://cloud.githubusercontent.com/assets/709553/13671279/bc6e9d16-e6ad-11e5-8218-272f21c0ef44.png)

Estou fechando a issue e integrando o Pull Request
