### ISSUE TITLE
Mensagem ruim na declaração de função

### ISSUE THREAD

**Issue by AlissonSteffens** [UNIVALI-LITE/Portugol-Studio#867]
Em algumas situações, a mensagem de erro na definição de funções não está boa.

Se eu esqueço de por o tipo em uma função que tem apenas um parâmetro, ele dá a mensagem boa:
```js
programa
{
	
	funcao inteiro metade(numero){
		retorne numero/2
	}
	funcao inicio()
	{
		escreva(metade(2))
	}
}
```
![image](https://user-images.githubusercontent.com/6234230/96461552-e667f180-11fa-11eb-8b7b-985263a95625.png)

Mas se o parâmetro existe em uma variável global, o erro já fica mais difícil de entender:

```js
programa
{
	inteiro numero = 2
	
	funcao inteiro metade(numero){
		retorne numero/2
	}
	funcao inicio()
	{
		escreva(metade(2))
	}
}
```
![image](https://user-images.githubusercontent.com/6234230/96461669-0a2b3780-11fb-11eb-9fd4-3e4082dfa171.png)

Mas se forem dois parâmetros, dai ele fica doidão

```js
programa
{
	inteiro numero = 2
	inteiro numero2 = 5
	
	funcao inteiro soma(numero, numero2){
		retorne numero+numero2
	}
	funcao inicio()
	{
		escreva(soma(2,4))
	}
}
```
![image](https://user-images.githubusercontent.com/6234230/96461740-229b5200-11fb-11eb-888d-cdc5a8b69a66.png)

**Comment by AdsonEsteves** [comment]
Parece fazer parte do combo do #308

**Comment by AlissonSteffens** [comment]
🤔 maybe. Acha que dá de resolver, pelo menos estas aqui?

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 
Pensando melhor acho que não deve ser o mesmo.
É um problema sintático, vai depender se o Parser captura o erro ou ignora que nem os erros do senao.
Se ele ignorar, tem que resolver ou arrumando o antlr, ou na "força bruta" provavelmente.
Só que olhando pelas mensagens de erro, provavelmente ele ta ignorando.

Interessante, que se o tipo é colocado na primeira variavel, o erro sai correto
![image](https://user-images.githubusercontent.com/8836540/97231272-0464c180-17ba-11eb-9ebc-c487a2ab4487.png)

Talvez não seja tão desesperador.

**Comment by AlissonSteffens** [comment]
🤔 uééé.

**Comment by AdsonEsteves** [comment]
What is tipagem? 
A miserable little pile of inexistence!
![image](https://user-images.githubusercontent.com/8836540/97231859-f5324380-17ba-11eb-802f-0f07e54b39b3.png)

**Comment by AlissonSteffens** [comment]
mas o q? 😮
