### ISSUE TITLE
Erro com caracteres

### ISSUE THREAD

**Issue by mih-silva** [UNIVALI-LITE/Portugol-Studio#868]
**Descrição do Problema**:
Assim que eu instalo o programa, quando eu abro um novo arquivo o idioma que esta em portugues, em algumas areas do programa fica escrito com caracteres,  já instalei e desinstalei, já instalei outras versões, mais o problema é persistente.
obrigada desde já

**Mensagem de Erro (se houver)**:

**Captura de Tela / 
![tela_portugol_erro](https://user-images.githubusercontent.com/71404820/97188606-75888280-1782-11eb-8d56-516a8ed6230c.jpg)
> Arquivo.por**:

**Especificações do sistema**:

**Comment by AlissonSteffens** [comment]
Acredito que o problema possa estar na codificação dos caracteres do arquivo. @mih-silva consegues nos mandar o arquivo que está dando este problema?

**Comment by mih-silva** [comment]
Então assim que eu abro um novo arquivo para codificar do zero, o programa ela já abre com esta falha 
![tela_portugol_erro_1](https://user-images.githubusercontent.com/71404820/97191854-10cf2700-1786-11eb-8a73-d331f060933f.jpg)

**Comment by mih-silva** [comment]
obs: Na parte inferior da tela

**Comment by AlissonSteffens** [comment]
@mih-silva pode testar se no seu sistema tem a fonte "Consolas"?
Você pode ver as fontes do seu sistema indo em:
Painel de Controle > Aparência e Personalização > Fontes

**Comment by AlissonSteffens** [comment]
Duplicate of #779

**Comment by mih-silva** [comment]
Não tem a fonte Consolas, e não conseguir baixar !!!

**Comment by mih-silva** [comment]
@AlissonSteffens eu instalei a fonte de um site sem ser da Microsoft , bom aparentemente deu certo, agradeço a eficiência do seu  feedback ... Boa tarde

**Comment by AlissonSteffens** [comment]
Que bom que resolveu @mih-silva. Obrigado por nos avisar, vamos trabalhar em como evitar que este problema aconteça novamente.

**Comment by AlissonSteffens** [comment]
@AdsonEsteves 2 @noschang acho que temos que mandar esta fonte junto com o Portugol. Ela deveria ser padrão do Windows não?

**Comment by noschang** [comment]
> @AdsonEsteves 2 @noschang acho que temos que mandar esta fonte junto com o Portugol. Ela deveria ser padrão do Windows não?

Achei que já tínhamos essa fonte no PS.
@AlissonSteffens, se tu já baixou, basta acrescentar nessa pasta aqui:
https://github.com/UNIVALI-LITE/Portugol-Studio/tree/master/ide/src/main/resources/br/univali/ps/ui/fontes

E depois registrar a fonte aqui:
https://github.com/UNIVALI-LITE/Portugol-Studio/blob/2a12511ae84e96675cf860399dabb487b0c4e3e4/ide/src/main/java/br/univali/ps/nucleo/PortugolStudio.java#L618

**Comment by AlissonSteffens** [comment]
Não vem no WIndows? vou tentar resolver isso hoje de noite

**Comment by AlissonSteffens** [comment]
@noschang to tendo o erro
```
java.io.IOException: Problem reading font data
```

estranho porque a fonte é a do windows que eu to tentando por
