### ISSUE TITLE
Inspetor não aceita vetores declarados como const

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#87]
No exemplo do jogo **Serpente** não é possível arrastar o vetor **INTERVALO_ATUALIZACAO** para o inspetor. Se este vetor for arrastado do código não acontece qualquer problema, mas se ele for arrastado da árvore o inspetor não aceita a inserção do vetor.

No código do jogo este vetor está declarado como **const**. Se a palavra **const** for removida do código tudo funciona normalmente. **Investigar o código que trata o arrastamento de símbolos da árvore**.

![image](https://cloud.githubusercontent.com/assets/1012741/13381528/38c878f6-de3d-11e5-87a8-2642ad1fb9bf.png)

**Comment by noschang** [comment]
@elieserdejesus, o mesmo ocorre com variáveis e matrizes constante. Acredito que isto tenha sido uma regra de negócio que você implementou. Se o símbolo for constante, não permite inspecionar, pois não faz sentido inspecionar um valor que nunca irá mudar.

Neste caso, acredito que basta adicionar dois desvios condicionais na classe do inspetor. Se o símbolo inspecionado for uma instância de vetor ou matriz, inspeciona sempre. Se for uma variável, só inspecionada se a flag "constante" for falso.

**Comment by elieserdejesus** [comment]
@noschang , o que achas de fazer o inspetor aceitar tudo? O aluno vai perceber que não faz sentido arrastar uma constante porque ela nunca muda, e nesse processo ele terá aprendido alguma coisa. Da forma como está agora provavelmente muitos alunos não entenderão por que a aplicação não deixa inspecionar uma determinada variável e deixar inspecionar outras. 

O que achas?

**Comment by noschang** [comment]
Acho válido!
Assume o trampo?

**Comment by elieserdejesus** [comment]
Sim, assumo, esse é moleza :)

**Comment by noschang** [comment]
OI @elieserdejesus! Como está este feature? Alguma novidade? Sem pressão hahahahahaha

**Comment by elieserdejesus** [comment]
@noschang , essa está pronta. Acho que eu comentei alguma coisa no pull request.

**Comment by noschang** [comment]
Corrigido no Pull Request #101.
Segue abaixo resultado dos testes:

![captura de tela de 2016-03-10 11 01 43](https://cloud.githubusercontent.com/assets/709553/13671658/e84e4d58-e6af-11e5-9f43-8047a5a3df55.png)
