### ISSUE TITLE
Variável usada no leia não acusa que não foi criada, gerando nullpointer do semantico

### ISSUE THREAD

**Issue by Rafaelfcosta** [UNIVALI-LITE/Portugol-Studio#873]
**Descrição do Problema**:
Se uma variável não for criada, porém usada em um leia o analisador não acusa o erro que ela não existe, apenas na execução onde ele gera um nullpointer.

O erro também não é capturado, sendo mostrado apenas como mensagem.

O problema acontece sempre ao usar uma variável inexistente no leia.

**Mensagem de Erro (se houver)**:

![image](https://user-images.githubusercontent.com/21344756/97616631-90b1f700-19fb-11eb-98c8-427142696072.png)

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/21344756/97616719-afb08900-19fb-11eb-974b-1609ab82053a.png)
![image](https://user-images.githubusercontent.com/21344756/97616764-bccd7800-19fb-11eb-8d99-739dce1a0e22.png)

**Comment by AdsonEsteves** [comment]
Duplicate of #837

**Comment by AdsonEsteves** [comment]
Ja foi corrigida
