### ISSUE TITLE
Erro de semântica na linha 0

### ISSUE THREAD

**Issue by marcio420** [UNIVALI-LITE/Portugol-Studio#879]
**Descrição do Problema**:Meu código está correto mas o programa acusa erro semântico na linha 0.

**Mensagem de Erro (se houver)**: aparecem várias mensagens de analisador semântico. Java 682, Java 533, Java 267, Java 88,
Java 2332, Java 889, Java 133, Java 209, Java 73, Java 139,  Java 60, Java 84, Java 29, Java 48, Java 1957, Java 266, Java 1149,
Java 624, Java  Java 748 

**Captura de Tela / Arquivo.por**:
programa
{
       funcao inicio()
       {
              inteiro numero
    
              numero = Valida_Inteiro (0, 100)
              escreva("Primeiro Número Válido = ", numero)

              numero = Valida_Inteiro (-50, 50)
              escreva("Segundo Número Válido = ", numero)
       }
       {

       funcao inteiro Valida_Inteiro (inteiro inferior, inteiro superior){
              inteiro numero

              escreva ( " Digite um valor entre", inferior, " e ", superior, " : ")
              leia(resultado)}

              enquanto ( resultado < inferior ou resultado > superior){
                      escreva (" Valor Inválido! Redigite!")
                      escreva ( " \nDigite um valor entre " inferior, " e ", superior, " : ")
                      leia(resultado)
              }
      }
              retorne resultado
}
              

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@marcio420 
o código está com erros de escopo com os `{` `}`
verifique por exemplo, os escopos estão se abrindo antes da função `Valida_Inteiro` e estão se fechando no `leia(resultado)`

As mensagens de erro serão consertadas nas próximas versões.

**Comment by marcio420** [comment]
Consegui tirar a chave antes da função Valida_Inteiro mas se tiro as outras chaves dá erro.

**Comment by AdsonEsteves** [comment]
A de depois do `leia(resultado)` tem que ser removida tbm.
O `retorne resultado` está fora da função e no ultimo escreva você esqueceu uma vírgula.
Fique de olho onde um escopo começa e termina. 
Se você colocar o ponto de inserção na frente de uma abertura de escopo `{`, ele vai te apontar onde ele fecha com `}`, vai estar realçado no arquivo:
![image](https://user-images.githubusercontent.com/8836540/99277936-368f9f00-280d-11eb-9c3d-c26737bebaef.png)
Utilize isso para verificar se os escopos estão corretos.

**Comment by marcio420** [comment]
Retirei a chave e agora realça a palavra inteiro e acusa erro de Recognition Exception.  No último escreva vai uma vírgula após o fechamento do parênteses?

**Comment by marcio420** [comment]
Achei a vírgula no último escreva mas continua dando erro de recognition exception.

**Comment by AdsonEsteves** [comment]
mostra o teu código como tá agora

**Comment by marcio420** [comment]
programa
{

        funcao inicio()
        
        {
              inteiro numero

              numero = Valida_Inteiro (0, 100)
              escreva("Primeiro Número Válido = ", numero)

              numero = Valida_Inteiro (-50, 50)
              escreva("Segundo Número Válido = ", numero)
       }     
       
       funcao inteiro Valida_Inteiro (inteiro inferior, inteiro superior)
             inteiro numero

             escreva("Digite um valor entre  ", inferior, " e ", superior, " : ")
             leia(resultado)

             enquanto (resultado < inferior ou resultado > superior)
                     escreva("Valor Inválido! Redigite!")
                     escreva(" \nDigite um valor entre ", inferior, " e ", superior, " : ")
                     leia(resultado)
                     retorne resultado
      }

**Comment by noschang** [comment]
@AdsonEsteves, o problema está no ```leia``` da variavel ```resultado```

Veja que ele não declarou essa variável, mas pelo fato de o leia estar inicializando ela, o semantico passa a entender que ela existe. Posteriormente quando o semantico tenta achar o tipo da variável ```resultado``` dá um ```NullPointerException``` pois a variável é nula dentro da tabela de símbolos.

Veja:

```
programa
{
	funcao inicio()    
	{
		inteiro numero

		numero = Valida_Inteiro (0, 100)
		escreva("Primeiro Número Válido = ", numero)

		numero = Valida_Inteiro (-50, 50)
		escreva("Segundo Número Válido = ", numero)
	}

	funcao inteiro Valida_Inteiro(inteiro inferior, inteiro superior)
	{
		inteiro numero
		//inteiro resultado // Descomente essa linha e o código passa a funcionar

		escreva("Digite um valor entre  ", inferior, " e ", superior, " : ")
		leia(resultado)

		enquanto (resultado < inferior ou resultado > superior)
		{
			escreva("Valor Inválido! Redigite!")
			escreva(" \nDigite um valor entre ", inferior, " e ", superior, " : ")
			leia(resultado)
		}
		
		retorne resultado
	}
}
```

**Comment by marcio420** [comment]
Obrigado Amigo!
