### ISSUE TITLE
programa não executa as instruções

### ISSUE THREAD

**Issue by marcio420** [UNIVALI-LITE/Portugol-Studio#882]
**Descrição do Problema**:O programa não executa as instruções indo direto para o final.

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
programa                                                    
{
        funcao inicio()
        {
              inteiro A[], B[], C[]}
                            
        {
              escreva("Entrada de dados do vetor A => \n")
              Leitura_Vetor(A, N)

              escreva("Entrada de dados do vetor B => \n")
              Leitura_Vetor(B, N)

              somaA = Soma_Vetor(A, N)
              somaB = Soma_Vetor(B, N)
        }
 }
                                                             

**Especificações do sistema**:

**Comment by AlissonSteffens** [comment]
O Portugol tem a função início como a sua função main. Isso quer dizer que independente do que estiver no arquivo, ele só vai executar as coisas que estiverem definidas a partir do fluxo da função inicial (Assim como o C e o C++).

Acontece que logo após declarar os tres vetores, você está fechando a função início, e todo o resto do seu cádigo está em um escopo externo anônimo. Este pedaço de código nunca será executado

```js
programa                                                    
{
        funcao inicio()
        {
              inteiro A[], B[], C[]
         }
                            
        {
              escreva("Entrada de dados do vetor A => \n")
              Leitura_Vetor(A, N)

              escreva("Entrada de dados do vetor B => \n")
              Leitura_Vetor(B, N)

              somaA = Soma_Vetor(A, N)
              somaB = Soma_Vetor(B, N)
        }
 }
```

Para resolver é só unir os escopos, apagando as chaves extras:

```js
programa                                                    
{
        funcao inicio()
        {
              inteiro A[], B[], C[]
              escreva("Entrada de dados do vetor A => \n")
              Leitura_Vetor(A, N)

              escreva("Entrada de dados do vetor B => \n")
              Leitura_Vetor(B, N)

              somaA = Soma_Vetor(A, N)
              somaB = Soma_Vetor(B, N)
        }
 }
```

IMPORTANTE: Note que as funções de ler e somar vetor deve ser adicionadas a este mesmo documento.

**Comment by marcio420** [comment]
Está dando outro problema com as chaves. Tirei as chaves extra mas quando declaro a função Leitura_Vetor aparece a mensagem de que a expressão não foi finalizada corretamente. Também não estou conseguindo fazer a chamada das funções na função inicio nem qual variavel adicionar na chamada.

**Comment by AdsonEsteves** [comment]
@marcio420 
Isso vai depender de como você escreveu elas.

Se estiver tendo muita dificuldade com a programação, sugiro olhar alguns dos videos na nossa página na seção `Aprenda`.
http://portugolstudio.com.br/
