### ISSUE TITLE
erro na compilação e variável não inicializada

### ISSUE THREAD

**Issue by marcio420** [UNIVALI-LITE/Portugol-Studio#883]
**Descrição do Problema**:Aparece erro na compilação e a mensagem de que a variável A não foi inicializada em alguns trechos.

**Mensagem de Erro (se houver)**:Erro na compilação e Existem alguns trechos do código onde a variável A pode não ter sido inicializada.

**Captura de Tela / Arquivo.por**:
programa
{
        
        funcao inicio()
        {
              inteiro A[], B[], N[], Soma_Vetor

              escreva("Entrada de dados do vetor A => \n")
              Leitura_Vetor(A, B, N)

              escreva("Entrada de dados do vetor B => \n")
              Leitura_Vetor(A, B, N)}

              somaA = Soma_Vetor(A, N)
              somaB = Soma_Vetor(B, N)

        funcao inteiro Leitura_Vetor (inteiro A[], inteiro B[], inteiro B[])
              {
                      inteiro somaA, inteiro somaB, inteiro Soma_Vetor
                      leia(Soma_Vetor)
              retorne Soma_Vetor }     
**Especificações do sistema**:

**Comment by AlissonSteffens** [comment]
@marcio420, este erro está relacionado ao seu código, e não é um problema na Linguagem.
Para tirar dúvidas relacionadas a lógica de programação, aconselho utilizar o nosso [Discord](https://discord.com/invite/fRW7Vq2), coloque suas dúvidas na aba `#ajuda-algoritmos` , lá o pessoal da comunidade vai poder te ajudar.
Além disso, você pode dar uma olhada no [nosso site](http://univali-lite.github.io/Portugol-Studio/) na seção aprenda, lá tem alguns vídeos que podem ser úteis, bem como link para um curso de introdução a programação.
