### ISSUE TITLE
bug muito loco

### ISSUE THREAD

**Issue by viniciusfernoli** [UNIVALI-LITE/Portugol-Studio#889]
**Descrição do Problema**:
Quando aperta ' ou " no teclado, todo o programa buga, sem erro 
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/74386669/100294726-6275f780-2f66-11eb-9809-c1b60eb2ed03.png)
![image](https://user-images.githubusercontent.com/74386669/100294774-889b9780-2f66-11eb-8062-aeebb430639d.png)
![image](https://user-images.githubusercontent.com/74386669/100294799-9a7d3a80-2f66-11eb-883d-efc24c61735f.png)

**Especificações do sistema**:
i5 7400
gtx1060
windows 10 pro
2 monitores
32gb de ram

**Comment by AdsonEsteves** [comment]
@viniciusfernoli 
Olha aqui: #421

**Comment by AdsonEsteves** [comment]
Duplicate of #421
