### ISSUE TITLE
Alguém cabulou as aulas de Português!

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#89]
Tan tan taaaaaaaannnnnn...

![porra_alisson](https://cloud.githubusercontent.com/assets/709553/13404809/463d53f4-defa-11e5-981a-64d6adb1d540.png)

**Comment by Shinjisky** [comment]
getos hoje, getos amanha, getos pra sempre

**Comment by AlissonSteffens** [comment]
Nois é do gueto mesmo mano...
![38d2e760-a699-4fec-83d1-69954b1e452f](https://cloud.githubusercontent.com/assets/6234230/13404876/9e789632-defa-11e5-8716-fb7dadc0e568.jpg)
