### ISSUE TITLE
Erro numero 38ee0e302425a4f9bb89dceacdb15e47bc9fd142 v2.7.5

### ISSUE THREAD

**Issue by cafumanairc** [UNIVALI-LITE/Portugol-Studio#894]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
@cafumanairc 
Como ocorreu esse erro?
Sempre ocorre?
