### ISSUE TITLE
Ponto de parada fantasma

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#90]
Alguns códigos estão exibindo pontos de parada fantasma.
Como replicar:

Abra o exemplo MoonLander e execute-o repetidas vezes sem fechar a aba de código. Após várias execuções, o depurador pára na linha 96 onde há uma declaração de matriz, como se um ponto de parada tivesse sido inserido.

No entanto, nenhum ponto de parada foi inserido, e na verdade, o núcleo sequer considera esta linha como "parável", embora ela seja.

Para que o bug ocorra, é preciso rodar várias vezes, pois aparentemente é aleatório e não consegui identificar um padrão até agora. No entanto, no caso específico do MoonLander, o bug parece ocorrer com mais frequência quando o usuário clica no botão para interromper o programa ou quando clica no "X" da janela ao invés de sair do exemplo usando a tecla "Esc".

O bug ocorre com outros programas aleatórios.

Segue print do bug:

![error](https://cloud.githubusercontent.com/assets/709553/13405422/1b314582-defd-11e5-99d0-df1594b0350d.png)

**Comment by elieserdejesus** [comment]
Vi o mesmo problema no exemplo da bateria. Não sei se tem relação, mas eu fiquei com a impressão de que o bug acontece quando o código escrito em Portugol faz muitas pinturas. Por exemplo, o código da bateria eletrônica não tem um "sleepzinho" pra dar uma aliviada no processador, é pau na cara e voadora nas costas o tempo todo :)  As vezes isso acontecia já na primeira vez que eu rodava o exemplo da bateria. Talvez esse exemplo seja um bom case para tentar descobrir esse bug.

**Comment by AlissonSteffens** [comment]
Acontece com o The Ball Saga também, acho que este erro está relacionado a mesma classe que era o erro da Issue #78.

**Comment by noschang** [comment]
Descobri um padrão neste bug. O breakpoint fantasma só ocorre em linhas onde está sendo declarado um vetor ou uma matriz.

Isto nos dá uma boa pista, pois este mesmo tipo de linha não está sendo marcado como "parável" pelo núcleo. Provavelmente é um bug na classe que determina os pontos de parada. 

@elieserdejesus, você que estava com a mão na massa nisso e implementou a maior parte, tens como dar uma olhada?

**Comment by elieserdejesus** [comment]
@noschang , posso adotar essa criança :)
Que código tu estavas testando quando descobrisses esse padrão no comportamento do muléque?

**Comment by noschang** [comment]
Então @elieserdejesus. Eu testei em vários códigos e os únicos que parecem dar pau mesmo são os que abrem interface gráfica (jogos e bateria).

Mas o erro só ocorre em linhas marcadas como não paráveis. Na maioria das vezes é em uma declaração de vetor ou matriz, mas teve uma vez que ocorreu em um laço enquanto, cuja linha estava marcada como não parável, e portanto, não tinha o ícone de bug na linha para ativar/desativar.
