### ISSUE TITLE
adicionar<- com a mesma finalidade do =

### ISSUE THREAD

**Issue by seitbnao** [UNIVALI-LITE/Portugol-Studio#905]
Blz?, bom em algumas faculdades principalmente as publicas utilizam o portugol  e tivemos dificuldades ao utilizar a ferramenta
pois o professor passava <- como atribuir e no portugol studio é =, teria possibilidade de implementar <- também como = ?

**Comment by AdsonEsteves** [comment]
@seitbnao 
<- é utilizado apenas no Visualg
O Portugol Studio utiliza =

Portugol Studio utiliza portugol 2.0, já o Visualg é portugol 1.
São linguagens diferentes.
