### ISSUE TITLE
Não está inserindo aspas simples ou duplas.

### ISSUE THREAD

**Issue by igormachado** [UNIVALI-LITE/Portugol-Studio#906]
**Descrição do Problema**:

**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@igormachado 
Pode dizer mais sobre o problema?
Acontece algum erro na tela?
Qual o seu teclado e as configuracoes do computador?
