### ISSUE TITLE
Problema com a biblioteca Tipo

### ISSUE THREAD

**Issue by moura79** [UNIVALI-LITE/Portugol-Studio#907]
Ao usar a biblioteca Tipos ,cadeia_para_inteiro(variável, 10) da erro.

A base deve ser 2,10 ou 16
Linha 19:                    num = t.cadeia_para_inteiro(teclado, 10)
                             ^

![Screenshot_20210107-151707](https://user-images.githubusercontent.com/72673933/103929150-9f9fde80-50fb-11eb-8bc0-616707b055bb.png)
Estou usando a versão mobile

**Comment by moura79** [comment]
Estou iniciando na programação ,e esse é um exercício do curso.

**Comment by AdsonEsteves** [comment]
@moura79 
A versão mobile não tem suporte pela equipe que faz a de desktop.
Tente entrar em contato com os desenvolvedores dela especificamente.
