### ISSUE TITLE
Operações em tipos não numéricos

### ISSUE THREAD

**Issue by nobnet** [UNIVALI-LITE/Portugol-Studio#912]
**Descrição do Problema**:
A soma de dois tipos caracteres resulta em uma cadeia, mas não é possível a conversão:
`
		caracter c1 = '0' //48
		caracter c2 = '9' //57
		/* Não funciona.
		cadeia c12 = c1 + c2 //Não converte em cadeia
		escreva(c12)
		
		inteiro i12 = c1 + c2 //Não converte cadeia em inteiro
		escreva(i12)		
		*/
		escreva(c1 + c2) //Exibe inteiro 105 = 48 + 57
`
**Mensagem de Erro (se houver)**:
incompatible types: int cannot be converted to String
**Captura de Tela / Arquivo.por**:
[https://pastie.io/oslnpi.cpp](url)
**Especificações do sistema**:
Windows 10 e PS 2.7.5

**Comment by AdsonEsteves** [comment]
@nobnet 
Qual versão você está utilizando? Na mais recente esse erro já está tratado.

Caracteres podem virar cadeias na linguagem, mas não é possível transformar cadeias em inteiros normalmente. é necessário usar a biblioteca tipos para isso.
