### ISSUE TITLE
Código aparece em símbolos

### ISSUE THREAD

**Issue by Raiane298** [UNIVALI-LITE/Portugol-Studio#926]
**Descrição do Problema**:
O código está aparecendo em símbolos
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:
![port](https://user-images.githubusercontent.com/80347403/110502756-3e37c400-80da-11eb-8dd3-1232a732702d.png)

**Especificações do sistema**:
Windows
v.2.7.5

**Comment by AdsonEsteves** [comment]
@Raiane298 
Pode ver se no seu sistema tem a fonte "Consolas"?
Você pode ver as fontes do seu sistema indo em:
Painel de Controle > Aparencia e Personalização > Fontes

@AlissonSteffens 
Parece que não resolveu ainda.

**Comment by AlissonSteffens** [comment]
Acho que se isso continuar acontecendo, temos que mudar a fonte que utilizamos no editor para uma das fontes que não dá problema. O que acha @AdsonEsteves ?

**Comment by AlissonSteffens** [comment]
Similar ao problema de #779 , #868 e #870

**Comment by AdsonEsteves** [comment]
@AlissonSteffens 
O problema é, como vamos saber se a fonte não dá problema? Podemos até tentar, mas seria um segundo tiro no escuro.
Tecnicamente o caso de teste do @Rafaelfcosta foi só ver se funcionava, mas nunca vimos esse erro realmente acontecer. Acho que o certo seria primeiro tentar reproduzir o erro.
O @Rafaelfcosta tinha usado uma VM sem a fonte, mas só foi testada a versão "corrigida". Tem que pegar esse mesmo sistema sem a fonte e testar sem a correção pra ver se o problema é realmente a falta da fonte.
Talvez nem seja isso.

**Comment by AlissonSteffens** [comment]
O que quis dizer, é utilizar uma destas fontes que estão na interface e funcionando. Mas não sei se tem alguma monospace.

**Comment by AdsonEsteves** [comment]
@AlissonSteffens sim, eu entendi.
O que quis dizer, é que isso é assumindo que esse problema pode ser resolvido só trocando. Nunca chegamos a ver o erro realmente acontecendo, só assumimos que registrar a fonte no PS resolvia. A única resposta que temos é que no #868 era a falta e só precisava baixar pro sistema.
Talvez seja um problema que faltou alguma coisa a mais pra ser resolvido. Então verificar o problema em um ambiente sem a fonte, confirmar o erro e resolver a partir dali é necessário.
Talvez nem seja preciso trocar a fonte.
