### ISSUE TITLE
[Mac] Nome do formulário principal está aparecendo como nome da aplicação

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#94]
O problema está descrito no título desta issue. A solução é exibir o nome da aplicação ao invés do nome do formulário.
![screen shot 2016-03-01 at 10 24 02 am](https://cloud.githubusercontent.com/assets/1012741/13428236/f966a9c4-df97-11e5-9240-3a64a42ea870.png)

**Comment by noschang** [comment]
@elieserdejesus, veja o pull request #99.

**Comment by noschang** [comment]
Foi resolvido no Pull Request https://github.com/UNIVALI-LITE/Portugol-Studio-Inicializador/pull/1 do Projeto Portugol-Studio-Inicializador
