### ISSUE TITLE
Tela Duplicando 

### ISSUE THREAD

**Issue by brunnix** [UNIVALI-LITE/Portugol-Studio#949]
**Descrição do Problema**:quando eu entro para criar um arquivo a tela vai se multiplicando infinitamente

**Mensagem de Erro (se houver)**:nenhum

**Captura de Tela / Arquivo.por**:
![image](https://user-images.githubusercontent.com/86077142/122457277-7aea4580-cf7c-11eb-8724-7d3f9b2f2406.png)

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@brunnix 
Verifique aqui: #421

**Comment by AdsonEsteves** [comment]
Duplicate of #421
