### ISSUE TITLE
[Mac] Ícone da aplicação não é exibido

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#95]
No Mac o ícone da aplicação não aparece no docker, o ícone que aparece é aquele famigerado ícone padrão do Java:

![screen shot 2016-03-01 at 10](https://cloud.githubusercontent.com/assets/1012741/13428400/0e242d22-df99-11e5-91d9-8e97c055c866.png)

**Comment by noschang** [comment]
@elieserdejesus, quando você roda o aplicativo de dentro do Netbeans isso é inevitável. Não há o que fazer, pois o ícone é obtido a partir do nome do processo que disparou a aplicação, neste caso o Java.

No entanto, quando a aplicação é empacotada como um ".app" do MAC, é possível informar um ícone dentro do mesmo, e este ícone será utilizado pelo SO.

Tente baixar e instalar esta versão do Studio e veja se o problema do ícone persiste:
https://sourceforge.net/projects/portugolstudio/files/2.2/Mac/ps-2.2-osx.zip/download

**Comment by elieserdejesus** [comment]
@noschang , tens razão quanto a execução a partir do NetBeans, e a imagem que eu postei foi feita nestas condições. Entretanto, eu baixei o instalador do mac no link que postasses, instalou tudo corretamente, foi criada uma pasta UNIVALI dentro da pasta de aplicações do Mac, tudo certo. Quando executo o PS também não aparece o ícone no docker. Aparece o ícone padrão do java. Realmente tem algum problema no ícone do docker.

**Comment by noschang** [comment]
@elieserdejesus, as formas que eu conheço de alterar o ícone:

Windows: criar um executável nativo já com o ícone a ser usado. Este executável é usado como um wrapper da JVM. Esta é a estratégia utilizada pelo Netbeans e pelo Eclipse.

Linux: cria-se um arquivo ".desktop" referenciando o arquivo de imagem a ser utilizado. No meu Linux Mint esta abordagem funcionou sem problema.

MAC: criar um pacote "app" com o ícone. Eu me lembro de ter testado numa VM do VirtualBox, mas não lembro se havia funcionado.

Fora isso, a única outra coisa é setar o ícone na janela principal. Mas isso já é feito.

**Comment by elieserdejesus** [comment]
Eu fiz isso funcionar no mac, mas não lembro como. Pode deixar que eu verifico essa questão assim que possível.

**Comment by elieserdejesus** [comment]
@noschang , no último comentário desse [post] tem uma receita para embutir o icone (.icns) na aplicação, mas só funciona se o arquivo .dmg estiver sendo gerado pelo netbeans.

Outra opção é passar mais um parâmetro para a jvm: **-Xdock:icon=/path/icone.png**
Essa última opção é limitada porque teríamos que escolher um tamanho para esse png, a primeira solução usa o .icns que tem todas as resoluções já concebidas pela humanidade :)

**Comment by noschang** [comment]
@elieserdejesus, o Problema deste parâmetro de JVM é que ele deve bugar no Windows da mesma forma que o parâmetro para definir o título do menu no MAC. Temos que achar um jeito deste parâmetro de JVM ser injetado de forma condicional ao invés de tê-lo fixo no projeto do Netbeans/JAR gerado para o Studio.

Faz o seguinte teste:

- Clona o projeto Portugol-Studio-Inicializador na tua máquina

- Abra o projeto no Netbeans
- Descomenta esta linha e adiciona a do ícone também. E coloque tudo dentro de um "if" testando se está rodando no MAC ou não: https://github.com/UNIVALI-LITE/Portugol-Studio-Inicializador/blob/master/src/br/univali/ps/Inicializador.java#L140

- Mande executar o Portugol Studio através deste projeto ao invés do projeto do próprio Portugol-Studio

Se tudo correr como estou imaginando, o ícone do Java vai aparecer por um instante (este é o projeto Portugol-Studio-Inicializador) e depois, o Portugol Studio vai abrir com o ícone certo (esta é uma nova JVM que foi lançada de dentro do inicilizador com os novos parâmetros).

**Comment by elieserdejesus** [comment]
@noschang , quando rodo o projeto Inicializador obtenho um erro. A JVM não é encontrada. O inicializador precisa que o instalador crie um diretório para a jvm , alguma coisa assim?

![screen shot 2016-03-07 at 10 12 45 am](https://cloud.githubusercontent.com/assets/1012741/13570518/7be6e4f4-e44d-11e5-923d-e5ca29aa9171.png)

**Comment by noschang** [comment]
Isso @elieserdejesus. Foi falha minha!

- Clone o projeto Portugol-Instalador: https://github.com/UNIVALI-LITE/Portugol-Instalador. Não precisa abrí-lo no Netbeans, ele só é um projeto para agrupar alguns arquivos do instalador

- No Netbeans, selecione a aba "Arquivos" e navegue até o arquivo "build.xml". Clique com o botão direito e mande executar o destino "ant" chamado "gerar-arquivos-instalador"

- Na primeira vez vai demorar um pouco porque ele vai baixar as versões atualizadas da JVM. Aguarde até completar todo o processo de build

- Após a conclusão, mande executar o projeto Portugol-Studio-Inicializador

**Comment by elieserdejesus** [comment]
@noschang , não encontrei o target no build.xml. Esse build.xml que tem o target está em qual projeto?

**Comment by noschang** [comment]
@elieserdejesus. Foi mal, é o do projeto do Portugol-Studio.

**Comment by elieserdejesus** [comment]
@noschang , pior que não achei o target cara :) Dá uma conferida aí. Eu já procurei em 3 projetos, conferi se estava na branch certa, e nada desse target do ant nos build.xml que eu olhei.

**Comment by noschang** [comment]
@elieserdejesus. Certifique-se de estar no branch "master" do Portugol-Studio. Clique com o botão direito no build.xml. O target não vai aparecer logo de cara, mas vai ter uma opção no menu do Netbeans chamada "Outros destinos". Ao selecionar este menu irão aparecer as demais opções.

**Comment by elieserdejesus** [comment]
@noschang , achei o target. Executei o target e apareceu uma coisa meio preocupante na saída do netbeans:
```
Created dir: /Users/elieser/Desktop/PS/Portugol-Instalador/arquivos/java
Baixando o Java para Windows x86
Getting: http://installbuilder.bitrock.com/java/jre1.8.0_73-windows.zip
To: /Users/elieser/Desktop/PS/Portugol-Instalador/arquivos/java/jre1.8.0_73-windows.zip
```
Estou no mac, então não faz muito sentido baixar a jre do windows.

**Comment by noschang** [comment]
@elieserdejesus. Veja que o nome do Target é "gerar-arquivos-instalador". Ele vai baixar e gerar todos os arquivos necessários para criar os instaladores do Portugol Studio.

Como o Portugol Studio pode ser instalado nas 3 plataformas, essa task já baixa as versões de Java para as 3 plataformas, em x86 e x64. O objetivo é deixar tudo pronto para que possa ser criada qualquer versão do instalador.

Isto ocorre uma vez só. Depois que as versões de Java são baixadas, elas ficam na máquina prontas para serem incluídas na instalação. Além disso, existem dois targets chamados "gerar-distribuicao-multi-plataforma-32-bits" e "gerar-distribuicao-multi-plataforma-64-bits". Eles criam um zip que contém todas as versões de Java, assim o Portugol Studio pode ser executado em qualquer plataforma a partir de uma única instalação.

Ou seja, o processo é:

1. Gerar os arquivos de instalação

2. Gerar o instalador específico de cada plataforma

**Comment by elieserdejesus** [comment]
@noschang , fiz essas alterações no inicializador e o nome da aplicação e o ícone do docker estão funcionando corretamente:
```
private static void incluirParametrosJVM(CommandLine parametros)
    {
        Properties parametrosJVM = lerParametrosJVM();

        String xms = "-Xms";
        String xmx = "-Xmx";

        parametros.addArgument(xms.concat(parametrosJVM.getProperty("jvm.Xms", "128M")));
        parametros.addArgument(xmx.concat(parametrosJVM.getProperty("jvm.Xmx", "512M")));
        
        parametros.addArgument("-Xdock:name=Portugol-Studio");
        parametros.addArgument("-Xdock:icon=/Users/elieser/Desktop/PS/Portugol-Studio-Inicializador/src/portugol-studio.icns");
        parametros.addArgument("-Dvisualvm.display.name=Portugol-Studio");
    }
```

Como podes ver o caminho do ícone está absoluto, e eu copiei manualmente o arquivo .icns para a raiz do inicializador. Como resolver esse problema do caminho absoluto? O arquivo .icns já está disponível no diretório do PS quando ele é instalado?

**Comment by noschang** [comment]
Oi @elieserdejesus. Sim, o instalador coloca o ícone na pasta correta durante a instalação.
Só tem algumas coisas importantes:

1. Ao invés de utilizar o caminho absoluto, utilize a classe "Caminhos". O Correo seria:

```
Caminhos.extrairCaminho(new File(new File(new File(Caminhos.diretorioAplicacao, "icones"), "mac"), "portugol-studio.icns"));
```
2. Você obrigatoriamente deve colocar os parâmetros específicos do MAC em um desvio condicional, caso contrário a JVM não vai inciar no Linux e no Windows. Veja o meu código que está no "master":

```

**Comment by elieserdejesus** [comment]
@noschang , te enviei uma mensagem pelo facebook, eu não consigo fazer um push no repositório do inicializador.

**Comment by noschang** [comment]
Foi resolvido no Pull Request https://github.com/UNIVALI-LITE/Portugol-Studio-Inicializador/pull/1 do Projeto Portugol-Studio-Inicializador
