### ISSUE TITLE
Erro de compilação no portugol 

### ISSUE THREAD

**Issue by tioace** [UNIVALI-LITE/Portugol-Studio#952]
sempre que eu dou play no meu código aparece a mensagem "erro de compilação" e "a variável resultado não foi inicializada", sendo que a mesma recebe o parâmetro "valorCompra" e a conta de porcentagem. 

programa
{
	funcao inicio(){ //essa função interage com o usuário e recebe a função imposto. 

	inteiro ano 
	real valor

	faca{
		escreva("Digite o ano em que foi comprado o veículo: ")
		leia(ano)
		escreva("Digite o valor de compra do veículo veículo: ")
		leia(valor)
		imposto(ano,valor)
	}enquanto(ano>0)
	}
	
	funcao real imposto(inteiro anoCompra, real valorCompra){ //essa funcão calcula o imposto e retorna o valor da conta para a funcao inicio.
	
	real resultado
	
	se(anoCompra<2000){
		resultado=valorCompra/1/100
		escreva("O valor do imposto a ser pago será de: ", resultado)}
	senao se(anoCompra>=2000 e anoCompra<2005){
		resultado=valorCompra/5/100
		escreva("O valor do imposto a ser pago será de: ", resultado)}
	senao se(anoCompra>=2005 e anoCompra<2010){
		resultado=valorCompra/10/100
		escreva("O valor do imposto a ser pago será de: ", resultado)}	
	senao se(anoCompra>=2010 e anoCompra<2015){
		resultado=valorCompra/15/100
		escreva("O valor do imposto a ser pago será de: ", resultado)}	
	senao se(anoCompra>2015){
		resultado=valorCompra/20/100
		escreva("O valor do imposto a ser pago será de: ", resultado)}
		
	retorne (resultado)
	}
}

**Comment by AdsonEsteves** [comment]
@AdsonEsteves 
Vc deve inicializar a variavel resultado com algum valor
por exemplo
real resultado = 0.0
