### ISSUE TITLE
galera comecei faz pouco tempo a programar e queria saber como posso ativar o plugin java no portugol studio

### ISSUE THREAD

**Issue by braian1983** [UNIVALI-LITE/Portugol-Studio#958]
faz 10 dias que estou tentando fazer um pequeno programa simples

**Comment by AdsonEsteves** [comment]
@braian1983 
O Portugol é feito em Java, mas não possui nenhum plugin java.
Vc pode ver na página do portugol studio na secao aprenda, alguns canais do youtube de graca com cursos sobre o Portugol Studio.
