### ISSUE TITLE
[Mac] NullPointerException ao tentar abrir um arquivo

### ISSUE THREAD

**Issue by elieserdejesus** [UNIVALI-LITE/Portugol-Studio#96]
Para reproduzir o bug no Mac (não tenho certeza se é apenas no Mac):
1 - Abra o PS
2 - Clique no botão para abrir arquivos (botão com ícone de pasta)
3 - Clique onde está marcado na imagem abaixo.
4 - O resultado é uma NullPointerException
![screen shot 2016-03-01 at 10](https://cloud.githubusercontent.com/assets/1012741/13428574/1e1bd422-df9a-11e5-844a-5610458a4f2e.png)

**Comment by noschang** [comment]
@elieserdejesus, abra o Portugol Studio no Netbeans, vá nas propriedades do projeto e, no menu "Executar" adicione o parâmetro: -debug.

![print](https://cloud.githubusercontent.com/assets/709553/13436840/f5c7782a-dfbf-11e5-8d17-87133da41ca6.png)

Ao fazer isso, o Portugol Studio será executado em modo debug e irá exibir um stack da exceção no JOptionPane. Assim você poderá depurar para ver o que ocorre. Se quiser, poste o stack aqui na issue para que possamos colaborar na solução.

**Comment by elieserdejesus** [comment]
@noschang , esse bug só acontece no mac mesmo?

**Comment by noschang** [comment]
@elieserdejesus, a solução pare este bug é simples. É só não clicar naquele lugar ali. :-D

**Comment by elieserdejesus** [comment]
assignei me a mim mesmo para resolver o bug supra citado :)

**Comment by elieserdejesus** [comment]
@noschang , criei uma nova aplicação no mac para testar o JFileChooser. Tudo funciona normalmente usando o LAF do sistema e também funciona se eu uso o WebLaf.

O problema é que no PS estamos combinando os dois LAFs. Na classe **FabricaDeFileChooser** estamos setando o LAF do sistema antes de instanciar os JFileChoosers, assim eles ficam com a cara do sistema, e logo em seguida instalamos o WebLaf, e o resto da aplicação usa esse LAF. É essa combinação que não está funcionando totalmente no mac.

Eu tentei usar outros LAF antes de instanciar os JFileChooser para ver se melhorava a situação, mas só piorou. 

Vejo duas soluções:
1 - Usar o JFileChooser do WebLaf, assim a aplicação inteira vai usar WebLaf e o problema é resolvido.
2 - Usar a classe FileDialog da AWT. Ela tem um visual nativo em todas as plataformas.

A solução 1 tem o problema de que o visual do FileChooser não tem nada a ver com o visual nativo de cada plataforma, mas poderíamos tentar configurar o FileChooserUI para chegar em algum resultado satisfatório.

A solução 2 tem um bom visual e não precisa de ajustes nesse sentido. Entretanto eu lembro que a classe FileDialog tinha alguma limitação em relação aos filtros que estão sendo usados para os arquivos .por.

Pelo que eu vi não tem solução perfeita, acho que vamos ter que escolher a solução menos ruim. O que achas?

**Comment by noschang** [comment]
@elieserdejesus, eu tenho uma solução que talvez lhe soe como gambiara, mas pode funcionar.

A gente pode criar uma mini-aplicação em Java que abre um socket e fica escutando em uma porta específica.

Quando o Portugol Studio quer abrir um arquivo, ele conecta via socket nesta aplicação, enviando pelo socket a lista com os filtros de tipo de arquivo.

A aplicação então abre o JFileChooser pro usuário escolher os arquivos e, após, envia como resposta no Socket a lista de arquivos selecionados, juntamente com um código de status indicando se o usuário clicou em "OK" ou simplesmente mandou cancelar.

O mesmo teria que ser feito na hora de salvar um arquivo.

**Comment by elieserdejesus** [comment]
@noschang , tenho certeza que essa solução funcionaria, só acho muito complexa para o problema em questão. O problema que temos é: um dos controles (um checkbox) do FileChooser não está funcionando no Mac e a causa é o mix de LAFs. Acho que se adotarmos uma solução mais simples vamos evitar gastar energia com algo que é simples.

**Comment by AlissonSteffens** [comment]
@elieserdejesus como tá o andamento desse bug?

**Comment by elieserdejesus** [comment]
@AlissonSteffens , ainda não temos um consenso sobre como resolver o bug com o mínimo de efeitos colaterais. Não é um bug que comprete o PS como um todo, acho que isso pode ficar no neverlog :)

**Comment by elieserdejesus** [comment]
Segundo (essa thread)[https://lists.apple.com/archives/java-dev/2008/Dec//msg00043.html] realmente não deveríamos misturar os LAFs. Segundo o que comentam na thread se o mix de LAFs funciona em alguns é só uma questão de sorte, não deveria ser o comportamento esperado.

E se **apenas no mac** usarmos o JFileChooser do WebLAF? Já testei e ele funciona, feio, mas funciona :)

**Comment by AdsonEsteves** [comment]
Se for possível, pode ser uma boa ideia.
Tem que ver se o problema que ocorria na biblioteca Arquivo quando se utilizava o WebLaf não ocorre no abrir e salvar como do portugol.
Acontecia que o campo de nome do arquivo ficava desativado, onde só era possivel selecionar um arquivo já existente, e não era possivel criar um novo
