### ISSUE TITLE
Erro numero 54caae2370684a5c7efe69e4a07101ca1865a883 v2.7.4

### ISSUE THREAD

**Issue by TheBiggest011** [UNIVALI-LITE/Portugol-Studio#960]
> Esta issue foi gerada automaticamente

[pressione o botao "copiar erro" no Portugol Studio e cole o erro aqui antes de enviar]

**Comment by AdsonEsteves** [comment]
@TheBiggest011 
Qual erro ocorreu? Consegue repetir ele?
