### ISSUE TITLE
Atualizar licença e referências das bibliotecas

### ISSUE THREAD

**Issue by noschang** [UNIVALI-LITE/Portugol-Studio#97]
Na tela "Sobre", ao clicar no botão "Visitar página", alguns dos sites das bibliotecas estão desatualizados e não entram mais.

![print1](https://cloud.githubusercontent.com/assets/709553/13428545/ebf2d4fa-df99-11e5-86f4-2f4f914541b7.png)

![print2](https://cloud.githubusercontent.com/assets/709553/13428553/f7100268-df99-11e5-85d2-7d8bbd4c2cec.png)

Deve ser verificado quais sites estão fora e atualizar a referência para o local correto. O botão "Visitar página" também está zoado no Linux. Não sei se o mesmo ocorre em outras plataformas, mas acredito que devemos aumentar um pouco a largura do botão e isso já será resolvido.

Além disso, é necessário incluir as licenças para as novas bibliotecas de som utilizadas pelo motor de áudio. Este processo consiste em duas etapas

1. Incluir uma entrada para a biblioteca no arquivo "licencas.xml", localizada no pacote "br.univali.ps.licencas"

2. Incluir o arquivo txt com a licença dentro do pacote. O nome do arquivo deve ser o mesmo declarado no xml e deve seguir o padrão: licenca-{nome-da-biblioteca}-{versao}.txt

![print3](https://cloud.githubusercontent.com/assets/709553/13428705/e9844630-df9a-11e5-815c-9b0ce3aa37c7.png)

O arquivo de licença geralmente consiste do copyright seguido do ano e nome do autor/instituição no topo do arquivo. Deve-se apenas tomar cuidado para que o conteúdo do arquivo fique legível na hora de exibí-lo na tela.

Para isso, deve-se evitar, por exemplo, digitar todo o texto da licença em parágrafos muito grandes, sem quebra de linha. Isso evita que parte do texto da licença fique oculto na hora de exibí-lo no componente.

![print4](https://cloud.githubusercontent.com/assets/709553/13428856/d9f6d510-df9b-11e5-8d8c-78aec25cd640.png)

![print5](https://cloud.githubusercontent.com/assets/709553/13428857/df3983b0-df9b-11e5-845a-b31d092be84a.png)

Também deve-se verificar e arrumar o nome dos JARs na pasta de bibliotecas. Os JARs devem seguir uma nomenclatura parecida com o nome da licença: {nome-da-biblioteca}-{versao}.jar. 

![print6](https://cloud.githubusercontent.com/assets/709553/13428966/9ede8c6a-df9c-11e5-8461-c579a92d4f6a.png)

O objetivo em adotar esta nomenclatura, é permitir identificar facilmente a troca de versão das bibliotecas utilizadas. Isto é importante porque às vezes, a troca de versão de uma biblioteca pode introduzir bugs e se não soubermos a versão exata fica difícil de rastrear ou voltar atrás se necessário.

Por último, é necessário verificar se há algum biblioteca que não utilizamos mais e nesse caso eliminá-las, não esquecendo de remover: o JAR, a referência dentro do XML e o arquivo de licença.

**Comment by AdsonEsteves** [comment]
Atualizado as licenças e todas as bibliotecas estão sendo utilizadas de acordo com o @AlissonSteffens
