### ISSUE TITLE
Erro de transição de tela

### ISSUE THREAD

**Issue by wanderson-dcf** [UNIVALI-LITE/Portugol-Studio#998]
**Descrição do Problema**:
Quando um novo Arquivo é iniciado, se a aba inferior mensagens estiver selecionada antes de rodar o código,  a tela de console ao lado não fica clicavel ou seja ela não muda de mensagens para console, porém se antes de rodar o código a aba console estiver selecionada nenhum problema ocorre.
**Mensagem de Erro (se houver)**:

**Captura de Tela / Arquivo.por**:

**Especificações do sistema**:

**Comment by AdsonEsteves** [comment]
@wanderson-dcf 
Interessante o seu reporte, comigo isso não está acontecendo.
Veja se os passos que fiz são os mesmos que o seu:
>Clicar em novo arquivo (Abre com o escreva("Ola mundo"))
>Trocar para a aba de mensagens
>Executar

Quando executo a aba muda automaticamente para o Console.

@wanderson-dcf 
Qual o seu sistema operacional?

**Comment by wanderson-dcf** [comment]
OI estava revendo o meu portugol e não encontrei mais o problema talvez fosse algo no meu pc.

**Comment by wanderson-dcf** [comment]
> @wanderson-dcf Interessante o seu reporte, comigo isso não está acontecendo. Veja se os passos que fiz são os mesmos que o seu:
> 
> > Clicar em novo arquivo (Abre com o escreva("Ola mundo"))
> > Trocar para a aba de mensagens
> > Executar
> 
> Quando executo a aba muda automaticamente para o Console.
> 
> @wanderson-dcf Qual o seu sistema operaciona
